shuup/shuup

- setup.py
- shoop/utils/money.py
- shoop_tests/utils/test_money.py
Creating a Money object in used to call settings.SHOOP_HOME_CURRENCY.
That is not good, because Money objects may be used at import time and
settings should not be read before Django is properly initialized.
Add a test case for this and for default currency being correct and for
the _units_match method.
> Money: Do not read Django settings at init

- shoop/front/templates/shoop/front/product/category.jinja
- shoop/front/templates/shoop/front/product/detail.jinja
`get_parents()` wasn't actually even a thing...
> Fix usages of `Category.get_ancestors()` in templates.

- shoop/core/management/commands/shoop_init.py
This will enable creation of `ShopProduct` with `ShopProductFormPart` in `shoop/admin/modules/products/views/edit.py:56` when shoop was initialized with management command `shoop_init`.
Add status parameter `status=ShopStatus.ENABLED` when creating default shop.
> Init default shop as active

- shoop/front/views/checkout.py
This is because some custom phases might need `GET` params to operate.
> Persist GET parameters in checkout phase redirect

- shoop_setup_utils/finding.py
Both versions of shoop_setup_utils.find_packages function always
returned None, rather than the correct result of package list, because
return statements were missing.  Fix that.
> shoop_setup_utils: Fix find_packages (SHOOP-994)

- .dockerignore
- Dockerfile
- shoop_setup_utils/commands.py
- shoop_workbench/settings/base_settings.py
- shoop_workbench/settings/utils.py
This PR adds a basic Dockerfile that can be used to boot up an "evaluation" instance of Shoop.
> Docker, Docker everywhere

- shoop/admin/__init__.py
- shoop/admin/modules/system/__init__.py
- shoop/admin/modules/system/views/telemetry.py
- shoop/admin/templates/shoop/admin/system/telemetry.jinja
- shoop/admin/views/dashboard.py
- shoop/core/settings.py
- shoop/core/telemetry.py
- shoop/testing/admin_module/__init__.py
- shoop_tests/core/test_telemetry.py
Implements an **opt-in-by-default** telemetry sender.
The receiving side is <del>still missing</del>currently in PR review, so this doesn't do much except slow down loading of the admin dashboard for a few seconds every 72 hours.
> Telemetry Sender

- shoop/admin/gulp_bits/bower-files.js
- shoop/admin/gulp_bits/bower-install-task.js
- shoop/admin/gulp_bits/index.js
- shoop/admin/gulp_bits/js-packages.js
- shoop/admin/gulp_bits/metatasks.js
* I noticed the NPM `glob` module has an ignore mechanism, so why not use that.
* As discussed on Slack, clean installations would kvetch about Bower files being missing before running `gulp bower`. Now, the regular tasks that use Bower files aren't even being installed if we're doing `gulp bower`, so that won't happen. (In addition, there's lots less code to load in this case, so speed-ups too! Win win!)
* Code style, man! JSCS'd the heck out of those bits.
> Clean up and speed up admin statics build

- setup.py
- shoop_setup_utils/commands.py
- shoop_setup_utils/versions.py
- shoop_workbench/settings/__init__.py
Fix pip install from Git submodule (SHOOP-1032) and exclude
local_settings.py from the Python package (SHOOP-1027). Also allow
specifying local settings for shoop_workbench by giving path of
local_settings.py in an environment variable.
> Installation fixes (SHOOP-994)

- shoop_workbench/settings/__init__.py
There is no execfile in Python 3, so convert the code to use open,
compile and exec directly.  Now it should work with Python 3 too.
SHOOP-994 / SHOOP-1027
> workbench: Port execfile usage to Python 3

- shoop/admin/modules/contacts/views/detail.py
- shoop/admin/templates/shoop/admin/contacts/detail.jinja
Order.orderer is PersonContact so it can't be filtered with CompanyContact object.
Showing current addresses fail since None is not iterable. This happens when contact has only one address set.
> Fix showing contact detail at admin

- shoop/admin/static_src/base/less/shoop/custom-forms.less
Other input fields have the 2px solid border but bootstrap select
was missing it.
Refs SHOOP-1036
> Add borders to bootstrap select in admin

- shoop/front/template_helpers/product.py
- shoop/front/templates/shoop/front/macros.jinja
- shoop/front/templates/shoop/front/product/detail.jinja
* Add a template helper to be used in templates to render the wanted cross-sell products.
* Add all of them to the default template (related, recommended and computed)
* Translate the texts from finnish to english
Refs SHOOP-1040
> Cross-sells to product detail page in default templates

- shoop/admin/modules/products/views/variation/variable_variation_forms.py
- shoop/core/fields/__init__.py
- shoop/core/migrations/0002_identifier_field_unique.py
- shoop/core/models/attributes.py
- shoop/core/models/categories.py
- shoop/core/models/contacts.py
- shoop/core/models/manufacturers.py
- shoop/core/models/methods.py
- shoop/core/models/orders.py
- shoop/core/models/product_media.py
- shoop/core/models/product_variation.py
- shoop/core/models/products.py
- shoop/core/models/shops.py
- shoop/core/models/suppliers.py
- shoop/core/models/taxes.py
- shoop/core/models/units.py
- shoop/notify/models/script.py
- shoop/simple_cms/models.py
- shoop_tests/admin/test_product_variation.py
Form regression introduced in 43a88d2092a525ac1785588443d2789c095403c5, refs SHOOP-1075.
More importantly: this adds a brand-new migration to fix the slightly broken `InternalIdentifierField` implementation. Refs SHOOP-1092.
> Fix variable variation form regression (and an important root cause)

- shoop/admin/gulp_bits/js-packages.js
- shoop/admin/static_src/base/js/jquery.form-submission-attributes.polyfill.js
Submitting forms in Shoop admin didn't work because IE doesn't support `form`
attribute in `<button>` element.
Refs SHOOP-1090
> Admin: Polyfill forms to ensure IE support

- shoop/core/models/categories.py
I had mistakenly made `Category.identifier` `unique=False` in
cf04c8458a725f495813c44ca7557348a15e397b, but no migration had been made
of that, so no harm, no foul.
> Make `Category.identifier` unique again

- shoop_workbench/settings/base_settings.py
Allow overriding BASE_DIR and SHOOP_ENABLED_ADDONS_FILE from the
environment to make it easier to customize deployment of shoop_workbench
for QA environments and such.
> workbench: Allow overriding couple settings from env

- shoop/admin/modules/products/views/forms.py
- shoop/admin/templates/shoop/admin/attributes/edit.jinja
- shoop/admin/templates/shoop/admin/contact_groups/edit.jinja
- shoop/admin/templates/shoop/admin/macros/multilanguage.jinja
- shoop/admin/templates/shoop/admin/methods/edit.jinja
- shoop/admin/templates/shoop/admin/products/_edit_attribute_form.jinja
- shoop/admin/templates/shoop/admin/shops/edit.jinja
- shoop/utils/multilanguage_model_form.py
Add more tools to render language dependent content
Use these tools to render translated fields for attributes, product attributes, contact groups, methods and shops correctly.
Refs SHOOP-1049
> Translated fields to tabs

- shoop/apps/settings.py
Currently shoop.apps.settings module tries to check that no setting is
declared in two separate apps.  It should raise ImproperlyConfigured
exception when that happens, but the code was left in broken state on
refactoring and therefore AttributeError was raised instead.
Fix the code to provide more info about which apps are declaring the
conflicting setting.
Refs SHOOP-1277
> Fix checking of duplicate settings

- shoop/core/migrations/0005_drop_defaults_at_moneyfields.py
- shoop/notify/migrations/0002_notification_identifier.py
- shoop/simple_pricing/migrations/0004_simpleproductprice_price.py
Core: Add migration to drop default values from moneyfields
Notify: Add migration to make notification identifier not unique
Simple pricing: Add migration to drop default from price
> Add missing migrations

- shoop/themes/classic_gray/bower.json
- shoop/themes/classic_gray/gulpfile.js
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/base.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/index.jinja
Classic gray theme: Add missing bootstrap-select to bower.json
Classic gray theme: Use shop logo and public name in templates
Refs SHOOP-1178
> Add logo and name for classic gray

- shoop_workbench/settings/base_settings.py
Add shoop.themes.classic_gray to INSTALLED_APPS to make it available for
theme selection in the Shop Admin.
> Enable Classic Gray theme (SHOOP-1194)

- shoop/themes/classic_gray/gulpfile.js
- shoop/themes/classic_gray/static_src/js/vendor/imagelightbox.js
- shoop/themes/classic_gray/static_src/less/classic-gray/product.less
- shoop/themes/classic_gray/static_src/less/vendor/imagelightbox.less
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/macros.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_product_images.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja
* Remove image carousel from macros since it is not used anywhere
* Update Gulp to include lightbox and fix path for owl carousel
* Update product page template for product images:
* Move product image to it's own file
* Provide image titles and descriptions as data-attributes
* Use background images instead of images so that every aspect ratio images can be used without the need of cropping every image to square
* Thumbnails now use owl carousel
* Add styles for images on product page and lightbox
* Update lightbox javascript
* Add overlay, loader icon, close button and arrows
* Support for image titles and descriptions
> Classic gray product images

- shoop/core/models/products.py
- shoop/core/models/shops.py
- shoop/core/pricing/__init__.py
- shoop/core/pricing/default_pricing.py
- shoop/core/pricing/price.py
- shoop/core/pricing/price_info.py
- shoop/core/shortcuts/__init__.py
- shoop/discount_pricing/module.py
- shoop/front/basket/objects.py
- shoop/simple_pricing/module.py
- shoop/testing/factories.py
- shoop/themes/default_theme/templates/default/shoop/front/product/detail.jinja
- shoop/utils/_united_decimal.py
- shoop/utils/money.py
- shoop_tests/core/test_default_pricing.py
- shoop_tests/core/test_price_info.py
- shoop_tests/discount_pricing/test_discount_pricing.py
- shoop_tests/simple_pricing/test_simple_pricing.py
- shoop_tests/utils/test_money.py
- shoop_tests/utils/test_united_decimal.py
Also set the correct discount amounts for SourceLine, BasketLine and
OrderLine when they are created.
Refs SHOOP-975 / SHOOP-1462
> Fix PriceInfo usage with non-one quantities (SHOOP-1462)

- shoop/xtheme/static_src/injection/style.less
Placeholders were collapsing over each other so for better
readability and usability, add a 10px margin after every
editable placeholder in xtheme editor.
> Add a margin after every placeholder in xtheme editor

- shoop/themes/classic_gray/static_src/less/classic-gray/product-list.less
Transitions caused the list/grid view toggler (Classic Gray Theme)
to always slide from left to right even if the state itself never
changed on page reload. Remove transitions so that the toggler stays
on the right position without sliding on page load.
Refs SHOOP-1391
> Remove CSS transition from list/grid toggler (Classic Gray)

- shoop/front/template_helpers/general.py
- shoop/utils/iterables.py
- shoop/utils/translation.py
- shoop_tests/admin/test_media_module.py
- shoop_tests/front/test_general_template_helpers.py
10,000 Categories.
One Index Page.
Left: new hotness. Right: old and busted.
---
Now that `cache_translations` works again, this PR will likely speed up other, unrelated parts of Shoop as well. Yayness!
> Fix `get_root_categories` performance

- shoop/themes/classic_gray/static_src/less/classic-gray/product.less
- shoop/themes/classic_gray/templates/classic_gray/product_preview.jinja
Since all the other headings use the default base color,
use that for product titles as well.
> Use normal text color on product name (Classic Gray)

- shoop/core/migrations/0006_shop_add_logo_and_public_name.py
Do not import Shop models directly from shoop.core.models, but use the
apps.get_model instead.  This is needed, because importing Shop
directly will use the newest version of the model, not the version of
the previous migration level and that makes it impossible e.g. to add
fields to Shop.
Refs SHOOP-1153 / SHOOP-1502
> Fix shoop.core.migrations.0006

- shoop/front/template_helpers/general.py
The GET parameter is a string and should be converted to int.
Refs SHOOP-1419
> template_helpers: Fix get_pagination_variables

- shoop/front/apps/auth/templates/shoop/user/login.jinja
- shoop/front/apps/auth/views.py
- shoop/front/apps/customer_information/urls.py
- shoop/themes/classic_gray/templates/classic_gray/shoop/user/login.jinja
- shoop_tests/front/test_auth.py
- shoop_workbench/settings/base_settings.py
Front Auth: Ensure `next` is transferred through login flow
Front: view `/customer/` now requires login
`LOGIN_URL` now defined in workbench settings
Refs SHOOP-1514
> Customer URL now requires login

- shoop/themes/classic_gray/static_src/js/custom.js
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja
- shoop/themes/classic_gray/views/__init__.py
- shoop/themes/classic_gray/views/product_price.py
* Create custom product_prices view for classic gray theme
* Call product_prices view with AJAX, with product id, quantity and
optional child id parameters
* Render correct prices at _detail_order_section template based on
previous parameters
Refs SHOOP-1356
> Classic gray theme: Reload product prices with AJAX in quantity change

- MANIFEST.in
Add multiple levels of bower_components and node_modules to be pruned out of builds.
Refs SHOOP-1470
Refs SHOOP-1535
> Prunes, manifests

- shoop/xtheme/admin_module/__init__.py
- shoop/xtheme/templates/shoop/xtheme/admin/config.jinja
Xtheme view was not looking like the rest of admin so add correct
templates for it.
Also the theme section is quite important so in main menu, move it
from "System" to be a main level menu item itself.
> Admin: Update Xtheme views

- shoop/simple_cms/admin_module/views.py
- shoop/simple_cms/models.py
- shoop_tests/simple_cms/test_page_creation.py
Ensure `Page` outputs text from `__str__`
CMS: No duplicate URLs allowed from now on
Refs SHOOP-1571
> Cms duplicate

- shoop/admin/static_src/base/less/shoop/custom-forms.less
Input groups did not have any styles in admin. This is done since
in the future we might want to use this feature for like datepickers
or other additional info like icons next to the input field.
Example:
```{{ bs3.field(form.field_name, addon_after="<a href='#'><i class='fa fa-calendar-o'></i></a>") }}```
> Admin: Add styles for bootstrap input-group

- shoop/core/models/attributes.py
- shoop_tests/admin/test_product_attributes_form.py
Time interval field had `IntegerField` as a formfield type. This was not
intented as the value was actually considered as decimal.
Refs SHOOP-1550
> Admin: Time interval attribute now renders as `DecimalField`

- shoop/themes/classic_gray/static_src/less/classic-gray/product-card.less
- shoop/themes/classic_gray/static_src/less/classic-gray/product-list.less
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/macros.jinja
Product card included multiple links to product detail page on its elements.
Wrap card contents to one link instead of multiple ones so the card itself
acts as a link to the product detail page.
"Shop" is not used in classic gray so remove it from product box macro.
Since the whole product card acts now as a link, remove "open" button from
the bottom actions.
> Update product card macro and styles (classic gray)

- shoop/core/models/products.py
Customer with `is_all_seeing` `True` could see variation children in product
listings and this caused multiple problems and was not intented.
Refs SHOOP-1596
> Front: Fix issue with variation children being listed for admin user

- shoop/themes/classic_gray/templates/classic_gray/shoop/front/basket/partials/_basket_content.jinja
Basket lines did not show if the product had any discounts.
Add base price as overlined text under the line total price if
it has any discounts.
> Classic Gray basket: Show base price on discounted line items

- shoop/notify/templates/notify/admin/script_item_editor.jinja
Add novalidate to form to allow backend validate fields and give
proper error messages. Also add generic error message at the top of
the form to tell there is error in fields.
Refs SHOOP-1553
> Notify: Add better error handling for "step edit"-popup

- shoop/themes/classic_gray/templates/classic_gray/shoop/simple_search/search.jinja
render_field has selectpickers enabled so use it in classic gray's
search select field.
> Classic Gray search: Use render_field instead of bs3 in select

- shoop/core/models/product_shops.py
- shoop_tests/admin/test_product_module.py
Admin has no customer, therefore the visibility cannot be checked the same way
as in frontend.
SHOOP-1604
> Admin: Fix issue where visibility errors caused an error

- shoop/core/migrations/0010_fk_on_delete.py
- shoop/core/models/addresses.py
- shoop/core/models/attributes.py
- shoop/core/models/categories.py
- shoop/core/models/contacts.py
- shoop/core/models/methods.py
- shoop/core/models/orders.py
- shoop/core/models/product_media.py
- shoop/core/models/product_packages.py
- shoop/core/models/product_shops.py
- shoop/core/models/product_variation.py
- shoop/core/models/products.py
- shoop/core/models/shipments.py
- shoop/core/models/shops.py
- shoop/core/models/supplied_products.py
- shoop/default_tax/migrations/0003_fk_on_delete.py
- shoop/default_tax/models.py
- shoop/discount_pricing/models.py
- shoop/front/models/stored_basket.py
- shoop/notify/migrations/0003_fk_on_delete.py
- shoop/notify/models/notification.py
- shoop/simple_cms/migrations/0002_fk_on_delete.py
- shoop/simple_cms/models.py
- shoop/simple_pricing/models.py
- shoop/simple_supplier/migrations/0002_fk_on_delete.py
- shoop/simple_supplier/models.py
- shoop/utils/analog.py
- shoop_tests/core/test_categories.py
- shoop_tests/core/test_foreignkeys.py
- shoop_tests/core/test_shops.py
`Shop` and `Category` were both missing `on_delete=models.SET_NULL`. This caused them to be deleted also when attached image was deleted in media browser.
Fixes #205
> Prevent `Shop` being deleted when image was deleted

- shoop/admin/utils/bs3_renderers.py
- shoop/themes/classic_gray/__init__.py
- shoop/themes/classic_gray/config_form.py
*Add multiselect widget_class for ModelMultipleChoiceFields automatically to
prevent checking field class in templates.
* Footer CMS Pages field are no longer required
* Update label for Footer links to avoid confusion
Refs SHOOP-1631
> Classic gray: Update admin xtheme edit

- shoop/addons/templates/shoop/admin/addons/upload_confirm.jinja
- shoop/admin/templates/shoop/admin/categories/edit.jinja
- shoop/admin/templates/shoop/admin/contact_groups/edit.jinja
- shoop/admin/templates/shoop/admin/contacts/detail.jinja
- shoop/admin/templates/shoop/admin/contacts/edit.jinja
- shoop/admin/templates/shoop/admin/macros/general.jinja
- shoop/admin/templates/shoop/admin/methods/edit.jinja
- shoop/admin/templates/shoop/admin/orders/detail.jinja
- shoop/admin/templates/shoop/admin/product_types/edit.jinja
- shoop/admin/templates/shoop/admin/products/_edit_attribute_form.jinja
- shoop/admin/templates/shoop/admin/products/_edit_shop_form.jinja
- shoop/admin/templates/shoop/admin/products/edit.jinja
- shoop/admin/templates/shoop/admin/products/edit_cross_sell.jinja
- shoop/admin/templates/shoop/admin/products/edit_media.jinja
- shoop/admin/templates/shoop/admin/sales_units/edit.jinja
- shoop/admin/templates/shoop/admin/shops/edit.jinja
- shoop/admin/templates/shoop/admin/suppliers/edit.jinja
- shoop/admin/templates/shoop/admin/taxes/edit.jinja
- shoop/admin/templates/shoop/admin/taxes/edit_customer_tax_group.jinja
- shoop/admin/templates/shoop/admin/taxes/edit_tax.jinja
- shoop/admin/templates/shoop/admin/taxes/edit_tax_class.jinja
- shoop/admin/templates/shoop/admin/users/change_password.jinja
- shoop/admin/templates/shoop/admin/users/change_permissions.jinja
- shoop/admin/templates/shoop/admin/users/detail.jinja
- shoop/admin/templates/shoop/admin/users/reset_password.jinja
- shoop/default_tax/templates/shoop/default_tax/admin/edit.jinja
- shoop/notify/templates/notify/admin/edit_script.jinja
- shoop/simple_cms/templates/shoop/simple_cms/admin/edit.jinja
- shoop/xtheme/templates/shoop/xtheme/admin/config_detail.jinja
Use new macro for wrapping the admin content. This helps creating new templates when the structure
is automated.
Also unify the code styles in templates and use correct indentation.
Refs SHOOP-1660
> Admin: Template refactoring

- shoop/themes/classic_gray/static_src/less/classic-gray/navigation.less
Since logo padding was changed the logo text line height needs to be updated too.
Refs SHOOP-1630
> Classic Gray: Fix logo text line height

- shoop/admin/modules/products/views/edit.py
- shoop_tests/admin/test_product_module.py
Fix issue with `sku` and `name` `GET` params not being handled in product
view when adding products through search.
Refs SHOOP-1062
> Admin: Transfer sku properly to product

- shoop/front/apps/auth/forms.py
- shoop/front/apps/auth/templates/shoop/user/recover_password.jinja
- shoop/front/apps/auth/templates/shoop/user/recover_password_mail_content.jinja
- shoop/front/apps/auth/views.py
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/user/recover_password.jinja
- shoop_tests/front/test_auth.py
- shoop_tests/front/test_registration.py
Allow login with email.
Allow password recovevry with username. Add more user information
to password recovery email.
Refs SHOOP-1670
> Auth: Enable email login and password recovery with username

- doc/provides.rst
- shoop/xtheme/engine.py
- shoop_tests/xtheme/test_addon_injections.py
Enable "xtheme_resource_injection" as a provider category that
defines function to add resources to theme.
Refs SHOOP-1685 / SHOOP-1690
> Xtheme: Allow addons to inject resources

- shoop/themes/classic_gray/static_src/less/classic-gray/base.less
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/base.jinja
Add a dismissable alert banner if the shop is in maintenance mode.
Now the admin can see in shop side if the maintenance mode is left on.
Refs SHOOP-1585
> Classic Gray: Show maintenance mode for admin

- shoop/core/cache/__init__.py
- shoop/core/cache/impl.py
- shoop/core/settings.py
- shoop/front/apps/simple_search/views.py
- shoop/front/utils/product_statistics.py
- shoop_tests/utils/test_cache.py
This is the versioned cache API as introduced in #62, rebased, extracted and slightly updated too.
> Add autoexpiring versioned cache API (SHOOP-1702)

- shoop/core/taxing/utils.py
- shoop/default_tax/admin_module/views.py
- shoop/default_tax/migrations/0005_taxrule_override_group.py
- shoop/default_tax/models.py
- shoop/default_tax/module.py
- shoop/default_tax/templates/shoop/default_tax/admin/edit.jinja
- shoop_tests/core/test_taxing_utils.py
- shoop_tests/default_tax/test_default_tax.py
Fix tax calculations of default_tax to make added and compounded taxes
work correctly.
Implement override groups for TaxRules.
Refs SHOOP-1636/SHOOP-1622
> Fix tax calc and implement override groups (SHOOP-1622)

- shoop/core/requirements.txt
- shoop/front/requirements.txt
Prensence of requirements.txt makes some tools interpret the directory
as project root.  We don't use these files for anything, so better just
remove them.
> Remove unused requirements.txt from core and front

- shoop/testing/factories.py
- shoop/testing/utils.py
- shoop_tests/admin/test_contact_page.py
- shoop_tests/admin/test_media_module.py
- shoop_tests/admin/test_modules.py
- shoop_tests/admin/test_multishop_setting.py
- shoop_tests/admin/test_order_creator.py
- shoop_tests/admin/test_order_module.py
- shoop_tests/admin/test_product_module.py
- shoop_tests/admin/test_tax_module.py
- shoop_tests/admin/test_user_module.py
- shoop_tests/admin/test_views.py
- shoop_tests/core/test_order_creator.py
- shoop_tests/core/test_product_packages.py
- shoop_tests/front/test_middleware.py
- shoop_tests/front/test_simple_search.py
- shoop_tests/simple_cms/test_page_view.py
- shoop_tests/utils/__init__.py
In `shoop.testing.factories` there was an import from `shoop_tests` for
`apply_request_middleware` function.  This caused `shoop.testing` to
depend on BeautifulSoup, since `shoop_tests.utils` imports `bs4`.  This
dependency is undesirable and not even stated in `setup.py`.
Fix this by moving the `apply_request_middleware` to
`shoop.testing.utils` and update its users accordingly.
> Move apply_request_middleware to testing

- doc/taxes.rst
- shoop/core/taxing/utils.py
- shoop/default_tax/migrations/0006_taxrule_help_texts.py
- shoop/default_tax/models.py
* Rephrase "value added taxes" to "added taxes"
- Value added taxes (VAT) is totally different thing as the taxes added
together, which usually is used to implement sales taxes.
* Fix error in TaxRule help text: "priority" to "override group"
Refs SHOOP-1636
> Fix couple tax related terms

- shoop/front/__init__.py
- shoop/themes/classic_gray/__init__.py
- shoop_tests/utils/__init__.py
When `fooapp.settings` is imported, that `settings` is injected into the
`fooapp` parent module, overriding the `django.conf` import, making it
impossible to actually access `django.conf.settings`.
Notably, this caused `shoop.front` to never actually honor
`SHOOP_FRONT_INSTALL_ERROR_HANDLERS`, which in kind made application
initialization begin importing the root urlconf, which in the case of e.g.
Django-CMS caused database accesses, causing exceptions during migration.
> Don't use `from django.conf import settings` in app init modules.

- shoop/front/checkout/addresses.py
- shoop/front/checkout/single_page.py
- shoop_tests/front/test_checkout.py
If SHOOP_ADDRESS_HOME_COUNTRY is set, prefill that as country in address forms.
Rationale: shops are often based in a certain country, operating mostly in that area. Prefill a default country in address forms to help the majority of users.
> Set default country in checkout address forms

- shoop/core/management/commands/shoop_init.py
- shoop/core/models/contacts.py
- shoop/core/models/taxes.py
- shoop_tests/core/test_customers.py
- shoop_tests/core/test_taxes.py
Add default group getters for `CustomerTaxGroup`
Add default tax groups to `shoop_init` management command
Refs SHOOP-1621
> Assign created customers to CustomerTaxGroups on creation

- shoop/admin/modules/shops/views/edit.py
- shoop/core/models/_base.py
- shoop/core/models/order_lines.py
- shoop/core/models/orders.py
- shoop/core/models/shops.py
- shoop/core/models/taxes.py
- shoop/front/models/stored_basket.py
Changing currency or taxfulness of Shop's prices while it has any orders
is not good, so deny it.
Also rename ImmutableMixin to ChangeProtected and improve it a bit and
make the non-field errors visible in ShopEditView.
> Deny price unit changes of in-use Shop (SHOOP-1658)

- shoop/admin/modules/shops/views/edit.py
- shoop/core/models/shops.py
- shoop/core/utils/form_mixins.py
- shoop/testing/factories.py
- shoop_tests/admin/test_shop_edit.py
- shoop_tests/utils/forms.py
Add better error message when trying to save shop that has protection triggered.
Add protection handling to `MultiLanguageModelForm`
Refs SHOOP-1896
> Protected fields

- shoop_setup_utils/commands.py
Clear DJANGO_SETTINGS_MODULE when executing the
"django-admin compilemessages", because it might prevent message
compilation even though a settings module should not be needed.
This happened on our QA environment, previnting updating of Shoop.
> BuildMessagesCommand: Clear DJANGO_SETTINGS_MODULE (SHOOP-1886)

- shoop/admin/utils/urls.py
The redirect_to_login expects login_url argument to be str (i.e. bytes
on Py2, unicode on Py3).
Ref SHOOP-1922
> admin: Fix URL encoding in redirect to login

- shoop/admin/generated_resources.txt
- shoop/admin/gulp_bits/metatasks/js-metatask.js
- shoop/admin/package.json
Also enable source maps for Webpack artifacts in production (this required a minor Webpack upgrade).
Refs SHOOP-1839
Refs #279
> Admin: JavaScript compilation fixes

- shoop/admin/gulp_bits/js-packages.js
- shoop/admin/gulp_bits/metatasks/js-metatask.js
You can use `export DEBUG=*` before running `gulp js:dashboard` to verify Babel only traverses our components:
> Admin Gulp: Really fix the es6 switch.

- setup.py
Add '*.py[cod]' and '.cache' to exclude patterns in setup.py and reorder
the listing to more logical order.
This should make the caching of "build_resources" work better, since
previously also the pyc files were included when determining the cache
key for a resource compile source directory.
> setup.py: Tune exclude patterns

- MANIFEST.in
Include the source maps of CSS and JS files in the Python
packages (including wheel) to make developers happy.
> MANIFEST.in: Include *.map to the Python package

- shoop/core/management/commands/makemessages.py
- shoop/core/management/commands/shoop_makemessages.py
Doing "shoop_makemessages" in the shoop directory updates all the
translation base files, but it unnecessarily updates also the
POT-Creation-Date header which causes all PO files to change even if
there is no change to messages.  This makes it hard to periodically
update the message files (with clean commits).
Update the Shoop's "makemessages" command to support skipping
POT-Creation-Date updating of PO files which don't have any changes to
messages and make "shoop_makemessages" to toggle that option on by
default.
> Do not forcibly update POT-Creation-Date with makemessages (SHOOP-1932)

- .travis.yml
- setup.py
- tox.ini
[Seems to work!](https://travis-ci.org/akx/shoop/builds/94130836)
Once the wheels have been cached, the install step is a snappy 10 to 18 seconds, so the build time is about 2 minutes altogether. Not bad!
The project has been set up on Travis, but build hooks are currently switched off there.
> Add Travis CI

- shoop/core/migrations/0013_address_changes.py
- shoop_tests/core/test_migrations.py
* Do RenameModel first, which handles all foreign key changes to database.
* FakeAlterField applies only state forwards.
> Core: Fix migration 0013_address_changes (SHOOP-2003)

- .travis.yml
- tox.ini
Add "-ra" argument to py.test to make it show warnings.  This unifies
test running of Travis and Tox.
Also clean-up the travis.yml a bit and remove now unneeded
"--cov-config" argument from py.test call in tox.ini.
> Travis: Show py.test warnings

- _misc/sanity_utils.py
This is needed to make _misc/check_sanity.py run cleanly after tox is
ran (in our Jenkins master builder).
> sanity_utils: Ignore coverage.xml and var directory (SHOOP-1954)

- .travis.yml
- shoop/core/modules/interface.py
- shoop/utils/_united_decimal.py
- shoop/utils/excs.py
- shoop/utils/iterables.py
- shoop/utils/text.py
- tox.ini
Coverage reporting for Tox was broken on commit d7a4a6a97bf (which was
made, because there was some version of Tox that did not support
envsitepackagesdir variable).  Fix it.
Also enable doctests for Tox and Travis and fix some incorrectly
formatted doctests.
Refs SHOOP-1954
> Fix coverage reporting of Tox and do doctests

- shoop/admin/templates/shoop/admin/dashboard/dashboard.jinja
- shoop/admin/views/dashboard.py
Added the Shoop version number to the admin dashboard to help merchant/
admin troubleshooting process
Refs SHOOP-1999
> Version number in shop admin

- shoop/admin/gulp_bits/js-packages.js
- shoop/admin/static_src/base/js/language-changer.js
- shoop/admin/static_src/base/less/shoop/navigation.less
- shoop/admin/static_src/base/less/variables.less
- shoop/admin/template_helpers/shoop_admin.py
- shoop/admin/templates/shoop/admin/base/_navigation.jinja
- shoop/admin/urls.py
- shoop/core/templatetags/shoop_common.py
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/language_changer.jinja
- shoop_workbench/settings/base_settings.py
Add localized language names to both frontend and admin language changers.
A language's localized name defaults to its Django default translation when its language name is set equal to its country code (i.e., ``("en", "en")``), however this can be overridden by specifying a localized display name, as below with 'ENGLISH':
LANGUAGES = [
('en', 'ENGLISH'),
('fi', 'fi'),
('ja', 'ja'),
('zh-Hans', 'zh-Hans'),
]
> Translate language names

- .travis.yml
- setup.py
- shoop/front/basket/objects.py
- shoop_tests/front/test_basket.py
- tox.ini
Noticed this while working on an internal project.
Also, since my currently installed Py3 is 3.5, had to make things work with it too.
> Fix basket dirty flag not always being correctly set

- doc/changelog.rst
- shoop/admin/static_src/vendor/bower.json
- shoop/campaigns/admin_module/views.py
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/basket/partials/_basket_content.jinja
* Campaigns: Make admin sorting with name and discount amount work
* Classic gray: Modify basket lines
* Admin: Bump bootstrap-datetimepicker version to 2.3.8
Refs SHOOP-2118 / SHOOP-2119 / SHOOP-2121 / SHOOP-494
> Campaign fixes

- shoop/front/apps/auth/views.py
- shoop/front/apps/registration/views.py
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/user/login.jinja
- shoop_tests/front/test_registration.py
The `next` context variable contains an URL to redirect the user after a successful registration. It is optional and may allow redirects to certain pages after the registration.
> Add `next` context variable in registration process

- doc/changelog.rst
- shoop/core/order_creator/_source.py
- shoop/core/settings.py
- shoop/core/taxing/_module.py
- shoop_tests/core/test_taxes.py
Move calculate taxes automitacally from OrderSource to TaxModule.
Create setting SHOOP_CALCULATE_TAXES_AUTOMATICALLY.
Refs SHOOP-1911
> Core: Move calculate taxes automatically under TaxModule

- doc/changelog.rst
- shoop/addons/admin_module/views/reload.py
- shoop/addons/installer.py
- shoop/addons/locale/en/LC_MESSAGES/django.po
- shoop/addons/templates/shoop/admin/addons/reload.jinja
- shoop/apps/settings.py
* Use upgrade flag while installing new addons. This allows
updating old addons.
* Run migrations command while reloading application
* Run collectstatic command while reloading application
Refs SHOOP-2106 / SHOOP-1770
> Addons: Enable upgrade, migrations and collectstatic

- doc/changelog.rst
- shoop/front/basket/storage.py
- shoop_tests/front/test_basket.py
`finalize` never called `delete` correctly (it obviously requires the `basket` argument).
This was noticed by yours truly and @RauliL while working on a client project.
> BasketStorage: fix mis-call of `delete` in `finalize`

- setup.py
* django-registration version 1.4 doesn't work with our custom get_success_url
* fake-facotry version 0.5.4 does not work with Shoop
> Add version limits to 3rd party packages

- doc/changelog.rst
- shoop/core/api/orders.py
- shoop_tests/core/test_payments_api.py
* Add create_payment detail route to OrderViewSet
* Add custom PaymentSerializer with amount_value,
currency, payment_identifier and description as fields.
Refs SHOOP-2117 / SHOOP-1973
> Core: option to create payments with REST API

- shoop/core/order_creator/_source.py
- shoop/core/settings.py
- shoop/core/taxing/__init__.py
- shoop/core/taxing/_module.py
- shoop_tests/core/test_taxes.py
Change the logic whether to calculate taxes automatically in OrderSource.
Rename setting ``SHOOP_CALCULATE_TAXES_AUTOMATICALLY`` to
``SHOOP_CALCULATE_TAXES_AUTOMATICALLY_IF_POSSIBLE``. If this
setting is False then taxes shouldn't be calculated automatically
otherwise use ``TaxModule.calculating_is_cheap`` to make that
decision.
Refs SHOOP-1911
> Taxes: Changes to automatic tax calculations

- doc/changelog.rst
- shoop/admin/modules/orders/json_order_creator.py
- shoop/admin/modules/orders/views/create.py
- shoop/core/order_creator/_creator.py
- shoop/core/order_creator/_source.py
- shoop/core/order_creator/signals.py
- shoop/core/pricing/_context.py
- shoop/core/pricing/_module.py
- shoop/core/shortcuts/__init__.py
- shoop/front/basket/__init__.py
- shoop/front/basket/objects.py
- shoop/front/checkout/confirm.py
- shoop/front/checkout/single_page.py
- shoop/front/notify_events.py
- shoop/front/signals.py
- shoop/testing/factories.py
- shoop_tests/campaigns/test_basket_campaigns.py
- shoop_tests/core/test_order_creator.py
- shoop_tests/core/test_product_packages.py
* Move order_creator_finished signal from front to
core.order_creator.signals
* Admin: Make all enabled shipping and payment methods available in
order creation
* OrderCreator: Make request argument optional
*  Remove request from OrderCreator init calls
* Admin: Order creating: Populate Order.ip_address
* factories: Depend less on request
* Ensure pricing context gets shop and customer
First two of those commits are from @tulimaki (I only fixed the Refs format and rephrased change log item from "Enable all methods for order creator" to "Make all enabled shipping and payment methods available in order creator". The rest commits are related clean-ups/refactoring that we should do while moving the signal, since they fix a long standing TODO item and improves OrderCreator by making it …
> Move order_creator_finished signal etc. (SHOOP-2114)

- doc/changelog.rst
- shoop/core/locale/en/LC_MESSAGES/django.po
- shoop/core/models/_contacts.py
- shoop_tests/core/test_contacts.py
- shoop_tests/core/test_customers.py
* Default contact groups for anonymous, person and company contacts
* Groups is assigned during save
* Make ContactGroup TranslatableShoopModel
Refs SHOOP-1981 / SHOOP-2141
> Core: Add default contact groups

- shoop/core/models/_base.py
- shoop/core/models/_contacts.py
- shoop_tests/core/test_contacts.py
- shoop_tests/core/test_customers.py
Fix couple things that popped into my mind while reviewing PR #358:
* We shouldn't really define `__str__` for any of our models unless
there is a very good reason, but rather make the version in
TranslatableShoopModel work for most of the cases.
* Rename `Contact.get_default_contact_group` to
`Contact.get_default_group` and make it classmethod.
* Add tests for ContactGroup str and repr.
> Couple tiny improvements for default ContactGroups (SHOOP-2141)

- shoop/admin/generated_resources.txt
In commit e657ce669 some new resources were added for
gulp (i.e. `contact-group.js*`), but they were not added to
generated_resources.txt. This causes the build cache to not function
properly, since it does not know which of the files are source files and
which are generated.  Add the missing resources to the
`generated_resources.txt` file (and sort it).
Refs SHOOP-1981
> admin: Fix generated_resources.txt

- shoop/front/template_helpers/product.py
- shoop/themes/classic_gray/__init__.py
- shoop/themes/classic_gray/plugins.py
- shoop/themes/classic_gray/templates/classic_gray/cross_sells_plugin.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/macros.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja
- shoop_tests/front/test_product_template_helpers.py
- shoop_tests/themes/classic_gray/test_plugins.py
Add a product cross sells xtheme plugin to classic_gray theme, replacing
hard-coded sections in theme templates.
Refs SHOOP-1970
> Themes: Add product cross sells plugin to classic_gray (SHOOP-1970)

- shoop/admin/modules/contact_groups/views/edit.py
- shoop/admin/modules/contact_groups/views/forms.py
- shoop/core/models/_contacts.py
- shoop_tests/core/test_contacts.py
Core: Fix ``get_price_display_options`` for ``Contact``
Admin: Define price display options for ``ContactGroup``
Refs SHOOP-1981 / SHOOP-2143
> Define price display options in ContactGroup admin (SHOOP-2143)

- doc/changelog.rst
- shoop/xtheme/__init__.py
- shoop/xtheme/locale/en/LC_MESSAGES/django.po
- shoop/xtheme/plugins/snippets.py
- shoop_tests/xtheme/test_plugins.py
Add a generic simple snippets plugin for doing simple integrations that
primarily require adding JavaScript or CSS resources to the page.
This is related to the PR #379, which is a refactor of PR #375.
Refs SHOOP-1972
> Xtheme: Add generic snippets plugin for simple integrations

- doc/changelog.rst
- shoop/themes/classic_gray/static_src/less/classic-gray/social-media-links.less
- shoop/themes/classic_gray/static_src/less/style.less
- shoop/xtheme/__init__.py
- shoop/xtheme/locale/en/LC_MESSAGES/django.po
- shoop/xtheme/plugins/social_media_links.py
- shoop/xtheme/templates/shoop/xtheme/plugins/social_media_links.jinja
- shoop_tests/xtheme/test_plugins.py
Add an xtheme plugin in classic_gray to display social media links on the
shop front.
This is a refactor of PR #375.
Refs SHOOP-1972
> Classic Gray: Add social media xtheme plugin

- shoop/core/order_creator/_source.py
- shoop_tests/campaigns/test_basket_contact_conditions.py
The customer, orderer and creator properties of OrderSource (or its
subclass BaseBasket) are used quite carelessly in some places, e.g. in
ContactGroupBasketCondition.matches.  Previously these properties could
have been None and then code like `basket.customer.groups.all()` would
fail to AttributeError.
Make OrderSource always return non-None objects for those three
attributes to fix ContactGroupBasketCondition.matches and possibly other
similar issues.
Add a test case for the issue in ContactGroupBasketCondition.matches.
Refs SHOOP-1981/SHOOP-2246
> Always return non-None for OrderSource contacts (SHOOP-2246)

- doc/changelog.rst
- doc/provides.rst
- shoop/admin/modules/shops/views/edit.py
- shoop/core/order_creator/_creator.py
Admin: Enable extra form parts for Shops
Core: Change customer marketing permission while creating order
Refs SHOOP-787 / SHOOP-2172 / SHOOP-2175
> Extra shop form part and marketing permission (SHOOP-2172, SHOOP-2175)

- shoop/admin/locale/en/LC_MESSAGES/django.po
- shoop/admin/locale/fi_FI/LC_MESSAGES/django.po
- shoop/admin/modules/contact_groups/views/forms.py
Since there is currently only four different modes of showing prices,
make the contact group editing form show those as a dropdown rather than
as two dropdowns.  This should be easier for the merchant.
Also update related translation fiels and translate added messages to
Finnish.
> Admin: Improve configuring price display mode (SHOOP-2269)

- doc/changelog.rst
- shoop/core/locale/en/LC_MESSAGES/django.po
- shoop/core/models/_products.py
- shoop/front/management/commands/compute_bought_with_relations.py
- shoop/front/template_helpers/general.py
- shoop/front/template_helpers/product.py
- shoop/front/utils/product_relations.py
- shoop/testing/factories.py
- shoop/themes/classic_gray/plugins.py
- shoop_tests/front/test_compute_bought_with_relations.py
- shoop_tests/front/test_general_template_helpers.py
- shoop_tests/front/test_product_template_helpers.py
* Front: Fix for ``get_visible_products`` template helper
* Core: Add bought with relation to ``ProductCrossSellType``
* Classic Gray: Update cross-sells plugin
* Front: Add management command to generate bought with relations
Refs SHOOP-2245
> Compute product  bought with relations (SHOOP-2245)

- shoop/front/template_helpers/product.py
- shoop/themes/classic_gray/plugins.py
* At plugin use ``ProductCrossSellType`` enum instead of strings
* At the product template helper ``get_product_cross_sells`` convert
strings to ``ProductCrossSellType`` if needed.
Refs SHOOP-2245
> Front/Classic Gray: Fix cross sell plugin

- shoop/front/template_helpers/product.py
- shoop/themes/classic_gray/plugins.py
- shoop_tests/themes/classic_gray/test_plugins.py
The type field of ProductCrossSellsPlugin used to use translated string as
field values as choices were given as (enum, string) pairs, where the
enum part was converted to translated string implicitly.  Fix this by
not defining the form field at all, but rather construct the form field
from the model field with `ProductCrossSell.type.field.formfield()`.
This will use the enum values as choice values.
Database may have old translated string values, use RELATED for those.
Also improve error handling of get_product_cross_sells (the second commit).
> Fix choices of ProductCrossSellsPlugin type field (SHOOP-2305)

- doc/changelog.rst
- shoop/admin/modules/contacts/views/edit.py
- shoop/admin/templates/shoop/admin/contacts/_edit_base_form.jinja
- shoop/core/migrations/0001_initial.py
- shoop/core/migrations/0018_add_first_and_last_name.py
- shoop/core/models/_contacts.py
- shoop/front/apps/customer_information/views.py
- shoop/testing/factories.py
- shoop_tests/admin/test_contact_edit.py
- shoop_tests/core/test_contacts.py
- shoop_tests/front/test_customer_information.py
* Add first and last name for PersonContact
* Admin: Enable edit for PersonContact first and last name
* Add first and last name for customer information edit
This replaces PR #395.
The differences to PR #395 are:
* Data migration for filling first_name and last_name
* PersonContact.name property getter and setter
* New tests
* get_person_contact: Use user.first_name and user.last_name
* Change Log entry
For full diff see `git diff 37fb7e4`.
> Add first and last name for PersonContact (SHOOP-832)

- shoop/testing/management/commands/shoop_populate_mock.py
This enables the usage of a custom AUTH_USER_MODEL in Shoop using mock data.
> Enable custom AUTH_USER_MODEL with username field other than `username`.

- shoop/simple_cms/plugins.py
- shoop_tests/simple_cms/test_plugins.py
Simple CMS: Make plugin hide expired pages correctly
Simple CMS: Initalize pages-field in plugin correctly
Refs SHOOP-2179 / SHOOP-2315, SHOOP-2316
> Simple CMS plugin fixes (SHOOP-2179)

- doc/changelog.rst
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_footer.jinja
- shoop/xtheme/__init__.py
- shoop/xtheme/parsing.py
- shoop/xtheme/rendering.py
- shoop/xtheme/static_src/injection/index.js
- shoop/xtheme/view_config.py
- shoop/xtheme/views/editor.py
- shoop_tests/xtheme/templates/global_complex.jinja
- shoop_tests/xtheme/test_editor_view.py
- shoop_tests/xtheme/test_layout.py
- shoop_tests/xtheme/test_load_save.py
- shoop_tests/xtheme/test_parsing.py
- shoop_tests/xtheme/test_plugin_forms.py
- shoop_tests/xtheme/test_rendering.py
Enable a ``global`` parameter for Xtheme placeholders which would store
a site-wite placeholder configuration.
This is done by overriding the placeholder's view name as
``_XthemeGlobalView`` and should work as expected when editing,
rendering, etc.
Currently, this only applies to global placeholders that are within the
same template (but might be included in other templates), so if two
placeholders are marked as ``global`` but are not in the same template
they will not share the same settings.
Refs SHOOP-2219
> Xtheme: Enable global placeholder type (SHOOP-2219)

- shoop/admin/modules/orders/static_src/create/reducers/order.js
- shoop/admin/modules/orders/static_src/create/view/methods.js
- shoop/admin/modules/orders/views/create.py
Hide method prices for order creator until user reaches confirmation
view where they can be more easily calculated.
> Order creator: Hide initial method prices (SHOOP-2319)

- doc/changelog.rst
- shoop/admin/modules/service_providers/__init__.py
- shoop/admin/modules/service_providers/views/__init__.py
- shoop/admin/modules/service_providers/views/_delete.py
- shoop/admin/modules/service_providers/views/_edit.py
- shoop/core/models/_service_payment.py
- shoop/core/models/_service_shipping.py
- shoop_tests/admin/test_service_providers.py
Services linked to service provider is not removed, but the
service provider foreign key is set to null and service is disabled.
Refs SHOOP-2297
> Admin: Add delete for service providers admin module (SHOOP-2297)

- doc/api/shoop.front.admin_module.carts.rst
- doc/api/shoop.front.admin_module.carts.views.rst
- doc/api/shoop.front.admin_module.rst
- doc/api/shoop.front.rst
- doc/changelog.rst
- shoop/admin/modules/orders/views/list.py
- shoop/admin/utils/picotable.py
- shoop/front/__init__.py
- shoop/front/admin_module/__init__.py
- shoop/front/admin_module/carts/views/__init__.py
- shoop/front/admin_module/carts/views/_list.py
- shoop/front/locale/en/LC_MESSAGES/django.po
- shoop/utils/i18n.py
- shoop_tests/admin/test_picotable.py
Add an admin carts module that allows merchants to monitor abanded
user carts, total sales, date since last update, and other
useful information.
Refs SHOOP-2237
> Admin: Add carts module for monitoring abandoned carts

- shoop/admin/modules/services/__init__.py
- shoop/admin/modules/services/views/__init__.py
- shoop/admin/modules/services/views/_delete.py
- shoop/admin/modules/services/views/_edit.py
- shoop/core/models/_service_payment.py
- shoop/core/models/_service_shipping.py
- shoop_tests/admin/test_services.py
Do not allow delete if shipping or payment method is linked to order
> Admin: Enable deleting unused shipping and payment methods (SHOOP-2051)

- doc/changelog.rst
- shoop/front/checkout/methods.py
- shoop/themes/classic_gray/static_src/less/classic-gray/methods.less
- shoop/themes/classic_gray/static_src/less/style.less
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/method_choice.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/methods.jinja
- shoop_tests/front/test_methods_phase.py
* Create custom method widget to render method logo and description in
checkout.
* Group methods by service provider and also show service provider
logo or name at the methods phase in checkout
> Front: Enable description and logo for methods in checkout (SHOOP-2406)

- shoop/admin/modules/services/views/_edit.py
New services couldn't be created since the delete url is not available
in new mode.
Refs SHOOP-2051 / SHOOP-2418
> Admin: In service admin set delete url to None in new mode

- doc/changelog.rst
- shoop/core/shortcuts/__init__.py
- shoop_tests/core/test_basic_order.py
Assing product name into order line text instead of name
> Core: Fix for updating order line from product in shortcuts (SHOOP-2443)

- setup.py
Remove usage of "~=" version specifier and allow django-polymorphic 0.9.
It seems that "~=" version specifier is not supported by older
setuptools version and this causes problems e.g. with Ubuntu 14.04.
Also, django-polymorphic 0.9 seems to work too (as noticed while doing
SHOOP-2293).
> setup.py: Update version specifiers (SHOOP-2150)

- shoop/front/template_helpers/product.py
- shoop/themes/classic_gray/plugins.py
- shoop_tests/themes/classic_gray/test_plugins.py
Fix the inital configuriaton for the cross sells plugin.
Currently, configuration is stored as an enum, but initial settings
are received as a string. These are now mapped to the correct enum
type on initialization.
Refs SHOOP-2409
> Classic gray: Fix initial config for cross sells plugin

- doc/changelog.rst
- shoop/admin/modules/contacts/views/detail.py
- shoop/admin/templates/shoop/admin/contacts/detail.jinja
- shoop/core/models/_base.py
- shoop/core/models/_contacts.py
- shoop_tests/admin/test_contact_page.py
- shoop_tests/core/test_contacts.py
If contact belongs to multiple groups, the contact details views used to
fail on Python 3, since there was a call `contact.groups.all()|sort` in the
template, which tries to sort ContactGroup objects.  Fix this by adding
sorted contacts to the context and remove sorting from the template.
Also while at it:
* Render the contact groups as links.
* Add test case for this.
* Fix ContactGroupQuerySet to derive from TranslatableQuerySet.
And since I got some problems rendering the details page in Finnish,
because my contact groups didn't have Finnish translations, add a fix
for that too in TranslatableShoopModel.
> Admin: Fix contact detail page with many groups (SHOOP-2397)

- setup.py
Remove couple more usages of "~=" version specifiers which were
forgotten in commit b1508010.
Allow newer djangorestframework, since it now works, as long as also
django-parler-rest is updated to 1.3.
> Update requirements more (SHOOP-2150)

- doc/changelog.rst
- shoop/admin/modules/products/views/toolbars.py
In case variation children included in some package. ``EditProductToolbar``
show only variation siblings. This makes also package siblings visible for
variation child that is in product package.
Refs SHOOP-2387
> Admin: Show package siblings for variation children

- doc/changelog.rst
- shoop/admin/locale/en/LC_MESSAGES/django.po
- shoop/admin/templates/shoop/admin/orders/detail.jinja
- shoop/core/models/_orders.py
- shoop/themes/classic_gray/locale/en/LC_MESSAGES/django.po
- shoop/themes/classic_gray/templates/classic_gray/shoop/personal_order_history/order_detail.jinja
- shoop_tests/core/test_tracking_codes.py
Core: Add ``get_tracking_codes`` to ``shoop.core.models.Order``
Admin: Show tracking codes in order detail
Classic Gray Theme: Show tracking codes in order detail
> Make tracking codes visible ( SHOOP-2281)

- doc/changelog.rst
- shoop/admin/modules/products/views/toolbars.py
Don't allow converting to childeren or package parent if the product
is already variation or package product.
Refs SHOOP-2387
> Admin: Fix convert to parent menu items in ``EditProductToolbar``

- shoop_setup_utils/finding.py
Port our FastFindPackages speed-up to work with newer setuptools.  Since
version 18.2 of setuptools, there is no longer `_all_dirs` function, but
rather `_candidate_dirs` which does more or less the same thing.
This makes all "setup.py" commands, with a fresh setuptools, much faster
when ran from a checkout which has node_modules and bower_components.
> shoop_setup_utils: Speed-up for setuptools 18.2 or newer

- shoop/simple_supplier/admin_module/forms.py
- shoop_tests/simple_supplier/test_simple_supplier.py
Fix bug when creating new product with simple supplier set as
default by only rendering stock management form for saved products.
Refs SHOOP-2207
> Simple Supplier: Fix product create view bug

- setup.py
- shoop_setup_utils/__init__.py
- shoop_setup_utils/excludes.py
- shoop_setup_utils/resource_building.py
The shoop_setup_utils package provides a nice way to do resource
generating on "setup.py build" phase.  It is used here in Shoop, but it
is also useful for Shoop addons.
Improve it a bit so that is more useful for addons.  See the commit
messages for details.
> Improve shoop_setup_utils for addons (SHOOP-2507)

- doc/changelog.rst
- shoop/order_printouts/templates/shoop/order_printouts/admin/macros.jinja
Display tax rates in order printouts as percentages.
Refs SHOOP-2490
> Order printouts: Fix tax rate percent display

- doc/changelog.rst
- shoop/core/models/_shipments.py
- shoop_tests/core/test_basic_order.py
- shoop_tests/core/test_orders.py
- shoop_tests/core/test_shipment_weights.py
Instead of ``Product`` and ``ShipmentProduct`` ``Shipment`` weights  are
stored as a kilograms.
Add the missing grams to kilograms conversion in ``Shipment.cache_values``
> Core: Convert ``Shipment`` weights to kilograms (SHOOP-2494 / SHOOP-2511)

- doc/changelog.rst
- shoop/admin/forms/widgets.py
- shoop/admin/modules/products/forms/package_forms.py
- shoop/admin/modules/products/views/list.py
When adding products to a package product, hide invalid choices,
including variation parents and package products.
Refs SHOOP-2389
Notes: There might be a better way to do this. The browse widget has a built-in "filter" parameter, however since we need to use Q objects to filter multiple valid modes, I had to implement a workaround by just indicating the "mode" in the filter setting.
> Admin: Hide invalid package product choices (SHOOP-2389)

- doc/api/shoop.admin.modules.services.rst
- doc/api/shoop.admin.modules.services.weight_based_pricing.rst
- doc/api/shoop.campaigns.rst
- shoop/campaigns/models/contact_group_sales_ranges.py
- shoop/campaigns/signal_handlers.py
- shoop/campaigns/utils.py
- shoop_tests/campaigns/test_sales_ranges.py
Add automatic update to customer groups based on sales range when
sales ranges are created or edited.
Refs SHOOP-2439
> Campaigns: Add automatic update for sales range groups (SHOOP-2439)

- doc/changelog.rst
- shoop/admin/locale/en/LC_MESSAGES/django.po
- shoop/admin/modules/orders/views/detail.py
- shoop/core/models/_orders.py
- shoop_tests/admin/test_order_module.py
Enable cancelation in admin Order edit view for unpaid and unshipped
orders.
Refs SHOOP-2401
> Admin: Enable order cancelation in Order edit view (SHOOP-2401)

- doc/api/shoop.admin.modules.orders.views.rst
- doc/changelog.rst
- shoop/admin/locale/en/LC_MESSAGES/django.po
- shoop/admin/locale/en/LC_MESSAGES/djangojs.po
- shoop/admin/modules/orders/__init__.py
- shoop/admin/modules/orders/views/__init__.py
- shoop/admin/modules/orders/views/detail.py
- shoop/admin/modules/orders/views/payment.py
- shoop/admin/templates/shoop/admin/orders/_order_contents.jinja
- shoop/admin/templates/shoop/admin/orders/create_payment.jinja
- shoop/admin/templates/shoop/admin/orders/detail.jinja
- shoop/core/models/_orders.py
- shoop_tests/core/test_orders.py
Add payment creation view to order admin.
Refs SHOOP-2399
> Add payment creation view to order admin (SHOOP-2399)

- doc/changelog.rst
- shoop/core/migrations/0022_change_order_method_name_lengths.py
- shoop/core/models/_orders.py
- shoop_tests/core/test_methods.py
Make max length for shipping and payment method names in `Order` the
same as max length for model names.
Refs SHOOP-2489
> Core: Change max length for service method names in `Order` (SHOOP-2489)

- shoop/admin/modules/orders/views/detail.py
I think there is an error in the logic for cancelling orders. The "else" here should only be executed when given a status of "canceled".
> Admin: Order cancelation logic fix

- doc/changelog.rst
- shoop/front/checkout/addresses.py
- shoop/front/checkout/single_page.py
- shoop/front/settings.py
- shoop_tests/front/test_checkout.py
Add SHOOP_FRONT_REQUIRED_ADDRESS_FIELDS setting to define required
address settings in checkout address form in addition to those defined
at the model leve.
Refs SHOOP-2503
> Front: Make required fields of address configurable (SHOOP-2503)

- shoop/testing/templates/shoop_testing/simple_checkout_phase.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/_base.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/_buttons.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/addresses.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/confirm.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/empty.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/methods.jinja
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/single_phase.jinja
* Add block checkout_phase_content which can be wrapped with appropriate
container elements in themes by overriding the content block in
`checkout/_base.jinja`.
* Also add macros for rendering the buttons.
* Use new template API for the test checkout phase
> Make checkout templates easier to extend (SHOOP-2537)

- doc/changelog.rst
- shoop/core/order_creator/__init__.py
- shoop/core/order_creator/_creator.py
- shoop/core/order_creator/_modifier.py
- shoop_tests/core/test_order_modifier.py
Add OrderModifier class which can be used to modify existing orders using an OrderSource.
This is the first part of enabling editing orders.  Splitting the PR #466 to two pieces to make it easier to review.  The leftover commits will for the second part.
> Add OrderModifier (SHOOP-2338)

- shoop/admin/modules/orders/views/edit.py
- shoop/core/order_creator/_modifier.py
Core: Enable modifying orders with taxes
Admin: Use correct taxed prices for order editing
> Fix tax bugs in order edit (SHOOP-2338, SHOOP-1993)

- shoop/front/template_helpers/general.py
``Supplier.get_suppliable_products`` returns list of shop product pk's.
Missing tests since SHOOP-2576 will change this logic completely at the end of this week.
> Front: Filter suppliable products correctly

- doc/api/shoop.admin.modules.orders.views.rst
- doc/changelog.rst
- shoop/admin/locale/en/LC_MESSAGES/django.po
- shoop/admin/locale/en/LC_MESSAGES/djangojs.po
- shoop/admin/modules/orders/__init__.py
- shoop/admin/modules/orders/views/__init__.py
- shoop/admin/modules/orders/views/detail.py
- shoop/admin/modules/orders/views/log.py
- shoop/admin/templates/shoop/admin/orders/_order_log_entries.jinja
- shoop/admin/templates/shoop/admin/orders/detail.jinja
- shoop_tests/admin/test_order_module.py
Enable adding log entries to orders
Merchant can create `note` log entries for orders under `Log
Entries` in order detail view.
Refs SHOOP-2240
> Admin: Enable adding log entries to orders

- shoop/campaigns/admin_module/form_parts.py
- shoop/campaigns/models/contact_group_sales_ranges.py
- shoop/campaigns/utils.py
- shoop_tests/campaigns/test_sales_ranges.py
Campaigns: Save sales ranges only when the forms data is changed
Campaigns: Update group members in sales range save
> Update group members in sales range (SHOOP-2609)

- doc/changelog.rst
- shoop/core/order_creator/_source.py
- shoop/core/pricing/_priceful.py
- shoop/core/taxing/_line_tax.py
- shoop/core/taxing/_module.py
- shoop/core/taxing/_tax_summary.py
- shoop/core/taxing/utils.py
- shoop/default_tax/module.py
- shoop/front/basket/objects.py
- shoop/utils/money.py
- shoop_tests/core/test_orders.py
- shoop_tests/core/test_utils_prices.py
- shoop_tests/functional/test_discount_taxing.py
- shoop_tests/functional/test_tax_system.py
Implement taxing of lines without a tax class, especially discount
lines.
Has some other related changes too.  See the commit messages for
details.
> Taxing of lines without tax class (SHOOP-2077)

- doc/changelog.rst
- shoop/core/models/__init__.py
- shoop/core/models/_contacts.py
- shoop/front/middleware.py
- shoop_tests/core/test_contacts.py
- shoop_tests/front/test_middleware.py
Associate company members with company contact details by default.
If a user's PersonContact is a member of a CompanyContact, use the
company's contact details by default.
This replaces PR #486.
> Log-in as company (SHOOP-884)

- doc/changelog.rst
- shoop/admin/modules/orders/json_order_creator.py
- shoop/admin/modules/orders/views/edit.py
- shoop/campaigns/modules.py
- shoop/core/locale/en/LC_MESSAGES/django.po
- shoop/core/migrations/0024_add_order_modified_info.py
- shoop/core/migrations/0025_add_codes_for_order.py
- shoop/core/models/_orders.py
- shoop/core/order_creator/_creator.py
- shoop/core/order_creator/_modifier.py
- shoop/core/order_creator/_source.py
- shoop/core/order_creator/_source_modifier.py
- shoop_tests/admin/test_order_creator.py
- shoop_tests/campaigns/test_discount_codes.py
- shoop_tests/core/test_order_creator.py
- shoop_tests/core/test_order_modifier.py
- shoop_tests/functional/test_order_edit_with_coupons.py
Core: Add modified by and modified on for orders
Admin: Preserve data for unhandled fields in order edit
Test that coupon usages is added correctly
Campaigns: Preserve coupon codes in order edit
> Preserve order data while editing (SHOOP-2587)

- doc/changelog.rst
- shoop/core/order_creator/_creator.py
- shoop/core/order_creator/_source.py
- shoop_tests/core/test_product_packages.py
Parent lines were never assigned for child lines, because the code was
simply incorrect.  It used `source_line.parent_line_id` even though package
products are not expanded in the source, i.e. the child lines don't exist
there. Rewrite the parent linkage code to fix it.
This also fixes how tax lines are set for the child lines.  Previously
child lines incorrectly got taxes of the parent line, since their source
line was set to the parent line.  Now child lines get taxes from the
corresponding child line in the source, if there is such source line. Child
lines that don't exist in the source won't get any taxes.  This works
correctly e.g. for the child product lines of a package product.
Also add test cases for the parent linkage and child line taxing bugs, plus
another test case for making …
> OrderCreator: Fix parent line linking and taxing (SHOOP-2622)

- shoop/themes/classic_gray/templates/classic_gray/shoop/front/order/payment_canceled.jinja
The URL for "Retry payment" button was empty, because it used incorrect
property name `payment`.  Fix it to use the correct `payment_url` which
actually exists in `PaymentUrls` class.
> Classic Gray: Fix "Retry payment" (SHOOP-2677)

- shoop_tests/utils/test_patterns.py
Add a test case which demonstrates how same pattern can match in two
different ways: numerically and alphabetically.  Results might be
somewhat unexpected when the numbers are different length.  It is a good
idea to point out this oddity with a test case.
Refs SHOOP-2607
> Test case for numeric/alphabetic pattern match

- shoop/xtheme/rendering.py
In case when view has both normal and global placeholders in it the
normal view config for the view can't be used for the global
placeholders.
In ``xtheme.rendering:get_view_config`` use _xtheme_global_view_config
as a config key for global view configs.
> XTheme: Get global view config separately (SHOOP-2666)

- doc/changelog.rst
- shoop/core/fields/__init__.py
- shoop_tests/core/test_fields.py
Fix decimal notation on model decimal fields so values do not display
in scientific notation (i.e., a value of `0` rendering as `0E-9`).
Refs SHOOP-2616
> Core: Fix decimal notation on model decimal fields (SHOOP-2616)

- shoop/campaigns/forms.py
- shoop_tests/campaigns/test_admin.py
Fix form population bug in Campaigns Admin when populating
non-many-to-many fields.
Refs SHOOP-2617
> Campaigns: Fix form population bug in Campaigns Admin

- doc/changelog.rst
- shoop/front/checkout/addresses.py
- shoop_tests/front/test_checkout.py
Only add company info form fields if user is not logged in
Ref SHOOP-2643
> Front: Remove "Ordering for company" from checkout if logged in

- shoop/admin/templates/shoop/admin/auth/logout.jinja
stack buttons vertically instead of horizontally.
Note layout bugs due to translations will likely become a more widespread issue. We should probably come up with a more general-purpose strategy (shrinking fonts/clipping/using ellipsis).
> Admin: Sign in again in finnish language goes over the box (SHOOP-2691)

- doc/changelog.rst
- shoop/admin/locale/en/LC_MESSAGES/django.po
- shoop/admin/modules/contacts/views/detail.py
- shoop/core/models/_contacts.py
- shoop/front/apps/auth/forms.py
- shoop_tests/admin/test_contact_module.py
- shoop_tests/front/test_auth.py
Add a login check so that inactive contacts cannot log into front.
Enable contact deactivation from Contact list view under Shoop Admin.
Refs SHOOP-2236
> Admin: Enable contact deactivation (SHOOP-2236)

- doc/changelog.rst
- shoop/admin/modules/orders/views/edit.py
Round product prices to 2 decimals since the total is also rounded and more
than 2 decimals will cause problems with discounts.
> Admin: Add product price rounding in order edit (SHOOP-2640)

- doc/changelog.rst
- shoop/admin/modules/orders/views/edit.py
Reverts PR #522. It's incorrect, since unit prices should not be rounded. See the comments in PR #522 for details.
> Revert "Admin: Add product price rounding in order edit (SHOOP-2640)"

- shoop/admin/static_src/picotable/picotable.js
Initialize default filters in the UI for picotable views
that are rendered in the mobile view (ie popups).
Refs SHUUP-2744
> Fix default filters for mobile picotable views (SHUUP-2744)

- shoop/xtheme/templates/shoop/xtheme/_model_widget.jinja
Ensure selected value comparison is done using the same datatypes.
Refs SHUUP-2748
> Fix selected value for XThemeModelChoiceWidget (SHUUP-2748)

- shoop/xtheme/plugins/social_media_links.py
Fix 'URL' KeyError thrown when attempting to save the social
media links config form
Refs SHUUP-2747
> Xtheme: Fix social media plugin error on save (SHUUP-2747)

- doc/changelog.rst
- shoop/admin/modules/orders/static_src/create/actions/index.js
- shoop/admin/modules/orders/static_src/create/reducers/lines.js
- shoop/admin/modules/orders/views/edit.py
- shoop_tests/campaigns/test_catalog_campaigns.py
Fix line item pricing to reflect customer/campaign discounts for admin
order editor. Use `product.get_price_info` to get prices.
Refs SHUUP-2721, SHUUP-2719
> Update product prices when customer is changed (SHUUP-2719, SHUUP-2721)

- doc/changelog.rst
- shoop/admin/locale/en/LC_MESSAGES/djangojs.po
- shoop/admin/modules/orders/static_src/create/reducers/lines.js
- shoop/admin/modules/orders/static_src/create/view/lines.js
- shoop/admin/modules/orders/views/edit.py
- shoop_tests/admin/test_order_creator.py
Show physical and logical stock counts to merchant when he is creating
an order.
Refs SHUUP-2730
> Admin: Show stock on order creation (SHUUP-2730)

- shoop/front/apps/auth/forms.py
- shoop/front/middleware.py
- shoop_tests/core/test_contacts.py
* Front: Authentication form: Use get_person_contact
* Front: Middleware: Explicitly change inactive person to anonymous
* Document AnonymousContact tests a bit
> Tune details of inactive contact checks (SHUUP-2845)

- doc/api/shoop.admin.modules.orders.rst
- doc/api/shoop.admin.modules.product_types.views.rst
- doc/api/shoop.campaigns.models.rst
- shoop/campaigns/apps.py
- shoop/campaigns/locale/en/LC_MESSAGES/django.po
- shoop/campaigns/migrations/0007_freeproductline.py
- shoop/campaigns/models/__init__.py
- shoop/campaigns/models/basket_line_effects.py
- shoop/campaigns/modules.py
- shoop/core/order_creator/_source.py
- shoop/front/basket/objects.py
- shoop_tests/campaigns/test_basket_campaigns.py
- shoop_tests/campaigns/test_effects.py
Included:
* Core: Add `line_source` to `SourceLine`
* Core: Add `Enum` `LineSource` that contains four different identifiers.
* Core: Add `SourceLine.line_source` to identify lines.
* Modify `can_delete()` and `can_change_quantity()` to take `LineSource` into account in `BasketLine`
* Campaigns: Add Buy X get Y campaign
Refs SHUUP-2733
> Buy X get Y campaign (SHUUP-2733)

- shoop/admin/modules/orders/static_src/create/reducers/lines.js
- shoop/admin/modules/orders/views/edit.py
* Admin order creator: Return unit prices when fetching product data
* Admin order creator: Reduce discount amount precision to two decimals
* Admin order edit: Do not preserve lines with parent
> Tune order editor/creator prices (SHUUP-2853, SHUUP-2640)

- shoop/front/checkout/addresses.py
- shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/addresses.jinja
Some assumptions:
Grabbed data from customer instead of person object. i.e. Use saved company address if exists else use saved account address if exists.
Changed the default checkbox option for "Ship to my billing address" to unchecked.
> saved address (from customer) now populates fields in checkout

- shoop/utils/numbers.py
Add function for rounding numbers to a specific quant, like 0.05.  This may be useful e.g. for rounding prices for cash payments.
This implements the function I proposed in a comment of PR #522: https://github.com/shuup/shuup/pull/552/files#r67639992
> utils: Add nickel_round function (SHUUP-2723)

- doc/changelog.rst
- shoop/core/pricing/_price.py
- shoop/utils/_unitted_decimal.py
- shoop/utils/money.py
- shoop/utils/numbers.py
- shoop_tests/utils/test_unitted_decimal.py
It's a decimal with an unit.  The original name was just bad spelling.
> Rename UnitedDecimal to UnittedDecimal (SHUUP-2879)

- shoop/campaigns/admin_module/forms/_base.py
Set queryset none for field initial when instance is not set
> Campaigns: Fix for admin process fields

- doc/changelog.rst
- shoop/admin/__init__.py
- shoop/admin/modules/orders/receivers.py
- shoop/admin/modules/services/forms.py
- shoop/core/locale/en/LC_MESSAGES/django.po
- shoop/core/migrations/0028_roundingbehaviorcomponent.py
- shoop/core/models/__init__.py
- shoop/core/models/_service_behavior.py
- shoop/core/models/_service_payment.py
- shoop_tests/admin/test_service_behavior_components.py
- shoop_tests/core/test_custom_payment_processor.py
- shoop_tests/core/test_rounding_behavior_component.py
Add cash payments to the custom payment processor which sets created orders
to fully paid on creation. Also add rounding behavior component to round
order totals to the nearest 0.05.
Refs SHUUP-2723
> Add cash payment method (SHUUP-2723)

- doc/changelog.rst
- shoop/admin/locale/en/LC_MESSAGES/djangojs.po
- shoop/admin/modules/contacts/views/detail.py
- shoop/admin/modules/orders/static_src/create/actions/index.js
- shoop/admin/modules/orders/static_src/create/index.js
- shoop/admin/modules/orders/static_src/create/reducers/customerDetails.js
- shoop/admin/modules/orders/static_src/create/reducers/index.js
- shoop/admin/modules/orders/static_src/create/view/customers.js
- shoop/admin/modules/orders/static_src/create/view/lines.js
- shoop/admin/modules/orders/static_src/create/view/utils.js
- shoop/admin/modules/orders/views/edit.py
- shoop/admin/static_src/base/less/shoop/content-blocks.less
- shoop/admin/static_src/base/less/vendor.less
- shoop_tests/admin/test_order_creator.py
Add new modal for admin order creation that shows detailed customer info,
order summary, and recent orders.
Refs SHUUP-2725
> Add customer detail modal to admin order creator (SHUUP-2725)

- doc/changelog.rst
- shoop/admin/locale/en/LC_MESSAGES/django.po
- shoop/admin/modules/orders/__init__.py
- shoop/admin/modules/orders/sections.py
- shoop/admin/modules/orders/views/__init__.py
- shoop/admin/modules/orders/views/detail.py
- shoop/admin/modules/orders/views/refund.py
- shoop/admin/templates/shoop/admin/orders/_refund_order_contents.jinja
- shoop/admin/templates/shoop/admin/orders/create_full_refund.jinja
- shoop/admin/templates/shoop/admin/orders/create_refund.jinja
- shoop/core/excs.py
- shoop/core/locale/en/LC_MESSAGES/django.po
- shoop/core/models/_order_lines.py
- shoop/core/models/_orders.py
- shoop/core/signals.py
- shoop_tests/admin/test_refund_creator.py
- shoop_tests/core/test_orders.py
- Add core support for refunds
- Add refund creator in Orders admin
- Show log entries section or all orders
Refs SHUUP-2400, SHUUP-2821, SHUUP-2874, SHUUP-2875, SHUUP-2877
> Add order refunds (SHUUP-2400, SHUUP-2821, SHUUP-2874, SHUUP-2875, SHUUP-2877)

- doc/changelog.rst
- shoop/admin/__init__.py
- shoop/admin/modules/services/forms.py
- shoop/core/locale/en/LC_MESSAGES/django.po
- shoop/core/migrations/0031_staffonlybehaviorcomponent.py
- shoop/core/models/__init__.py
- shoop/core/models/_service_behavior.py
- shoop/core/models/_service_payment.py
- shoop_tests/admin/test_service_behavior_components.py
- shoop_tests/core/test_custom_payment_processor.py
- shoop_tests/core/test_rounding_behavior_component.py
- shoop_tests/core/test_staff_only_behavior.py
* Add staff only behavior component
* Add fix to support empty forms and forms with initial values
* Update `CustomPaymentProcessor` to use `RoundingBehaviorComponent` and
`StaffOnlyBehaviorComponent` by default when service is "cash"
* Remove `get_unavailability_reasons` from `RoundingBehaviorComponent`
* Use better dispatch_uid for order created signal
Refs SHUUP-2888
> Cash payment fixes and improvements (SHUUP-2888)

- shoop/admin/modules/permission_groups/views/edit.py
If admin modules do not have names set, do not allow as choices in
the `PermissionGroup` admin since there is no way to differentiate
modules when selecting modules to grant permissions.
Refs SHUUP-2901
> Admin: Only allow permissions for named modules

- doc/changelog.rst
- shoop/core/migrations/0001_initial.py
- shoop/core/models/_categories.py
Since Category is a MPTT model, it should be ordered appropriately when
doing queries.  Make that happen by adding correct ordering specifier
to Category classes meta attributes.
This should fix ValueErrors like this for Category query sets:
Node <class 'parler.managers.TranslatableQuerySet'> not in
depth-first order
> Core: Add ordering for Category model (SHUUP-2671)

- shoop/core/migrations/0028_roundingbehaviorcomponent.py
- shoop/core/models/_service_behavior.py
Length of the mode column should be enough to hold the string values of
the decimal rounding constants.  Currently longest of them
"ROUND_HALF_DOWN", which is 15 characters.  Update the length of the
column from 10 to 50 to make all values fit (and leave some space for
possibly longer values in the future).
> Core: Fix RoundingBehaviorComponent.mode length (SHUUP-2913)

- shoop_tests/admin/test_permission_groups_module.py
- shoop_tests/admin/test_permissions.py
Test that all url and module-level permissions are valid for enabled
modules.
Also test that only modules with defined names are shown as choices in
`PermissionGroup` admin.
Refs SHUUP-2909
> Admin: Add permission-related tests

- shuup/campaigns/models/catalog_filters.py
Filter with product_id instead of products. This will make the queryset much
faster since only id's is fetched for products and extra joins is avoided.
> Campaigns: Make catalog filters faster

- shuup/simple_cms/plugins.py
- shuup_tests/simple_cms/test_plugins.py
Instead of allowing only pages visible in menu allow all visible pages
for merchant to set in page plugin.
> Simple CMS: Enable Page plugin for all visible pages (SHUUP-2931)

- doc/changelog.rst
- shuup/admin/modules/orders/json_order_creator.py
- shuup/admin/modules/orders/views/edit.py
- shuup_tests/admin/test_order_creator.py
* Remove orderability checks while fetching product data
* Add ``AdminOrderSource`` to skip validation
* Add ``AdminOrderCreator`` and ``AdminOrderModifier`` to skip
orderability checks
> Admin: Remove orderability checks from admin order editor (SHUUP-2934)

- doc/changelog.rst
- shuup/guide/admin_module.py
- shuup/guide/settings.py
Fix admin search when Shuup Guide URL settings result in invalid
response.
Additionally, temporarily fix default Shuup Guide URL settings.
Refs SHUUP-2938
> Guide: Fix admin search for invalid API URL settings

- doc/changelog.rst
- shuup/campaigns/migrations/0002_productsinbasketcondition_operator.py
- shuup/campaigns/models/basket_conditions.py
- shuup_tests/campaigns/test_basket_product_conditions.py
Add 'exact' or 'greater than or equal to' comparisons on
`ProductsInBasketCondition` quantities.
Refs SHUUP-2957
> Add comparison op to ProductsInBasketCondition (SHUUP-2957)

- doc/changelog.rst
- shuup/core/models/_categories.py
- shuup_tests/core/test_categories.py
Remove duplicates in case category have multiple visibility groups set.
Remove order_by from all_visible-filter as unnecessary. The category
meta already defines the default ordering.
> Core: Prevent duplicate categories from all_visible-filter

- doc/changelog.rst
- shuup/admin/modules/categories/__init__.py
- shuup/admin/modules/contacts/__init__.py
- shuup/admin/modules/contacts/views/detail.py
- shuup/admin/modules/products/__init__.py
- shuup/admin/modules/shops/__init__.py
- shuup/admin/template_helpers/shuup_admin.py
- shuup/admin/templates/shuup/admin/contacts/detail.jinja
- shuup/admin/templates/shuup/admin/macros/order_view.jinja
- shuup/admin/toolbar.py
- shuup/admin/utils/picotable.py
- shuup/admin/utils/urls.py
- shuup/admin/views/dashboard.py
- shuup_tests/admin/test_modules.py
- shuup_tests/admin/test_permissions.py
- shuup_tests/admin/test_urls.py
Add permission checks for:
- Toolbar buttons
- shuup.admin.utils.url.get_model_url
- shuup.admin.template_helpers.shuup_admin.model_url
- Dashboard blocks
- Fixes for various modules
Refs SHUUP--2898
> Permission fixes (SHUUP-2898)

- shuup/admin/templates/shuup/admin/orders/create_refund.jinja
- shuup/core/models/_orders.py
* Ensure new form is visible when "Add More Refunds" is clicked.
* Ensure products are restocked when full refunds are done with the product
restock checkbox ticked.
> Refund fixes (SHUUP-3031, SHUUP-3032)

- shuup/core/models/_orders.py
- shuup_tests/core/test_orders.py
Fix negative quantities when refunding shipped items.
Also fix related error in `Order.get_product_summary` when querying
refunded product lines.
Refs SHUUP-2917
> Core: Fix negative quantities when refunding shipped items

- shuup/campaigns/admin_module/forms/_basket_effects.py
Make percentage field not required for DiscountFromCategoryProductsForm.
The form field shouldn't be required based on model field.
> Campaigns: Fix bug in DiscountFromCategoryProductsForm (SHUUP-3043)

- shuup/admin/modules/orders/views/edit.py
Fix NOT NULL constraint violation for tax number when creating orders
through admin for person contacts and company contacts without an address.
Refs SHUUP-3053
> Ensure tax number is not null (SHUUP-3053)

- shuup/core/order_creator/_modifier.py
- shuup/testing/factories.py
- shuup_tests/core/test_order_modifier.py
- shuup_tests/core/test_product_packages.py
Ensure child order lines are deleted before parent lines when editing
an order through admin order creator.
Refs SHUUP-3061
> Fix order edit for orders with child lines (SHUUP-3061)

- doc/api/shuup.admin.modules.contacts.rst
- doc/changelog.rst
- doc/provides.rst
- shuup/admin/__init__.py
- shuup/admin/base.py
- shuup/admin/modules/contacts/sections.py
- shuup/admin/modules/contacts/views/detail.py
- shuup/admin/modules/contacts/views/edit.py
- shuup/admin/modules/orders/sections.py
- shuup/admin/modules/orders/views/detail.py
- shuup/admin/templates/shuup/admin/contacts/_contact_addresses.jinja
- shuup/admin/templates/shuup/admin/contacts/_contact_basic_info.jinja
- shuup/admin/templates/shuup/admin/contacts/_contact_members.jinja
- shuup/admin/templates/shuup/admin/contacts/_contact_orders.jinja
- shuup/admin/templates/shuup/admin/contacts/detail.jinja
- shuup/admin/templates/shuup/admin/macros/general.jinja
- shuup/testing/__init__.py
- shuup/testing/admin_module/sections.py
- shuup/testing/admin_module/toolbar.py
- shuup/testing/templates/shuup_testing/_contact_mock_section.jinja
- shuup_tests/admin/test_contact_extensibility.py
Makes contact views extendable similar to Order views
Adds three new extensibility points into the contact views using the provides system.
- `admin_contact_toolbar_button` and `admin_contact_edit_toolbar_button`
provide toolbar extensibility for detail and edit views respectively.
- `admin_contact_section` makes it easy to add additional sections to contacts detail view.
The existing contact detail view was refactored to take advantage of the new sections system.
Refs SHUUP-2892
> Make contact views extendable

- shuup/core/models/_units.py
When the unit name contains unicode chars an exception is raised on python 2.7
> Fix: removed unnecessary str() call for python2 compatible class

- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/products/views/toolbars.py
- shuup/admin/templates/shuup/admin/products/edit.jinja
Create a 'Save as a copy' button on product admin toolbar to make it easier to duplicate products.
> Admin: Create a 'Save as a copy' button on product toolbar

- doc/changelog.rst
- shuup/simple_cms/templates/shuup/simple_cms/plugins/page_links.jinja
- shuup_tests/simple_cms/test_plugins.py
Make sure plugin only renders absolute links.
Refs SHUUP-3119
> Simple CMS: Fix plugin links

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/locale/en/LC_MESSAGES/djangojs.po
- shuup/admin/modules/categories/__init__.py
- shuup/admin/modules/categories/forms.py
- shuup/admin/modules/categories/views/__init__.py
- shuup/admin/modules/categories/views/copy.py
- shuup/admin/templates/shuup/admin/categories/_edit_base_form.jinja
- shuup/admin/templates/shuup/admin/categories/edit.jinja
- shuup_tests/admin/test_category_module.py
Add the ability to copy category visibility settings to products with the
corresponding main category. Also copy category visibility settings over to
products when using the category product management form.
Refs SHUUP-3069
> Admin: Copy category visibility to products (SHUUP-3069)

- doc/changelog.rst
- shuup/admin/static_src/picotable/picotable.js
Refresh the table when enter is pressed, input value is empty or on outside focus.
Reloading picotable on every filter change causes unwanted bouncing with letters
since the whole page is reloaded isntead of just updating the rows.
> Admin: Prevent picotable from reloading after every change (SHUUP-3063)

- doc/changelog.rst
- shuup/core/models/_service_payment.py
- shuup/testing/factories.py
- shuup_tests/core/test_custom_payment_processor.py
- shuup_tests/core/test_methods.py
Make payments for `CustomPaymentProcessor` not paid instead of deferred
by default to allow orders with manual service methods to be edited in
admin.
Refs SHUUP-3118
> Core: Make payments for `CustomPaymentProcessor` not paid

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/orders/views/refund.py
- shuup/admin/templates/shuup/admin/orders/create_refund.jinja
- shuup/core/excs.py
- shuup/core/locale/en/LC_MESSAGES/django.po
- shuup/core/migrations/0003_update_orderline_refunds.py
- shuup/core/models/_order_lines.py
- shuup/core/models/_orders.py
- shuup/core/suppliers/enums.py
- shuup/simple_supplier/module.py
- shuup/simple_supplier/utils.py
- shuup/testing/factories.py
- shuup_tests/admin/test_refund_creator.py
- shuup_tests/core/test_orders.py
- shuup_tests/functional/test_refunds.py
* Add `StockAdjustmentType` `RESTOCK_LOGICAL` which allows restocking
unshipped products. If an order is partially shipped, restock from the
unshipped inventory first.
* Merge `OrderLineType.QUANTITY_REFUND` and `OrderLineType.AMOUNT_REFUND`
into `OrderLineType.REFUND`. Set refundable quantity and amount as default.
* Create refund order line with equal magnitude and opposite sign
when creating a full refund.
* Create tax lines with `tax_rate` instead of proportionally.
Refs SHUUP-3114, SHUUP-3036
> Refund inventory, discount, and tax fixes (SHUUP-3114, SHUUP-3036)

- doc/changelog.rst
- shuup/customer_group_pricing/templates/shuup/admin/customer_group_pricing/form_part.jinja
Make more than 2-3 contactgroups usable at the same time by re-organising the layout.
Make it responsive.
Refs SHUUP-3011
> Re-style contactgroup pricing form (SHUUP-3011)

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/users/__init__.py
- shuup/admin/modules/users/views/__init__.py
- shuup/admin/modules/users/views/detail.py
- shuup/front/checkout/_mixins.py
- shuup/front/checkout/confirm.py
- shuup/front/checkout/single_page.py
- shuup_tests/admin/test_user_module.py
* Add "Login as User" button to user detail screen which allows superadmins
to login as customers.
* Set `order.creator` to impersonator
* Misc: Fix single page checkout view for customers not associated with a company
Refs SHUUP-2968
> Allow superadmins to login as customers (SHUUP-2968)

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/templates/shuup/admin/products/_edit_shop_form.jinja
- shuup/core/locale/en/LC_MESSAGES/django.po
- shuup/core/migrations/0003_shopproduct_backorder_maximum.py
- shuup/core/models/_product_shops.py
- shuup/core/suppliers/base.py
- shuup_tests/core/test_suppliers.py
Allow products to be sold after stock logical count is less than or equal to zero.
> Add orderable minimum (SHUUP-3049, SHUUP-3052)

- doc/changelog.rst
- shuup/simple_cms/admin_module/views.py
- shuup/simple_cms/locale/en/LC_MESSAGES/django.po
- shuup_tests/simple_cms/test_page_creation.py
Add a form error when setting parent page to itself rather than raising
an exception.
Refs SHUUP-3083
> Simple CMS: Add error when setting parent to self (SHUUP-3083)

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/locale/en/LC_MESSAGES/djangojs.po
- shuup/admin/modules/orders/static_src/create/view/customers.js
- shuup/admin/modules/orders/views/edit.py
- shuup_tests/admin/test_order_creator.py
Add duplicate contact warning to order creator.
Also, fix bug when populating company contact tax numbers in order
creator.
Refs SHUUP-3110
> Admin: Add duplicate contact warning to order creator (SHUUP-3110)

- doc/changelog.rst
- shuup/front/apps/auth/forms.py
- shuup_tests/front/test_registration.py
Ensure the users email is not blank prior to sending the password reset email.
Refs SHUUP-3125
> Front: Check for blank email on password reset

- doc/changelog.rst
- shuup/admin/templates/shuup/admin/products/_edit_media_form.jinja
- shuup/core/models/_product_shops.py
- shuup/core/models/_products.py
- shuup/front/views/product.py
* Exclude images from `get_product_media` to coincide with admin
product media/images representation. Also add properties
to shop product to get public images.
* Hide the "Purchased" checkbox since it is applicable only for product media. Note: I left the description field since lightbox uses it.
* Only show public images on product detail page
> Product media fixes (SHUUP-2993)

- doc/changelog.rst
- shuup/admin/modules/orders/views/list.py
- shuup/core/models/_orders.py
- shuup_tests/core/test_order_customer_name.py
* Core: Add `get_customer_name` for `Order`
* Admin: Fix bug with empty customer names in order list view
> Fix bug with empty customer names in order list view (SHUUP-3149)

- doc/changelog.rst
- shuup/front/apps/registration/views.py
No need for extra messages in registration if activation is not required.
The customer is logged in so it should be obvious that registration was
successful.
> Front registration: Skip message if activation email is not send (SHUUP-3172)

- doc/changelog.rst
- shuup/front/checkout/_mixins.py
At checkout addresses company form. Add tax number and company_name
validation errors for fields instead of just raising validation error.
> Front checkout: show company form validation errors for fields (SHUUP-3132)

- doc/changelog.rst
- doc/provides.rst
- shuup/admin/__init__.py
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/products/sections.py
- shuup/admin/modules/products/views/edit.py
- shuup/admin/templates/shuup/admin/products/_product_orders.jinja
- shuup/admin/templates/shuup/admin/products/edit.jinja
Note - I added a new provides key - `admin_product_section`. Using the pre-existing `form_part` provide seemed wrong since we're dealing with read-only tabular data.
Refs SHUUP-3105
> Admin: Add past orders section for product page (SHUUP-3105)

- shuup/campaigns/models/basket_line_effects.py
- shuup/campaigns/models/catalog_filters.py
- shuup_tests/campaigns/test_filters.py
- shuup_tests/campaigns/test_multiple_campaigns.py
First batch of fixes for campaigns. Campaigns should be worked even more to give more control to merchant to decide when campaigns are actually matched.
Fix a bug with `ProductFilter` where the `shop_product.pk` was compared to `product.pk`.
Fix an issue with basket line effects not honoring the previously given discounts
Refs SHUUP-3141
> Campaign inheritance (SHUUP-3141)

- shuup/admin/modules/orders/views/list.py
* Fix problem with sorting with customer_name
* Add billing address, shipping address and orderer names to
customer name filters. Since the customer name is shown based
on these fields then the filter should work with those.
Refs SHUUP-3149 / SHUUP-3176
> Admin: Fix bug in sort and add new fields to customer name filter (SHUUP-3149 / SHUUP-3176)

- doc/changelog.rst
- shuup/admin/modules/products/static_src/product-variation-variable-editor.js
- shuup/admin/static_src/product/edit_media.js
- shuup/admin/templates/shuup/admin/macros/general.jinja
- shuup/admin/templates/shuup/admin/products/_edit_media_form.jinja
- shuup/admin/templates/shuup/admin/products/variation/_simple_variation_children.jinja
- shuup/admin/templates/shuup/admin/products/variation/_variable_variation_children.jinja
- shuup/admin/templates/shuup/admin/products/variation/_variation_variables.jinja
Wrap content blocks in untranslated section id so styling and behavior is
consistent across languages. Also fix variation variable delete functionality
across languages.
Refs SHUUP-2992
> Fix admin content block styling (SHUUP-2992)

- doc/changelog.rst
- shuup/admin/modules/categories/views/list.py
- shuup/admin/static_src/base/less/shuup/picotable.less
- shuup/admin/static_src/base/less/shuup/select.less
- shuup/admin/static_src/picotable/picotable.js
- shuup/admin/utils/picotable.py
- shuup/core/models/_categories.py
- shuup_tests/admin/test_picotable.py
Improve the usability of the admin category list view
* Remove the parent column and instead indent the name column to represent
parent/child relationships
* Add a picotable select2 filter
* Add an MPTT filter which allows filtering by parent and all descendants
* Combine both `TranslatableManager` and `TreeManager` `get_queryset` calls
Refs SHUUP-2983
> Admin: Improve category list filtering (SHUUP-2983)

- doc/changelog.rst
- shuup/admin/modules/products/views/edit.py
Set default SKU to product id + 1. Note this can result in a duplicate SKU error if the user has multiple "create product" tabs open or if multiple users are creating products simultaneously. Users are, however, provided proper errors in the event of a dup.
Refs SHUUP-2964
> Admin: Use last product id + 1 as a default SKU

- doc/changelog.rst
- shuup/admin/modules/products/views/edit.py
- shuup/admin/static_src/base/js/content-blocks.js
- shuup/admin/static_src/base/less/shuup/content-blocks.less
- shuup/admin/templates/shuup/admin/macros/general.jinja
- shuup/admin/templates/shuup/admin/products/_edit_attribute_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_base_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_collapsed_base_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_collapsed_shop_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_media_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_shop_form.jinja
- shuup/admin/templates/shuup/admin/products/edit.jinja
- shuup/core/fields/__init__.py
- shuup/customer_group_pricing/templates/shuup/admin/customer_group_pricing/form_part.jinja
- shuup/simple_supplier/templates/shuup/simple_supplier/admin/product_form_part.jinja
- shuup_tests/browser/admin/test_product_detail.py
- shuup_tests/core/test_fields.py
Products can now be created by simply adding a product name and pressing save. Note the product is not orderable since supplier is not defaulted.
* Fix `FormattedDecimalField` default value
* Allow content blocks to be collapsed on initialization
* Rearrange product creation and edit pages
> Product creation/edit redesign (SHUUP-3168)

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/contacts/form_parts.py
- shuup/admin/modules/contacts/forms.py
- shuup/admin/modules/contacts/views/edit.py
- shuup/admin/modules/contacts/views/list.py
- shuup/admin/modules/users/views/detail.py
- shuup/admin/static_src/base/less/shuup/select.less
- shuup/admin/templates/shuup/admin/contacts/_contact_addresses.jinja
- shuup/admin/templates/shuup/admin/contacts/_edit_addresses_form.jinja
- shuup/admin/templates/shuup/admin/contacts/_edit_base_form.jinja
- shuup/admin/templates/shuup/admin/contacts/edit.jinja
- shuup/admin/templates/shuup/admin/orders/detail.jinja
- shuup/core/models/_contacts.py
- shuup_tests/admin/test_contact_edit.py
* Add "New person" and "New company" toolbar buttons to list view
* Split out company contact and person contact edit into two separate forms
* Use select2multiple for contact group input
* Mark first name and last name as required for person contacts
* Show only required and related fields on contact creation
* Show all fields on contact edit
* Allow billing address to be used as shipping address when creating a contact. Also, put billing address before contact address for order and contact detail address sections.
* Add type filter to contact list view
* Make select2 multiple default height more in line with other form inputs. (note: it still isn't exact due to browser sub-pixel rendering but its better than before - before it was ~4 pixels taller, now it is <1px different).
> Contact creation refactor (SHUUP-3158)

- shuup/core/models/_service_behavior.py
All customers belong to the "Anonymous" group by default (AKA. not signed in users),
thus it's pointless to check for the existance of the user in the database. This
also causes limiting to `not logged in users only` to be impossible.
Fix the issue explained above by removing a check for customer's existance in the database.
> Fix contact group availability behavior component

- shuup/default_reports/reports/sales_per_hour.py
- shuup/default_reports/reports/total_sales.py
- shuup/reports/templates/shuup/reports/report.jinja
- shuup_tests/default_reports/test_default_reports.py
* Use Shuup admin form tools to enable datepickers
* Fix issue with zero total sales
* Fix hours in sales per hour report
> Fix bugs in default reports (SHUUP-2085 / SHUUP-3219 / SHUUP-3220 / SHUUP-3221)

- shuup/admin/modules/orders/views/shipment.py
This comparision would raise an "unorderable types: NoneType()> int()" exception. Fix this by checking
for a value before comparing.
There were issues with Travis https://github.com/shuup/shuup/pull/724 so ths will replace that PR.
> Fix an issue where None comparison to int is failing

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/djangojs.po
- shuup/admin/modules/orders/static_src/create/actions/index.js
- shuup/admin/modules/orders/static_src/create/index.js
- shuup/admin/modules/orders/static_src/create/reducers/index.js
- shuup/admin/modules/orders/static_src/create/reducers/quickAdd.js
- shuup/admin/modules/orders/static_src/create/view/customers.js
- shuup/admin/modules/orders/static_src/create/view/lines.js
- shuup/admin/modules/orders/static_src/create/view/methods.js
- shuup/admin/modules/orders/static_src/create/view/utils.js
- shuup/admin/static_src/base/js/select.js
- shuup/admin/templates/shuup/admin/services/edit.jinja
- shuup/campaigns/templates/shuup/campaigns/admin/edit_campaigns.jinja
- shuup_tests/browser/admin/test_order_creator.py
Refactor `activateSelects`
Add the ability for products to be added to the order without any keyboard/mouse interaction.
Add browser tests for order line entry
Refs SHUUP-3152
> Add product quick add (SHUUP-3152)

- doc/changelog.rst
- shuup/admin/modules/products/views/edit.py
- shuup/admin/static_src/base/less/shuup/content-blocks.less
- shuup/admin/templates/shuup/admin/products/_edit_base_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_extra_base_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_extra_shop_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_media_form.jinja
- shuup/admin/templates/shuup/admin/products/_edit_shop_form.jinja
- shuup/admin/templates/shuup/admin/products/edit.jinja
- shuup/customer_group_pricing/templates/shuup/admin/customer_group_pricing/form_part.jinja
- shuup/simple_supplier/templates/shuup/simple_supplier/admin/product_form_part.jinja
- shuup_tests/browser/admin/test_product_detail.py
* At product edit convert collapsed sections into tabs
* At product edit divide required/general information to
two columns to avoid scrolling
* Hide accounting tab at admin product edit as unused information
* Do not collapse admin module product section at customer group
pricing and simple supplier apps
> Admin: Convert product edit collapsed sections into tabs (SHUUP-3234)

- doc/changelog.rst
- shuup/admin/static_src/picotable/picotable.js
- shuup_tests/browser/admin/test_picotable.py
Show fewer pagination links for picotable list views to prevent
UI issues for extremely large querysets.
Refs SHUUP-2619
> Admin: Show fewer pagination links for picotable list views

- doc/changelog.rst
- shuup/core/__init__.py
- shuup/core/excs.py
- shuup_tests/core/test_settings.py
Parler settings were actually required by Shuup and running the application without them caused errors.
This issue was comprehensively documented by @akx in issue #597.
Fixes #597
> Require Parler related settings when loading application (#597)

- shuup/front/apps/simple_search/views.py
- shuup_tests/front/test_simple_search.py
The original query caused errors since not all versions of MySQL
support LIMIT & IN/ALL/ANY/SOME subquery. By forcing the queryset to
list the product ids can be limited before caching the product ids.
> Simple Search: Fix bug in limiting query (SHUUP-2990 / SHUUP-3261)

- doc/changelog.rst
- shuup/admin/modules/orders/views/shipment.py
- shuup/core/excs.py
- shuup/core/models/_orders.py
- shuup_tests/admin/test_shipment_creator.py
The order form already requires shipping information when creating an
order. This commit ensures that a shipping_address is set on the order
at the time of shipment creation, otherwise it raises a
NoShippingAddressException.
Refs SHUUP-3257
> Admin: require shipping address before creating shipment (SHUUP-3257)

- doc/changelog.rst
- shuup/utils/pdf.py
Check whether the resource path startswith realpath from
`settings.STATIC_ROOT`.
In case settings STATIC_ROOT is behind symlink the resource path
will not anymore start with STATIC_ROOT since symlink is resolved.
> Utils: Fix issue with pdf stylesheets (SHUUP-2933)

- doc/changelog.rst
- shuup/front/apps/simple_search/templates/shuup/simple_search/search.jinja
- shuup/front/static_src/less/front/product-card.less
Add extra class `search-view` for product-box and set
column width in less to enable more customizable search
list.
> Simple Search: Set column width in less (SHUUP-3201)

- doc/changelog.rst
- shuup/admin/templates/shuup/admin/orders/detail.jinja
Simply hides the shipping address in Order detail if it's missing,
though the order form should prevent this from happening in the first
place.
Refs SH-120
> Admin: Fix missing shipping_address on order views (SH-120)

- doc/changelog.rst
- shuup/admin/modules/categories/forms.py
- shuup/admin/modules/categories/views/copy.py
- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/modules/products/views/edit.py
- shuup/admin/templates/shuup/admin/products/_edit_shop_form.jinja
- shuup/core/api/products.py
- shuup/core/locale/en/LC_MESSAGES/django.po
- shuup/core/migrations/0005_shopproduct_visibilty.py
- shuup/core/models/__init__.py
- shuup/core/models/_product_shops.py
- shuup/core/models/_products.py
- shuup/front/apps/simple_search/views.py
- shuup/front/template_helpers/general.py
- shuup/front/views/category.py
- shuup/testing/factories.py
- shuup_tests/admin/test_category_module.py
- shuup_tests/admin/test_order_creator.py
- shuup_tests/core/test_product_variations.py
- shuup_tests/core/test_products.py
- shuup_tests/core/test_products_in_shops.py
- shuup_tests/front/test_basket_commands.py
- shuup_tests/front/test_general_template_helpers.py
- shuup_tests/front/test_simple_search.py
- shuup_tests/functional/test_admin_orders.py
Replace visibility-related fields (visible, listed, searchable) for shop products with an enum indicating visibility mode.
Also, replace `list_visible` manager with a `visible` manager, and add additional `listed` and `searchable` managers for getting listed or searchable products.
Refs SH-79
> Fix product visibility (SH-79)

- doc/changelog.rst
- shuup/front/apps/registration/templates/shuup/registration/register.jinja
Import `render_field` from `shuup/front/macros/general.jinja`
instead of `shuup/front/macros.jinja` that does not exist.
> Registration: Fix bug in importing macro

- doc/changelog.rst
- shuup/admin/modules/products/views/edit.py
- shuup/admin/utils/views.py
- shuup_tests/admin/test_views.py
Allow create-or-update views using form parts to show form errors as
messages.
Refs SH-24
> Admin: Allow form group edit views to show errors as messages

- shuup/campaigns/models/campaigns.py
- shuup_tests/campaigns/test_coupons.py
Coupons with unicode in their code would result in an UnicodeDecodeError when passed
to the "force_text()" function. Fix this issue.
Replcase https://github.com/shuup/shuup/pull/776 for tests.
> Fix using "force_text()" on coupons

- doc/changelog.rst
- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/templates/shuup/admin/base.jinja
- shuup/admin/templates/shuup/admin/products/_edit_base_form.jinja
- shuup/core/migrations/0008_blank_slugs_for_product.py
- shuup/core/models/_categories.py
- shuup/core/models/_products.py
- shuup/core/utils/slugs.py
- shuup/front/templates/shuup/front/base.jinja
- shuup/utils/i18n.py
- shuup/utils/multilanguage_model_form.py
- shuup/xtheme/editing.py
- shuup_tests/browser/admin/test_order_creator.py
- shuup_tests/core/test_generating_slugs.py
- shuup_tests/utils/test_multilanguage_model_form.py
* MultiLanguageModelForm: Use Parler default as a default
* MultiLanguageModelForm: Avoid partially/empty translation objects
* Core: Fix bug in product and category slugs generation
* Admin: Add key prefix to JavaScript catalog page cache
* Admin: Add lang parameter for JS catalog load
* Xtheme: Skip adding JS-catalog for editing
* Tests: Add test for loading JS catalog
> Fixes for translation fallbacks and JS catalog loading (SH-17, SH-90)

- doc/changelog.rst
- shuup/admin/utils/views.py
In case there is no configurations saved for Picotable list view
columns the columns list is initialized to empty. Avoid this
for empty columns list fallback to default columns.
> Admin: Ensure there is columns in Picotable by default (SH-204)

- doc/changelog.rst
- shuup/simple_supplier/admin_module/views.py
Since the stock management list view is linked to Product model
and the stock management does not have model of it's own the
dynamic column configurations can't be used for stock management
with current implementation.
> Simple supplier: Make admin stock management columns static (SH-205)

- doc/changelog.rst
- shuup/core/models/_product_shops.py
- shuup/core/order_creator/_source.py
- shuup/front/basket/commands.py
- shuup/front/basket/objects.py
- shuup/front/basket/update_methods.py
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/static_src/less/front/basket.less
- shuup/front/templates/shuup/front/basket/default_basket.jinja
- shuup/front/templates/shuup/front/macros/basket.jinja
- shuup_tests/core/test_order_creator.py
- shuup_tests/front/test_basket.py
- shuup_tests/front/test_basket_commands.py
- shuup_tests/front/utils.py
Fix handling of package orderability in Front and Core.
Also, display package orderability problems to customer in basket view to allow them to make changes (for example, if the stock changes after the product is placed into basket).
One test (test_basket_update_errors) has been removed since implementation has changed a bit regarding when orderability errors are shown.
> Package orderability changes (SH-145)

- shuup/admin/modules/contacts/__init__.py
- shuup/admin/modules/orders/__init__.py
- shuup/admin/modules/users/__init__.py
- shuup/admin/utils/urls.py
Fix urls when creating list-settings urls so breadcrumbs can be
correctly inferred.
Note, if the breadcrumb can't be inferred (i.e., in the Campaigns module), then no breadcrumbs are displayed. This should be fine for now, since at least it doesn't show incorrect breadcrumbs.
SH-208
> Admin: Fix breadcrumbs for Picotable settings views (SH-208)

- doc/changelog.rst
- shuup/core/migrations/0009_update_tax_name_max_length.py
- shuup/core/models/_taxes.py
- shuup/default_tax/migrations/0002_postal_code_pattern_to_text.py
- shuup/default_tax/models.py
* Core: Update tax name max length to 124 characters
* Default tax: Change tax rule postal codes pattern to textfield
> Tax field changes for US taxes (SH-190)

- shuup/admin/modules/orders/sections.py
- shuup/core/models/_orders.py
- shuup/core/signals.py
- shuup/front/__init__.py
- shuup/front/notify_events.py
- Front: Create notify events for payment created, refund created, shipment created and shipment deleted
- Notify: changed Enum typology to return the enum identifier name instead of its value or translatable label
> Created notify events and fixed payment order section method name

- .tx/config
- doc/changelog.rst
- shuup/front/apps/carousel/__init__.py
- shuup/front/apps/carousel/admin_module/__init__.py
- shuup/front/apps/carousel/admin_module/forms.py
- shuup/front/apps/carousel/admin_module/views/__init__.py
- shuup/front/apps/carousel/admin_module/views/_delete.py
- shuup/front/apps/carousel/admin_module/views/_edit.py
- shuup/front/apps/carousel/admin_module/views/_list.py
- shuup/front/apps/carousel/apps.py
- shuup/front/apps/carousel/forms.py
- shuup/front/apps/carousel/locale/en/LC_MESSAGES/django.po
- shuup/front/apps/carousel/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/apps/carousel/migrations/0001_initial.py
- shuup/front/apps/carousel/models.py
- shuup/front/apps/carousel/plugins.py
- shuup/front/apps/carousel/templates/shuup/carousel/admin/_edit_base_form.jinja
- shuup/front/apps/carousel/templates/shuup/carousel/admin/_edit_slide_form.jinja
- shuup/front/apps/carousel/templates/shuup/carousel/admin/edit.jinja
- shuup/front/apps/carousel/templates/shuup/carousel/carousel.jinja
- shuup/front/gulpfile.js
- shuup/front/static_src/js/carousel.js
- shuup/front/static_src/less/front/carousel.less
- shuup_tests/front/test_carousel.py
- shuup_workbench/settings/base_settings.py
Move Shuup Carousel addon to Shuup base under front apps.
Note! Instances using shuup-carousel addon should be updated to use
this new app. There is no migration tools for old carousel and the old
carousels and slides needs to be copied manually to new app before removing
shuup-carousel addon from installed apps.
Modified from commit introduced in https://github.com/shuup/shuup/pull/761 by @shawnadelic
> Front: Add carousel app (SH-11)

- doc/changelog.rst
- shuup/core/models/_products.py
- shuup/front/apps/simple_search/views.py
- shuup_tests/front/test_simple_search.py
Add customer to searchable queryset while fetching product ids for query string. Form cache key from query string, shop and customer to avoid same cached results for every customer/shop.
> Fix simple search results for non public products (SH-225)

- doc/changelog.rst
- shuup/admin/modules/orders/views/edit.py
- shuup/admin/signals.py
- shuup/admin/utils/views.py
- shuup_tests/browser/admin/test_order_creator.py
- shuup_tests/browser/admin/test_product_create.py
Signal is fired from CreateOrUpdateView form_valid when in new mode. Also add the same signal for order created view.
This is needed since some of the admin forms has multiple saves before the object is "complete" so using the post_save signal created parameter is not optimal. For example contact creation.
> Admin: Add object created signal (SH-219)

- shuup/admin/modules/sales_dashboard/dashboard.py
- shuup/core/fields/__init__.py
- shuup/core/fields/utils.py
- shuup/core/models/_order_lines.py
- shuup/core/models/_orders.py
- shuup/core/order_creator/_source.py
- shuup/core/pricing/_priceful.py
- shuup_tests/core/test_orders.py
- shuup_tests/core/test_rounding.py
- shuup_tests/functional/test_tax_system.py
* Round priceful taxless and taxful prices into two decimals
* Round taxes to two decimals when getting order line tax
amount.
* Limit source line base_unit_price and discount_amount to
9 decimals like it is in order line
* Limit priceful price to 9 decimals
* Remove uneccessary rounding while calculating order totals
One option would have been to round priceful price to two decimals,
but it will cause problems when calculating other price components
like discount rate since all the other price components would be
with full precision.
All spots with rounding to two decimals can be changed to round
based on currency decimals later.
See the extra test for refunds which will not be solved by
this PR in case that is a problem. I think we shouldn't refund
with higher precision that the …
> Core: Price rounding change (SH-129)

- shuup/admin/form_part.py
- shuup_tests/browser/admin/test_product_create.py
Also send signal from saved form parts when object is created. Fix product created test to actually fail when signal is not fired.
> Admin: Fix bug in object created signal (SH-219 / SH-231)

- doc/changelog.rst
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/notify_events.py
Since the translations for help_texts is done while loading the
application the curent language won't affect those. Also at least
in Finnish the help_texts  causes unicode decode errors.
Avoid problems by removing the help_texts for now.
> Front: Fix unicode decode errors in notify events

- doc/changelog.rst
- shuup/admin/utils/picotable.py
Using translated manager is not needed and can't be used anymore since the database doesn't contain empty translation for all language codes by default.
> Admin: Fix bug in Picotable sorting with translated models (SH-209)

- shuup/front/apps/auth/forms.py
When the AUTH_USER_MODEL class has not a username field it was impossible to reset passwords
> Bugfix for custom user model

- shuup/front/apps/auth/forms.py
- shuup/front/apps/auth/settings.py
A setting was created to make it possible to change EmailMessage
content_subtype from plain text to whatever is needed, especially html.
> Auth: Enable user to configure emails sent by auth app to use HTML

- shuup/core/settings.py
- shuup/core/telemetry.py
- shuup_tests/core/test_telemetry.py
* Add daily sales, paid_sales, created products and
created contacts to telemetry data
* Add debug information to telemetry data
* Send telemetry every 24 hours
Example for daily data:
```python
[{
'orders': 4,
'paytrail': 11.67,
'date': '2016-09-15',
'total_sales': 46.68,
'stripe': 0,
'contacts': 197,
'products': 105,
'checkoutfi': 0
}]
```
> Core: Add daily data to telemetry (SH-82 / SH-267)

- shuup/admin/modules/media/views.py
Try to get upload action from `request.GET` if action is not available in `request.POST`
> Admin: Fix bug in media browser upload

- shuup/admin/modules/media/views.py
Try to get upload folder_id from `request.GET` if not available in `request.POST`
> Admin: Fix bug in media browser upload folders

- shuup/core/models/_order_lines.py
- shuup/core/order_creator/_source.py
- shuup/core/pricing/_priceful.py
- shuup/core/pricing/_priceful_properties.py
- shuup/core/taxing/_tax_summary.py
- shuup_tests/core/test_rounding.py
- shuup_tests/functional/test_discount_taxing.py
Fix issues with rounding stuff multiple times.
The rounded taxless or taxful total shouldn't be calculated based on rounded values like rounded tax_amount.
The `Priceful.tax_rate` shouldn't never be calculated based on rounded taxless or taxful total.
Priceful properties where the taxfulness is forced with `TaxfulFrom` or `TaxlessFrom` should never be calculated based on rounded taxless or taxful total.
Add `Priceful.raw_taxful_price` and `Priceful.raw_taxless_price` which could be used to calculate the properties mentioned above.
Skip ensuring the `Priceful.price` since the priceful properties should stay untouched until those are shown somewhere. Only `OrderSourceLine` should ensure things to make sure the key components that is saved later to database with certain precision will match. …
> Pricing: Avoid rounding multiple times (SH-308)

- shuup/testing/browser_utils.py
Ignore Selenium exception that is caused by dynamic DOM changes
while waiting for a condition to occur.
> Tests: Ignore StaleElementReferenceExceptions

- doc/changelog.rst
- shuup/admin/__init__.py
- shuup/admin/modules/orders/__init__.py
- shuup/admin/modules/orders/sections.py
- shuup/admin/modules/orders/views/__init__.py
- shuup/admin/modules/orders/views/edit.py
- shuup/admin/templates/shuup/admin/orders/_admin_comment.jinja
- shuup/admin/templates/shuup/admin/orders/_admin_comment_extra_js.jinja
- shuup_tests/admin/test_order_module.py
Make it possible to update order's admin comment. Add new section to admin order module which displays order's admin comment. Updates admin comment via ajax call to new view which updates the current order object.
> Add admin comment section to admin order module

- shuup/admin/utils/views.py
Retrieve the "next" parameter from POST when generating the success url
> Admin: Fix CreateOrUpdateView success url

- doc/changelog.rst
- shuup/front/static_src/js/update_price.js
- shuup/front/static_src/less/front/badges.less
- shuup/front/static_src/less/front/modals.less
- shuup/front/static_src/less/front/product-card.less
- shuup/front/static_src/less/front/product.less
- shuup/front/static_src/less/style.less
- shuup/front/templates/shuup/front/macros/category.jinja
- shuup/front/templates/shuup/front/macros/product.jinja
- shuup/front/templates/shuup/front/macros/product_image.jinja
- shuup/front/templates/shuup/front/macros/product_ordering.jinja
- shuup/front/templates/shuup/front/product/detail.jinja
- shuup/front/templates/shuup/front/product/detail_order_section.jinja
- shuup/front/templates/shuup/front/product/detail_order_section_no_product.jinja
- shuup/front/templates/shuup/front/product/product_preview.jinja
- shuup/front/templates/shuup/front/product/products_view.jinja
- shuup/front/utils/product.py
- shuup/front/views/product.py
- shuup/xtheme/layout.py
- shuup/xtheme/rendering.py
- shuup/xtheme/views/forms.py
- shuup_tests/browser/front/test_checkout.py
- shuup_tests/xtheme/test_editor_forms.py
Add a helper to get product context easily
Front: Enable multiple product order sections in one page
Front: Unify a way sales badges are used
Add placeholders into category view
Xtheme: Enable cell aligning
> Front improvements (SH-354)

- shuup/front/static_src/js/category.js
If customer has page loaded and filters are being changed by admin, it causes an error that won't go away
Add forced reload to the page if form causes error
Refs SH-284, SH-345
> Fix issue with faulty filters

- shuup/admin/modules/shops/forms.py
Save `shop.name` properly when multiple languages are enabled when
completing the wizard.
Refs SH-358
> Admin: Fix multilingual wizard shop name save (SH-358)

- shuup/front/utils/sorts_and_filters.py
- shuup_tests/browser/front/test_category_view.py
In old implementation, whenever the `get_queryset(...)` returned an
empty queryset or `None`, the old queryset was used.
This caused the following prolem:
* Product A is has manufacturer Y defined
* Product B is a variation with Colors Red and Green
* Now filter to show manufacturer Y and color Red, you will see Product A.
The queryset handling in `get_product_queryset` ignored all the querysets that resulted empty
(alongside the `None` values it should ignore). And when doing so, it
did fallback to the previous queryset, which still had the
previous filters' results in it thus could never end in a situtiation where
nothing was shown.
Refs SH-284
> Fix issue with stacking filters (SH-284)

- setup.py
It would be convenient if Shuup was in PyPI.  It was not uploaded there
earlier because PSF issued terms that would give PSF and PyPI users too
much permissions for the uploaded packages without accepting the AGPLv3
conditions.
Unfortunately we failed to see back then that it's possible to register
to PyPI without uploading the packages there. (Thanks @jaywink for
pointing this out.)  This PR enables registering Shuup to PyPI with a
download_url which points to the wheel file at Github.
Refs SHUUP-976
> Allow registering Shuup to PyPI

- shuup/admin/modules/services/views/_list.py
Without this the special symbols in choice name will fail with Python 2.7.
> Admin: Force text in service list choice column

- doc/changelog.rst
- shuup/admin/static_src/base/less/shuup/navigation.less
- shuup/admin/template_helpers/shuup_admin.py
- shuup/admin/templates/shuup/admin/base/_navigation.jinja
- shuup/core/management/commands/shuup_init.py
- shuup/core/settings.py
- shuup/core/telemetry.py
Save a six digit support id for shuup installations that are sending telemetry and show the id in the admin navbar.
Please merge and deploy shuup.com updates before this.
> Add support pin (SH-301)

- doc/changelog.rst
- shuup/front/apps/simple_search/forms.py
- shuup/front/forms/product_list_modifiers.py
- shuup/front/utils/sorts_and_filters.py
- shuup_tests/browser/front/test_search_view.py
* Pass data for `ProductListFormModifier.sort_products`
* Add search results from words in query string
* Add default sorting based on distance between product name and full query distance
> Front: Fill search results with words in query (SH-357, SH-254)

- doc/changelog.rst
- shuup/core/order_creator/_creator.py
- shuup/front/apps/auth/forms.py
- shuup/front/checkout/_view_mixin.py
- shuup/front/checkout/checkout_method.py
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/templates/shuup/front/checkout/_horizontal_phases.jinja
- shuup/front/templates/shuup/front/checkout/_vertical_phases.jinja
- shuup/front/templates/shuup/front/checkout/checkout_method.jinja
- shuup/front/templates/shuup/front/checkout/register.jinja
- shuup/front/views/checkout.py
- shuup/testing/checkout_with_login_and_register_urls.py
- shuup/testing/single_page_checkout_with_login_and_register_conf.py
- shuup_tests/browser/front/test_checkout_with_login_and_register.py
* Core: Populate some unfilled customer fields from order
* Front: Add is_visible_for_user method for checkout view phase
* Front: Add checkout view with option to login and register
* Front: Enable login and register phases for vertical process
> Add checkout view with register and login phases (SH-376)

- doc/changelog.rst
- shuup/front/template_helpers/general.py
- shuup/front/templates/shuup/front/macros/category.jinja
- shuup/front/templates/shuup/front/macros/general.jinja
- shuup_tests/front/test_general_template_helpers.py
Paginator page range is now a sliding window of five pages
such that the selected page is always shown as the "middle"
value except when on either end of the page range.
Refs SH-411
> Front: Restrict the pagination range to five pages (SH-411)

- doc/changelog.rst
- doc/provides.rst
- shuup/admin/form_modifier.py
- shuup/admin/modules/attributes/views/edit.py
- shuup/admin/modules/orders/views/shipment.py
- shuup_tests/admin/test_shipment_creator.py
Refactor `ShipmentFormModifier`  to make it reusable
Allow the attribute form extension
Refs SH-278
> Attribute form extension (SH-278)

- Dockerfile
By default, bower disallows running it as root. On a traditional system this makes sense: it uses the unix user model to separate bower packages from the system. By not being root, foreign scripts can't really attack the system. In Docker, the separation is provided by the container system, so running foreign scripts as root isn't as much of an issue. By being in a container, foreign scripts can't attack the system.
Allowing root disables the user-based separation model.
Without this change, bower fails with an `ESUDO` error when `docker build` is run.
> Add allow-root to the bower config in the Dockerfile

- doc/changelog.rst
- shuup/admin/modules/products/views/edit_cross_sell.py
ProductCrossSellFormSet is using wrong model in ProductCrossSellEditView, which can cause errors in some shops. Change ProductCrossSellFormSet model to use ProductCrossSell instead of ProductMedia model.
Now when trying to delete a product from product's cross-sell, form errors are:
[{'id': ['Select a valid choice. That choice is not one of the available choices.']}, {'id': ['Select a valid choice. That choice is not one of the available choices.']},... and nothing happens. After I changed to use ProductCrossSell model everything works correct.
> Use correct model in ProductCrossSellFormSet

- doc/changelog.rst
- shuup/front/apps/saved_carts/templates/shuup/saved_carts/cart_detail.jinja
- shuup/front/templates/shuup/front/macros/basket.jinja
- shuup/front/templates/shuup/front/macros/order.jinja
For variation children fallback images to variation parent
images in basket, checkout and saved cart. This allows option to
add images only for the parent.
> Front: Fallback to variation parent image (PP-50)

- doc/changelog.rst
- shuup/front/template_helpers/general.py
- shuup/front/utils/product_statistics.py
- shuup_tests/front/test_general_template_helpers.py
Show variation parents in product highlight plugins to avoid the variants from flooding the results.
thanks to @tulimaki and @Pikkupomo for their input!
Refs PP-49
> Front: Show variation parents in highlight plugin (PP-49)

- shuup/front/static_src/less/front/product-card.less
- shuup/front/static_src/less/front/product-list.less
Safari was not wrapping the product lists in categories and search results properly
Refs PP-45
> Front: Remove flex from product and search product lists (PP-45)

- shuup/front/forms/product_list_modifiers.py
- shuup/front/templates/shuup/front/macros/product.jinja
First commit should notably improve the category load speed.
Second commit fixes issue where thumbnail image was not found but still used. It caused category page to being called again
> Cache product list

- shuup/core/utils/forms.py
The name extension field is displayed on an address if it's filled, however, it isn't editable
Basically this means an address can only be edited partially
Fix this by adding the "name_ext" field to the address edit form
No refs
> Add "name_ext" field to address edit form

- doc/changelog.rst
- shuup/admin/modules/shops/forms.py
- shuup/admin/modules/shops/views/__init__.py
- shuup/admin/modules/shops/views/edit.py
- shuup/admin/modules/shops/views/wizard.py
- shuup/front/template_helpers/general.py
- shuup/testing/factories.py
- shuup_tests/admin/test_shop_edit.py
- shuup_tests/admin/test_wizard.py
- shuup_workbench/settings/base_settings.py
Doing changes logic around settings like LANGUAGE, LANGUAGES and
PARLER_DEFAULT_LANGUAGE_CODE will not work correctly without
actually change these settings and reload the application.
Also changing these settings can be done different ways depending
on project needs so this will be not provided from Shuup base.
> Admin: Remove language layer for shops (SH-369)

- doc/changelog.rst
- shuup/admin/modules/categories/forms.py
- shuup/admin/modules/products/__init__.py
- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/modules/products/signal_handlers.py
- shuup/admin/templates/shuup/admin/products/_edit_extra_base_form.jinja
- shuup/core/models/_categories.py
- shuup/core/settings.py
- shuup_tests/admin/test_views.py
- shuup_tests/campaigns/test_basket_campaigns.py
- shuup_tests/campaigns/test_catalog_campaigns.py
- shuup_tests/campaigns/test_matcher.py
- shuup_tests/core/test_products_in_shops.py
Both `Product` and `ShopProduct` have primary category and
shop product also categories. Category setting in `Product` isn't used
in shop front where the categories matter.
This commit introduces `SHUUP_AUTO_SHOP_PRODUCT_CATEGORIES` setting
that enables autopopulation of categories.
Examples with `SHUUP_AUTO_SHOP_PRODUCT_CATEGORIES = True`:
Example A:
```
shop_product.categories = []
shop_product.primary_category = "A"
shop_product.save()
=> "A" will be added to categories
```
Example B:
```
shop_product.primary_category = None
shop_product.categories = ["A", "B"]
=> "A" will be made the shop_product.primary_category
```
* Remove `primary_category` from product editing form
* Add option `SHUUP_AUTO_SHOP_PRODUCT_CATEGORIES` to enable
autopopulating categories
Refs SH-130
> Autopopulate `ShopProduct` categories

- shuup/admin/static_src/base/less/shuup/custom-forms.less
- shuup/admin/utils/bs3_renderers.py
For some reason help text was rendered with error text where it was hard to differentiate the two.
* Overwrite `FieldRenderer:append_to_field` in `AdminFieldRenderer` to split help and error texts
Refs SH-80
> Admin: Split help and error texts (SH-80)

- doc/changelog.rst
- shuup/admin/static_src/base/js/main-menu.js
- shuup/admin/static_src/base/less/shuup/base.less
- shuup/admin/static_src/base/less/shuup/main-menu.less
- shuup/admin/templates/shuup/admin/base.jinja
- shuup/admin/templates/shuup/admin/base/_main_menu.jinja
- shuup_tests/browser/admin/test_menu.py
- shuup_tests/browser/admin/test_order_list.py
- shuup_tests/browser/admin/test_picotable.py
- shuup_tests/browser/front/test_category_view.py
- shuup_tests/browser/front/test_checkout.py
- shuup_tests/browser/front/test_checkout_with_login_and_register.py
- shuup_tests/browser/front/test_search_view.py
Main menu didn't allow any clicks on mobile size.
The menu was loaded with ajax which caused blinking on load.
In large lists the merchant could not scroll into the last items since they were hidden outside the browser window
Quicklinks menu was way too wide in mobile size, this fix forces it to certain width and alters the styles
* Change the way admin menu is being rendered: show it without ajax
* Fix clicks in mobile size
* Add padding to menu
* Fix quicklinks menu in mobile size
Refs SH-435, SH-433, SH-436, SH-427
> Admin Fix Menu (SH-435, SH-433, SH-436, SH-427)

- doc/changelog.rst
- shuup/admin/modules/settings/__init__.py
- shuup/admin/modules/settings/views/__init__.py
- shuup/admin/utils/views.py
* Center the select column
* Show default columns that don't necessarily belong to the table (ie aggregate columns, etc) and ensure they are selectable
Refs SH-408
> Admin: Picotable column fixes (SH-408)

- shuup/core/fields/__init__.py
Cleaning the extincted languages in field init will cause
slowness at least in migrations and it is not necessary there.
> Core: Remove `clean_language_codes` from language field

- doc/changelog.rst
- shuup/admin/modules/products/forms/base_forms.py
- shuup/utils/multilanguage_model_form.py
- shuup_tests/admin/test_product_attributes_form.py
- shuup_tests/admin/test_product_module.py
- shuup_tests/utils/test_multilanguage_model_form.py
Ensure `PARLER_DEFAULT_LANGUAGE_CODE` is the first tab
in multilingual tab forms.
Refs SH-448
> Admin: Ensure default language tab is shown first (SH-448)

- shuup/testing/factories.py
Trying to import anything from `shuup.testing.factories` in tests could result in
```
RuntimeError: Model class
shuup.testing.models._behavior_components.ExpensiveSwedenBehaviorComponent doesn't declare an
explicit app_label and isn't in an application in INSTALLED_APPS
```
if done in a Django 1.9 environment.
The changes in this commit seem to fix it, but if not, at least the problem will be localized to a specific import instead of failing on all factories imports
> Fix app_label problem in shuup.testing module

- doc/changelog.rst
- shuup/core/models/_orders.py
- shuup_tests/core/test_shipments.py
Allow setting order complete if there is nothing to ship.
> Core: Fix bug in `Order.can_set_complete` (SH-489)

- shuup/admin/modules/orders/views/shipment.py
Extract the shipment creation code to it's own method
This is done so it's possible to override/extend without overriding the entire form_valid method
No refs
> Shipment creation view: Improve extendability

- shuup/default_tax/models.py
- shuup/utils/patterns.py
- shuup_tests/default_tax/test_default_tax.py
If postal code was a wildcard it was never matched to anything (except a '*'). When postal code was changed to empty it was never changed in database level and caused non matching rules.
> Taxes: Fix default tax bugs (SH-341)

- shuup/testing/browser_utils.py
- shuup_tests/browser/admin/test_product_detail.py
Parametrize fixed header height and set the header height to 320
for mobile size admin product detail tests.
> Browser tests: Parametrize `FIXED_HEADER_HEIGHT`

- shuup/xtheme/parsing.py
- shuup_tests/browser/front/test_product_view.py
If your service uses caching engine like incapsula, static files
might be cached many hours after updating Shuup. This change
ties static files to a commit, which means that they will be
always refreshed in cache.
No ref
> Make static file urls more dynamic

- shuup_tests/browser/front/test_category_view.py
Wait until the elements are present in the browser before interacting with them
No Refs
> Improve browser tests to avoid errors

- setup.py
This change is necessary since it seems that 2.9.1 is not backwards compatible with 2.8 in Shuup.
> Limit jinja2 version to <2.9

- shuup/admin/modules/products/static_src/product-variation-variable-editor.js
The identifier label was prepended to the input tags, breaking the
table layout. This fix moves the 'Identifer' label in the thead.
> Move the label for the identifier in the header

- shuup/addons/admin_module/views/reload.py
This prevents having color codes printed out in the web output.
> Remove color from internal use of commands

- doc/web_api/rest_setup.rst
- shuup/admin/urls.py
- shuup/front/apps/auth/urls.py
- shuup/front/apps/customer_information/urls.py
- shuup/front/apps/personal_order_history/urls.py
- shuup/front/apps/registration/urls.py
- shuup/front/apps/saved_carts/urls.py
- shuup/front/apps/simple_search/urls.py
- shuup/simple_cms/urls.py
- shuup/testing/checkout_with_login_and_register_urls.py
- shuup/testing/single_page_checkout_test_urls.py
- shuup/testing/single_page_checkout_with_login_and_register_conf.py
- shuup_tests/admin/utils.py
- shuup_tests/notify/notification_test_urls.py
- shuup_workbench/test_urls.py
- shuup_workbench/urls.py
In Django 1.10, the patterns function is deprecated, this PR should allow an easier migration to the current version.
> Update URLConf to suppress usage of patterns

- shuup/front/templates/shuup/front/checkout/_vertical_phases.jinja
When user clicks continue in vertical checkout view to move into next phase, scrolls html document up little bit to prevent the user to skip any new information. 
New phase content is fetched via ajax and inserted html content but for example if user has scrolled to the bottom of the html document, some of the new phase content is possibly inserted out of the user's screen and it is easily skipped. 
This fix scrolls document up after moving to new phase so that user doesn't accidentally miss any phase information like shipping or payment methods for example.
> Scroll up after submitting checkout phase form

- requirements-doc.txt
- setup.py
- shuup/addons/admin_module/views/upload.py
- shuup/addons/verify.py
- shuup/apps/settings.py
- shuup/front/templates/shuup/front/checkout/_vertical_phases.jinja
This optionally enables Wheel validation for addon uploads.
To enable it, WHEEL_USER and WHEEL_PASSWORD have to be provided
WHEEL_USER should be set to the value of vk when running `wheel keygen`
on the machine used to build and sign wheels.
WHEEL_PASSWORD should be the value returned by:
``keyring get wheel WHEEL_USER``
where WHEEL_USER matches the value of the previously aquired vk.
It is also necessary to properly set up the keyring backend in:
~/.local/share/python_keyring/keyringrc.cfg:
```
[backend]
default-keyring=keyrings.alt.file.PlaintextKeyring
```
The same keyring used when building the wheels should be copied to:
~/.local/share/python_keyring/keyring_pass.cfg
Ref: MAR-19
> Provide mechanism to validate uploaded wheels

- shuup/xtheme/plugins/forms.py
- shuup_tests/front/test_carousel.py
I wasn't able to update existing plugin using the xtheme editor though I was able to create new ones. I discovered that the full_clean method of the PluginForm had the line 
```
def full_clean(self):
"""
Use initial values as defaults for cleaned data
"""
super(PluginForm, self).full_clean()
for name in self.fields:
if name in self.data:
continue
if self.fields[name].initial is not None:
self.cleaned_data[name] = self.fields[name].initial
self.cleaned_data
```
For instance, the value for name for Carousel plugin is 'carousel' but the corresponding key in the raw form data is 'plugin-carousel'. This check would consistently fail for existing plugin config. New plugins can be created but existing ones can't be edited and updated.
My change simply checks for the updated fields in the …
> Fixed xtheme plugin update and carousel test

- doc/howto/getting_started_dev.rst
- shuup_setup_utils/nodejs_verify.py
Add the minimum version of Node required to build the resources (v0.10 isn't compatible anymore).
> Specify minimum Node version compatible with Shuup

- shuup/admin/modules/orders/json_order_creator.py
- shuup/core/api/orders.py
- shuup_tests/api/test_order_api.py
The REST API for Orders requires less mandatory fields. Orders can now
be created without a customer, without a shipping or billing address
and without a shipping or billing method.
Refs: SH-519
> API: Improve Order create API (SH-519)

- doc/changelog.rst
- doc/ref/provides.rst
- shuup/admin/modules/orders/utils.py
- shuup/admin/modules/orders/views/detail.py
- shuup/admin/templates/shuup/admin/orders/detail.jinja
- shuup_tests/admin/test_order_detail_extensibility.py
This provide category is used to add extra info rows into Order detail page. Provide objects should inherit from `shuup.admin.modules.orders.utils.OrderInformation` class. Classes inheriting `OrderInformation` are turned into info rows by using the title variable as row title and information property as row data. Includes test for checking that info rows can be added to the Order detail page.
> Introduce provided order information

- shuup/core/api/category.py
- shuup/front/api/products.py
- shuup_tests/api/test_front_products_api.py
- Filtering products by categories ID (which has a db index)
- Removed not working and unnecessary `is_root` filter
**Needs to have Category permission to work.**
> Filtering products by categories ID

- setup.py
This PR should allow uploading Shuup to PyPI with Twine.
Also updated some info in the classifiers, e.g. development status.
> setup.py: Fix/update Trove classifiers

- shuup/core/api/basket.py
- shuup/core/api/orders.py
- shuup/front/api/__init__.py
- shuup/front/api/orders.py
- shuup_tests/api/test_basket_api.py
- shuup_tests/api/test_front_orders_api.py
- shuup_tests/api/test_order_api.py
* Add API that allows users to retrieve their own orders.
* Allow products from a pre-existing order to be added to the basket.
The way errors are handled for APIs is a mess right now. We need to eventually come up with a standard approach that applies across all APIs.
> Front order API

- shuup/admin/modules/products/views/edit.py
- shuup/core/models/_product_shops.py
- shuup/core/models/_shops.py
- shuup_tests/simple_supplier/test_simple_supplier.py
This prevents an error when checking orderability when some child products are not available in a shop
> Check that product children are available for the current shop

- doc/changelog.rst
- shuup/admin/error_handlers.py
- shuup/front/error_handlers.py
- shuup_tests/core/test_error_handling.py
(This is a re-pull of #1000 under a personal repo and personal CLA)
Update the default error handler to return the appropriate HTTP status code.
The status_code variable is passed to the jinja template for rendering the error, but the HTTP status is always left as the default, which is 200.
This fix is applied to both the admin and front error handlers.
The tests have been updated to no longer check for status_code == 200, and now check for the appropriate status value.
I have not been able to get the tests running locally.
It would be appreciated if someone could verify the tests pass.
> Return the appropriate error code in the HTTP response

- shuup/front/templates/shuup/front/checkout/method_choice.jinja
Caching service prices may cause faulty prices when using
Waiving cost behaviour component. If user deletes some products
after passing the Shipping & Payment phase, next time Shipping & Payment
phase will show the cached price which could be the waived price. Though
prices are correct when moving to confirmation view but this has caused
confusion among users.
> Don't cache service prices in checkout templates

- shuup/admin/static_src/base/less/shuup/base.less
- shuup/admin/static_src/base/less/shuup/support-navigation.less
Top panel takes 50% of screen space on a phone making viewing anything in shuup admin quite challenging.
Make top panel not fixed for smaller mobile devices.
> Remove position fixed from top panels on mobile devices.

- shuup/campaigns/migrations/0007_add_excluded_categories.py
- shuup/campaigns/models/basket_conditions.py
Don't require excluded categories in CategoryProductsBasketCondition. Because this change affects only in validation I believe its safe to add this to the migration also.
Or is there some kind of reason why excluded categories is required? People thinks that this is weird to require them.
> Make excluded categories optional in CategoryProductsBasketCondition

- .travis.yml
Disable running browser tests in Travis for now, since they cause false
errors.
If browser tests are fixed at some point, then they should be
re-enabled. Until that, it's better to have them disabled.
> Travis: Disable browser tests

- shuup_tests/reports/test_reports.py
- tox.ini
BeautifulSoup4 4.4.0 does not work with recent html5lib (0.99999999 or
newer), so update it to newer version which works better.
Also pin html5lib so we don't get such surprises anymore.
> tox.ini: Update BeautifulSoup4 and pin html5lib

- doc/changelog.rst
- doc/ref/provides.rst
- shuup/themes/classic_gray/templates/classic_gray/shuup/front/macros/theme/navigation.jinja
- shuup/xtheme/_theme.py
- shuup/xtheme/extenders.py
- shuup/xtheme/templates/shuup/xtheme/menu_extension.jinja
- shuup_tests/admin/test_mass_actions.py
- shuup_tests/admin/test_order_mass_actions.py
- shuup_tests/browser/front/test_recently_viewed_products.py
- shuup_tests/campaigns/test_caching.py
- shuup_tests/front/test_addressbook.py
- shuup_tests/notify/test_action_send_mail.py
- shuup_tests/xtheme/test_extenders.py
It was not possible for addons to provide objects into front menus.
This PR will add a support for Addons to extend main menus in Shuup Front.
> Front menu extender

- shuup/api/urls.py
- shuup/core/api/products.py
- shuup/core/models/_attributes.py
- shuup_tests/api/test_products_api.py
It is now possible to create ShopProducts and attach attributes through
same product API with a single API query.
This supersedes PR #1047 and includes the commit from it.  Difference is
that this also implements updates and partial updates.  And there is
also a fix included for making the API index views point to correct
views.
> Web API: Improve product API

- shuup/core/models/_attributes.py
- shuup_tests/core/test_attributes.py
Since we are using `django.forms.fields.NullBooleanField` in admin
we should return either None, True or False.
While the `Unknown` option (`None`) will never end up in the database
when product attribute is being saved in admin, it is possible to
create this value through API and that causes admin to break.
This commit allows `None` value reading from the numeric_value in
boolean situtiations.
> Admin: Fix boolean value presentation errors

- doc/changelog.rst
- shuup/core/models/_product_shops.py
Before, the orderability of all variations was checked needlessly.
Now, we only ensure at least one child product is orderable.
> Improve variation orderability check performance

- doc/howto/getting_started.rst
Remove stray period in example command to run shuup_init.
> Remove stray period in example command

- shuup/admin/static_src/base/js/select.js
- shuup/admin/template_helpers/shuup_admin.py
- shuup/core/api/orders.py
- shuup_tests/api/test_order_api.py
* Restrict queryset by accessible shops
* Enable searching by email or phone
* Tweak admin select2 to use URL provided by server config
> API: Update admin order API

- .coveragerc
- .travis.yml
- _misc/language_twister.py
- setup.cfg
- shuup/admin/templatetags/shuup_admin.py
- shuup/admin/urls.py
- shuup/core/fields/tagged_json.py
- shuup/core/management/commands/shuup_makemigrations.py
- shuup/core/models/_categories.py
- shuup/core/pricing/_context.py
- shuup/front/apps/registration/__init__.py
- shuup/front/apps/simple_order_notification/__init__.py
- shuup/front/middleware.py
- shuup/front/urls.py
- shuup/simple_supplier/__init__.py
- shuup/testing/__init__.py
- shuup_workbench/settings/__init__.py
- shuup_workbench/wsgi.py
- tox.ini
* Add Codecov coverager uploading.
* Use pytest-sugar to make the build outputs prettier.
* Use flake8-isort for import ordering tests.
- Drops out one extra build job.
- flake8-isort has better error messages than plain isort
* Update to newer code style checker utils
* Some code style fixes, because newer checkers are more strict
* Make .travis.yml a bit easier to read.
* Comment out nvm and selenium installing.
* Update version of mock
> Improve running of the tests

- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/locale/fi_FI/LC_MESSAGES/django.po
- shuup/admin/modules/orders/toolbar.py
- shuup/admin/modules/orders/views/payment.py
- shuup/core/models/_orders.py
- shuup_tests/admin/test_set_paid_action.py
If order payment status is not paid or deferred, allow creating zero price
payments. For example some addons can modify order payment status and
in some cases orders with deferred payment status and zero price are
need to be set paid.
> Allow zero price payments for deferred orders

- shuup/admin/modules/orders/mass_actions.py
- shuup/admin/static_src/picotable/picotable.js
"select_all" and "select_listed" keys were wrong way around. Add status code 400 to response if PicotableFileMassAction fails, then we can show error message to user if view doesn't return status code of 200.
> Fix bug in picotable mass actions select listed

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/locale/fi_FI/LC_MESSAGES/django.po
- shuup/admin/locale/sv_SE/LC_MESSAGES/django.po
- shuup/admin/modules/content/forms.py
- shuup/admin/modules/media/views.py
- shuup/core/api/attribute.py
- shuup/core/api/manufacturer.py
- shuup/core/api/product_media.py
- shuup/core/api/tax_class.py
- shuup/core/api/units.py
The non-unicode version of gettext_lazy shouldn't be used, since on
Python 2 it returns bytes (str) rather than unicode and that might cause
unicode encoding/decoding errors.
Also fix an invalid as-name for ugettext_lazy.  The translation was not
picked-up by makemessages, because the ugettext_lazy was imported with a
name that was unknown to makemessages.  Import the ugettext_lazy with
its original name and rerun makemessages to collect the translation.
> Fix invalid usages of non-unicode gettext_lazy

- doc/_ext/django_sphinx.py
- doc/changelog.rst
- doc/conf.py
This makes API documentation of our models contain the fields with their
help texts or verbose names.  The model documentation is much better
with this.
Separated this from PR #1068, because that PR was so big already.
> doc: Add Django model autodoc extension

- doc/changelog.rst
- doc/ref/provides.rst
- shuup/front/utils/product.py
- shuup_tests/front/test_product.py
This provide category can be used to add extra context data to the front product views. Provide objects should inherit from `shuup.front.utils.product.ProductContextExtra` object.
Add test to make sure its working.
This should make it very easy for addons to extend product context data.
> Introduce new provide category "product_context_extra"

- shuup/front/themes/views/_product_price.py
- shuup/utils/numbers.py
- shuup_tests/front/test_product_price.py
- shuup_tests/utils/test_numbers.py
Commit c7dedea of PR #1068 didn't have proper value validation in the
added _get_quantity method.  Fix this.
Add a new decimal parser for this too, since the parse_decimal_string
silently accepts invalid values.
> Fix decimal parsing in ProductPriceView._get_quantity

- shuup/admin/modules/shops/forms.py
It is important that the widget is passed to `Select2MultipleField`
init. Otherwise the attrs is not set correctly and the widget does
never get the data-model attribute.
> Admin: Fix bug in shop staff member select

- doc/changelog.rst
- shuup/xtheme/plugins/products.py
- shuup_tests/xtheme/test_cross_sell_plugin.py
Fix following bug: If the "type" paramater is invalid in the config, the
cross sells plugin causes internal server error.
The fix was to simply catch a correct exception type.
The invalid value could end up in the config e.g. after changing the
plugin type from ProductHighlightPlugin to ProductCrossSellsPlugin in
the Xtheme editor.
> Fix ProductCrossSellsPlugin with invalid type

- shuup/admin/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/apps/customer_information/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/apps/personal_order_history/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/apps/saved_carts/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/locale/fi_FI/LC_MESSAGES/django.po
- shuup/simple_cms/locale/fi_FI/LC_MESSAGES/django.po
- shuup/themes/classic_gray/locale/fi_FI/LC_MESSAGES/django.po
Unify the following translations:
* Home = Etusivu
* Dashboard = Hallintapaneeli
* Total price = Kokonaishinta
* Tax breakdown = Veroerittely
* Based on price = Veron peruste
> Fixes to Finnish translations

- shuup/front/apps/personal_order_history/templates/shuup/personal_order_history/macros/buttons.jinja
- shuup/front/apps/personal_order_history/views.py
When adding products from an order to basket, don't add child lines or
subscriptions.
Child lines are excluded because otherwise package contents are added
twice.  Subscriptions are excluded because those don't use normal
checkout flow.
> front: Fix re-ordering

- doc/changelog.rst
- shuup/front/notify_events.py
- shuup_tests/notify/test_order_notifications.py
Notifications can use that to send emails or send SMS to the shop for any reason
> Front: add shop phone and email in notification

- shuup/core/templatetags/shuup_common.py
- shuup/front/apps/registration/templates/shuup/registration/register.jinja
`context ` is a jinja's Context class, so context items should be accessed by calling a get method.
make 'Register as a company.' translatable.
> Fix get_shop_configuration templatetag

- shuup/front/checkout/_view_mixin.py
Django registration redux calls get_success_url like:
success_url = self.get_success_url(new_user)
which resulted in:
TypeError: get_success_url() takes 1 positional argument but 2 were given
Fix this error by accepting args and kwargs in CheckoutPhaseViewMixin
get_success_url method. Also call super if there is no next phase set.
> Fix registration while ordering

- doc/changelog.rst
- shuup/front/templatetags/thumbnails.py
- shuup_tests/front/test_thumbnails_templatetag.py
Easy thumbnails doesn't support SVG and the `thumbnailer.get_thumbnail`
call here used to raise an IOError when called with an SVG file.
There is no much sense in thumbnailing SVGs since they are vector
graphics, so fix this bug by returning a direct url to the SVG file
rather than even trying to create thumbnails for them.
This fixes e.g. the maintenance mode page rendering when shop logo is an
SVG file.
> front: Fix thumbnail template tag for SVG files

- shuup/core/api/basket.py
- shuup_tests/api/test_basket_api.py
Before, the API would give a permission denied error
when an anonymous user attempted to access an anonymous
basket. Now, we forgo the permissions check for anonymous
baskets.
> API: Allow baskets for anonymous users

- .tx/config
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/locale/fi_FI/LC_MESSAGES/django.po
- shuup/api/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/apps/registration/forms.py
- shuup/front/apps/registration/locale/en/LC_MESSAGES/django.po
- shuup/front/apps/registration/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/apps/registration/notify_events.py
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/templates/shuup/front/macros/checkout.jinja
Make the company registration form more DRY (to reduce number of
to-be-translated messages) and translate it to Finnish.
Add also "shuup.api" to Transifex configuration and translate it to
Finnish.
Translate a couple other found untranslated messages too.
> Translate company registration etc. to Finnish

- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/locale/sv_SE/LC_MESSAGES/django.po
- shuup/front/templates/shuup/front/macros/general.jinja
Use non-shortened term for Admin*, because term "Admin" is hard to
translate, since it can mean "Administrator" or "Administration".  It's
also nice to be clear what's being administrated; for the translators
and for the users.
Change term "Maintenance" to "Maintenance mode" to reuse its
translation.  The former had incoherent translation in Finnish.
> Fix messages in the administration toolbar

- shuup/front/static_src/js/category.js
- shuup/front/template_helpers/general.py
Fix get_pagination_variables and its helper function _get_page_range.
Make reloadProducts more robust so that it won't fail if there is no
products-wrap element.  (It's called after selecting a page from
pagination element.)
> Pagination fixes

- shuup/core/api/basket.py
- shuup/core/api/service.py
- shuup/core/basket/objects.py
- shuup_tests/api/test_basket_api.py
* Add service serializers for basket
* Add option to set payment and shipping methods through API
* Avoid having lazy gettext objects in the error messages
> Basket API: Add option to set shipping and payment methods

- doc/changelog.rst
- shuup/campaigns/locale/en/LC_MESSAGES/django.po
- shuup/campaigns/models/campaigns.py
- shuup/campaigns/modules.py
- shuup_tests/campaigns/test_basket_campaigns.py
- shuup_tests/campaigns/test_coupons.py
- shuup_tests/campaigns/test_discount_codes.py
- shuup_tests/core/test_order_creator.py
Make sure to include source/order shop in to calculations whether the code can be used or not.
Do not limit coupon code to be unique. In multi shops sharing same code like "XMAS" should be pretty common thing.
Instead limit that shop does not have multiple active basket campaigns for same code. Which would make figuring out which code to use pretty hard.
As a side note. Fix the `seed_source` test to allow shop as a parameter to actually guarantee that the source, shipping and payment method shares the same shop. This method is called all over the places so adding this extra in to it might be useful for future when we add more multi shop tests.
> Campaigns: Fix issue in the multi shop coupons

- shuup/core/basket/objects.py
- shuup_tests/api/test_basket_api.py
- shuup_tests/campaigns/test_discount_codes.py
Make `_set_value_to_data` and `_get_value_from_data` actually set and get correct values. For addresses and methods always save the method.
Fix campaigns tests since now the service lines is restored from saved data.
> Core: Fix bug in basket object addresses and methods

- shuup/front/utils/sorts_and_filters.py
Superusers has ability to view all products or only visible
products in the frontend. This requires that cache identifier
is different and user specific when the all seeing property is
toggled on. This way we don't fetch inaccurate product queryset
from the cache.
> Build cache identifier differently for all seeing users

- shuup/xtheme/plugins/products.py
ProductHighlightPlugin uses get_best_selling_products function
if type best_selling is selected. Plugin passed arguments
without keywords and so some arguments got assigned to
wrong parameters. Fix this by passing orderable_only with keyword.
> Fix product highlight plugin best selling products

- shuup/front/apps/registration/__init__.py
- shuup/front/apps/registration/signals.py
- shuup_tests/front/test_registration.py
When user clicked activation link in the email, PersonContact
related to the user was not set to active and user still couldn't
login because PersonContact wasn't active altough the auth user was.
Fix this by activating also the PersonContact when user clicks
activate link.
> Fix PersonContact not activated after clicking activate link

- shuup/core/models/_orders.py
- shuup/core/signals.py
- shuup/front/notify_events.py
Create a new signal which is dispatched after the shipment_created
has dispatched. Connect notify script to this event so you can be sure
that every function connected to shipment_created signal has already
processed and so the shipment contains all information including data
fetched from 3rd party apis for example.
> Add create shipment view succeeded signal and event

- shuup/front/apps/customer_information/templates/shuup/customer_information/customer_dashboard_item.jinja
If customer has not set some details show only dash instead of not
translated string.
> Show dash if customer detail is not set

- shuup/core/api/basket.py
- shuup_tests/api/test_basket_api.py
- Set the basket customer when the basket is loaded
- When adding contents to the basket from an existing order, the order customer should either the basket customer or the request customer
> API: fix basket create from order endpoint

- shuup/admin/modules/contacts/views/list.py
Filtering contacts by type caused
filter_queryset() takes 4 positional arguments but 5 were given
because filter_queryset in ContactTypeFilter was missing
context parameter.
> Fix contact list type filter

- shuup/core/api/front_products.py
- shuup_tests/api/test_front_products_api.py
Best selling products interface should return same paginated response like when getting list of products. The caller shouldn't need to process the response differently for best selling products.
> API: Add pagination for best selling products

- shuup/front/apps/registration/locale/en/LC_MESSAGES/django.po
- shuup/front/apps/registration/locale/fi_FI/LC_MESSAGES/django.po
- shuup/front/apps/registration/locale/sv_SE/LC_MESSAGES/django.po
- shuup/front/apps/registration/notify_events.py
- shuup/front/apps/registration/views.py
- shuup_tests/front/test_registration.py
Disable the default user registration activation email sending.
Extend the RegistrationReceived event so that it can include
activation url. Then this event can be used to send customized
activation email to registered user.
> Handle registration activation email sending via notify scripts

- doc/changelog.rst
- shuup/xtheme/plugins/social_media_links.py
The SoMe links plugin couldn't be saved because it tried to access the
translated fields incorrectly from the cleaned_data dictionary in its
clean method.
This for-loop
for field in plugin_fields:
cleaned_data[field] = precleaned_data.pop(field)
tried to access, e.g. field named "topic" even though there was no such
field in the precleaned_data dictionary.  There was only "topic_*",
"topic_en", "topic_fi", etc.
Fix this by rewriting the clean method to not touch the fields it
doesn't understand, but rather juts rewrite the links, which it knows.
> xtheme: Fix Social Media Links plugin

- doc/changelog.rst
- shuup/front/generated_resources.txt
- shuup/front/gulpfile.js
- shuup/front/static/.gitignore
- shuup/themes/classic_gray/generated_resources.txt
- shuup/themes/classic_gray/gulpfile.js
- shuup/xtheme/parsing.py
- shuup_tests/browser/front/test_product_view.py
Make it possible to use ManifestStaticFilesStorage for implementing
auto-updating URLs for static files and revert the earlier hack which
tried to achieve the same functionality.
See the commit messages for details.
> Fix static files auto-updating URLs

- .travis.yml
- tox.ini
Shuup should work fine with Python 3.6, so add it to the build matrix.
But since, we don't want the tests take too long, remove couple entries
too.  All supported Python versions (2.7, 3.4, 3.5, 3.6) and Django
versions (1.8, 1.9) are still tested (although not all combinations).
> Travis: Add py36, remove py35-django18 and py34-django19

- doc/changelog.rst
- shuup/core/api/orders.py
The JSON fields of Order (payment_data, shipping_data, extra_data and
codes) should be serialized as objects rather than strings.
Previously the output was like
{
"id": 123,
...
"payment_data": "{\"hello\":\"world\"}",
...
}
This fixes the JSON strings to be proper objects, e.g.:
{
"id": 123,
...
"payment_data": {
"hello": "world"
},
...
}
This makes a bigger difference, if XML serialization is used, since
previously the XML field used to contain JSON string, but this makes it
contain a proper XML object.
> core/api: Fix JSON fields in Order serialization

- shuup/admin/templates/shuup/admin/service_providers/edit.jinja
This allows using Form Assets for the widgets in the form.  See
https://docs.djangoproject.com/en/1.8/topics/forms/media/ for details.
> admin: Add media to service provider form template

- shuup_tests/admin/test_sales_dashboard_module.py
The test_recent_orders_block used to fail randomly, because sometimes
the name of the randomly generated person contains characters that are
escaped in the HTML, e.g. `'` will be escaped as `&#39;`, like here:
https://travis-ci.org/shuup/shuup/jobs/232588736
Fix the test by properly escaping the name which is looked up from the
content.
> tests/admin/dashboard: Fix test_recent_orders_block

- shuup/core/utils/price_display.py
- shuup/front/template_helpers/product.py
- shuup_tests/core/test_price_display.py
Use the request as the context for the context cache instead of the
Jinja2 context.  This will include the customer and groups in the cache
key.  Without the customer information a wrong price or visibility was
cached and presented to a wrong customer.
This is a cherry-pick of the commit from PR #1127.  Only changed the
commit message a bit to be more detailed.
> core: Fix price display and is_visible caching

- shuup/campaigns/models/basket_line_effects.py
CategoryProductsBasketCondition applies to basket if basket
contains child products that doesn't belong to specified category
but parent does. If this condition was used with
DiscountFromCategoryProducts effect, user didn't get any discount
because DiscountFromCategoryProducts basket line effect only
checks if current product belongs to a specified categories.
Fix this by using different logic if product in the basket is
a child product and then checking if neither parent and child
doesn't belong to given category.
> Give discount for child products also in category products line effect

- doc/changelog.rst
- shuup/front/apps/customer_information/forms.py
- shuup/front/settings.py
- shuup_tests/front/test_customer_information.py
Add new setting called SHUUP_PERSON_CONTACT_FIELD_PROPERTIES
which can be used the way as SHUUP_ADDRESS_FIELD_PROPERTIES
setting to override form field properties. You can specify a
dict containing the field name as the key and the value is a
another dict containing the field properties and their new values.
> Make it possible to override person contact form properties

- shuup/admin/modules/contacts/views/detail.py
- shuup/admin/modules/settings/consts.py
- shuup/admin/modules/settings/forms/system.py
- shuup/front/apps/customer_information/templates/shuup/customer_information/macros/buttons.jinja
- shuup/front/apps/customer_information/views.py
- shuup/front/apps/registration/__init__.py
- shuup/front/apps/registration/forms.py
- shuup/front/apps/registration/notify_events.py
- shuup/front/apps/registration/signals.py
- shuup_tests/front/test_customer_information.py
- shuup_tests/front/test_registration.py
- shuup_tests/functional/test_notify_on_company_created.py
Provide user activation link for the company approved event template
so it can be used to send "Company has been approved" message
containing activation link for the user to activate his account.
This way admin only needs to activate the CompanyContact and it will
trigger the CompanyApproved event which sends the activation link
for the user to activate his own account.
Create a new signal which will be dispatched when the company is
activated through the admin panel. This signal has the request
object which is used to build the activation url. Connect the
send_company_activated_first_time_notification function to this
signal instead of post_save on CompanyContact.
If company registration is not allowed hide the button from customer
dashboard which creates a company contact. Differentiate …
> Company registration updates

- shuup/core/api/basket.py
- shuup/testing/basket_helpers.py
- shuup_tests/api/test_basket_api.py
- shuup_tests/api/test_basket_from_order.py
Mainly for staff. This is needed for shop staff that needs to re-order some past order for anonymous customer.
> Basket API: Allow re-order for anonymous customers

- shuup/default_reports/reports/sales.py
- shuup/default_reports/reports/sales_per_hour.py
- shuup_tests/default_reports/test_default_reports.py
- shuup_tests/default_reports/utils.py
The order dates should be localized to the current timezone configuration before using that to group.
> Report: consider the timezone when grouping order dates

- shuup/default_tax/module.py
- shuup_tests/default_tax/test_default_tax.py
When tax rule has a specific customer tax group, do not allow contexts with no customer tax groups to match.
In some situations where a tax is only applied to a specific customer group, it is more than necessary to avoid taxing customers that do not belong to that group or which don't even have a group configured.
So, in cases where we have taxes for companies like B2B and also sell to a regular customer with different prices and also allow anonymous ordering, we don't want to tax the anonymous user the same way we tax companies.
To create a tax rule that applies to any customer group, creating a simple rule with no customer tax group will work as expected.
No refs
> DefaultTax: filter tax rules correctly

- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/locale/fi_FI/LC_MESSAGES/django.po
- shuup/admin/locale/it/LC_MESSAGES/django.po
- shuup/admin/locale/ja_JP/LC_MESSAGES/django.po
- shuup/admin/locale/pt_BR/LC_MESSAGES/django.po
- shuup/admin/locale/sv_SE/LC_MESSAGES/django.po
- shuup/admin/locale/zh_Hans/LC_MESSAGES/django.po
- shuup/core/models/_products.py
Add a own translation for shipping mode as "shipped (deliverable)"
and "not shipped (non-deliverable)"
Refs #1175
Suggestion for https://github.com/shuup/shuup/pull/1196
> Product admin: Shipping mode translations (#1175)

- shuup/reports/forms.py
- shuup/reports/utils.py
- shuup_tests/reports/test_parse_date_range_presets.py
Since reports doesn't show time but just dates it is convenient to include the start of the day to reports. For example when getting report for last 7 days the last day should be include
fully and not for last hour if the report is run at 11pm.
As a note: No need to set the range to future when choice is today.
> Reports: Include start of the day to reports and introduce this week as a date range choice

- shuup/core/basket/update_methods.py
- shuup/front/basket/update_methods.py
- shuup/front/settings.py
The core basket update methods will raise exception on onderability errors.
Front basket update methods will still save orderability errors in messages framework.
No Refs
> Core: make basket raise orderability errors

- doc/changelog.rst
- shuup/admin/views/select.py
- shuup_tests/admin/test_select_view.py
Allow fetching only "sellable" product modes through admin ajax select view.
> Admin: Filter variation parents for select view

- doc/changelog.rst
- shuup/reports/forms.py
- shuup/reports/utils.py
- shuup/reports/writer.py
- shuup/utils/dates.py
- shuup_tests/utils/test_dates.py
Make it possible to filter objects also by time.
This is useful for filtering orders in a time range inside a single day, for example.
> Report: change date filter field to DateTime

- shuup/admin/views/select.py
- shuup_tests/admin/test_select_view.py
Allow filtering with sales unit symbol for `shuup.admin.views.MultiselectAjaxView`.
> Admin: Add option to filter with sales unit symbol

- shuup/admin/npm-shrinkwrap.json
- shuup/front/npm-shrinkwrap.json
- shuup/notify/npm-shrinkwrap.json
- shuup/xtheme/npm-shrinkwrap.json
Update the npm-shrinkwarp.json files to lockfileVersion 1.
Currently the best Node.js version to build Shuup resources is 6, but
then a more fresh npm is also needed compared to the version which was
used to create the shrinkwraps.  Newer npm expects a new lock file
format and these shrinkwraps will therefore be regenerated every time
when building the resources.
Committing those regenerated contents here so that they wouldn't change
after each build anymore.
> Update npm-shrinkwrap.json files

- doc/changelog.rst
- shuup/core/api/basket.py
- shuup/core/basket/commands.py
- shuup/core/order_creator/_creator.py
- shuup_tests/api/test_basket_api.py
- shuup_tests/core/test_basket_commands.py
- shuup_tests/core/test_order_creator.py
This is useful to track the products added to the basket
Add option to pass additional arguments to add command like `extra`, `force_new_line` and `parent_line`
> Core: make core basket command return added basket line id

- doc/changelog.rst
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/orders/views/shipment.py
- shuup/admin/templates/shuup/admin/orders/create_shipment.jinja
- shuup/core/models/_orders.py
- shuup/core/models/_product_shops.py
- shuup/core/suppliers/base.py
- shuup_tests/api/test_basket_api.py
- shuup_tests/api/test_basket_packages.py
- shuup_tests/core/test_shipments.py
- shuup_tests/core/test_suppliers.py
- shuup_tests/simple_supplier/test_simple_supplier.py
- shuup_tests/simple_supplier/utils.py
Core: Validate stocks for stock managed suppliers only
* Also only check stocks for stock managed suppliers when
creating shipments.
* Skip supplier checks for variation parents and package
parents. Variation parents is not meant to be added to
basket and package parent supplier availability is
determined by the package components.
* Add supplier stock managed info to shop product
is orderable cache to avoid issues when supplier stock
managed attribute is changed.
Admin: Match shipment supplier to order line supplier
> Validate stocks based on supplier stock managed attribute and make sure shipments supplier matches with the order line

- doc/changelog.rst
- shuup/admin/forms/_auth.py
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/templates/shuup/admin/auth/recover_password_mail_content.jinja
- shuup/admin/templates/shuup/admin/auth/recover_password_mail_subject.jinja
- shuup/admin/templates/shuup/admin/auth/request_password.jinja
- shuup/admin/templates/shuup/admin/auth/reset_password.jinja
- shuup/admin/urls.py
- shuup/admin/views/password.py
- shuup/core/utils/forms.py
- shuup_tests/admin/test_password_reset.py
Staff users can request to change their passwords directly through Shuup admin interface.
The user emails are used to send the reset email link
> Admin: add specific form to request and reset staff user password

- doc/changelog.rst
- shuup/front/admin_module/checkout/form_parts.py
- shuup_tests/admin/test_shop_edit.py
An error raises when creating a new shop from admin view.
No Refs
> Admin: fixed checkout form to skip if there is no form at all

- doc/changelog.rst
- shuup/admin/modules/users/views/detail.py
- shuup/admin/modules/users/views/permissions.py
- shuup_tests/admin/test_user_module.py
When managing a superuser, do not add or remove it from the current shop staff member list.
Refs POS-2414
> Admin: do not add or remove superusers from shop staff members

- shuup_tests/front/test_middleware.py
A front unit test was breaking subsequent tests by not reverting the timezone set
> Fix SimpleCMS children test

- doc/changelog.rst
- shuup/importer/admin_module/__init__.py
Require only `shuup.change_shop` permission to execute data imports 
Refs POS-2349
> Data import: require only shop change permission to execute data imports

- shuup/testing/__init__.py
- shuup_tests/core/test_fk_constraint.py
This prevents bugs when developing and prevents errors when in production
> Core: enable ForeignKey constraint for SQLite database backends

- shuup/testing/__init__.py
- shuup_tests/admin/test_category_module.py
- shuup_tests/admin/test_product_mass_edit.py
- shuup_tests/admin/test_product_module.py
- shuup_tests/admin/test_views.py
- shuup_tests/api/test_basket_api.py
- shuup_tests/conftest.py
- shuup_tests/core/test_fk_constraint.py
- shuup_tests/importer/test_product_import.py
- Re-enable ForeignKey constraint for SQLite database backends. The constraint is not enabled for browser tests
- Change the shop product id sequence when testing. It is very important that product and shop product ids are not mixed together. This adds a auto fixture to start shop product ids in #1500
No Refs
> Improve unit tests

- doc/changelog.rst
- shuup/gdpr/locale/en/LC_MESSAGES/django.po
- shuup/gdpr/locale/fi_FI/LC_MESSAGES/django.po
- shuup/gdpr/models.py
- shuup/gdpr/resources.py
- shuup/gdpr/static_src/less/index.less
- shuup/gdpr/templates/shuup/gdpr/privacy_policy_update.jinja
- shuup/gdpr/urls.py
- shuup/gdpr/utils.py
- shuup/gdpr/views.py
- shuup_tests/gdpr/test_consent_requirements.py
- shuup_tests/gdpr/test_consent_resource.py
- shuup_tests/gdpr/test_data_download.py
- shuup_tests/gdpr/test_front_views.py
Before this PR, user had no idea the consent pages were changed. This PR adds a top bar on the front prompting for new consent.
> GDPR: Show consent changes

- shuup/core/models/_products.py
- shuup/front/template_helpers/general.py
- shuup/front/utils/product.py
- shuup/front/utils/sorts_and_filters.py
- shuup/xtheme/plugins/products.py
- shuup_tests/browser/front/test_category_view.py
- shuup_tests/core/test_products_in_shops.py
- shuup_tests/front/test_general_template_helpers.py
- shuup_tests/front/test_utils.py
Parler has a bug that fails to load translations after they are fetched from cache
Check the PR that fixes the bug in Parler https://github.com/django-parler/django-parler/pull/228
> General: cache object ids instead of the model instances

- doc/changelog.rst
- shuup/core/api/front_products.py
- shuup/core/models/_product_shops.py
- shuup/front/__init__.py
- shuup/front/admin_module/translation/form_parts.py
- shuup/front/apps/auth/locale/en/LC_MESSAGES/django.po
- shuup/front/apps/registration/locale/en/LC_MESSAGES/django.po
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/middleware.py
- shuup/front/template_helpers/general.py
- shuup/front/templates/shuup/front/admin/translation.jinja
- shuup/front/utils/translation.py
- shuup_tests/conftest.py
- shuup_tests/front/test_languages.py
- shuup_tests/functional/test_admin_orders.py
Merchants can now limit the language options to be selected in storefront by users.
Refs POS-2438
Requires https://github.com/django-parler/django-parler/pull/228
> Front: add shop option to limit storefront language options

- shuup_tests/browser/front/test_category_view.py
Way too inconcistent. Let's consider activating this at next round of browser tests fixes.
> Browser tests: Disable `test_category_product_filters_3`

- doc/changelog.rst
- doc/ref/provides.rst
- shuup/admin/__init__.py
- shuup/admin/template_helpers/shuup_admin.py
- shuup/admin/utils/urls.py
- shuup/front/__init__.py
- shuup/front/template_helpers/urls.py
- shuup/front/utils/urls.py
- shuup_tests/front/test_model_resolver.py
Now it is possible to customize the way model URLs are resolved.
Replaces https://github.com/shuup/shuup/pull/1336
> General: add model url resolver as a setting for Front and Admin

- doc/changelog.rst
- shuup/core/cache/__init__.py
- shuup/core/models/_categories.py
- shuup/core/models/_products.py
- shuup/front/template_helpers/general.py
- shuup/xtheme/locale/en/LC_MESSAGES/django.po
- shuup/xtheme/plugins/products.py
- shuup_tests/admin/test_wizard.py
- shuup_tests/api/test_front_users_api.py
- shuup_tests/conftest.py
- shuup_tests/core/test_configurations.py
- shuup_tests/core/test_products_in_shops.py
- shuup_tests/front/test_general_template_helpers.py
- shuup_tests/simple_supplier/test_simple_supplier.py
- shuup_tests/utils/test_cache.py
- shuup_tests/xtheme/test_default_template_dir.py
- shuup_tests/xtheme/test_extra_views.py
- shuup_tests/xtheme/test_theme.py
- shuup_workbench/test_settings.py
- Add parameter to general template tags to filter only products on sale
- Add option to show only sale items in highlight plugin
- Translate Highlight option types
Refs POS-2484
> Xtheme: add option to show only sale items in highlight plugin

- shuup/xtheme/locale/en/LC_MESSAGES/django.po
- shuup/xtheme/templates/shuup/xtheme/admin/macros.jinja
Add a popover to help users to configure the theme. The popover is show when the page loads and it is hidden after 3 secs. 
Refs POS-2477
> Xtheme: highlight the configure button of the active theme

- doc/changelog.rst
- shuup/front/static_src/less/front/navigation.less
- shuup/themes/classic_gray/locale/en/LC_MESSAGES/django.po
- shuup/themes/classic_gray/templates/classic_gray/admin/extra_config.jinja
- shuup/themes/classic_gray/templates/classic_gray/admin/extra_config_css.jinja
- shuup/themes/classic_gray/templates/classic_gray/admin/extra_config_js.jinja
- shuup/themes/classic_gray/templates/classic_gray/shuup/front/macros/theme/navigation.jinja
- shuup/themes/classic_gray/theme.py
- shuup/xtheme/_theme.py
- shuup/xtheme/admin_module/views.py
- shuup/xtheme/templates/shuup/xtheme/admin/config_detail.jinja
- shuup_tests/front/test_classic_gray_theme_settings.py
Add Xtheme option to render extra templates in theme configuration. This enable template injection in the configuration page for more advanced visualization and options.
Refs POS-2476
> Classic Gray: add option to configure shop logo size styles

- doc/changelog.rst
- shuup/admin/forms/_quick_select.py
- shuup/admin/forms/widgets.py
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/categories/forms.py
- shuup/admin/modules/contacts/forms.py
- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/static_src/base/js/quick_add_related_objects.js
- shuup/admin/static_src/base/less/shuup/custom-forms.less
- shuup/admin/static_src/base/less/shuup/quick-add.less
- shuup/admin/template_helpers/shuup_admin.py
- shuup/admin/templates/shuup/admin/forms/widgets/edit_button.jinja
- shuup/admin/templates/shuup/admin/forms/widgets/help_text.jinja
- shuup/admin/templates/shuup/admin/forms/widgets/quick_add_select.jinja
- shuup/admin/urls.py
- shuup/admin/utils/bs3_renderers.py
- shuup/admin/views/edit.py
- shuup/campaigns/admin_module/forms/_basket.py
- shuup/core/models/_configurations.py
- shuup/gdpr/admin_module/forms.py
- shuup/tasks/admin_module/views/edit.py
- shuup_tests/admin/test_edit_object_view.py
- shuup_tests/browser/admin/test_quick_add_edit_button.py
Now one can open edit page for related objects right on the object selector.
This makes it handy to open the related object page and make some changes.
Also, more quick add widgets were added in admin.
Refs POS-2486
> Admin: add button to edit selected instances on select inputs

- doc/changelog.rst
- shuup/front/forms/product_list_modifiers.py
- shuup_tests/browser/front/test_category_view.py
**Issue:** some manufacturers were available for filtering and when applied, no product was returned. The queryset was not considering invisible shop products that had the manufacturer linked.
Excluding invisible shop products fixes the issue.
The current shop was also added to the manufacturer and shop product queryset to avoid considering other shops.
Refs POS-2497
> Front: fix manufacturer modified filter to consider only visible shop products

- shuup/front/middleware.py
- shuup/front/urls.py
- shuup_tests/front/test_languages.py
The same approach is done by Django `LocaleMiddleware` middleware.
Use a different js catalog function in front urlpatterns to prevent forcing the shop language settings in admin js catalog.
Refs POS-2495
> Front: ensure the request has the correct language code

- README.rst
Should be useful to indicate that Shuup is available at PyPI. 
[![PyPI](https://img.shields.io/pypi/v/shuup.svg)](https://github.com/shuup/shuup)
> Add PyPI badge to readme

- doc/changelog.rst
- shuup/front/templatetags/thumbnails.py
- shuup_tests/front/test_thumbnails_templatetag.py
With external media like S3 this check makes it super slow since every single file is openeed and fetched from S3 just for this check on every single request.
And if some SVG files gets past this check then maybe the merchant just deserves the fail.
> Front: Do not open files to check whether SVG

- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/templates/shuup/admin/forms/widgets/help_text.jinja
The translation was getting formatted before the actual string translation
This ensures the translation is formatted after the correct string is being returned
No Refs
> Admin: fix translatable string format

- shuup/front/template_helpers/general.py
- shuup_tests/conftest.py
- shuup_tests/front/test_general_template_helpers.py
- shuup_tests/xtheme/test_theme.py
- shuup_workbench/test_settings.py
Enabling cache will simulate better the real world scenario when Shuup is deployed.
Refs #1375
> Re-enable cache for unit tests

- shuup/front/bower.json
- shuup/themes/classic_gray/bower.json
This fixes the carousel bug that occurs on IE Mobile 11.
Ref: POS-2512
> Owl Carousel plugin set to the newest version

- shuup/admin/modules/products/views/list.py
- shuup_tests/browser/admin/test_picotable.py
Well there is certain limitations with our Picotable filters since for example filtering with categories would require to use current shop  to filter the filter options. The name filter here looks pretty handy. When we have the admin design update done maybe we then introduce more options for related filters.
Since pretty much only option to add filters to the columns is define column as default column I removed few to add the categories. Shop shouldn't be needed since the products are already filtered by currently active shop. Also product type shouldn't have too much importance in basic installation.
> Admin: Add option to filter product with categories

- .travis.yml
- doc/changelog.rst
- shuup/admin/template_helpers/shuup_admin.py
- shuup/admin/templates/shuup/admin/macros/multilanguage.jinja
- shuup/testing/browser_utils.py
- shuup/testing/utils.py
- shuup/xtheme/plugins/forms.py
- shuup/xtheme/plugins/text.py
- shuup/xtheme/templates/shuup/xtheme/_editor_cell.jinja
- shuup/xtheme/templates/shuup/xtheme/editor.jinja
- shuup_tests/browser/front/test_xtheme_plugin_form.py
Make the initial selected language be the current language in multi-language forms to save extra clicks from users.
Improve xtheme to make TextPlugin fallback to empty string instead of `None` and also make the Parler default language be the first one in multi-language forms.
Refs POS-2510
> Xtheme:  make the initially selected language be the active one in form tabs

- shuup/front/apps/registration/forms.py
The contact instance was None always as `shops.add()` doesn't return the instance
No Refs
> Front: fix contact registration signal to send the person instance

- setup.py
Pinning this requirement should not be needed.
Note: Maybe still we need closer look, but let's first check what Travis has to say about this.
Refs https://github.com/shuup/shuup/issues/1395
> Unpin cryptography

- shuup/gdpr/static_src/js/index.js
- shuup/gdpr/static_src/less/index.less
- shuup/gdpr/templates/shuup/gdpr/gdpr_consent.jinja
Fixed gdpr-privacy bar issues with iOS & Windows phone (On Win Phone the text would go over the screen, on iOS the 'accept' button wasn't visible when rotated horizontally) 
Also fixed the privacy-preference box issue, the text was showing up outside of the box on mobile devices.
Tickets for some of the issues here don't exist.
> Front: Fix Windows phone & iOS issues (POS-2513)

- tox.ini
MPTT 0.9.1 dropped support for old Django versions
https://github.com/django-mptt/django-mptt/commit/b18933b24a8ab25e91916e4fc3104a867eadcf88
> Fix MPTT version to max 0.9.0 for Django <= 1.9

- shuup/front/templates/shuup/front/checkout/method_choice.jinja
When service providers and methods don't have a name set, a template error was rendered.
Use translation getter and fallback to blank string when no language was set
Refs POS-2531
> Front: fallback checkout method names to blank text

- doc/changelog.rst
- shuup/admin/template_helpers/shuup_admin.py
- shuup/default_importer/importers/product.py
- shuup/importer/admin_module/forms.py
- shuup/importer/admin_module/import_views.py
- shuup_tests/importer/test_product_import.py
- Create a new shop product for the current shop when importing products. The importer was changing the shop of existing shop products to the current importer one
- Removed shop field from importer form and using the current admin shop
Refs POS-2538
> Importer: do not change the current shop for existing shop products

- shuup/front/static_src/js/category.js
Things like for example Wishlist plugin might call this reload on wrong times like frontpage for example.
> Front: Do not continue product reload without ajax div

- doc/changelog.rst
- shuup/admin/template_helpers/shuup_admin.py
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/static_src/less/front/navigation.less
- shuup/front/template_helpers/general.py
- shuup/front/templates/shuup/front/macros/general.jinja
- shuup_tests/front/test_edit_in_admin_toolbar.py
Add edit in admin button to toolbar to enable editing the current object in admin page
Refs POS-2487
> Front: add edit object link to admin toolbar

- shuup/gdpr/static_src/gdpr.js
- shuup/gdpr/templates/shuup/gdpr/gdpr_consent.jinja
- shuup_tests/browser/front/test_gdpr_consent.py
Consent-bar form is now purely ajax POST form.
GDPR divs are removed upon successful completion of AJAX.
Possible issues:
Missing tests?
https://github.com/shuup/shuup/issues/1425
> GDPR: Turn consent-form into an ajax form

- shuup/front/apps/simple_search/settings.py
As there is no default setting, the app will break when trying to use this setting
No Refs
> Simple Search: add default setting for search limit

- doc/changelog.rst
- shuup/admin/modules/orders/views/status.py
- shuup/simple_cms/admin_module/views.py
- shuup/tasks/admin_module/views/list.py
All of them are translation fields and they need to filter by the related field name
Refs POS-2551
> Fix filter fields in order status, simple cms and tasks type admin modules

- shuup/admin/modules/orders/static_src/create/utils/numbers.js
toFixed in ensureNumericValue was returning a string instead of an int or a float,
that's what was breaking the addition of stock products to the order in admin.
Refs #1431
> Admin: Fix adding stock products to the order

- doc/changelog.rst
- shuup/admin/static_src/wizard/js/wizard.js
- shuup/admin/static_src/wizard/less/wizard.less
Make the button align horizontally with Next/Finish button
No Refs
**Before**
**After**
> Admin: fix wizard skip button alignment

- shuup/admin/static_src/base/js/editor.js
- shuup/xtheme/templates/shuup/xtheme/editor.jinja
The issue is with summernote itself, this is a simple workaround. Summernote content can now be saved from codeview.
This fixes #1467
> Fix summernote codeview

- shuup/admin/forms/widgets.py
- shuup/admin/modules/contacts/forms.py
- shuup/admin/modules/products/signal_handlers.py
- shuup_tests/core/test_product_caching_object.py
- Core: Fix ShopProduct & Category ManyToMany relation
A check needed to be done in `update_categories_through` to see if the
instance sent is a Category or a ShopProduct and then to proceed accordingly.
Test I wrote here will break without the mentioned check.
Fixes #1188
- Admin: Enable Contact Group Quick add for Contact edit page
Made a new widget -` QuickAddContactGroupMutliSelect` because if I changed
the QuickAdd`ContactGroupSelect` to inherit QuickAdd`RelatedObjectMultiSelect` it would
crash the discount module which supports only one group per discount. Perhaps that should be changed?
Fixes #1489
> Fix ShopProduct & Category ManyToMany relation, Enable Contact Group Quick add for Contact edit page

- shuup/admin/static_src/base/scss/shuup/summernote.scss
- shuup/admin/static_src/base/scss/style.scss
It seems on scroll some Summernote JS sets it's header width to 20px while making it's position fixed while scrolling close to top. Couldn't find any unwanted side effects from this fix either.
Separated .scss since easier to spot and throw out once this re-fixed in some future release.
Fixes https://github.com/shuup/shuup/issues/1521
> Admin: hotfix summernote editor scroll

- shuup/admin/static_src/base/js/base.js
- shuup/admin/static_src/base/js/components.js
- shuup/admin/static_src/base/js/main-menu.js
- shuup/admin/static_src/base/scss/shuup/base.scss
- shuup/admin/templates/shuup/admin/base.jinja
- shuup/admin/templates/shuup/admin/dashboard/dashboard.jinja
Add a button to the bottom center of the admin pages that will scroll to top when the page is scrolled.
This help users to back to the top when pages are too long.
Refs POS-2611
> Admin: add scroll to top button

- shuup/admin/locale/en/LC_MESSAGES/djangojs.po
- shuup/admin/modules/categories/views/list.py
- shuup/admin/modules/products/views/list.py
- shuup/admin/static_src/base/scss/shuup/picotable.scss
- shuup/admin/static_src/picotable/picotable.js
- shuup/simple_supplier/admin_module/views.py
- shuup/simple_supplier/templates/shuup/simple_supplier/admin/base_picotable.jinja
- shuup_tests/admin/test_category_list_view.py
- shuup_tests/admin/test_product_list_view.py
- shuup_tests/api/conftest.py
- shuup_tests/simple_supplier/test_list_view.py
- Make the column expand when possible and take advantage of free space.
- Do not add link to stock management rows
- Add box style to the abstract view when there is no link
- Show category name instead of the hierarchy in picotable columns 
Refs POS-2593
> Admin: fix picotable abstract view for mobile devices

- shuup/admin/npm-shrinkwrap.json
- shuup/admin/package.json
- shuup/admin/static_src/base/js/tour.js
- shuup/admin/static_src/base/scss/shuup/tour.scss
Updated shepherd to 2.0.0-beta.27,
Product and Category tours can now be cancelled by "X".
Issue now is that product's first step style differs from other steps.
Fixes #1560
> Admin: Fix tour cancel button & update shepherd

- shuup_tests/admin/test_category_list_view.py
Category factory uses random choices for status which affects negatively to list view results.
> Tests: remove some randomness from category list tests

- shuup/xtheme/static_src/editor/editor.js
Fix jQuery event selector by replacing comma with space.
JQuery documentation says it is a string keys that represent one or more space-separated event types
Refs ENT-2565
> Xtheme: fix publish on save routine

- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/products/views/mass_edit.py
- shuup/admin/static_src/base/js/drag-n-drop.js
- shuup/admin/static_src/picotable/picotable.js
- shuup/admin/templates/shuup/admin/edit_settings.jinja
- shuup/admin/templates/shuup/admin/mass_action/mass_edit.jinja
- shuup/admin/utils/picotable.py
- shuup/utils/dates.py
- shuup_tests/utils/test_dates.py
Some picotable filters use time and it was not expected when parsing the values
Render fields separately through bs3.field method making form apply standard styles
Improve selected items count message
Add more styles to the item template when adding a field to picotable
Check whether the field value has changed before making a new request
Refs ENT-2551
> Admin: picotable general fixes

- shuup/xtheme/templates/shuup/xtheme/plugins/image.jinja
This prevents adding an empty h2 tag which can add extra padding/margin to the placeholder
> Xtheme: fix image plugin by rendering h2 only when necessary

- shuup/api/docs.py
- shuup/core/api/front_passwords.py
- shuup/customer_group_pricing/admin_form_part.py
- Admin: Remove duplicate fields in Contact Group Pricing & Discount forms
Contact group pricing & discounts for products were showing duplicate fields.
- API: Fix docs view bugs
Accessing /api/docs would throw a django assertion error, SetPasswordViewSet & PasswordResetViewSet were missing
serializer_class. Defined the base serializer for them.
Clicking "Try it out" on docs in api/docs would throw a 406 error.
Fixes #1602
> Admin: Remove duplicate fields in CGP & Fix API Docs 

- shuup/admin/modules/orders/static_src/create/index.js
- shuup/admin/modules/orders/views/edit.py
- First error was being caused by bad queries, the deleted query & if statement can already be found in Shop.get_for_user.
- Second error was being caused by purgeAll, a function that was removed in v4 of redux-persist. - https://github.com/rt2zz/redux-persist/issues/373
Refs #1631
> Admin: Fix order creation errors

- shuup/admin/static_src/base/js/form-utils.js
- shuup/admin/static_src/base/scss/shuup/buttons.scss
- shuup/admin/static_src/base/scss/shuup/support-navigation.scss
Item save button is now moved to the bottom right corner when it's not visible.
Refs #1628
> Admin UI: Move save button to bottom right corner when not visible

- setup.py
- shuup/core/models/_products.py
- shuup/core/models/_units.py
- shuup/core/shop_provider.py
- shuup/core/utils/context_cache.py
- shuup/front/apps/saved_carts/templates/shuup/saved_carts/cart_detail.jinja
- shuup/front/template_helpers/general.py
- shuup/front/templates/shuup/front/macros/order.jinja
- shuup/front/templates/shuup/front/macros/product.jinja
- shuup/front/templates/shuup/front/macros/product_information.jinja
- shuup/front/templates/shuup/front/macros/product_ordering.jinja
- shuup/front/utils/cache.py
- shuup/simple_cms/plugins.py
- shuup/xtheme/plugins/category_links.py
- shuup_tests/front/test_general_template_helpers.py
IDs were used because of a bug of Django Parler which was fixed in django-parler/django-parler#228
As the fix was not release in PyPi, use the last commit of GitHub repository available.
Fixes #1323
Refs ENT-2729
Context cache was creating new user group queries everytime for the same context object.
Cache the groups inside the instance so we can reuse that for the same request
Refs ENT-2729
- Use shop product cache in templates
- Prefetch and select related objects in several queries to prevent a lot of db queries
Refs ENT-2729
> Fix parler cache

- shuup/core/models/_categories.py
- shuup/core/signal_handers.py
- shuup/core/utils/context_cache.py
- shuup/front/signal_handlers.py
- shuup/front/templatetags/thumbnails.py
- shuup/xtheme/plugins/products.py
- shuup_tests/browser/admin/test_tour.py
- shuup_tests/core/test_context_cache.py
- shuup_tests/front/test_thumbnails_templatetag.py
Make sure to change the key to customer_groups when creating the cache key
Cache thumbnail images to prevent excessive thumbnails queries between requests
Refs ENT-2729
> Cache improvements

- shuup/admin/static_src/base/scss/shuup/content-blocks.scss
Lowered theme-card-body z-index to 900, so it doesn't mess up the search
dropdown.
Refs ENT-2749
> Admin: Fix theme-card style

- shuup/xtheme/static_src/editor/editor.less
Make the title column be max 50% of width.
Some cases where plugins have only checkboxes the title width was 100%.
No Refs
> Xtheme: fix plugin form styles

- shuup/front/apps/personal_order_history/views.py
- shuup/testing/factories.py
- shuup_tests/front/test_reorder.py
Do not use the first available supplier to add items to the basket when reordering.
Use the own order line supplier instead.
Refs ENT-2744
> Front: fix reordering from order history

- shuup/admin/modules/categories/views/list.py
- shuup/admin/static_src/picotable/picotable.js
- shuup/admin/utils/picotable.py
This fixes a bug in Category List View which was breaking when filling the name input
No Refs
> Admin: add option to prevent highlighting a picotable column

- shuup/core/utils/product_statistics.py
- shuup/utils/dates.py
- shuup_tests/utils/test_dates.py
When converting from date to datetime the time component will be
always 00:00 and in some cases, after applying the timezone information,
pytz will raise exception because the time can not exists at all.
This will occur when the date is a date which the timezone changes to DST,
adding 1 hour to time at 00:00 o'clock of the previous date.
To fix the issue, we first try making the datetime aware without DST mode,
if pytz raises NonExistentTimeError is because that time doesn't exist,
this way we try again but now informing that DST should be used instead.
No Refs
> Core: improve to_aware function to consider DST cases

- doc/ref/provides.rst
- shuup/front/template_helpers/urls.py
- shuup/front/utils/urls.py
Make the caller raise exception if set to do so.
In cases where custom model url resolvers were used,
the exception inside the front resolver was preventing other
resolvers to be called as it was breaking the provides iteration.
No Refs
> Front: do not raise exception in Front model url resolver

- shuup/utils/dates.py
- shuup_tests/utils/test_dates.py
`shuup.utils.dates.dst_safe_timezone_aware` was added but doesn't work with Django 1.8 since `timezone.make_aware` does not have "is_dst" option. Well instead worrying this too much we will raise here.
In case this becomes problem for some old projects we accept better fixes for this, but be highly suggest updating project Django version instead.
> Fix broken tests for Django 1.8

- shuup/utils/dates.py
- shuup_tests/utils/test_dates.py
As is_dst parameter doesn't exist, we should call pytz.localize instead
> Core: fix dst_safe_timezone_aware function for Django 1.8

- shuup/admin/template_helpers/shuup_admin.py
Instead expecting request having shop use admin shop provider get shop to get current shop.
Admin middleware makes rest of the admin code work but this template helper code is called
already in login where there is no logged in user which means admin shop is not defined.
> Admin: do not expect shop for request

- shuup/reports/report.py
- shuup_tests/reports/test_reports.py
Previously it tries to sum None and numeric values, which raises a TypeError, when first data item contains None value in countable keys
Refs: #1687
> Fix a bug in report get_totals

- shuup/admin/modules/orders/static_src/create/index.js
- shuup/admin/static_src/base/js/form-utils.js
- shuup/admin/static_src/base/scss/shuup/buttons.scss
- shuup/admin/static_src/base/scss/shuup/support-navigation.scss
- Admin: Fix order edit view
`purgeAll` was replaced completely by `purge` in redux v4. 
This should have been done in https://github.com/shuup/shuup/pull/1633 but I guess I didn't see it then.
No refs
- Admin: Fix Save button not working properly with xtheme edit
There's also a simpler but dumber fix I made for this: https://github.com/maximlion/shuup/commit/9f1b9bcfb991c3df6b99005a525052c1f1a63107
Perhaps that should be merged instead.
Fixes #1691
> Admin: Fix order edit view

- shuup/front/static_src/js/carousel.js
- shuup/front/static_src/less/front/carousel.less
- Front: Fix carousel not working with Firefox
Turns out that carousel arrows weren't working with Firefox. Everything seems to work good with Ghostery.
- Front: Increase carousel arrow padding
No refs
> Fix carousel not working with Firefox & increase padding.

- shuup/core/models/_categories.py
- shuup/discounts/utils.py
- shuup_tests/core/test_categories.py
This is useful for example in templates where it is usual to traverse the tree
Do not use IN operation when there is only a single item. This reduces the number of joins and makes the query faster
Refs ENT-2770
> Core: performance improvements

- shuup/admin/modules/products/views/delete.py
- shuup_tests/admin/test_product_module.py
What was going on:
Product that was supposed to be deleted had an id that was different from it's ShopProduct's id.
Our logic sends ShopProduct object to Product delete view which was causing the problems. These changes extract Product object from received ShopProduct in ProductDeleteView.
Fixes #1699
> Admin: Fix Product deletion returning 404

- shuup/front/templatetags/thumbnails.py
It is possible to have broken image in Shuup which raises ValueError while thumbnailing. It is not worth fail rendering template because of this.
> Front: fix issue with image thumbnails

- shuup/admin/modules/orders/mass_actions.py
- shuup/admin/modules/products/mass_actions.py
- shuup_tests/admin/test_mass_actions.py
`.update()` is a direct SQL statement so it wasn't calling save() at all, hence it didn't trigger post_save signals at all
to bump caches.
This iterates through the whole query after the update bumping caches for each shop product id
Fixes #1710
> Admin: bump product cache when using mass action, limit mass action changes to one shop

- shuup/admin/static_src/picotable/picotable.js
- shuup/front/apps/customer_information/dashboard_items.py
- shuup/front/apps/customer_information/views.py
- shuup/front/apps/registration/views.py
- shuup_tests/front/test_customer_information.py
- shuup_tests/front/test_registration.py
- shuup_tests/functional/test_notify_on_company_created.py
- Admin: Fix picotable checkboxes breaking the layout
The first `thead` had `colspan(2)` attribute which was making problems, I removed it completely since I believe that it's unnecessary.
Fixes #1654
- Front: Improve company registration logic 
Redirect  regular contact to customer information when he tries to register a company & company registration is not allowed.
No refs
> Fix picotable checkboxes breaking the layout &  Improve company registration logic

- shuup/admin/static_src/base/js/dropzone.js
For backwards compatibility, make the dropzone browsable by default
> Admin: make the media browsable by default

- shuup/admin/templates/shuup/admin/base/_navigation.jinja
Removed Support ID from the template,
but left function here in case we need it in the future, https://github.com/shuup/shuup/blob/829dfaa4fec7ead2a4992016e5a7458a63233c1c/shuup/admin/template_helpers/shuup_admin.py#L67
Refs ENT-2978
> Remove Support ID from admin

- shuup/admin/static_src/base/scss/shuup/picotable.scss
Longs columns just don't work and 500px limit should be fair enough.
> Admin: setup max-width for picotable columns

- shuup/admin/modules/labels/views.py
- shuup/reports/report.py
- shuup_tests/reports/test_reports.py
Django crashes when rendering the success message because the label name was invalid
as the label was deleted
> Admin: fix crash when deleting a label

- shuup/reports/report.py
- shuup_tests/reports/test_reports.py
Make the min and max support different timezones and prevent overflow and underflow
> Reports: fix max and min dates when values are set to None

- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/templates/shuup/front/macros/general.jinja
- shuup/front/templates/shuup/front/macros/product.jinja
- shuup/front/templates/shuup/front/macros/product_information.jinja
- shuup/front/templates/shuup/front/macros/product_ordering.jinja
- shuup/front/templates/shuup/front/product/detail.jinja
- shuup/front/templatetags/shuup_front.py
- shuup/front/themes/__init__.py
- shuup/themes/classic_gray/locale/en/LC_MESSAGES/django.po
- shuup/themes/classic_gray/theme.py
- shuup_tests/front/test_product_detail_theme_settings.py
Create mixin and move classic gray fields that are expected to exist in
Front base template to it.
Improve the product detail template by allowing merchant to hide
products tabs and listing attributes using a responsive table.
Refs MYS-16
> Front: add mixin with fields for base template

- shuup/front/admin_module/sorts_and_filters/form_parts.py
- shuup/front/signal_handlers.py
- shuup/front/utils/sorts_and_filters.py
When a product is changed, the filters cache must be bumped as
products can have attributes changed.
> Front: bump sort & filters queryset cache

- shuup/admin/base.py
- shuup/admin/modules/permission_groups/views/edit.py
- shuup/reports/admin_module/__init__.py
- shuup/reports/admin_module/views.py
- shuup/reports/forms.py
- shuup/reports/report.py
- shuup_tests/reports/test_admin_permissions.py
- shuup_tests/reports/test_reports.py
Add get_extra_permissions-method for BaseAdminModule for custom permissions inside the admin module which not necessarily depend on URLs.
Use these extra permissions to define permissions for provided reports.
Pass request to ReportView for custom logic based on current user, shop or supplier.
> Reports: introduce report permissions and pass request

- shuup/front/admin_module/sorts_and_filters/form_parts.py
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/templates/shuup/front/admin/macros.jinja
- shuup/front/templates/shuup/front/admin/sorts_and_filters_category.jinja
- shuup/front/templates/shuup/front/macros/basket.jinja
- shuup/front/templates/shuup/front/macros/navigation.jinja
- shuup/front/utils/sorts_and_filters.py
- shuup/front/views/dashboard.py
- shuup_tests/browser/front/test_category_view.py
- shuup_tests/front/test_customer_information.py
- shuup_tests/front/test_filters.py
- shuup_tests/functional/test_sorts_and_filters_admin.py
When the merchant configured some list sort & filter for a category there was no option to clear the configuration and use the shop's default again.
Added a option to category configuration that overrides the shop default configuration when checked.
Refs MYS-57
> Front: add option to explicitly override shop's list sort & filter configuration

- shuup/simple_supplier/admin_module/views.py
- shuup/simple_supplier/module.py
Use Django's save() when changing a product managed stock flag to allow
signals to be attached and behave accordingly to the new stock status.
Refs MYS-71
> Simple Supplier: use Django get_or_create instead of update to allow signal handling

- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/templates/shuup/front/macros/general.jinja
- shuup/front/templates/shuup/front/macros/product.jinja
- shuup/front/templates/shuup/front/product/product_preview.jinja
Do not render link in product card as <a> elements can't be inside another <a> elements.
Refs MYS-91
> Front: add option to render supplier link in macro

- doc/ref/provides.rst
- shuup/admin/__init__.py
- shuup/admin/template_helpers/shuup_admin.py
- shuup/admin/urls.py
- shuup_tests/admin/test_template_helpers.py
One can now inject basic urls into browser using provides
Refs TCP-8
> Admin: add option to extend browser urls through provides

- shuup/admin/npm-shrinkwrap.json
- shuup/front/npm-shrinkwrap.json
- shuup/front/package.json
- shuup/front/static_src/js/index.js
- shuup/themes/classic_gray/npm-shrinkwrap.json
- shuup/themes/classic_gray/package.json
- shuup/xtheme/npm-shrinkwrap.json
- shuup/xtheme/package.json
Move `babel-core` to dependencies for production builds. Add `babel-polyfill` for old browsers like IE 11. Bump `parcel-bundler`.
> Update NPM packages to latest versions

- shuup/admin/static_src/base/scss/shuup/custom-modals.scss
- shuup/admin/static_src/base/scss/shuup/quick-add.scss
- shuup/admin/toolbar.py
- shuup/notify/actions/email.py
- shuup/notify/admin_module/forms.py
- shuup/notify/templates/notify/admin/generic_script_template.jinja
- shuup/notify/templates/notify/admin/script_item_editor.jinja
- shuup_tests/notify/test_notify_admin.py
The user serializer bug was happening because a User model was being passed to the template
instead of just model's primary key. This ensures that doesn't happen.
Replaced normal text editor for email body with summernote.
Refs #1783, #1807
> Notify: Fix toolbar button style & user serializer error

- shuup/admin/static_src/picotable/picotable.js
- shuup/admin/utils/picotable.py
- shuup_tests/admin/test_picotable.py
Now it is possible to return extra info for each object in picotable list.
There are some special keys like `class` that is used to change the row class list for each item.
Refs MYS-97
> Admin: introduce extra info for items in picotable

- shuup/campaigns/admin_module/sections.py
- shuup/campaigns/templates/shuup/campaigns/admin/_product_campaigns.jinja
- shuup_tests/campaigns/test_product_section.py
Show active campaigns for currently active shop. Do not show catalog campaigns at all since catalog campaigns are not supported and will be deprecated on Shuup 2.0 (discounts-app) shoudl be used instead.
> Campaigns: fix product active campaigns form part

- shuup/front/apps/customer_information/locale/en/LC_MESSAGES/django.po
- shuup/front/apps/customer_information/notify_events.py
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/simple_supplier/module.py
- shuup/simple_supplier/notify_events.py
- shuup_tests/simple_supplier/test_simple_supplier.py
Sometimes the supplier and or the shop should be warned about low stocks and now that is possible
No Refs
> SimpleSupplier: add shop email and supplier email in alert limit

- shuup/admin/static_src/picotable/picotable.js
- shuup/core/models/_product_shops.py
- shuup/front/template_helpers/product.py
- shuup/front/views/category.py
Remove some levels of cache from front. When products becomes invisible
or any other visibility rule changes products must disapear from storefront.
Refs MYS-100
> Front: remove excessive levels of cache

- shuup/admin/modules/orders/mass_actions.py
When try to make delivery pdf for 1 shipment only, it will work if order.id == shipment.id (accidentally). In all other cases get_delivery_pdf() will try to run Shipment.objects.get() query using order.id (because you used ids[0]). Also it will show success notification without any pdf to download, but in logs will show error, if Shipment.objects.get() will raise exception.
With proposed changes pdf generation works correctly for 1 order/shipment or for several orders with 1 created shipment (other orders without shipments). Nothing changed for several shipments.
> Fix OrderDeliveryPdfAction when in action 1 order/shipment only

- shuup/campaigns/models/basket_line_effects.py
- shuup/campaigns/modules.py
- shuup_tests/campaigns/test_effects.py
- shuup_tests/campaigns/test_supplier_campaigns.py
When lines causes new lines to basket it is important that those discount lines are linked to correct supplier based on campaign.
> Campaigns: add campaign supplier to discount lines

- shuup/admin/modules/users/views/permissions.py
Fix to show initial permission groups for /sa/users/$user_id_here$/change-permissions/ page.
With current master code initial user groups doesn't showed in Permission Groups field. 
Firstly I tried to use initial= of Select2MultipleField, but then I found @tulimaki removed initial from Select2MultipleField in this commit due to some Select2MultipleField bug:
https://github.com/shuup/shuup/commit/1e1f8ba2abcf4d64a82ba7508e5fb7dc209e7e5b
Btwn, changes that made tulimaki works for manufactures shops: https://github.com/shuup/shuup/blob/master/shuup/admin/modules/manufacturers/views/edit.py#L33 because `super(ManufacturerForm, self).__init__(*args, **kwargs) ` return initial shops in self.initial
> Show initial permissions groups on change-permissions user page in /sa/

- shuup/admin/modules/currencies/views/edit.py
- shuup/admin/modules/orders/views/status.py
Using BreadcrumbedView is useless for Order Status and Currencies list views in /sa/. Breadcrumbs generated correctly without this view. But with BreadcrumbedView they displayed with duplicated entries, please check screens:
> Fix breadcrumbs for Order Status and Currencies

- shuup/campaigns/admin_module/forms/_basket_effects.py
- shuup_tests/campaigns/test_basket_campaign_admin.py
`for error in shop_product.get_quantity_errors(self.cleaned_data["quantity"]):`  was throwing an error because `ignore_minimum`  in `get_quantity_errors` has not been set.
Refs ENT-3006
> Admin: Fix bug in Campaign free product effect

- shuup/front/static_src/js/category.js
Rather skip the reloads when the state is undefined.
Refs MOOS-38
> Front: do not try to reload products with invalid state

- shuup/front/apps/registration/forms.py
Company Registration failed with error 'Manager isn't available; 'auth.User' has been swapped for 'users.User'' due to another reference on 'django.contrib.auth.forms.UserCreationForm' in CompanyRegistrationForm which use the django default 'User' model. Solved by overriding django 'UserCreationForm' and its Meta class in 'shuup/front/apps/registration/forms.py' to use the project swapped User model in CompanyRegistrationForm.
> Company Registration failed with swapped User model

- shuup/front/template_helpers/urls.py
- shuup/front/templates/shuup/front/macros/navigation.jinja
- shuup/front/urls.py
- shuup/front/views/misc.py
- shuup_tests/functional/test_stop_impersonating.py
Make it easier to get back to admin contacts list when impersonating. Introduce `shuup.urls.get_logout_url` template helper which returns stop impersonating URL when the shop staff is impersonating users.
Stop impersonate by logging out user and redirecting to admin login with contact list as next parameter. After this simply re-login for safety and the shop staff is back at contacts list to manage contacts.
> Front: improve logout when impersonating

- shuup/simple_cms/models.py
- shuup/simple_cms/views.py
- shuup_tests/simple_cms/test_page_view.py
Allow page creator option to preview the page on site before publishing it.
> Simple CMS: allow page owner see invisible page

- shuup/core/management/commands/compute_bought_with_relations.py
- shuup/core/utils/product_bought_with_relations.py
- shuup_tests/core/test_compute_bought_with_relations.py
Since product card is shown for variation parent it is important that the related bought with products are also calculated for variation parents.
> Core: include variation parents to bought with calculations

- shuup/front/apps/customer_information/forms.py
- shuup/front/apps/customer_information/settings.py
- shuup/front/apps/customer_information/views.py
- shuup/front/apps/personal_order_history/templates/shuup/personal_order_history/macros/order_detail.jinja
- shuup/front/apps/personal_order_history/templates/shuup/personal_order_history/order_detail.jinja
- shuup/front/checkout/methods.py
Add option to change form groups for Customer Information, Company Information and Address Book forms.
This enables users to customize specially the fields which are needed for specific solutions and hide forms when not needed
Refs MOOS-46
> Front: add option to customize customer information forms

- shuup/front/static_src/js/update_price.js
- shuup/front/templates/shuup/front/macros/product_image.jinja
This should fix broken images with normal products.
Lightbox init should not be called if the images are not available. Also we can not empty the images and then expect to find some images from the container.
> Front: fix bug in product images

- shuup/core/order_creator/_creator.py
- shuup/core/order_creator/_source.py
- shuup/testing/supplier_provider.py
1) Add `RequestSupplierProvider`. This provides an easy way to test supplier related requests
2) Expose `._data` to the public from `SourceLine`. It was strange that this was hidden after all. Basically, you could use the `to_json` but it's not always what you might want.
3) Ensure data is being carried from `SourceLine` to `OrderLine` properly.
> Multiple minor improvements

- shuup/front/views/misc.py
- shuup_tests/functional/test_stop_impersonating.py
After user stop impersonating, the old user is the active one again.
This prevents the user to do login again.
Refs MOOS-26
> Front: back to old user when stop impersonating

- shuup/front/templates/shuup/front/macros/navigation.jinja
* Product name in basket is limited to 45 chars
* Product name is not cut in the middle of the word
Refs ENT-2636
> Product name: Shorten product name in basket

- shuup/core/api/manufacturer.py
- shuup_tests/api/test_manufacturer_api.py
Setting primary product's image is possible through API by putting the ProductMedia id of the picture. 
Refs #1717, ENT-2773
> Admin API: Enable manufacturer logo addition

- shuup/front/apps/auth/views.py
- shuup/front/apps/registration/views.py
- shuup/front/template_helpers/general.py
When registration and login forms were in the same template, there could be fields id collision
No refs
> Front: add custom field ids format to prevent duplicates

- shuup/front/templates/shuup/front/macros/footer.jinja
The tag doesn't have the opening pair
> Front: remove extra div tag

- shuup/admin/templates/shuup/admin/contacts/edit.jinja
- shuup/admin/templates/shuup/admin/orders/_address_edit.jinja
- shuup_tests/browser/admin/test_order_detail.py
Contact address form was breaking on copying billing address region to shipping address.
This prevents that.
Edited code from [checkout.jinja](https://github.com/shuup/shuup/blob/be28e6eeee099445842bd02b72e03664c0318451/shuup/front/templates/shuup/front/macros/checkout.jinja)  so that it works with admin.
Fixes #1921
> Admin: Fix contact address form breaking on region copy

- shuup/core/management/commands/compute_bought_with_relations.py
Without that the same product could run many times wasting time and resources
No Refs
> Core: make sure to get unique product ids when computing relations

- shuup/core/api/category.py
- shuup_tests/api/test_category_api.py
- API: Include shops in category API
When making a category through API the category wouldn't be connected with any shops because the shops field was excluded. This fixes that.
Refs #1708
- API: Enable image upload for Categories
Refs #1717, ENT-2832, #1708
> Improve category API

- shuup/notify/admin_module/forms.py
- shuup_tests/xtheme/test_resources.py
- Xtheme: Improve the test for rendering resources
Refs #1849
- Notify: Replace empty text in "Bind to variable" with lines
This makes the select field much cleaner & more visible. (Before after choosing something from select, empty value was barely visible)
Refs #1783
> Xtheme: Improve the test for rendering resources & Improve notify styles

- shuup/front/static_src/js/update_price.js
- shuup/front/templates/shuup/front/macros/product_ordering.jinja
- shuup/front/templates/shuup/front/product/detail_order_section_no_product.jinja
when product was not orderable, the template rendered didn't contain
the correct product id making the product images disappear.
Refs MYS-139
> Front: add missing data- attribute with the product ID

- shuup/front/static_src/js/category.js
- shuup/front/static_src/js/index.js
- shuup/front/static_src/js/utils.js
Add the target of the scrolling after product list load into a global variable. This can be changed by 3rd party to control the scroll enabling it to even be disabled.
Add a custom event to warn when the product list is about to be loaded
Use jQuery .get() instead of .load() in ajax_content in order to be able to replace the DOM element with the content loaded
Move debounce to utils file and expose it to a global object
> Front: improve front filters JS customisation

- shuup/front/checkout/confirm.py
- shuup/front/templates/shuup/front/macros/checkout.jinja
- shuup/gdpr/providers.py
- shuup_tests/front/test_checkout.py
- shuup_tests/gdpr/test_forms.py
Save a configuration for each customer inside the options field and make sure it is not asked on the checkout anymore
Refs MYS-132
> Save and memorise options selected by the user

- shuup/core/models/_labels.py
- shuup/core/models/_product_variation.py
- shuup/core/models/_products.py
- shuup/core/models/_shops.py
- shuup/core/models/_units.py
`__str__` should always return strings and when using `safe_translation_getter` it returns a `__proxy__` instead
No Refs
> Core: use force_text in models __str__ method to make sure to return strings

- shuup/notify/conditions/simple.py
- shuup_tests/notify/test_conditions.py
A False constant implies to be a None value as the checkbox is never checked.
Converting values to bool solves the issue
Refs HEAL-30
> Notify: fix boolean test when a false constant is needed

- shuup/admin/forms/_auth.py
- shuup/front/apps/auth/forms.py
- shuup/front/apps/auth/views.py
- shuup_tests/front/test_auth.py
Shuup has a bug of not displaying a correct error message to users that are inactive and are trying to log in either in the front login form or in the admin login form. This is due to the confirm_login_allowed function not being called in the form validation process when inactive user is trying to log in. Thus, the default invalid login error is displayed even for inactive users trying to log in.
This can be fixed by overriding the clean method in both front and admin auth forms and manually calling the confirm_login_allowed function in case the user trying to log in is inactive similar to this:
[https://stackoverflow.com/a/46459998](url)
In the front auth view we also need to check that the user exists to pass the unit test regarding invalid login.
> Fix inactive users error

- shuup/admin/static_src/base/js/dropzone.js
When browse is not permitted the dropzone browse should open local filesystem instead.
> Admin: fix issue with media dropzone (HEAL-47)

- shuup/front/views/misc.py
Hey guys,
I saw you implemented new feature to back to super/staff_user after using 'Login as' function. This option is great and was waited by many users. Thanks.
After I tested this function on my dev workbench I found this nuance:
1) It back to /sa/contacts/ page after stop impersonating. But why contacts? From contacts or contact page we can't use 'Login as'. In this case better to redirect to /users/ page.
2) From my point of view, even better to redirect to user page, where 'Login as' was used. This was done in this commit.
So, commit changes will redirect user to /sa/users/user_id/ page, where 'Login as' was used. In other words, it will redirect to last super/staff_user page in /sa/ where user was before 'Login as'
> Back to user page after stop impersonating

- shuup/front/templates/shuup/front/macros/general.jinja
Also include fallback for using a first image if product has no primary image set
Refs HEAL-48
> Front: Include product image dimensions in Open graph tags

- shuup/core/models/_contacts.py
- shuup_tests/core/test_contact_groups.py
- shuup_tests/core/test_contacts.py
Remove custom error that was being called upon Contact Group creation which was preventing
the shop field to be empty/null
Refs RO-42
> Core: Set that contact group shop field can be empty

- shuup/core/models/_product_shops.py
- shuup/core/models/_products.py
- shuup/front/template_helpers/product.py
- shuup/front/templates/shuup/front/macros/product_ordering.jinja
- shuup/front/utils/product.py
- shuup_tests/core/test_product_variation_child_pricing.py
Some variation children is not available for all customers or pricing context meaning that with different shop or customer combinations might have different "cheapest price" for parent product. This also affects on orderability and few other situations.
> Core: improve filtering for variation children

- shuup/notify/actions/email.py
- shuup/notify/base.py
- shuup/notify/settings.py
- shuup_tests/notify/test_email.py
Currently the SendMail action uses the default email address from
settings all the time.
Now it is possible to change the email's sender information
Refs REAL-42
> Notify: make it possible to use from_email when sending emails

- shuup/admin/modules/orders/views/refund.py
- shuup/core/models/_order_lines.py
- shuup_tests/admin/test_refund_creator.py
- shuup_tests/core/test_order_refund_utils.py
Allow refunding all lines with value and quantity. There has to be option to refund shipping and payment methods as well as "other" lines as long as there is value and quantity available.
> Allow refunding all but refund lines

- shuup/admin/modules/products/views/list.py
- shuup_tests/admin/test_product_list_view.py
When multiple suppliers are enabled add suppliers column to default column. Also ensure that when suppliers is used as column the filtering by name is also set for the column.
> Admin: add suppliers to product list by default

- shuup/admin/modules/orders/views/refund.py
The object keys are the lines ordering and the value is the line data.
In cases when the line ordering didn't match the line data array index
the content was loaded incorrectly showing information of a different
line.
Making the line data be an object makes it possible to use the key to
directly access the data.
Refs REAL-39
> Admin: make the refund lines data be an object instead of an array

- shuup/notify/actions/email.py
- shuup/notify/settings.py
- shuup/notify/template.py
- shuup_tests/notify/test_email.py
Do not use any kind of string formatting as HTML can contains all sorts
of characters that make it impossible to format without a break.
Use the good old find/replace instead.
Also create environment provider method set through settings
In some cases one want to allow custom template tags for using while
rendering templates in notifications. Add a setting to set the
environment provider which can allow changing the `SandboxedEnvironment`
for anything else.
Refs REAL-20
> Notify: fix the email template variable name

- shuup/core/taxing/_module.py
- shuup_tests/campaigns/test_basket_campaigns.py
- shuup_tests/core/test_order_creator.py
- shuup_tests/core/test_order_refund_taxes.py
In cases line discounts attached to other lines, the discount line was
not calculated correctly.
Refs HEAL-9
> Core: allow taxes on order source children lines

- shuup/importer/admin_module/import_views.py
- shuup/importer/importing/importing.py
- shuup_tests/importer/test_admin.py
- shuup_tests/importer/test_product_import.py
- set `custom_file_transformer` to True into your `DataImporter` if you want to use internal `transform_file` classmethod
- fixed slug field issue, it raised `Data too long for column 'slug'`
> Admin: allow to use custom file_transformer

- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/modules/products/views/edit_media.py
- shuup/admin/static_src/product/edit_media.js
- shuup/admin/templates/shuup/admin/products/_edit_media_form.jinja
The main issue is that AJAX is used to add the files uploaded to the
current product media. It already generates the many-to-many relations
in the backend and the formset forms don't contain the ids of the
ProductMedia instances created.
To solve the issue, we return the ids of the ProductMedia created in the
backend and attach those to the hidden control inputs. Each ProductMedia
will have a corresponding hiden control input in the frontend.
This allows to set the primary image
Refs REAL-100 REAL-111
Fixes #1955
> Admin: fix the product images management form part

- shuup/admin/static_src/base/scss/shuup/custom-forms.scss
modal-dialog elements are left under the modal-bg becuase of z-index
Fix this with giving the modal-dialog the same z-index value
refs SHU-35
> Fix z-index on the modal-dialog

- shuup_tests/core/test_basket.py
- shuup_tests/core/test_order_creator.py
I think also passing extra_data should work since that is what you might expect if you check the order line attribute for this. Now you need to find the order creator "hack" around this. Not sure if there is reason, but here is few extra tests to show current behavior around this.
> Add tests around basket line extra data

- shuup/admin/forms/_quick_select.py
- shuup/admin/forms/quick_select.py
- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/settings.py
- shuup/admin/static_src/base/js/select.js
- shuup/xtheme/static_src/editor/editor.js
It is a common request of merchants to have categories options loaded
asynchronously or on page load. To solve this issue we are introducing a
new setting `SHUUP_ADMIN_LOAD_SELECT_OBJECTS_ASYNC` that can be adjusted
per project and adjust fields according to the business model.
The setting is enabled by default and will make categories and suppliers
fields to load objects asynchronously (through AJAX requests). When
disabled, the options will be rendered on page load.
Refs HEAL-35
> Admin: add settings to make select2 fields to load data asynchronously

- shuup/admin/modules/products/forms/base_forms.py
When async is disabled, show category hierarchy instead of the name alone
Refs HEAL-35
> Admin: fix the initial categories for product edit view

- shuup/admin/settings.py
- shuup/admin/urls.py
- shuup/front/apps/auth/settings.py
- shuup/front/apps/auth/views.py
Make it possible to set the authentication forms through settings.
This makes it easier to replace the form in custom projects
> General: move admin and front login forms to settings spec

- shuup/core/models/_contacts.py
- shuup/front/middleware.py
- shuup_tests/core/test_utils_users.py
- shuup_tests/front/test_contact_forcing_views.py
There were some issues when some addon used this get person contact util to fetch contact to admin which in this force mode caused odd behavior.
Move force anonymous contact and person contact to front middleware since mostly only for seeing front outside the group the contact would otherwise belong. For staff editing front content with editor.
> Core: move force anons and person contacts to front (SHU-53)

- shuup/core/migrations/0061_order_line_dates.py
To avoid situations like psycopg2.IntegrityError: column "modified_on" contains null values. I have one confirmation that this indeed helps with the problem.
> Core: add default to order line modified on migration

- shuup/core/utils/context_cache.py
- shuup/front/signal_handlers.py
- shuup_tests/cache/test_cache_bumping.py
Also enables bumping of a list of product id's. This is backwards compatible so that shops and plugins using
non id product cache bumping don't need to be changed.
refs SHU-34
> Add product cache removal ("bumping") by product id's

- shuup/core/migrations/0065_add_db_indexes_to_prod_cat_and_supplier_texts.py
- shuup/core/models/_products.py
It is not good idea to add indexes to textfields. It easily results to "BLOB/TEXT column 'keywords' used in key specification without a key length".
> Core: fix bug with migration 0065 related to indexes

- shuup/xtheme/static_src/editor/editor.js
- shuup_tests/browser/front/test_xtheme_plugin_form.py
This was initially caught by using the `Product Selection` plugin,
because the existing customer wondered how to add entries (the
`Products` field was empty and not selectable; despite there being a lot
of products added in the back-end already) in that plugin and if some
kind of add/select button existed as he remembered.
Browser consoles gave `Uncaught ReferenceError: sync is not defined`
error.
The long story short: the error was fixed by removing reference to
`sync` that was used but wasn't used anywhere.
This tiny change also fixed a bunch of other issues we didn't even know
we had with `Select2 widget`.
This commit also simultaneously fixes:
- all other plugins that use Select2 widget like Category Products
Highlight, Product Selection, Category Links, CMS Page Links, etc.
- the …
> Fix `Uncaught ReferenceError: sync is not defined` error

- shuup/campaigns/admin_module/forms/_basket.py
- shuup/xtheme/locale/en/LC_MESSAGES/djangojs.po
- shuup/xtheme/static_src/editor/editor.js
- Admin: Replace empty coupon field choice in campaigns
Replaced empty/None coupon field choice with `---------`
Fixes #2072 
- Xtheme: Add warning for unsaved changes when switching between cells
Fixes #2073
> Admin: Replace empty coupon field choice in campaigns & Xtheme: Add warning for unsaved changes when switching between cells

- CHANGELOG.md
- shuup/admin/middleware.py
- shuup/core/middleware.py
- shuup/front/middleware.py
- shuup/xtheme/middleware.py
- shuup/xtheme/resources.py
This enables the use of `MIDDLEWARE_CLASSES` or `MIDDLEWARE` setting
Check whether there is rendered content for the location
before checking whether the injection tag exists inside the content.
Multiple regex call can slow down the page loads by several times.
No Refs
> Xtheme improvements

- CHANGELOG.md
- shuup/admin/forms/fields.py
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/static_src/base/js/select.js
In cases when the field is not required, an error was raising
because the lack of placeholder option to use.
Instead of having a simple text, use a set of id/text with a nice fallback text.
Refs MYS-75
> Admin: fix select2 placeholder when field is not required

- shuup/admin/modules/users/__init__.py
- shuup/admin/modules/users/views/__init__.py
- shuup/admin/modules/users/views/detail.py
- shuup/admin/settings.py
- shuup/admin/template_helpers/shuup_admin.py
- shuup/admin/templates/shuup/admin/base/_navigation.jinja
- shuup/admin/urls.py
- shuup/admin/views/impersonate.py
- shuup_tests/admin/test_user_module.py
Mostly a superuser feature but allowed to staff as long as not impersonating superuseres. Also add template helper for logout url which stops the staff user impersonation properly.
> Admin: add option to impersonate staff users

- shuup/admin/static_src/base/scss/shuup/site-search.scss
Currently the search-result-canvas always has space on the bottom. But 
if there are more search results than can fit the screen, a visual bug 
happens, with results being displayed, but outside the canvas.
This change makes it so that the canvas will continue until the very 
bottom edge of the screen. Only when needed, otherwise there is still a 
space.
> Fix search results overflowing the canvas

- CHANGELOG.md
- shuup/admin/static_src/base/js/messages.js
- shuup/admin/static_src/base/scss/shuup/messages.scss
No users can dismiss alert messages through a dismiss icon.
It helps to remove the messages and let the user handle lots of error when
using mobile devices
Refs MYS-233
> Admin: make alert messages dismissible

- CHANGELOG.md
- shuup/admin/static_src/base/js/side-nav.js
If the tab's content is small (fitting on one screen), then clicking on 
that tab caused the view jump to page's top. This is good.
But if the tab didn't fit on one screen, then clicking on the tab cause 
a view to jump to that tab section hashtag anchor link location 
(url/#something). This sounds good, but in practice it was inconsistent 
and caused a graphical bug (important content not being seen).
refs SHU-36
> Fix bug: page jumps after selecting tabs

- CHANGELOG.md
- shuup/front/package.json
- shuup/front/static_src/js/category.js
- shuup/front/static_src/js/index.js
keep the current query parameters as the initial state when refreshing product filters.
This way, parameters that are not part of the product filters modifiers will be preserved.
Refs MYS-340
> Front: set the current query string as initial state when refreshing filters

- CHANGELOG.md
- shuup/notify/admin_module/views/edit.py
The notification name was <class 'object'> and not name of the notification
> Fix notification name

- shuup/notify/admin_module/forms.py
If you tried to edit a step which has a unilingual template it would break on line 89 (the for loop) because `self.template_languages` was a list of strings, not a list of tuples as it should be.
This commit fixes this bug.
No refs
> Notify: Fix language bug with unilingual templates

- shuup/admin/utils/picotable.py
Capitalizing items that is created from objects might cause some confusion at admin side. If someone decided the category name is in lowercases for some reason we should just show it as is. Same applies to items created all caps by admin.
> Admin: show picotable item choices as is

- CHANGELOG.md
- shuup/admin/modules/contacts/views/list.py
- shuup/front/themes/__init__.py
- shuup_tests/admin/test_contact_module.py
- shuup_tests/browser/admin/test_picotable.py
Add Staff filter option to contact list and by default do not list staff since most of the time staff should be managed directly through users or some other custom admin module for exact that purpose.
> Admin: make contact list filter out staff by default

- CHANGELOG.md
- shuup/admin/modules/manufacturers/__init__.py
- shuup/admin/modules/manufacturers/views/__init__.py
- shuup/admin/modules/manufacturers/views/edit.py
- shuup_tests/admin/test_manufacturer.py
- Added ability to delete a manufacturer when editing it.
- Added the get_context function to the manufacturer edit view so if a the manufacturer dose not have a url to there site the front_url won't be "/None" but instead it will redirect you to the front page.
> Add ability to delete manufacturer

- CHANGELOG.md
- shuup/admin/browser_config.py
- shuup/admin/static_src/base/js/dropzone.js
- shuup/admin/static_src/product/edit_media.js
- Add error message when upload fails. At media queue complete do not resave product media if the file-count has not changed. This for example prevents media save when the upload itself fails.
- Add option to override dropzone upload path by using data attribute
- Add upload path to browser URLs and use it to fallback on media uploads when the actual media path is not available.
> Admin: improve product media uploads

- CHANGELOG.md
- shuup/admin/modules/orders/json_order_creator.py
- shuup/admin/modules/orders/static_src/create/reducers/lines.js
- shuup/admin/modules/orders/static_src/create/reducers/quickAdd.js
- shuup/admin/modules/orders/static_src/create/view/lines.js
- shuup/admin/modules/orders/static_src/create/view/utils.js
- shuup/admin/modules/orders/views/edit.py
- shuup/admin/settings.py
- shuup/admin/static_src/base/scss/shuup/picotable.scss
- shuup/core/models/_orders.py
- shuup/core/settings.py
- shuup/front/static_src/js/category.js
- shuup/front/static_src/js/update_price.js
- shuup/front/templates/shuup/front/macros/product_image.jinja
Front: fix issues with Lightbox and app history
Front: avoid stacking app history on product list updates
Core: add option to enable order edit for multiple vendors
Admin: improve order edit tool
- Add option to make shipping and payment method optional
- Add supplier to pricing context
- Show supplier name on product column
- Make auto add for product select false by default
- Fix product select2 missing URL and data handler since the whole ajax method was passed as attrs.
- Add option to open/close collapsed content sections in mobile
> Fix front app history handling and tune admin order creator

- CHANGELOG.md
- shuup/front/apps/carousel/templates/shuup/carousel/carousel.jinja
- shuup/front/static_src/less/front/carousel.less
Make use of `render_image_text` plugin configuration to render title
Refs #2169
> Front: only show carousel title when there is one

- shuup/admin/modules/orders/views/list.py
- shuup/admin/modules/settings/view_settings.py
- shuup/front/checkout/addresses.py
- shuup_tests/admin/test_view_settings.py
- shuup_tests/browser/admin/test_picotable.py
Ensure company name and tax number is set to both billing and shipping address same way as when filled through company form when customer is not logged in. Company name and tax number at order addresses seems to help with some taxation logic as well as makes things more
consistent.
Make sure related custom columns are added accrodingly. Fix issue with filtering through columns that are by default hidden
> Improve front checkotu as compnany and fix issue with custom list view columns

- shuup/simple_cms/plugins.py
- shuup/simple_cms/utils.py
This would break if values given to the `order_query_by_values` were None. This fixes that.
No refs
> Simple CMS: Fix a bug with the page links plugin

- CHANGELOG.md
- shuup/admin/static_src/base/js/messages.js
- Reset the timeout for hiding the messages when a new message is added.
- Immediately clear the already hidden messages a when new one is added.
- Don't hide messages when clicking just random background elements.
- Allow dismissing all of the messages by clicking any one of them anywhere.
Came up when working on DO-138
> Admin: Improve window.Messages hiding and showing

- CHANGELOG.md
- setup.py
- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/modules/suppliers/forms.py
- shuup/admin/settings.py
- shuup/core/templatetags/shuup_common.py
- shuup/front/templates/shuup/front/macros/product.jinja
- shuup/front/templates/shuup/front/macros/product_information.jinja
- shuup/front/templates/shuup/front/product/product_preview.jinja
- shuup_tests/core/test_template_tags.py
New settings:
`SHUUP_ADMIN_ALLOW_HTML_IN_PRODUCT_DESCRIPTION` (default `True`)
`SHUUP_ADMIN_ALLOW_HTML_IN_VENDOR_DESCRIPTION` (default `True`)
The default values are `True` for allowing full backwards compatibility.
New projects should most probably set these to `False`.
Refs SHU-24
> Admin: Add settings for disabling HTML in descriptions

- CHANGELOG.md
- shuup/notify/actions/email.py
- shuup/notify/signals.py
- shuup_tests/notify/test_email.py
The notification can be captured to log the emails sent and presented in a list view for auditing
> Add signal when an email is sent by a notification

- CHANGELOG.md
- shuup/admin/modules/products/forms/base_forms.py
We already did this to vendor description, so it only makes sense to do it here as well.
No refs
> Sanitize product description on save if the setting is toggled

- CHANGELOG.md
- shuup/admin/modules/orders/json_order_creator.py
> Admin: return `None` when the order source was not correctly initialized in JsonOrderCreator

- CHANGELOG.md
- shuup/gdpr/anonymizer.py
Before if an order of a contact that was about to be anonymized
had an order with a null shipping or billing address, it would result in the error:
>     AttributeError: 'NoneType' object has no attribute '_meta'`
when `Address.save()` was called.
Refs DO-190
> GDPR: Fix order anonymization for null addresses

- shuup/front/templates/shuup/front/macros/basket.jinja
Fix for https://github.com/shuup/shuup/issues/2277
In basket form all "product remove" buttons have type="submit" and when you press Enter, first "remove product" button submits the form.  That's why first product deleted from the basket.
In this fix I added additional events to track Enter keydown to prevent event, then in keyup for Enter form submitted. I supposed to add keydown and keyup, because keydown could fire several times (event attribute repeat=True) and in this case I need to check if it's initial Enter press or repeated. Decided to change this behaviour and used keyup event to release the form.
> Fix product quantity input on enter press

- CHANGELOG.md
- shuup/core/templatetags/shuup_common.py
- shuup_tests/core/test_template_tags.py
Example description:
Before:
After this PR:
> Core: Always preserve newlines in vendor and product descriptions

- CHANGELOG.md
- shuup/admin/locale/en/LC_MESSAGES/djangojs.po
- shuup/front/locale/en/LC_MESSAGES/django.po
- shuup/front/notify_events.py
- shuup/notify/base.py
- shuup/notify/templates/notify/admin/generic_script_template.jinja
- shuup/notify/templates/notify/admin/macros.jinja
- shuup/notify/templates/notify/admin/script_item_editor.jinja
Add a new `attributes` attribute to `shuup.notify.base.Variable` for
showing examples of which attributes can be accessed in the script templates.
Refs IP-7
The new `attributes` look like this in the script editor:
**(Note that the the javascript for the variable links didn't work even before this PR, but once it gets fixed the attributes were made so that they should work just fine with that)**
> Notify: Show more Order related variables in editor

- CHANGELOG.md
- shuup/admin/modules/media/static_src/media/browser/BrowserView.js
- shuup/admin/modules/media/static_src/media/browser/FileUpload.js
- shuup/admin/modules/media/views.py
- shuup/utils/filer.py
- shuup_tests/admin/test_media_module.py
- shuup_tests/utils/filer.py
The reason for this change was that previously all of the items in
the Root folder (aka `folder=None`) were visible for all users with
media browsing permission. This could lead to the situation where
a user uploads some files to that folder and doesn't realize that it
will be visible for many other users as well.
Refs AH-30
As expected, a superuser sees the 'Root' folder in `/admin/media/`:
But an other kind of staff account, with no `"media.view-all"` permission, cannot see it at all:
> Admin: Require media.view-all permission to see 'Root' folder

- CHANGELOG.md
- shuup/admin/modules/products/forms/base_forms.py
- shuup/admin/templates/shuup/admin/products/_edit_media_form.jinja
In some cases, instances were wrongly fetched by Django
in https://github.com/django/django/blob/2.2.16/django/forms/models.py#L613
as the index 0 and 1 were returning the same instance:
```
>> qs[0] == qs[1]
True
```
This could be reproduced locally while using PostgreSQL database only.
The bug didn't happen while forcing the evaluation of the queryset using the list() constructor:
```
>> list(qs)[0] == list(qs)[1]
False
```
Using .distinct() also fixed the issue:
```
>> qs.distinct()[0] == qs.distinct()[1]
False
```
Refs CR-84
> Admin: prevent duplicate images in product media form

- CHANGELOG.md
- shuup/core/basket/objects.py
- shuup_tests/core/test_basket.py
- shuup_tests/front/test_basket.py
Fix the implementation that was using the same memory
object for all baskets instances in the same process.
The `_DataValueProperty` was wrongly implemented while saving
the default value inside the `__init__`. The default object was a dictionary
that was always referencing to the same instance for all baskets instances,
and this object was updated by the same process every time.
The `_DataValueProperty` was replaced by an implementation in a way
that the default value is always a new dict object.
> Core: fix basket attribute issue

- CHANGELOG.md
- shuup/admin/static_src/picotable/picotable.js
Refs OWL-11
Looks like this when waiting for a request response:
> Admin: Show a loader in place of picotable when a request is pending

- CHANGELOG.md
- shuup/core/basket/objects.py
- shuup/front/checkout/methods.py
After setting the payment and shipping methods, we uncache the basket to force
shipping and payment total recalculation
> Front: force recalculate lines in checkout phase

- CHANGELOG.md
- shuup/front/forms/product_list_modifiers.py
- shuup/front/views/category.py
Refs EZI-31
Include Products belonging to Child-Categories of selected category filter(s)
eg.
Instead of giving product three categories:
- Category: Dress / Women / Clothes
- Category: Dress / Women
- Category: Dress
Only the deepest one would be needed:
- Category: Dress / Women / Clothes
Currently If product has only "Dress" category set, it would only be shown in "Dress", not in "Women" or "Clothes".
> Include child categories in product category filter

- CHANGELOG.md
- shuup/admin/modules/users/views/list.py
- shuup/admin/modules/users/views/permissions.py
- shuup_tests/admin/test_user_module.py
- Do not show is_superuser field for non-superusers no matter who they are editing
- Do not show superuser column in list since the superusers are already filtered out from non-superusers who are main people using the admin panel.
> Admin: do not allow non-superusers manage superusers

- CHANGELOG.md
- shuup/admin/modules/users/views/detail.py
- shuup/admin/modules/users/views/permissions.py
- shuup_tests/admin/test_user_module.py
The user can incorrectly be added to shop staff list without actually being
part of the staffs of the shop.
> Admin: do not add/remove shop staff member while saving a staff user

- CHANGELOG.md
- shuup/admin/static_src/base/js/editor.js
Other font sizes were there by default.
Refs MYYR-89
> Add font size 16 to SummerNote text editor

- CHANGELOG.md
- shuup/simple_cms/models.py
Show all CMS pages for authenticated users when there is no group filter attached to the page
> SimpleCMS: Fix page filter for authenticated users

- CHANGELOG.md
- shuup/xtheme/views/forms.py
- shuup_tests/xtheme/test_editor_forms.py
- shuup_tests/xtheme/test_layout.py
This allow the usage of more advanced plugins that should expand
to the whole screen size without the need of usage of bootstrap column sizes
Refs SH-84
> Xtheme: add option to set a custom cell width in placeholders

- shuup/xtheme/rendering.py
- shuup_tests/xtheme/utils.py
Now zero values are custom size which means the cell shouldn't receive any BS class
> Xtheme: consider negative values as flags to hide the cell

- shuup/admin/modules/products/forms/base_forms.py
Makes the name only required field when creating product. The price is there quite down at the form and a bit annoying if you just want to quick add some product.
> Admin: set default price value to zero by default

- CHANGELOG.md
- shuup/admin/modules/contacts/views/list.py
- shuup/admin/modules/products/views/list.py
when using `values_list` on translated field
As translations are separate objects, accessing translations directly through for example: `translations__name` results in an implicit join of multiple translations and multiple translations are returned.
> Fix multiple translations of object returned

- CHANGELOG.md
- shuup/core/migrations/0068_help_text_improvements.py
The previous migration file 0067_supplier_name_max_length_to_128 changed the field to be
greater than 64 chars, but probably because of some merge issue, the field size was
reverted to have only 64 chars.
No Refs
> Fix `0068_help_text_improvements` migration file to have the correct field char size: 128

- CHANGELOG.md
- shuup/core/__init__.py
- shuup/core/basket/objects.py
- shuup/core/models/_orders.py
- shuup/core/order_creator/_creator.py
- shuup/core/order_creator/_modifier.py
- shuup/core/signal_handlers.py
- shuup/core/signals.py
- shuup/core/suppliers/base.py
- shuup/core/utils/context_cache.py
- shuup/simple_supplier/module.py
- Move stock update and cache bump to signal handlers
- Select related data when possible
- Do not make basket dirty when it is loaded
- Improve cache bump using product ID instead of loading from database
Refs CS-43
> Improve the way the cache is bumped when order is created and changed

- shuup/gdpr/static_src/gdpr.js
- shuup/notify/actions/email.py
- GDPR: hide consent immediately on accept
- Notify: Remove HTML editor from notifications since summernote does not
function Jinja syntax very well and for example for-loops and ifs
cause easily broken notifications.
- Notify: Make HTML default format for emails
Preview option for email notifications and email templates will follow this pull request.
> Small changes to Notify and GDPR apps

- shuup/core/utils/price_display.py
- shuup/front/settings.py
- shuup/front/static_src/js/update_price.js
- shuup/front/templates/shuup/front/macros/product_ordering.jinja
- shuup/front/utils/product.py
- Front: optimize child product orderability checks a bit
- Front: add option to replace product detail context
- Front: optimize rendering images for variation products
- Core: optimize price range calculations
Note: the price range calculation is also huge help in listing products since the loading time wont be affected on how complex are the variation products.
> Optimize default front calculations around variation products

- shuup/front/static_src/js/xtheme_async_plugins.js
Also add option to easily override breakpoints by re-defining the breakpoint variable.
> Front: improve async product carousel breakpoints

- shuup/admin/static_src/base/scss/shuup/picotable.scss
- shuup/admin/static_src/picotable/picotable.js
Do not save and refresh Picotable lists on filter change, but wait that the user selects the "Apply filter" option. Also show badge for active filters to indicate that some content is filtered out. Consider "_all" as not filter.
> Admin: add apply filters button and display active filters counter badge

- shuup/admin/forms/widgets.py
- shuup/admin/static_src/base/js/code-mirror.js
- shuup/admin/static_src/base/scss/shuup/code-mirror.scss
- shuup/admin/templates/shuup/admin/forms/widgets/code_editor_with_preview.html
- shuup/notify/actions/email.py
- shuup/notify/admin_module/views/email_template.py
- shuup/notify/templates/notify/admin/script_content_editor.jinja
- shuup/notify/templates/notify/admin/script_item_editor.jinja
- shuup_tests/notify/test_email_template.py
Here HTML test email with multiple lines:
Leads to this kind of email which should be right:
Here plain text test email with multiple lines
And the email received looks like having linebreaks correctly:
> Notify: add HTML preview for email notification and template

- shuup/admin/static_src/base/scss/shuup/content-blocks.scss
- shuup/admin/static_src/base/scss/shuup/custom-forms.scss
- shuup/admin/static_src/base/scss/shuup/quick-add.scss
Admin: Fix block title and subtitle spacing
* Also fix the border top/bottom width of the titles in different screen sizes
Admin: Adjust form field spacing
* Make the form fields a bit wider, increasing the width from 80% to 85% in desktop, and make them 100% wide in mobile
* Reduce margin between form fields
* Fix mobile styling of quick add buttons
* Position tooltips on the right side above the fields on mobile
> Admin: Adjust block title and form input spacing

- shuup/admin/modules/media/static_src/media/browser/BrowserView.js
- shuup/admin/modules/media/static_src/media/browser/components/gridFileView.js
- shuup/admin/modules/media/static_src/media/browser/components/images.js
- shuup/admin/modules/media/static_src/media/browser/media-browser.scss
- shuup/admin/modules/media/static_src/media/browser/menus/menuItem.js
- shuup/utils/filer.py
* Fix mobile styling so that more content is visible at once
* Fix overflowing sort button in mobile screen sizes
* Adjust file and folder design to be more consistent
* Add bootstrap dropdown link styles for the dropdown menu
Ensure media browser images are squares without cropping:
* Add white padding around the images so that the image won't be cropped and the users can see the whole image contents
<hr>
**Before:**
<hr>
**After:**
> Improve media browser styles

- CHANGELOG.md
- shuup/core/basket/objects.py
Fixes a case where Variation Parents that are turned to normal products by having all their variations removed can't be added to basked because basket is incorrectly identifying product as a parent due to it having deleted children.
> Fix adding products with deleted children to basket

- shuup/front/templates/shuup/front/macros/navigation.jinja
For stability purposes. Looks this is having some issues with custom baskets. Add per project if you find this useful.
> Remove template cache from basket partial

- shuup/admin/modules/products/__init__.py
- shuup_tests/admin/test_product_module.py
Do not throw 500 if the module can not handle the object. Outcome is clear and that that is that URL can not be defined by that module. Log error and move to next module.
> Admin: fix product module not to fail on object does not exists

- shuup/front/urls.py
Avoid mixing up this with static media path when the ending "/" is not added to some checks.
> Front: update media upload URL

- CHANGELOG.md
- shuup/admin/static_src/base/js/editor.js
- shuup/admin/templates/shuup/admin/base.jinja
Convert the script functions into an object that can is called in the base template
Also add more blocks to enable more customization of the base admin template
⚠️  This will break summernote in projects that customize `base.jinja` in Admin as they miss the new initialization block script.
> Admin: add option to hide font selection and paste plain text in editors

- CHANGELOG.md
- shuup/admin/modules/products/forms/base_forms.py
Overriding the fields caused field labels to not be translated properly
> Add missing labels to product category and supplier fields

- shuup/core/models/_orders.py
- shuup/core/taxing/_module.py
Since each refund line you need to take care of the taxes it is more logical if the tax module handles the whole thing. With some 3rd party taxation tool you need an option to handle refund taxes in different way.
> Core: move refund order line logic to tax module

- CHANGELOG.md
- shuup/importer/transforms.py
In cases where imported file has cleared, but not deleted rows, rows with only `None` values are included.
They should be ignored, but are instead counted towards rows of imported data
> Importer: Ignore rows without any data

- shuup/admin/template_helpers/shuup_admin.py
- shuup/core/models/_contacts.py
- shuup/core/models/_units.py
- shuup/core/utils/static.py
- shuup/front/middleware.py
- shuup/front/templatetags/shuup_front.py
- shuup/gdpr/models.py
- shuup/utils/i18n.py
- shuup_tests/cache/test_lang_lru_cache.py
`lru_cache` is shared between everyone and every language, which means incorrect translations are returned if different language is cached than is in use by user
> Language aware lru_cache

- CHANGELOG.md
- shuup/notify/admin_module/views/email_template.py
- Fixed so there is no 500 error when accessing EmailTemplate settings page
refs https://sentry.io/organizations/shuup/issues/1840747854/?project=5357333&query=is%3Aunresolved
> Fix EmailTemplate settings page

- CHANGELOG.md
- shuup/core/taxing/_module.py
- shuup_tests/functional/test_tax_system.py
While getting the context from order source, if the order source has shippable lines,
use the shipping address, use billing address otherwise
> Taxes: fallback location to billing address when shipping address is not available

- CHANGELOG.md
- shuup/front/checkout/methods.py
- Front: Add so `basket.get_final_lines(with_taxes=True)` gets called after selecting shipping- and payment method.
Reason for this is so all the taxes gets calculated before end customers fills in their payment details
refs https://trello.com/c/mtVzzdDO/24-set-up-taxjar-integration
> Add so `basket.get_final_lines()` is called after MethodsPhase

- CHANGELOG.md
- shuup/admin/static_src/base/scss/shuup/picotable.scss
- Admin: Picotable to scroll in container on overflow rather, than entire screen scroll
Old version hiding the links at top:
New version correctly scrolling:
> fixed picotable overflow

- CHANGELOG.md
- shuup/admin/modules/products/forms/base_forms.py
Product form is saved multiple times which can lead to multiple images being created
> Fix Duplicate images being saved when creating a new product

- CHANGELOG.md
- shuup/front/apps/carousel/plugins.py
- shuup/simple_cms/plugins.py
- shuup/testing/factories.py
- shuup/xtheme/layout/_base.py
- shuup/xtheme/plugins/_base.py
- shuup/xtheme/plugins/category_links.py
- shuup/xtheme/plugins/image.py
- shuup/xtheme/plugins/products.py
- shuup/xtheme/plugins/products_async.py
- shuup/xtheme/rendering.py
- shuup/xtheme/settings.py
- shuup_tests/notify/test_order_notifications.py
- Xtheme: add attribute on every plugin to indicate whether it can be cached or not
- Xtheme: removed the SHUUP_XTHEME_USE_PLACEHOLDER_CACHE setting and do not cache the entire placeholder content
Example of full cache key: `shuup_xtheme_cell:0_0_3_public_2021-05-11t1801573378940000_en_homepage_content_homepage_content|product_highlight`
> Xtheme: make plugin indicate whether it can be cached

- CHANGELOG.md
- shuup/admin/utils/urls.py
```
>>>isinstance("asd", (str, bytes))
True
>>>from django.utils.translation import ugettext as _
>>>isinstance(_("asd"), (str, bytes))
True
>>>from django.utils.translation import ugettext_lazy as _
>>>isinstance(_("asd"), (str, bytes))
False
```
> Resolve string translation before passing it to urlencode

- CHANGELOG.md
- shuup/admin/menu.py
- shuup/admin/modules/menu/views/arrange.py
This will prevent showing the incorrect menu when the user changes
the current language.
Refs BH-116
> Admin: save the current user menu using the current language

- CHANGELOG.md
- shuup/admin/base.py
- shuup/admin/locale/en/LC_MESSAGES/django.po
- shuup/admin/modules/permission_groups/views/edit.py
- shuup/admin/modules/users/__init__.py
Add a method in AdminModule that allows returning help texts for permissions
This will allow the developer to define the help texts for the permissions
> Admin: show help texts in permission

- CHANGELOG.md
- shuup/campaigns/models/campaigns.py
- shuup/campaigns/models/matching.py
- shuup/core/models/_product_shops.py
- shuup/core/models/_products.py
- shuup/core/utils/context_cache.py
- shuup/core/utils/price_cache.py
- shuup/core/utils/price_display.py
- shuup/front/template_helpers/general.py
- shuup/front/templatetags/thumbnails.py
- shuup/xtheme/layout/_base.py
- shuup_tests/core/test_products_in_shops.py
Cache product orderability and prices using a list of user groups instead of per contact
> Core: change how price and orderability are cached

- CHANGELOG.md
- shuup/notify/admin_module/forms.py
It is impossible to clear fields once set
Refs FD-223
> Notify: always overrride the current notification data

- CHANGELOG.md
- doc/ref/provides.rst
- shuup/admin/modules/attributes/forms.py
The feature was already removed in https://github.com/shuup/shuup/commit/f267a869507b7d014126c707d1c4ec0f57e0a8c3
> Admin: remove the provides to allow adding extra fields to the Attribute form

- CHANGELOG.md
- shuup/simple_supplier/module.py
- shuup_tests/cache/test_cache_bumping.py
- shuup_tests/core/test_addresses.py
- shuup_tests/front/test_carousel.py
- shuup_tests/functional/test_shipment_delete_with_simple_supplier.py
- shuup_tests/functional/test_shipment_received_with_simple_supplier.py
- shuup_tests/simple_supplier/test_simple_supplier.py
- shuup_tests/xtheme/test_plugins.py
- shuup_tests/xtheme/test_plugins_async.py
Use a different queryset to filter the products model and relate to stock count
Refs RM-80
> SimpleSupplier: always return products as managed

- CHANGELOG.md
- shuup/core/tasks.py
- shuup/xtheme/plugins/snippets.py
- Core: fix so task don't require a identifier
- Xtheme: Add so snippets can have start of head content
refs https://sentry.io/organizations/shuup/issues/2450343058/?project=5687395&query=is%3Aunresolved
> Core: fix so task don't require a identifier

- CHANGELOG.md
- shuup/xtheme/templates/shuup/xtheme/plugins/highlight_plugin_async.jinja
- removed orderable boolean from async highlights plugin from being rendered
> Fixed boolean from being rendered in async highlights plugin

- CHANGELOG.md
- shuup/core/models/_service_base.py
- shuup/core/order_creator/_source.py
- Core: Fixed so we can get custom order source when getting the cost of service components
refs https://trello.com/c/WmXEs8Ab/157-vynlyf-multivendor-shipping-methods-not-calculating-correctly
> Core: fix service components get cost

- CHANGELOG.md
- shuup/admin/modules/permission_groups/views/edit.py
- shuup/admin/modules/users/views/list.py
- shuup_tests/admin/test_permission_groups_module.py
- Admin: remove the members field from the permission groups
- Admin: add the groups field in user picotable list
- Admin: improve the format of the user list for mobile devices
Refs OR-30
> Admin: improve user and permission groups admin

- CHANGELOG.md
- shuup/admin/modules/products/validators.py
- shuup/front/checkout/addresses.py
When there is a customer and the basket still doesn't have a customer,
set it on the address phase.
There are cases when an anonymous user create a basket (adding a product)
and the checkout phases can't have access to the current basket.customer
as it was never set after the user logs is.
Only set the customer when there is no one set previously.
Refs https://trello.com/c/YnkkHRR5
> Front: enforce setting the current customer to the basket

- CHANGELOG.md
- shuup/admin/templates/shuup/admin/base.jinja
- Admin title to use the shop's `requst.shup.public_name` value or `Shuup` as default
> Updated admin shop title to use shops public name

- CHANGELOG.md
- shuup/core/templatetags/shuup_common.py
- shuup/front/templates/shuup/front/macros/general.jinja
- shuup/front/templates/shuup/front/product/detail.jinja
- shuup/front/views/category.py
- shuup/simple_cms/templates/shuup/simple_cms/macros.jinja
- shuup_tests/core/test_template_tags.py
- Create new template filter to clean text to be used in meta tags
- Use product description as a fallback of the short description
- Strip tags in product safe description template filter instead of encoding chars
Refs https://trello.com/c/uBnRqjPj/137-check-seo-issues-reported-by-the-client
> Front: improve SEO

- CHANGELOG.md
- shuup/admin/modules/orders/views/shipment.py
- shuup/core/models/_orders.py
- shuup/core/models/_shipments.py
- shuup/simple_supplier/module.py
- shuup_tests/admin/test_order_shipments.py
- shuup_tests/browser/admin/test_refunds.py
- shuup_tests/core/test_basic_order.py
- shuup_tests/core/test_order_product_summary.py
- shuup_tests/core/test_orders.py
- shuup_tests/core/test_shipments.py
- shuup_tests/functional/test_refunds.py
Consider an order fully shipped only when all out shipments are sent
Refs https://trello.com/c/AuDBi8O4/140-bug-shipping-is-set-to-fully-shipped-by-default-not-not-shipped
> Core: change how orders are set to be fully shipped

- CHANGELOG.md
- shuup/core/excs.py
- shuup/core/models/_suppliers.py
- shuup/core/taxing/_module.py
- shuup_tests/core/test_order_refund_utils.py
- shuup_tests/core/test_orders.py
Prevent suppliers with no supply modules from creating shipments.
Reference: https://trello.com/c/YdNmeTJ0/99-fix-bug-that-makes-it-not-possible-to-create-shipments-in-shuup-os
> Core: suppliers must have supplier modules to ship
