shuup/shuup

ChangeLog.md
=> Add ChangeLog.md

shoop/utils/settings_doc.py
=> Fix `shoop_show_settings` for Python 3.

README.md
Promote the Gitter chat room with a badge.
=> README: Add "Chat" section

ChangeLog.md, README.md
* ChangeLog: Add all changes after 1.0.0
* README: Remove text about DCO
* README: Change markdown title formatting
=> Update ChangeLog and README (SHOOP-987)

_misc/ensure_license_headers.py
* Faster file discovery
* Better output
* Dry-run by default
=> Improve `ensure_license_headers`

shoop/admin/templates/shoop/admin/auth/login.jinja, shoop/admin/templates/shoop/admin/base_popup.jinja, shoop/admin/templates/shoop/admin/problem.jinja, shoop/admin/urls.py, shoop/admin/utils/urls.py, shoop/core/middleware.py, shoop/front/middleware.py, shoop/utils/excs.py, shoop_tests/admin/test_modules.py
Features some other incidental improvements too, as usual.
=> Better admin login flow (SHOOP-801)

shoop/admin/modules/attributes/views/list.py, shoop/admin/modules/categories/views/list.py, shoop/admin/modules/contacts/views/list.py, shoop/admin/modules/methods/views/list.py, shoop/admin/modules/orders/views/list.py, shoop/admin/modules/product_types/views/list.py, shoop/admin/modules/products/__init__.py, shoop/admin/modules/products/views/list.py, shoop/admin/modules/users/views/detail.py, shoop/admin/modules/users/views/list.py, shoop/admin/toolbar.py, shoop/admin/utils/views.py, shoop/notify/admin_module/views/list.py
=> Harmonize 'New' buttons in admin

ChangeLog.md
=> Update change log (up to 9785207e46b)

ChangeLog.rst, MANIFEST.in, setup.py
Update change log and add release instructions.
=> Prepare for 1.1 release (SHOOP-987)

shoop/admin/__init__.py, shoop/admin/modules/attributes/views/list.py, shoop/admin/modules/contact_groups/views/list.py, shoop/admin/modules/product_types/views/list.py, shoop/admin/modules/sales_units/__init__.py, shoop/admin/modules/sales_units/views/__init__.py, shoop/admin/modules/sales_units/views/edit.py, shoop/admin/modules/sales_units/views/list.py, shoop/admin/templates/shoop/admin/sales_units/edit.jinja, shoop/admin/utils/views.py
Refs Github issue #43
Refs SHOOP-1037
=> Admin: Sales Unit UI.

shoop/admin/templates/shoop/admin/sales_units/edit.jinja
=> Use translation tabs in sales units admin view

shoop/admin/modules/products/views/forms.py
Refs SHOOP-968
Same bug as SHOOP-639
=> Admin: Fix product attributes getting cleared unless they were edited

shoop/front/templates/shoop/front/includes/_navigation.jinja
=> Add link to admin panel in frontend

shoop/admin/modules/products/views/edit.py, shoop/admin/templates/shoop/admin/products/edit_cross_sell.jinja
* Wrap each cross-sell to a panel for better readability
* Add an icon (fa-exchange) to the cross-sell page
* Update the same icon to product edit toolbar button
Refs SHOOP-31
=> Update cross-sell layout in admin

_misc/check_sanity.py, setup.py, shoop/admin/package.json, shoop/admin/static_src/base/js/main-menu.js, shoop/admin/static_src/base/less/vendor/jquery-scrollbar/jquery.scrollbar.less, shoop/admin/static_src/vendor/bower.json
=> Fix admin menu scrolling

shoop/admin/modules/products/views/variation/edit_variation.py, shoop/admin/modules/products/views/variation/simple_variation_forms.py, shoop_tests/admin/test_product_variation.py, shoop_tests/utils/forms.py
=> Fix simple variation form (and add tests)

_misc/ensure_unicode_literals.py, shoop/addons/manager.py, shoop/admin/breadcrumbs.py, shoop/admin/forms/widgets.py, shoop/admin/modules/media/views.py, shoop/admin/modules/products/views/toolbars.py, shoop/admin/utils/forms.py, shoop/api/factories.py, shoop/core/middleware.py, shoop/core/models/manufacturers.py, shoop/core/models/product_variation.py, shoop/core/pricing/__init__.py, shoop/core/taxing/_line_tax.py, shoop/core/taxing/_tax_summary.py, shoop/core/utils/reference.py, shoop/front/apps/simple_search/views.py, shoop/front/basket/storage.py, shoop/front/basket/update_methods.py, shoop/front/checkout/addresses.py, shoop/front/templatetags/thumbnails.py, shoop/front/utils/product_statistics.py, shoop/notify/script.py, shoop/notify/typology.py, shoop/testing/factories.py, shoop/testing/pseudo_payment.py, shoop/testing/soup_utils.py, shoop/utils/analog.py, shoop/utils/form_group.py, shoop/utils/models.py
Fixes SHOOP-1083 as a side effect (by adding the stanza to shoop/admin/forms/widgets.py).
=> Add more `unicode_literals`

shoop/front/template_helpers/product.py
Refs SHOOP-1073
Will be superseded by #62
=> Fix `get_product_cross_sells` to work on MySQL

shoop/admin/modules/products/views/forms.py, shoop/admin/static_src/product/edit_media.js, shoop/admin/templates/shoop/admin/products/_edit_media_form.jinja
=> Product image fixes

shoop/admin/modules/products/views/variation/edit_variation.py
=> Admin: Add missing variation product link to breadcrumbs

ChangeLog.rst, shoop/admin/generated_resources.txt
* Update Change Log.
* Add couple missing files to admin/generated_resources.txt, which were
found out while checking that it builds fine as a wheel.
=> Prepare for Shoop 1.2 release (SHOOP-1107)

shoop/admin/__init__.py, shoop/admin/modules/manufacturers/__init__.py, shoop/admin/modules/manufacturers/views/__init__.py, shoop/admin/modules/manufacturers/views/edit.py, shoop/admin/modules/manufacturers/views/list.py, shoop/admin/templates/shoop/admin/manufacturers/edit.jinja
Admin: Add basic Manufacturer views
Refs SHOOP-1058
=> Admin: Add basic Manufacturer views

shoop/admin/__init__.py, shoop/admin/modules/suppliers/__init__.py, shoop/admin/modules/suppliers/views/__init__.py, shoop/admin/modules/suppliers/views/edit.py, shoop/admin/modules/suppliers/views/list.py, shoop/admin/templates/shoop/admin/suppliers/edit.jinja
=> Admin: Add basic Supplier views

shoop/admin/modules/categories/views/edit.py, shoop/admin/templates/shoop/admin/categories/_edit_base_form.jinja
=> Admin: Add image field for category

shoop/front/template_helpers/product.py
Add ordering by weight to product cross sells template helper.
Use same ordering as in admin where lowest weight is shown first.
Refs SHOOP-1064
=> Front: Add ordering for cross sells template helper

shoop/admin/modules/suppliers/views/edit.py
=> Change empty label for admin supplier module edit

shoop/admin/modules/suppliers/views/list.py
=> Admin: Add default module name to supplier list and make it sortable

shoop/simple_pricing/admin_form_part.py, shoop_workbench/settings/base_settings.py
=> Fix issue with price not being saved

shoop/admin/modules/shops/views/edit.py, shoop/admin/modules/shops/views/list.py, shoop_tests/admin/test_multishop_setting.py
=> Admin: Optionally disable creating shops

shoop_tests/xtheme/templates/h2g2/42.jinja, shoop_tests/xtheme/test_theme_selection.py, shoop_tests/xtheme/utils.py
Augments d6391fc9dab25963a68c590a336690eb42ac6c98
Refs SHOOP-1080
=> Add test for `_get_themed_template_names`.

shoop/admin/modules/products/views/edit.py, shoop/admin/modules/products/views/forms.py, shoop/admin/modules/products/views/toolbars.py, shoop/admin/static_src/base/less/shoop/product-edit.less, shoop/admin/static_src/product/edit_media.js, shoop/admin/templates/shoop/admin/products/_edit_media_form.jinja, shoop/core/models/product_media.py
Check commits for more information.
Refs SHOOP-1045
=> Add `Product Media` tab to product editing

shoop/admin/templates/shoop/admin/base.jinja, shoop/admin/templates/shoop/admin/base_popup_with_support.jinja, shoop/admin/templates/shoop/admin/media/browser.jinja
=> Media browser: Show the support nav in popup mode to allow buttony uploads

shoop/themes/classic_gray/static_src/less/classic-gray/product-list.less
=> Fix indentation of category navigation in classic gray theme

shoop/xtheme/urls.py
(I am a dummy, veritably.)
Augments d0ca6e9d8e21e9150
Refs SHOOP-1177
=> Xtheme: Correct URL pattern order

shoop/themes/classic_gray/__init__.py, shoop/themes/classic_gray/static_src/js/custom.js, shoop/themes/classic_gray/static_src/less/classic-gray/loader.less, shoop/themes/classic_gray/static_src/less/style.less, shoop/themes/classic_gray/templates/classic_gray/add_product_to_basket.jinja, shoop/themes/classic_gray/templates/classic_gray/navigation_basket_partial.jinja, shoop/themes/classic_gray/templates/classic_gray/product_quickview.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/base.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/macros.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja, shoop/themes/classic_gray/views/__init__.py, shoop/themes/classic_gray/views/basket.py, shoop/themes/classic_gray/views/product_preview.py
Classic gray theme: Add products to basket with AJAX
Classic gray theme: Enable product previews
Refs SHOOP-1210, SHOOP-1205, SHOOP-1206, SHOOP-1207, SHOOP-1208, SHOOP-1209
=> Product preview and add with ajax

_misc/check_sanity.py, shoop/themes/classic_gray/__init__.py, shoop/themes/classic_gray/config_form.py, shoop/themes/classic_gray/templates/classic_gray/shoop/front/base.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_footer.jinja, shoop/xtheme/template_ns.py, shoop/xtheme/theme.py
The usual bugfixes/foundation features on top of the PR again.
Refs SHOOP-1181, SHOOP-1217, SHOOP-1218
=> Classic Gray: add customizable footer

shoop/themes/classic_gray/static_src/less/classic-gray/loader.less
Make newlines follow the same pattern in classic gray's loader.less
=> Improve less consistency

shoop/admin/forms/widgets.py, shoop/admin/modules/media/views.py, shoop/admin/modules/products/views/forms.py, shoop_tests/admin/test_media_module.py
Also some minor plumbing to allow testing this feature without ui part.
Refs SHOOP-1278
=> Add `ImageChoiceWidget`

shoop/themes/classic_gray/static_src/js/custom.js, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_category_menu.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/category.jinja
Classic gray theme: Make product list view remember it's mode
Classic gray theme: Add proper classes to category navigation
Refs SHOP-1188, Refs SHOOP-1180
=> Classic gray theme: Javascript to product list view

shoop/themes/classic_gray/static_src/less/classic-gray/modals.less, shoop/themes/classic_gray/static_src/less/classic-gray/product-card.less, shoop/themes/classic_gray/static_src/less/classic-gray/product.less, shoop/themes/classic_gray/static_src/less/style.less, shoop/themes/classic_gray/templates/classic_gray/product_quickview.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja
=> Update search and preview modal styling (classic gray)

shoop/themes/classic_gray/static_src/less/classic-gray/loader.less
=> Update styles for basket ajax loader (Classic Gray)

shoop/admin/static_src/base/js/browse-widget.js
=> Admin: Actually send `data-filter` to media browser from browse widgets

shoop/admin/modules/products/views/forms.py
Fix issue with saving images
Fix issue with product images and medias mixing
Refs SHOOP-1345
=> Media fixes

shoop/discount_pricing/__init__.py, shoop/discount_pricing/admin_form_part.py, shoop/discount_pricing/migrations/0001_initial.py, shoop/discount_pricing/models.py, shoop/discount_pricing/module.py, shoop/discount_pricing/templates/shoop/admin/discount_pricing/form_part.jinja, shoop_tests/discount_pricing/test_discount_pricing.py, shoop_tests/discount_pricing/test_form.py, shoop_workbench/settings/base_settings.py
This module handles simple discounted pricing for Shoop.
Refs SHOOP-1289
=> Add `DiscountPricingModule` (SHOOP-1289)

shoop/admin/static_src/base/js/search.js, shoop/admin/static_src/base/less/shoop/site-search.less, shoop/admin/templates/shoop/admin/base/_navigation.jinja
* Pressing ALT+S will focus the search bar
* Holding ALT will reveal access keys for the search results
* Pressing ALT+[KEY] will then activate that result
Refs SHOOP-264
=> Admin: Add keyboard shortcuts to megasearch

shoop/themes/classic_gray/static_src/less/classic-gray/navigation.less, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja
* Vertically center logos
* Change the order for pages visible in menu
Refs SHOOP-1389
=> Update classic gray main navigation

shoop/admin/static_src/base/js/form-utils.js
=> Admin: Show first language tab with errors

shoop/admin/static_src/base/js/content-blocks.js, shoop/admin/static_src/base/js/side-nav.js, shoop/admin/static_src/base/less/shoop/custom-forms.less, shoop/admin/static_src/base/less/shoop/inner-nav.less
* Remove the text shadow animation from icon and replace it
with icon scale animation
* Add red text to block header on mobile screen sizes to
indicate there's an error
Refs SHOOP-1397 SHOOP-1399
=> Update styles for admin form error indicators

shoop/admin/static_src/base/js/content-blocks.js, shoop/admin/static_src/base/js/form-utils.js
Admin: Activate first sidebar list item with errors
Admin: Make first language tab with errors work better
Refs SHOOP-1398, SHOOP-1396
=> Admin: Show errors more clearly

shoop/admin/modules/media/static_src/media/browser/components/folderBreadcrumbs.js, shoop/admin/modules/media/static_src/media/browser/components/folderClick.js, shoop/admin/modules/media/static_src/media/browser/components/folderTree.js
=> Admin: Make folder clicks work at media browser

shoop/xtheme/gulp-tools.js, shoop/xtheme/static_src/editor/style.less, shoop/xtheme/static_src/injection/index.js, shoop/xtheme/static_src/injection/style.less, shoop/xtheme/templates/shoop/xtheme/_editor_cell.jinja, shoop/xtheme/templates/shoop/xtheme/_editor_layout.jinja, shoop/xtheme/templates/shoop/xtheme/editor.jinja
=> Update templates and styles for Xtheme editor

shoop/admin/modules/media/static_src/media/browser/FileUpload.js, shoop/admin/modules/media/static_src/media/browser/components/listFileView.js
Admin: Better error message when unexpected error happens
Admin: Add edit option to media browser files in list view
Refs SHOOP-1405, SHOOP-1408
=> Media browser fixes

shoop/admin/modules/media/static_src/media/browser/components/folderLink.js
=> Admin: Fix media browser folderLink

shoop/xtheme/static_src/injection/index.js, shoop/xtheme/static_src/injection/style.less
=> Make xtheme editor toggler visible when editor is hidden

shoop/themes/classic_gray/static_src/less/classic-gray/footer.less, shoop/themes/classic_gray/static_src/less/style.less
=> Add styles for Classic Gray footer

shoop/core/migrations/0007_product_media.py, shoop/core/migrations/0008_maintenance_mode.py, shoop/core/models/shops.py, shoop/front/middleware.py, shoop/front/templates/shoop/front/maintenance.jinja, shoop_tests/front/test_middleware.py
Core: Add missing migration for product media external_url
Core: Enable maintenance mode
Refs SHOOP-1153
=> Maintenance mode (SHOOP-1153)

shoop/themes/classic_gray/templates/classic_gray/products_view.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/category.jinja, shoop/themes/classic_gray/views/__init__.py, shoop/themes/classic_gray/views/products_view.py
* Add products view to classic gray theme
* Show 9 newest products in products view
* Add link to products view in main navigation
* Drop categories from main navigation
* Make main navigation current page work
* Add products view link to category views breadcrumbs
Refs SHOOP-1402
=> Classic gray theme: Products view

shoop/front/template_helpers/general.py, shoop/themes/classic_gray/static_src/js/custom.js, shoop/themes/classic_gray/templates/classic_gray/base_ajax_content_only.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/macros.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/category.jinja, shoop_tests/front/fixtures.py, shoop_tests/front/test_general_template_helpers.py
* Add get_pagination_variables context function under
front.template_helpers.category
* Render product list based on pagination variables
* Reload category page with AJAX
Refs SHOOP-1419
=> Classic gray theme: Add pagination for category view

shoop/front/apps/registration/__init__.py
=> Ensure user is logged in after activating account

shoop/front/middleware.py, shoop_tests/front/test_middleware.py
=> Front middleware: Avoid maintenance mode in admin

shoop_tests/front/test_customer_information.py
=> Add test case for accessing customer view unauthorized

shoop/front/__init__.py, shoop/front/error_handling.py, shoop/front/settings.py, shoop/front/templates/shoop/front/errors/400.jinja, shoop/front/templates/shoop/front/errors/403.jinja, shoop/front/templates/shoop/front/errors/404.jinja, shoop/front/templates/shoop/front/errors/500.jinja, shoop_tests/front/test_error_handling.py, shoop_tests/utils/__init__.py
When project doesn't define handlers, we inject our own handlers.
Refs SHOOP-1490
=> Add Default ErrorHandling

shoop/front/views/product.py, shoop/themes/classic_gray/static_src/js/custom.js, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja, shoop/themes/classic_gray/views/product_price.py, shoop_tests/front/test_basket_commands.py
Also refactor the javascript needed for price changing
Add tests for basket complex variations
Refs SHOOP-1484, SHOOP-1414
=> Front: Add support for Complex variations 

shoop/front/template_helpers/urls.py, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/category.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja
=> Classic gray theme: Show categories in product detail breadcrumb

shoop/core/utils/maintenance.py, shoop/front/middleware.py
=> Maintenance mode: add maintenance mode exempt decorator

shoop/admin/modules/products/views/edit.py, shoop/admin/modules/products/views/forms.py, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja
Front: Show message if simple product not sellable.
Admin: Require minimum purchase quantity be over 0 
Admin: Require Sales Unit
Admin: Round Minimum Purchase Price based on the chosen Sales Unit
Refs SHOOP-1527
=> Various fixes

shoop/themes/classic_gray/static_src/js/custom.js, shoop/themes/classic_gray/static_src/less/classic-gray/product.less, shoop/themes/classic_gray/templates/classic_gray/product_preview.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja
Refs SHOOP-1414 SHOOP-1389 SHOOP-1461 SHOOP-1413
=> Product order section styling

shoop/themes/classic_gray/templates/classic_gray/products_view.jinja
=> Update products default list view in Classic Gray

shoop/themes/classic_gray/templates/classic_gray/shoop/front/basket/default_basket.jinja
=> Classic Gray: Fix back to products links in basket

shoop/front/middleware.py
=> Front middleware: Let shoop admin through when in maintenance mode

shoop/front/templates/shoop/front/index.jinja
=> Update template for default index page

shoop_tests/admin/test_user_module.py
Refs https://github.com/shoopio/shoop/pull/155#issuecomment-142689539
=> Tests: Make test_user_detail_contact_seed not fail randomly

shoop/themes/classic_gray/static_src/js/custom.js
Check that quantity input actually exist before validating it.
Refs SHOOP-1544
=> Classic gray theme: Fix selector issue with valid in price update

shoop/admin/static_src/base/less/shoop/custom-forms.less, shoop/admin/templates/shoop/admin/macros/general.jinja, shoop/admin/templates/shoop/admin/macros/multilanguage.jinja, shoop/admin/templates/shoop/admin/shops/edit.jinja, shoop/front/middleware.py, shoop/front/templates/shoop/front/maintenance.jinja
=> Update maintenance page and admin macros

shoop/themes/classic_gray/__init__.py
=> Classic gray theme: Fix footer links to cms pages

shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja
=> Classic gray theme: Enable login from logout page

shoop/themes/classic_gray/templates/classic_gray/shoop/front/errors/400.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/errors/403.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/errors/404.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/errors/500.jinja
=> Add error templates with messages to Classic Gray

shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja
=> Classic Gray: Fix CMS page navigation visibility

shoop/themes/classic_gray/templates/classic_gray/shoop/front/macros.jinja
Fix issue where product has variation children but none have price available
(no products attached to the variation).
No ref
=> Classic Gray: Fix issue with variation children prices

shoop/front/templates/shoop/front/index.jinja, shoop/testing/factories.py, shoop/xtheme/admin_module/__init__.py, shoop_workbench/settings/base_settings.py
Just usability or cosmetic fixes.
Came across these while working on SHOOP-1560.
=> Miscellaneous tiny fixes

shoop/themes/classic_gray/static_src/js/custom.js, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja
Classic Gray: Fix issue with simple variation orderability
Classic Gray: Remove preview window from DOM on close
Refs SHOOP-1594
=> Classic Gray: Fix simple variation orderability and product preview bug

shoop/front/error_handling.py, shoop/front/templates/shoop/front/errors/500.jinja, shoop_tests/front/templates/shoop/front/errors/500.jinja, shoop_tests/front/test_error_handling.py
=> Error handling fix

shoop/notify/templates/notify/admin/script_item_editor.jinja
=> Use the standardized "Please correct the errors below." error message

shoop/themes/classic_gray/__init__.py, shoop/themes/classic_gray/config_form.py, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_footer.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja
Classic gray theme: Remove hr-tag if footer has no content
Classic gray theme: Make footer cms pages selectable in configuration
SHOOP-1592
=> Show all visible pages in footer

shoop/front/apps/simple_search/views.py
=> Front: Fix issue with variation children visible in search results

shoop/admin/gulp_bits/js-packages.js, shoop/admin/static_src/base/js/datetimepicker.js, shoop/admin/static_src/base/less/paths.less, shoop/admin/static_src/base/less/vendor.less, shoop/admin/static_src/vendor/bower.json, shoop/admin/templatetags/shoop_admin.py, shoop/simple_cms/templates/shoop/simple_cms/admin/edit.jinja
=> Admin datetimepicker

shoop/admin/modules/taxes/__init__.py, shoop/admin/modules/taxes/views/edit.py, shoop/admin/modules/taxes/views/list.py, shoop/admin/templates/shoop/admin/taxes/edit_tax.jinja, shoop/admin/utils/picotable.py, shoop/core/migrations/0010_tax_field_verbose_names.py, shoop/core/models/taxes.py, shoop/core/templatetags/shoop_common.py, shoop/default_tax/__init__.py, shoop/default_tax/admin_module/__init__.py, shoop/default_tax/admin_module/views.py, shoop/default_tax/migrations/0003_tax_field_verbose_names.py, shoop/default_tax/models.py, shoop/default_tax/templates/shoop/default_tax/admin/edit.jinja, shoop/testing/factories.py, shoop/utils/i18n.py, shoop/utils/patterns.py
See the individual commit messages.
Refs SHOOP-975, SHOOP-1607, SHOOP-1608, SHOOP-1609
=> Various tax fixes and UX improvements (SHOOP-975)

shoop/core/migrations/0011_merge.py, shoop/default_tax/migrations/0004_merge.py
=> Merge migrations

shoop/default_tax/templates/shoop/default_tax/admin/edit.jinja
Move indented stuff to macros so the text is easier to read.
Refs SHOOP-975 / SHOOP-1607
=> Make default_tax/admin/edit.jinja easier to read

shoop/themes/classic_gray/static_src/less/classic-gray/basket.less, shoop/themes/classic_gray/static_src/less/classic-gray/navigation.less, shoop/themes/classic_gray/static_src/less/classic-gray/product-list.less, shoop/themes/classic_gray/templates/classic_gray/products_view.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/basket/default_basket.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_footer.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/category.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja
=> Classic Gray: Add new placeholders

shoop/admin/static_src/base/js/datetimepicker.js, shoop/admin/static_src/base/less/shoop/custom-buttons.less, shoop/admin/static_src/base/less/shoop/custom-forms.less, shoop/admin/templates/shoop/admin/attributes/edit.jinja, shoop/admin/templates/shoop/admin/categories/_edit_base_form.jinja, shoop/admin/templates/shoop/admin/methods/edit.jinja, shoop/admin/templates/shoop/admin/products/_edit_attribute_form.jinja, shoop/admin/templates/shoop/admin/products/_edit_media_form.jinja, shoop/admin/templates/shoop/admin/products/_edit_shop_form.jinja, shoop/admin/templates/shoop/admin/products/edit_media.jinja, shoop/admin/templates/shoop/admin/sales_units/edit.jinja, shoop/admin/templates/shoop/admin/shops/edit.jinja, shoop/admin/templates/shoop/admin/taxes/edit_tax.jinja, shoop/admin/templates/shoop/admin/taxes/edit_tax_class.jinja, shoop/admin/templatetags/shoop_admin.py, shoop/admin/utils/bs3_renderers.py, shoop/default_tax/templates/shoop/default_tax/admin/edit.jinja, shoop/simple_cms/templates/shoop/simple_cms/admin/edit.jinja, shoop/themes/classic_gray/__init__.py
=> Admin form updates

shoop/xtheme/models.py, shoop_tests/xtheme/test_load_save.py
=> Xtheme: don't crash when trying to revert unsaved configuration

shoop/xtheme/static_src/editor/index.js, shoop/xtheme/static_src/editor/style.less, shoop/xtheme/templates/shoop/xtheme/_editor_layout.jinja, shoop/xtheme/views/editor.py, shoop/xtheme/views/forms.py, shoop_tests/xtheme/test_editor_forms.py, shoop_tests/xtheme/test_editor_view.py
XTheme: simplify column width configuration in editor 
XTheme: Limit amount of cells in a row
XTheme: Add titles to row action buttons
Refs SHOOP-1688
=> Xtheme editor improvement

shoop/front/apps/auth/forms.py, shoop/themes/classic_gray/templates/classic_gray/shoop/user/recover_password.jinja, shoop_tests/front/test_auth.py
Auth: add error message to login when email is not in use
Password recovery: add better error handling
Refs SHOOP-1670 / SHOOP-1703, SHOOP-1704, SHOOP-1706
=> Tuning login with username

shoop/front/apps/auth/forms.py, shoop/front/apps/auth/templates/shoop/user/recover_password_sent.jinja
Front: change error message in password recovery form
Front: change password recover sent message
Refs SHOOP-1754 / SHOOP-1756 / SHOOP-1670
=> Change auth texts

shoop/admin/templates/shoop/admin/categories/edit.jinja, shoop/admin/templates/shoop/admin/products/edit.jinja
=> Admin: Enable markdown editor for product and category description

shoop/front/apps/auth/forms.py
=> Front: Change password recover error message

doc/api/shoop.core.models.rst, doc/api/shoop.rst, shoop/configuration.py, shoop/core/cache/impl.py, shoop/core/migrations/0012_add_configurations.py, shoop/core/models/__init__.py, shoop/core/models/configurations.py, shoop_tests/core/test_configurations.py
Cache: Change bump_version to increment one to current version
Core: Add model for dynamic configurations
Add API for dynamic configuration
Refs SHOOP-1719 / SHOOP-1720 / SHOOP-1698
=> Dynamic configuration

shoop/themes/classic_gray/static_src/less/classic-gray/carousel.less, shoop/themes/classic_gray/static_src/less/style.less
=> Classic gray: Carousel styles for Bootstrap carousel

shoop/themes/classic_gray/static_src/less/classic-gray/navigation.less
=> Classic Gray: Add styles for language dropdown in navigation

shoop/themes/classic_gray/static_src/less/classic-gray/base.less, shoop/themes/classic_gray/static_src/less/classic-gray/navigation.less
Add some styling for classic gray to make it possible
to use different brand primary colors in the future.
Refs SHOOP-1747 SHOOP-1746
=> Classic Gray: Add possibility for other future brand colors

shoop/locale/fi_FI/LC_MESSAGES/django.po, shoop/locale/fi_FI/LC_MESSAGES/djangojs.po
=> Add Finnish localization files

shoop/core/models/_base.py, shoop_tests/core/test_customers.py
=> Ensure `__str__` doesn't return lazy objects

shoop/admin/generated_resources.txt, shoop/themes/classic_gray/generated_resources.txt
The `order-creater.js` was missing from generated_resources.txt of
admin, so add it.
Sort all generated_resources.txt files.
=> Update generated_resources.txt files

shoop/admin/templates/shoop/admin/dashboard/_block-settings.jinja, shoop/admin/templates/shoop/admin/orders/_detail_payments.jinja, shoop/admin/templates/shoop/admin/products/_edit_media_form.jinja, shoop/admin/templates/shoop/admin/products/variation/_simple_variation_children.jinja, shoop/admin/templates/shoop/admin/products/variation/_variable_variation_children.jinja, shoop/front/apps/auth/templates/shoop/user/recover_password_mail_content.jinja, shoop/front/apps/auth/templates/shoop/user/recover_password_mail_subject.jinja, shoop/notify/templates/notify/admin/script_item_editor.jinja, shoop/simple_pricing/templates/shoop/admin/simple_pricing/form_part.jinja, shoop/themes/classic_gray/templates/classic_gray/navigation_basket_partial.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/basket/default_basket.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/_confirm_table.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/confirm.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/order/partials/product_table.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section_no_product.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/registration/activation_failed.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/registration/register.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/user/login.jinja, shoop/xtheme/templates/shoop/xtheme/admin/config.jinja
=> Template translations

shoop/front/urls.py, shoop/themes/classic_gray/static_src/js/custom.js, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/language_changer.jinja, shoop_workbench/urls.py
@suutari-ai picked this to separate PR #264 from @Pikkupomo's PR #254. Modified it based on @akx comments.
=> Classic gray language changer

shoop/core/models/addresses.py
=> Core: Enable creating immutable addresses

shoop/admin/modules/orders/views/create.py, shoop_tests/admin/test_order_creator.py
=> Admin: Fix method encoding in order creation

shoop/admin/modules/orders/static_src/create/reducers/lines.js, shoop/admin/modules/orders/static_src/create/view/lines.js
Refs SHOOP-1899, SHOOP-1900, SHOOP-1901
=> Admin order creation: Ensure fields are not left empty

shoop/admin/modules/orders/json_order_creator.py, shoop/admin/modules/orders/static_src/create/actions/index.js, shoop/admin/modules/orders/static_src/create/reducers/customer.js, shoop/admin/modules/orders/static_src/create/view/customers.js, shoop/admin/modules/orders/static_src/create/view/index.js, shoop/admin/modules/orders/static_src/create/view/lines.js, shoop/admin/modules/orders/views/create.py
Admin: Make order creator confirmation page cancel to back
Admin: Fix order creator customer/address handling
Admin: Add order creator line text max length to 256
Admin: Make order creator check orderability errors creating OrderSource
Admin: Order creation make customer prices work for products
Refs SHOOP-1799
=> Order creator improvements

shoop/admin/modules/orders/static_src/create/reducers/lines.js, shoop/admin/modules/orders/static_src/create/view/lines.js, shoop_tests/admin/test_order_creator.py
* Add tests
* Fix order creator discountPercent
Refs SHOOP-1799
=> Admin: Order creator fix and tests

shoop/admin/forms/widgets.py, shoop/admin/gulp_bits/js-packages.js, shoop/admin/toolbar.py, shoop/admin/utils/forms.py
Admin: Fix BasePopupChoiceWidget filter
Admin: drop strict-mode from dashboard
Admin js-packages: Enable es6 for picotable
Refs SHOOP-1839
=> Admin: Fix admin JS

shoop/admin/modules/orders/views/list.py, shoop/simple_cms/admin_module/views.py
Simple-cms: Fix admin module sorting with title
Admin: Fix order list sorting with taxful_total_price
Refs SHOOP-1836
=> Admin list sorting

shoop/core/models/product_media.py, shoop/core/models/products.py, shoop/themes/classic_gray/templates/classic_gray/shoop/front/macros.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/personal_order_history/order_detail.jinja
Core: Change ProductMedia url property to return correctly
Core: Add get_public_media-function for Product
Classic Gray: Add product media to templates
Refs SHOOP-1918
=> Product media with orders

shoop/admin/modules/orders/views/list.py
=> Fix order list sorting by total

ChangeLog.rst, shoop/admin/modules/contacts/views/edit.py, shoop/admin/modules/orders/json_order_creator.py, shoop/admin/modules/orders/static_src/create/actions/index.js, shoop/admin/modules/orders/static_src/create/view/index.js, shoop/admin/modules/orders/views/create.py, shoop/core/api/orders.py, shoop/core/migrations/0013_address_changes.py, shoop/core/models/__init__.py, shoop/core/models/addresses.py, shoop/core/models/contacts.py, shoop/core/models/orders.py, shoop/core/order_creator/creator.py, shoop/front/apps/customer_information/views.py, shoop/front/checkout/addresses.py, shoop/front/checkout/single_page.py, shoop/testing/factories.py, shoop_tests/core/test_addresses.py, shoop_tests/core/test_basic_order.py, shoop_tests/core/test_categories.py, shoop_tests/core/test_orders.py, shoop_tests/core/test_shops.py, shoop_tests/functional/test_tax_system.py, shoop_tests/utils/test_form_group.py
* Core: Make core work with mutable and immutable addresses
* Make front work work with mutable and immutable addresses
* Admin: Fix contact edit to work with immutable address
* Tests: Fix tests to work with mutable and immutable addresses
* Fix tests that failed with mysql
* Admin: Make order creator work with mutable addresses
Refs SHOOP-1924
=> Split Address to MutableAddress and ImmutableAddress

shoop/admin/modules/orders/static_src/create/view/methods.js, shoop/admin/modules/orders/views/create.py
=> Admin order creator: Don't encode unnecessary method extras

shoop/admin/gulp_bits/js-packages.js, shoop/admin/static_src/base/js/language-changer.js, shoop/admin/static_src/base/less/shoop/navigation.less, shoop/admin/static_src/base/less/variables.less, shoop/admin/template_helpers/shoop_admin.py, shoop/admin/templates/shoop/admin/base/_navigation.jinja, shoop/admin/urls.py
Add language changer to shop admin so current language can be set/changed
before activating frontend theme.
Refs SHOOP-1943
Screenshots:
=> Language changer for shop admin

.tx/config, shoop/front/basket/update_methods.py, shoop/simple_supplier/admin_module/views.py, shoop/simple_supplier/static/simple_supplier/js/extra.js, shoop_tests/front/fixtures.py, shoop_tests/front/test_basket_commands.py
Front: Show better error messages in basket update
Simple supplier: Make SKU-sort in stock management work
Simple supplier: Make admin filter+stock adjustment work
Simple supplier: Add djangojs.po file to transifex config
Refs SHOOP-1876
=> Stock management fixes

CLA.md, README.rst
=> Add CLA and update README.rst

shoop/addons/admin_module/views/reload.py, shoop/addons/admin_module/views/upload.py, shoop/addons/locale/en/LC_MESSAGES/django.po, shoop/addons/templates/shoop/admin/addons/reload.jinja, shoop/addons/templates/shoop/admin/addons/upload_complete.jinja, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/locale/en/LC_MESSAGES/djangojs.po, shoop/admin/modules/contacts/views/edit.py, shoop/admin/modules/methods/views/edit_detail.py, shoop/admin/modules/orders/static_src/create/view/lines.js, shoop/admin/static_src/picotable/picotable.js, shoop/admin/templates/shoop/admin/problem.jinja, shoop/admin/templates/shoop/admin/system/telemetry.jinja, shoop/themes/classic_gray/locale/en/LC_MESSAGES/django.po, shoop/themes/classic_gray/templates/classic_gray/shoop/front/index.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/user/login.jinja, shoop/xtheme/locale/en/LC_MESSAGES/django.po, shoop/xtheme/views/editor.py
Fix minor message construction and mistranslation issues with translatable message strings where found in various apps.
Refs SHOOP-1985
=> Fix translatable messages

doc/api/shoop.order_printouts.admin_module.rst, doc/api/shoop.order_printouts.rst, doc/changelog.rst
=> Add missing docs for simple_supplier and order_printouts

shoop/simple_supplier/admin_module/forms.py
Add stock should be available only for suppliers that
has simple_supplier as a module.
Refs SHOOP-2099 / SHOOP-1876
=> Simple supplier: Add simple_supplier identifier check

shoop/admin/toolbar.py
=> Admin: Enable toolbar for form views without object

shoop/addons/locale/pt_BR/LC_MESSAGES/django.po, shoop/admin/locale/pt_BR/LC_MESSAGES/django.po, shoop/admin/locale/pt_BR/LC_MESSAGES/djangojs.po, shoop/core/locale/pt_BR/LC_MESSAGES/django.po, shoop/default_tax/locale/pt_BR/LC_MESSAGES/django.po, shoop/front/apps/auth/locale/pt_BR/LC_MESSAGES/django.po, shoop/front/apps/customer_information/locale/pt_BR/LC_MESSAGES/django.po, shoop/front/apps/personal_order_history/locale/pt_BR/LC_MESSAGES/django.po, shoop/front/apps/registration/locale/pt_BR/LC_MESSAGES/django.po, shoop/front/apps/simple_order_notification/locale/pt_BR/LC_MESSAGES/django.po, shoop/front/apps/simple_search/locale/pt_BR/LC_MESSAGES/django.po, shoop/front/locale/pt_BR/LC_MESSAGES/django.po, shoop/notify/locale/pt_BR/LC_MESSAGES/django.po, shoop/notify/locale/pt_BR/LC_MESSAGES/djangojs.po, shoop/simple_cms/locale/pt_BR/LC_MESSAGES/django.po, shoop/simple_supplier/locale/pt_BR/LC_MESSAGES/django.po, shoop/testing/locale/pt_BR/LC_MESSAGES/django.po, shoop/themes/classic_gray/locale/pt_BR/LC_MESSAGES/django.po, shoop/utils/locale/pt_BR/LC_MESSAGES/django.po, shoop/xtheme/locale/pt_BR/LC_MESSAGES/django.po, shoop/xtheme/locale/pt_BR/LC_MESSAGES/djangojs.po, shoop_workbench/settings/base_settings.py
Portuguese (Brazil) translation.
=> Translate to pt_BR

shoop/core/models/_products.py, shoop/simple_supplier/admin_module/forms.py, shoop/simple_supplier/locale/en/LC_MESSAGES/django.po, shoop/simple_supplier/templates/shoop/simple_supplier/admin/product_form_part.jinja, shoop_tests/simple_supplier/test_simple_supplier.py
* Core: Add is_stocked method for Product model
* Simple Supplier: Show better information when product is not stocked
Refs SHOOP-2131 / SHOOP-1876
=> Enhance stocks admin

shoop/campaigns/forms.py, shoop/campaigns/migrations/0002_update_product_count.py, shoop/campaigns/migrations/0003_unique_coupon.py, shoop/campaigns/models/basket_conditions.py, shoop/campaigns/models/campaigns.py, shoop_tests/campaigns/test_admin.py, shoop_tests/campaigns/test_basket_campaigns.py
* Campaigns: Update product_count-field to allow bigger values
* Campaigns: add clean for campaign start and end
* Campaigns: limit BasketCampaigns per coupon to one
Refs SHOOP-2122 / SHOOP-2107 / SHOOP-2108
=> Campaign enhancements

doc/changelog.rst, shoop/admin/modules/orders/json_order_creator.py, shoop/admin/modules/orders/static_src/create/actions/index.js, shoop/admin/modules/orders/views/create.py, shoop/core/order_creator/_creator.py, shoop/core/order_creator/_source.py, shoop/front/basket/commands.py, shoop/front/basket/objects.py, shoop/themes/classic_gray/templates/classic_gray/add_product_to_basket.jinja, shoop_tests/campaigns/__init__.py, shoop_tests/campaigns/test_discount_codes.py, shoop_tests/front/test_basket.py, shoop_tests/simple_supplier/test_order_source.py, shoop_tests/simple_supplier/test_simple_supplier.py, shoop_tests/simple_supplier/utils.py
* Classic Gray: Show error messages while adding products to basket
* Front: Check product quantity already in basket while adding
* Core: Add shop product validation for OrderSource
* Admin: check product quantity on other lines when adding
Refs SHOOP-2132 / SHOOP-2130 / SHOOP-1876
=> Informative basket error handling

shoop/addons/reloader.py, shoop/addons/templates/shoop/admin/addons/upload_complete.jinja, shoop/apps/settings.py
Addons: Catch AttributeError when getting ``GunicornReloadMethod`` class
Apps: Clean AppDirectoriesFinder before reloading Django apps
Addons: Fix the link to reload page from installation complete page
Refs SHOOP-1770
=> Enhance addon installation process

doc/changelog.rst, shoop/core/models/_suppliers.py, shoop/front/template_helpers/general.py, shoop/themes/classic_gray/plugins.py, shoop_tests/core/test_suppliers.py, shoop_tests/front/test_general_template_helpers.py
Add option for highlights plugin to hide all out-of-stock products (true
by default).
Refs SHOOP-1969
=> Themes: Product highlights plugin improvements

shoop/campaigns/apps.py, shoop/campaigns/locale/en/LC_MESSAGES/django.po, shoop/campaigns/migrations/0004_add_contact_conditions.py, shoop/campaigns/models/basket_conditions.py, shoop/campaigns/models/context_conditions.py, shoop_tests/campaigns/test_basket_contact_conditions.py, shoop_tests/campaigns/test_basket_product_conditions.py, shoop_tests/campaigns/test_catalog_campaigns.py, shoop_tests/campaigns/test_context_conditions.py
Add contact group and contact conditions for basket and
context campaigns.
Refs SHOOP-1981 / SHOOP-2098
=> Campaigns: Add contact group and contact conditions (SHOOP-2098)

doc/changelog.rst, shoop/simple_cms/admin_module/views.py, shoop/simple_cms/migrations/0004_add_parents.py, shoop/simple_cms/models.py, shoop/simple_cms/templates/shoop/simple_cms/admin/edit.jinja, shoop/simple_cms/templates/shoop/simple_cms/page.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/simple_cms/page.jinja, shoop_tests/simple_cms/test_children.py
=> Simple CMS: Add parent for Page and list children on page (SHOOP-2144)

doc/changelog.rst, shoop/customer_group_pricing/module.py, shoop_tests/customer_group_pricing/test_customer_group_pricing.py
Enable price for ``AnonymousContact`` default group
Refs SHOOP-1981 / SHOOP-2218
=> Customer Group Pricing: Fix pricing for ``AnonymousContact`` (SHOOP-2218)

doc/changelog.rst, shoop/admin/modules/contact_groups/__init__.py, shoop/admin/modules/contact_groups/views/__init__.py, shoop/admin/modules/contact_groups/views/delete.py, shoop/admin/modules/contact_groups/views/edit.py, shoop/core/models/_contacts.py, shoop_tests/admin/test_contact_group_edit.py, shoop_tests/core/test_contact_group_delete.py
Core: Disable delete for default contact groups
Admin: Enable delete for contact groups
Refs SHOOP-1981 / SHOOP-2217
=> Delete for contact groups (SHOOP-2217)

shoop/admin/static_src/base/js/browse-widget.js
=> Admin: Enable scrollbar in browse-widget (SHOOP-2206)

shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja
=> Classic Gray: Disable "Add to cart"-button if prices is hidden (SHOOP-2255)

shoop/xtheme/static_src/editor/custom-modals.less, shoop/xtheme/static_src/editor/paths.less, shoop/xtheme/static_src/editor/remarkable.less, shoop/xtheme/static_src/editor/style.less, shoop/xtheme/static_src/editor/variables.less
Add local copy of less variables from admin to fix problems building
xtheme resources when admin resources have not been compiled yet.
This also allows for us to change less variables in xtheme styles.
Refs SHOOP-2287
=> Xtheme: Fix bootstrap less dependency

doc/changelog.rst, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/modules/contacts/views/edit.py, shoop/admin/templates/shoop/admin/contacts/_edit_base_form.jinja, shoop/admin/templates/shoop/admin/contacts/detail.jinja, shoop/core/locale/en/LC_MESSAGES/django.po, shoop/core/migrations/0019_contact_merchant_notes.py, shoop/core/models/_contacts.py
Core: Add merchant notes text-field for ``Contact``
Admin: Enable editing merchant notes for ``Contact``
Refs SHOOP-1994
=> Merchant notes for contact (SHOOP-1994)

shoop/addons/templates/shoop/admin/addons/reload.jinja
=> Admin: Fix addon reload JavaScript by adding event to onclick-event

shoop/xtheme/plugins/category_links.py, shoop_tests/xtheme/test_plugins.py
=> XTheme: Add customer and shop filter to category links plugin

shoop/front/management/commands/compute_bought_with_relations.py
=> Front: Fix the ``compute_bought_with_relations`` management command

doc/api/shoop.admin.modules.rst, doc/api/shoop.admin.modules.service_providers.rst, doc/api/shoop.admin.modules.service_providers.views.rst, doc/provides.rst, shoop/admin/__init__.py, shoop/admin/forms/__init__.py, shoop/admin/forms/_base.py, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/modules/service_providers/__init__.py, shoop/admin/modules/service_providers/forms.py, shoop/admin/modules/service_providers/views/__init__.py, shoop/admin/modules/service_providers/views/_edit.py, shoop/admin/modules/service_providers/views/_list.py, shoop/admin/templates/shoop/admin/service_providers/edit.jinja, shoop/testing/__init__.py, shoop/testing/payment_forms.py, shoop_tests/admin/test_service_providers.py
Add admin for service providers such as carriers and payment
processors.
=> Service provider admin (SHOOP-2061)

doc/changelog.rst, doc/provides.rst, shoop/admin/modules/contact_groups/views/edit.py, shoop/campaigns/admin_module/form_parts.py, shoop/campaigns/apps.py, shoop/campaigns/locale/en/LC_MESSAGES/django.po, shoop/campaigns/migrations/0005_sales_ranges.py, shoop/campaigns/models/__init__.py, shoop/campaigns/models/contact_group_sales_ranges.py, shoop/campaigns/signal_handlers.py, shoop/campaigns/templates/shoop/campaigns/admin/sales_ranges_form_part.jinja, shoop_tests/campaigns/test_sales_ranges.py, shoop_tests/campaigns/test_sales_ranges_admin.py
* Add ``admin_contact_group_form_part`` provider
* Campaigns: Add contact group sales ranges
* Campaigns: Add form part for contact group sales ranges
=> Contact group sales ranges (SHOOP-1975)

doc/api/shoop.admin.modules.rst, doc/api/shoop.admin.modules.services.rst, doc/api/shoop.admin.modules.services.views.rst, doc/changelog.rst, doc/provides.rst, shoop/admin/__init__.py, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/modules/service_providers/views/_edit.py, shoop/admin/modules/services/__init__.py, shoop/admin/modules/services/base_form_part.py, shoop/admin/modules/services/behavior_form_part.py, shoop/admin/modules/services/forms.py, shoop/admin/modules/services/views/__init__.py, shoop/admin/modules/services/views/_edit.py, shoop/admin/modules/services/views/_list.py, shoop/admin/templates/shoop/admin/services/_edit_base_form.jinja, shoop/admin/templates/shoop/admin/services/_edit_behavior_components_form.jinja, shoop/admin/templates/shoop/admin/services/edit.jinja, shoop/core/models/_service_base.py, shoop/core/models/_service_payment.py, shoop/core/models/_service_shipping.py, shoop/testing/models/_pseudo_payment.py, shoop/utils/multilanguage_model_form.py, shoop_tests/admin/test_service_behavior_components.py, shoop_tests/admin/test_services.py
* Admin: Add admin for services
* Admin: Add "Create Service"-button for ``ServiceProvider`` edit view
=> Service admin (SHOOP-2317, SHOOP-2336)

shoop/core/locale/en/LC_MESSAGES/django.po, shoop/core/models/_contacts.py, shoop/core/models/_shops.py, shoop/core/models/_suppliers.py, shoop/notify/enums.py, shoop/notify/locale/en/LC_MESSAGES/django.po, shoop/xtheme/locale/en/LC_MESSAGES/django.po, shoop/xtheme/models.py
Add missing translated messagens in Enums
=> Add translated messages in Enums.

shoop/campaigns/models/contact_group_sales_ranges.py, shoop/campaigns/signal_handlers.py, shoop_tests/campaigns/test_sales_ranges.py
When assigning to contact groups based on sales ranges contacts shouldn't
be removed from contact groups which doesn't have sales range or the sales
range is not active i.e. min_value and max_value equals zero.
Refs SHOOP-1975 / SHOOP-2416
=> Campaigns: Remove only from groups with active sales range

shoop_tests/core/test_shops.py
Add tests that check shop translations work as expected.  This should
work as a general "django-parler works as expected" test.
These test were written when tested some django-parler related stuff
for the new service API (SHOOP-2293).
=> Add tests for translating shops

shoop/admin/utils/picotable.py, shoop_tests/admin/test_picotable.py
Fix picotable bug when sorting querysets for translated fields.
Refs SHOOP-2398
=> Admin: Fix picotable sorting bug

doc/changelog.rst, shoop/core/models/_orders.py, shoop/core/signals.py, shoop_tests/core/test_shipment_weights.py
* Core: Prove that shipment weights is calculated correctly
* Core: Add signal for shipment created
* Core: Make ``create_shipment`` for orders atomic
=> Shipment weights (SHOOP-2494)

shoop/admin/modules/services/views/_list.py
Show service choice name in service provider admin list view.
=> Admin: Show service choice name in service provider admin

shoop/admin/modules/services/views/_list.py
Add check for service choice display name.
=> Admin: Add check for service choice display

doc/changelog.rst, doc/provides.rst, shoop/admin/modules/orders/views/shipment.py, shoop/admin/templates/shoop/admin/orders/create_shipment.jinja, shoop/core/migrations/0023_add_shipment_identifier.py, shoop/core/models/_orders.py, shoop/core/models/_shipments.py, shoop_tests/admin/test_shipment_creator.py, shoop_tests/core/test_shipment_weights.py, shoop_tests/core/test_shipments.py, shoop_tests/core/test_tracking_codes.py
* Core: Add unique shipment key for ``Shipment``
* Admin: Allow shipment creation extensions
=> Admin/Core: Shipment creation extensions (SHOOP-2501)

doc/api/shoop.admin.modules.orders.views.rst, doc/changelog.rst, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/locale/en/LC_MESSAGES/djangojs.po, shoop/admin/modules/orders/__init__.py, shoop/admin/modules/orders/json_order_creator.py, shoop/admin/modules/orders/static_src/create/actions/index.js, shoop/admin/modules/orders/static_src/create/index.js, shoop/admin/modules/orders/static_src/create/reducers/lines.js, shoop/admin/modules/orders/static_src/create/reducers/order.js, shoop/admin/modules/orders/static_src/create/store.js, shoop/admin/modules/orders/static_src/create/view/index.js, shoop/admin/modules/orders/views/__init__.py, shoop/admin/modules/orders/views/detail.py, shoop/admin/modules/orders/views/edit.py, shoop/admin/npm-shrinkwrap.json, shoop/admin/package.json, shoop/core/models/_orders.py, shoop_tests/admin/test_order_creator.py, shoop_tests/core/test_orders.py, shoop_tests/core/test_shipments.py
Implement order editing feature in Admin.
This also requires couple changes to Core:
* Update shipping status correctly in Order.create_shipment
* Add Order.can_edit
Utilizes the OrderModier implemented in PR #467.
This is the second part of PR #466 split to two pieces.
=> Admin: Enable editing orders (SHOOP-1993)

doc/changelog.rst, shoop/front/views/product.py, shoop/themes/classic_gray/static_src/less/classic-gray/basket.less, shoop/themes/classic_gray/templates/classic_gray/shoop/front/basket/partials/_basket_content.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/checkout/_confirm_table.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/macros.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/detail.jinja
Update UI for package products on product detail page and customer
basket display, listing products in package and their quantities.
Refs SHOOP-2274
=> Front: Update UI for package products

shoop/themes/classic_gray/locale/en/LC_MESSAGES/django.po
Add translations for package products.
Refs SHOOP-2274
=> Classic gray: Add translations for package products

shoop/core/models/_shipments.py
Instead of using ``ShipmentProduct`` id let's use product_id for
updating stock.
=> Core: Update stocks based on product id

shoop_tests/front/test_basket_commands.py
``shoop.front.basket.commands.handle_add_var`` takes request, basket
and product_id as a parameters. Let's use corect product_id instead
of 1.
=> Front: Test handle_add_var basket_command correctly

doc/api/shoop.testing.rst, doc/changelog.rst, shoop/front/checkout/_process.py, shoop/front/checkout/methods.py, shoop/testing/__init__.py, shoop/testing/migrations/0002_carrierwithcheckoutphase.py, shoop/testing/models/__init__.py, shoop/testing/models/_methods.py, shoop/testing/service_forms.py, shoop/testing/simple_checkout_phase.py, shoop/testing/templates/shoop_testing/simple_checkout_phase.jinja, shoop_tests/admin/test_service_providers.py, shoop_tests/front/test_checkout_flow.py
Testing: Add test carrier with checkout phase
Front: Fix bug with multiple service checkout phases
=> Enable multiple service checkout phases

.eslintrc, doc/api/shoop.admin.views.rst, doc/changelog.rst, shoop/admin/forms/widgets.py, shoop/admin/gulp_bits/css-packages.js, shoop/admin/gulp_bits/js-packages.js, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/locale/en/LC_MESSAGES/djangojs.po, shoop/admin/static_src/base/bower.json, shoop/admin/static_src/base/js/form-utils.js, shoop/admin/static_src/base/js/select.js, shoop/admin/static_src/base/less/paths.less, shoop/admin/static_src/base/less/shoop/picotable.less, shoop/admin/static_src/base/less/shoop/select.less, shoop/admin/static_src/base/less/style.less, shoop/admin/static_src/base/less/vendor.less, shoop/admin/static_src/vendor/bower.json, shoop/admin/static_src/vendor/css/select2.css, shoop/admin/templates/shoop/admin/base.jinja, shoop/admin/urls.py, shoop/admin/views/select.py, shoop/campaigns/forms.py, shoop_tests/admin/test_select_view.py
Admin: Add view and widget to support Select2 dropdowns
Admin: Enable multiselect dropdown with Select2
Admin: Remove support for selectpicker
Campaigns: Use Select2 for ManyToManyField's
=> Enhanced multiselect dropdowns (SHOOP-2324)

shoop/admin/base.py
Fix search result initialization by correctly setting relevance.
Refs SHOOP-2608
=> Admin: Fix search result initialization (SHOOP-2608)

doc/changelog.rst, shoop/core/models/_product_shops.py, shoop/front/template_helpers/general.py, shoop/front/template_helpers/product.py, shoop_tests/front/test_product_template_helpers.py, shoop_tests/themes/classic_gray/test_plugins.py
* Core: Add is_visible method for ShopProduct
* Front: In template helpers make get_visible_products faster
* Front: Make get_best_selling_products faster
* Front: Make get_product_cross_sells method faster
=> Front: Get highlighted products for plugins more efficiently (SHOOP-2576)

doc/changelog.rst, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/modules/contact_groups/views/forms.py, shoop/admin/modules/contacts/views/list.py, shoop/admin/templates/shoop/admin/contact_groups/_edit_members_form.jinja, shoop_tests/admin/test_contact_group_edit.py
Admin: Hide group members in contact group edit view
Admin: Filter contacts with contact group in contact list
=> Contact group members changes (SHOOP-2606)

shoop/admin/modules/contacts/views/detail.py
=> Remove `New User` from `CompanyContacts`

doc/api/shoop.guide.rst, doc/api/shoop.rst, doc/changelog.rst, shoop/admin/base.py, shoop/admin/static_src/base/js/search.js, shoop/guide/__init__.py, shoop/guide/admin_module.py, shoop/guide/apps.py, shoop/guide/locale/en/LC_MESSAGES/django.po, shoop/guide/settings.py, shoop_tests/admin/fixtures/test_module.py, shoop_tests/admin/test_modules.py, shoop_tests/guide/test_search_results.py
Add guide app for displaying merchant help documenation in admin
search results.
Refs SHOOP-2608
=> Guide: Add guide app for displaying merchant help documentation (SHOOP-2608)

doc/changelog.rst, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/modules/contacts/views/detail.py, shoop/admin/templates/shoop/admin/contacts/detail.jinja
=> Show companies in `PersonContact` detail view (SHOOP-2298)

doc/changelog.rst, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/modules/contacts/views/edit.py, shoop/admin/templates/shoop/admin/contacts/_edit_base_form.jinja, shoop/admin/templates/shoop/admin/contacts/detail.jinja, shoop_tests/admin/test_contact_edit.py
Admin: Add possibility to remove contacts from company
Admin: Add possibility to add contacts for company
Refs SHOOP-2589
=> Admin: Add Company's Contacts to Contact view (SHOOP-2589)

shoop/admin/modules/contacts/views/detail.py, shoop/admin/templates/shoop/admin/contacts/detail.jinja
=> Admin: Show companies only for person contacts

shoop/admin/modules/contacts/views/edit.py, shoop_tests/admin/test_contact_edit.py
Initialize members select only if currenly handled contact has
attribute members.
Refs SHOOP-2589 / SHOOP-2628
=> Admin: Fix bug in contact creation

shoop/guide/admin_module.py
=> Guide: Open search results in new tab

doc/provides.rst, shoop/admin/__init__.py, shoop/admin/base.py, shoop/admin/modules/orders/sections.py, shoop/admin/modules/orders/views/detail.py, shoop/admin/modules/orders/views/log.py, shoop/admin/templates/shoop/admin/orders/_order_log_entries_extra_js.jinja, shoop/admin/templates/shoop/admin/orders/detail.jinja
Fixed bug for custom user models
=> Admin: Create order detail section through provides

doc/changelog.rst, shoop/default_tax/migrations/0008_min_max_postal_code.py, shoop/default_tax/models.py, shoop/default_tax/module.py, shoop/utils/patterns.py, shoop_tests/default_tax/test_default_tax.py
=> Default Tax: Add min and max values to `TaxRule` (SHOOP-2616)

doc/changelog.rst, shoop/themes/classic_gray/templates/classic_gray/navigation_basket_partial.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/includes/_navigation.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja
* Hide cart when prices are hidden
* Hide product order section when prices are hidden
* Hide cart container ul element when cart is hidden.
This replaces PR #510.
=> Hide cart and product order section when prices are hidden (SHOOP-2679)

doc/changelog.rst, shoop/themes/classic_gray/templates/classic_gray/navigation_basket_partial.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/front/product/_detail_order_section.jinja
* Hide cart when prices are hidden
* Hide product order section when prices are hidden
=> Hide cart and product order section when prices are hidden (SHOOP-2638)

doc/changelog.rst, shoop/xtheme/plugins/widgets.py, shoop/xtheme/static_src/editor/index.js, shoop/xtheme/templates/shoop/xtheme/_model_widget.jinja
Add custom XThemeModelChoiceField and XThemeModelChoiceWidget for
showing edit link to admin
Refs SHOOP-1892 / SHOOP-2170
=> XTheme: Show edit link in model choice fields (SHOOP-2170)

doc/changelog.rst, shoop/admin/modules/contacts/views/list.py, shoop/admin/modules/users/views/list.py, shoop/admin/static_src/picotable/picotable.js, shoop/admin/utils/picotable.py, shoop_tests/admin/test_picotable.py
Refs SHOOP-2236, SHOOP-2642, SHOOP-2687
=> Add Picotable  `ChoiceFilter` defaults and only show active users and contacts by default (SHOOP-2236, SHOOP-2642)

shoop/core/fields/__init__.py, shoop_tests/core/test_fields.py
by default, django renders the step size in scientific notation when any decimal places
are present. This PR allows step size with up to 5 decimal places. If
FormattedDecimalFields need more decimal places, the step size becomes 1.
=> Numbers in input fields increment/decrement in scientific notation (SHOOP-2746)

doc/changelog.rst, shoop/front/apps/customer_information/locale/en/LC_MESSAGES/django.po, shoop/front/apps/customer_information/templates/shoop/customer_information/change_password.jinja, shoop/front/apps/customer_information/urls.py, shoop/front/apps/customer_information/views.py, shoop/themes/classic_gray/templates/classic_gray/shoop/customer_information/change_password.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/customer_information/edit_company.jinja, shoop/themes/classic_gray/templates/classic_gray/shoop/customer_information/edit_customer.jinja, shoop_tests/front/test_customer_information.py
Note: I'm using a view function since that's what django.contrib.auth uses and it's simpler just to do it this way. :smile: 
Refs SHOOP-2704
=> Front: Allow user to change password from shop front (SHOOP-2704)

shoop/admin/views/select.py, shoop_tests/admin/test_select_view.py
If a contact or user is marked as inactive, do not include in
multiselect search results.
Refs SHUUP-2745
=> Admin: Omit inactive contacts and users from multiselect (SHUUP-2745)

doc/changelog.rst, shoop/admin/locale/en/LC_MESSAGES/django.po, shoop/admin/modules/contacts/views/detail.py, shoop/admin/modules/orders/static_src/create/index.js, shoop/admin/modules/orders/views/edit.py, shoop_tests/admin/test_order_creator.py
Add an 'Add Order' button to the contact detail page. Clicking
this button opens the admin order creator for that contact.
Refs SHUUP-2729
=> Admin: Create order for contact from contact page (SHUUP-2729)

doc/changelog.rst, shoop/admin/modules/orders/static_src/create/reducers/lines.js, shoop/utils/numbers.py, shoop_tests/utils/test_numbers.py
Fix issues where order creation fails when then price or discount is very 
small.
Refs SHUUP-2640
=> Admin: Fix precision issues for order submission (SHUUP-2640)

doc/changelog.rst, shoop/admin/modules/products/views/list.py
Add new field to table to filter products by barcode.
Refs SHUUP-2681
=> Admin: Add product barcode filter (SHUUP-2681)

doc/changelog.rst, shoop/core/models/_contacts.py, shoop/front/locale/en/LC_MESSAGES/django.po, shoop/front/middleware.py, shoop_tests/front/test_middleware.py
* Core: Do not create multiple contacts for user
* Front: Logout if user is linked to inactive contact
=> Fix for deactivating contacts (SHUUP-2840)

.travis.yml, tox.ini
* Use tox for testing
* Rewrite tox.ini with additional environments and some other improvements.
* Disable migrations while testing
=> Travis: Make test runs faster (SHUUP-2846)

shoop/campaigns/admin_module/views.py, shoop/campaigns/apps.py, shoop/campaigns/forms.py, shoop/campaigns/locale/en/LC_MESSAGES/django.po, shoop/campaigns/migrations/0006_effects.py, shoop/campaigns/models/__init__.py, shoop/campaigns/models/basket_effects.py, shoop/campaigns/models/campaigns.py, shoop/campaigns/models/product_effects.py, shoop/campaigns/modules.py, shoop/campaigns/templates/shoop/campaigns/admin/edit_campaigns.jinja, shoop/front/apps/simple_order_notification/templates.py, shoop_tests/campaigns/test_admin.py, shoop_tests/campaigns/test_basket_campaigns.py, shoop_tests/campaigns/test_basket_contact_conditions.py, shoop_tests/campaigns/test_catalog_campaigns.py, shoop_tests/campaigns/test_context_conditions.py, shoop_tests/campaigns/test_discount_codes.py, shoop_tests/functional/test_order_edit_with_coupons.py
Campaigns gave the end results directly from campaign, this is not a good long term solution.
Refactored campaigns so that effects can be created separately from campaigns itself.
Refs SHUUP-2824
=> Refactor campaign effects (SHUUP-2824)

doc/changelog.rst, shoop/admin/__init__.py, shoop/admin/modules/services/forms.py, shoop/admin/static_src/base/js/select.js, shoop/admin/templates/shoop/admin/services/edit.jinja, shoop/core/locale/en/LC_MESSAGES/django.po, shoop/core/migrations/0027_contact_group_behavior.py, shoop/core/models/__init__.py, shoop/core/models/_service_behavior.py, shoop_tests/admin/test_service_behavior_components.py, shoop_tests/core/test_contact_group_behavior.py
* Add ``GroupAvailabilityBehaviorComponent`` behavior component which makes the
service available for certain groups.
* Add admin forms for the component.
* Enable option to activate select2 dropwdowns dynamically in service admin.
Refs SHUUP-2685 / SHUUP-2847
=> Services: Add contact group availability behavior (SHUUP-2847)

shoop/core/locale/en/LC_MESSAGES/django.po, shoop/core/models/_service_behavior.py, shoop_tests/core/test_contact_group_behavior.py
=> Core: Handle unsaved customers in group availability component (SHUUP-2878)

doc/changelog.rst, shoop/core/migrations/0028_roundingbehaviorcomponent.py, shoop/core/migrations/0029_update_order_phone_max_length.py, shoop/core/models/_orders.py
* Core: Remove bytes from migration 0028
* Core: Update order phone max length to 64 characters
=> Core: Fix migration 0028 and update order phone field

shoop/simple_cms/templates/shoop/simple_cms/plugins/page_links.jinja, shoop/xtheme/templates/shoop/xtheme/plugins/category_links.jinja
=> Fix section endings in category and cms links

shoop/campaigns/admin_module/__init__.py
=> Campaigns: Fix admin module permissions

shoop/admin/modules/orders/static_src/create/view/customers.js, shoop/admin/modules/orders/static_src/create/view/index.js
* Make the order summary and recent orders tables responsive
* Ensure modal doesn't disappear on small screens
* Comma separate group names
Refs SHUUP-2896, SHUUP-2897
=> Admin: Fix customer detail modal responsiveness (SHUUP-2896, SHUUP-2897)

shoop/admin/locale/en/LC_MESSAGES/djangojs.po, shoop/admin/locale/fi_FI/LC_MESSAGES/django.po, shoop/admin/locale/fi_FI/LC_MESSAGES/djangojs.po, shoop/core/locale/fi_FI/LC_MESSAGES/django.po
=> Fix translations messed in purchase order revert (SHUUP-2908)

doc/api/shoop.admin.modules.orders.rst, doc/api/shoop.admin.modules.orders.views.rst, doc/api/shoop.admin.modules.product_types.views.rst, doc/api/shoop.campaigns.rst
Regenerate API doc files with "generate_apidoc.py".
=> Update API doc files (SHUUP-2918)

shoop/core/migrations/0020_services_and_methods.py
Update migration shoop.0020 to migrate price, waiver limit, and
min/max weights from method data to behavior components.
Also enable methods that are using the default module and were
previously enabled.
=> Core: Migrate method data (SHUUP-2883)

doc/changelog.rst, shuup/admin/modules/orders/views/detail.py, shuup/admin/modules/orders/views/refund.py, shuup/core/models/_orders.py, shuup_tests/core/test_orders.py
- Fix handling of refunds for discount lines
- Replace buttons with dropdown in Orders admin
- Include quantities in refund order lines
Refs SHUUP-2914, 2916
=> Fix refund issues (SHUUP-2914, 2916)

shuup/campaigns/apps.py, shuup/campaigns/consts.py, shuup/campaigns/models/campaigns.py, shuup/campaigns/models/catalog_filters.py, shuup/campaigns/models/matching.py, shuup/campaigns/signal_handlers.py
* Add matching campaigns for context to cache
* Add matching context conditions for context to cache
* Add matching catalog filters for shop_product to cache
Minimize queries while solving matching catalog campaigns.
=> Campaigns: Add caching for solving CatalogCampaigns (SHUUP-2929)

shuup/campaigns/admin_module/forms/_basket.py, shuup/campaigns/locale/en/LC_MESSAGES/django.po, shuup/campaigns/migrations/0001_initial.py, shuup/campaigns/models/campaigns.py, shuup/xtheme/locale/en/LC_MESSAGES/django.po, shuup/xtheme/plugins/social_media_links.py, shuup/xtheme/views/editor.py
Xtheme: Make more strings translatable
Set more strings translated in campaigns admin
Refs SHUUP-2921
=> Add missing translations

doc/changelog.rst, shuup/admin/modules/orders/views/refund.py, shuup/admin/templates/shuup/admin/orders/create_refund.jinja, shuup/core/models/_orders.py, shuup_tests/core/test_orders.py
Refund the applicable proportion of tax when creating a refund for a
line item by quantity or amount.
Refs SHUUP-2946
=> Fix tax handling for refunds (SHUUP-2946)

doc/getting_started.rst, doc/getting_started_dev.rst
* add requirement sections
* add short descriptions of all apps in core
* add wheel installation guide
* add links to base settings and urls
Refs SHUUP-2959
=> Update "Getting Started" pages in documentation (SHUUP-2959)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/modules/categories/form_parts.py, shuup/admin/modules/categories/forms.py, shuup/admin/modules/categories/views/edit.py, shuup/admin/modules/products/views/list.py, shuup/admin/templates/shuup/admin/categories/_edit_products_form.jinja, shuup_tests/admin/test_category_module.py
* Filter based on categories in products list view
* Manage category products from category edit view
=> Admin: Category management (SHUUP-2984, SHUUP-2982)

shuup/front/apps/simple_search/views.py
Search didn't match single words, fix this by adding simple matching
=> Improve search

shuup/admin/modules/contacts/views/detail.py
=> Add permission check to contact "New Order" Button (SHUUP-2997)

doc/api/shuup.core.suppliers.rst, doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/orders/views/detail.py, shuup/admin/templates/shuup/admin/orders/_refund_order_contents.jinja, shuup/admin/templates/shuup/admin/orders/create_shipment.jinja, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/core/models/_order_lines.py, shuup/core/models/_orders.py, shuup/core/models/_suppliers.py, shuup/core/suppliers/base.py, shuup/core/suppliers/enums.py, shuup/simple_supplier/migrations/0002_stockadjustment_type.py, shuup/simple_supplier/models.py, shuup/simple_supplier/module.py, shuup/simple_supplier/utils.py, shuup_tests/admin/test_refund_creator.py, shuup_tests/core/test_orders.py
- Fix payment and shipment dropdown visibility in Order admin
- Fix stock management refund issues
- Fix shipment creation issues for refunded orders
Refs SHUUP-2915, SHUUP-2917, SHUUP-2958
=> Fix refund restock and shipment issues (SHUUP-2915, SHUUP-2917, SHUUP-2958)

doc/changelog.rst, shuup/admin/modules/orders/views/edit.py
Prepopulate the tax number field on contact selection for admin orders.
Refs SHUUP-3028
=> Set tax number for admin orders (SHUUP-3028)

doc/changelog.rst, shuup/campaigns/admin_module/forms/__init__.py, shuup/campaigns/admin_module/forms/_basket_conditions.py, shuup/campaigns/admin_module/forms/_basket_effects.py, shuup/campaigns/apps.py, shuup/campaigns/locale/en/LC_MESSAGES/django.po, shuup/campaigns/migrations/0002_productsinbasketcondition_operator.py, shuup/campaigns/migrations/0003_category_products.py, shuup/campaigns/models/basket_conditions.py, shuup/campaigns/models/basket_line_effects.py, shuup/campaigns/models/campaigns.py, shuup/campaigns/utils.py, shuup_tests/campaigns/test_basket_category_products_campaigns.py, shuup_tests/campaigns/test_basket_product_conditions.py
* Add category products basket condition and line effect
* Optimize basket condition queries
* Optimize basket campaign matching queries
=> Category products discounts (SHUUP-3002)

shuup/admin/modules/orders/static_src/create/view/customers.js, shuup/admin/modules/orders/views/edit.py, shuup_tests/admin/test_order_creator.py
Fix admin order creator customer detail request for customers
belonging to one or more companies.
Refs SHUUP-3068
=> Admin: Fix customer detail for customers with company

shuup/admin/modules/orders/static_src/create/actions/index.js
Disable order review and confirm buttons until ajax calls are complete.
Refs SHUUP-3081
=> Prevent admin order creator duplicate submission (SHUUP-3081)

shuup/admin/base.py
=> Fix OrderSection `visible_for_object` call

doc/changelog.rst, shuup/admin/modules/orders/views/edit.py
=> Admin: Redirect to order detail on creation

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/templates/shuup/admin/orders/detail.jinja
=> Show customer comment in admin order detail (SHUUP-3107)

doc/changelog.rst, shuup/core/models/_orders.py, shuup_tests/core/test_orders.py
Update shipping status, if necessary, whenever refunds are created.
Refs SHUUP-3113
=> Core: Fix shipping status for orders with refunds (SHUUP-3113)

doc/changelog.rst, shuup/admin/templates/shuup/admin/orders/detail.jinja
Fix the customer, creator, and ordered by links on the order detail page
Refs SHUUP-3122
=> Admin: Fix links on order detail page (SHUUP-3122)

doc/changelog.rst, shuup/admin/__init__.py, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/modules/orders/sections.py, shuup/admin/templates/shuup/admin/orders/_order_shipments.jinja
=> Admin: Add list of shipments to order (SHUUP-2500)

doc/changelog.rst, shuup/admin/modules/contacts/views/list.py, shuup/admin/modules/users/views/list.py
=> Admin: Show newest contacts/users first (SHUUP-3059)

doc/changelog.rst, shuup/simple_supplier/admin_module/views.py
=> Admin: hide deleted products in stock management (SHUUP-3106)

doc/changelog.rst, shuup/admin/modules/orders/static_src/create/reducers/lines.js, shuup/admin/modules/orders/static_src/create/view/index.js, shuup/admin/modules/orders/static_src/create/view/lines.js, shuup/admin/modules/orders/views/edit.py, shuup/admin/views/select.py
Add a form to order creator UI to quickly add products based on product
name, SKU, or barcode.
Refs SHUUP-3046
=> Admin: Add product line quick add to order creator (SHUUP-3046)

doc/changelog.rst, shuup/admin/modules/orders/static_src/create/view/lines.js, shuup/admin/static_src/base/less/shuup/order-create.less
Add link to product detail page for product lines in order editor.
Refs SHUUP-2963
=> Admin: Add link to order line product detail page (SHUUP-2963)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/products/forms/package_forms.py, shuup/admin/static_src/base/less/shuup/product-package.less, shuup/admin/templates/shuup/admin/products/package/_package_children.jinja
* Show package products as a list group instead of table
* Show stock values in package product management
* Show orderability errors in package product management
=> Admin: Package product usability fixes (SHUUP-3079)

shuup/admin/templates/shuup/admin/categories/_edit_base_form.jinja, shuup/admin/templates/shuup/admin/categories/edit.jinja
Only resolve the category visibility url when viewing/editing pre-existing
categories.
No ref
=> Admin: Fix category visibility url resolution

doc/changelog.rst, shuup/front/apps/customer_information/forms.py, shuup/front/apps/customer_information/views.py, shuup/themes/classic_gray/locale/en/LC_MESSAGES/django.po, shuup/themes/classic_gray/templates/classic_gray/shuup/customer_information/edit_company.jinja, shuup/themes/classic_gray/templates/classic_gray/shuup/customer_information/edit_customer.jinja, shuup/themes/classic_gray/templates/classic_gray/shuup/customer_information/macros.jinja
* Enable copy between customer information addresses
* Use home country by default in customer information
* Set default address when creating company
=> Customer information usability fixes (SHUUP-3123)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/modules/orders/static_src/create/view/confirm.js, shuup/admin/modules/orders/views/edit.py, shuup/admin/templates/shuup/admin/orders/_order_contents.jinja
=> Admin: Show discount percentage in order detail view (SHUUP-3074)

doc/changelog.rst, shuup/admin/modules/orders/views/edit.py, shuup_tests/admin/test_order_creator.py
=> Admin: Fix bug when editing anonymous orders (SHUUP-3138)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/orders/json_order_creator.py, shuup/admin/modules/orders/static_src/create/index.js, shuup/admin/modules/orders/views/edit.py, shuup/testing/factories.py, shuup_tests/admin/test_order_creator.py, shuup_tests/functional/test_admin_orders.py, shuup_tests/functional/test_order_edit_with_coupons.py
Ensure the admin order creator validates addresses
Refs SHUUP-3155
=> Admin: Validate order addresses (SHUUP-3155)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/modules/orders/static_src/create/view/confirm.js, shuup/admin/modules/orders/views/edit.py
Also align numeric columns right
Refs SHUUP-3156
=> Admin: Show discounted unit price on confirm page

doc/changelog.rst, shuup/campaigns/models/product_effects.py, shuup_tests/campaigns/test_catalog_campaigns.py
Make sure that campaign discount amounts are applied for each product.
Refs SHUUP-3163
=> Campaigns: Fix bug with campaign discount amounts

doc/changelog.rst, shuup/core/utils/price_display.py, shuup_tests/core/test_price_display.py
=> Core: Add tax display mode parameter to `PriceDisplayFilter` (SHUUP-2974)

doc/changelog.rst, shuup/admin/modules/users/__init__.py, shuup/admin/modules/users/views/detail.py, shuup/admin/modules/users/views/permissions.py
*Limit change permissions only for superusers
* Fix error message in permission change form
=> Admin: Fix bug in change permission form (SHUUP-2943, SHUUP-3058)

doc/changelog.rst, shuup/front/apps/customer_information/__init__.py, shuup/front/apps/customer_information/notify_events.py, shuup/front/apps/customer_information/views.py, shuup/front/apps/registration/__init__.py, shuup/front/apps/registration/notify_events.py, shuup_tests/functional/test_notify_on_company_created.py
* Registration: Send notify event from user registration
* Customer information: Send notify event from company created
=> New notify events for front (SHUUP-3124)

shuup/themes/classic_gray/static_src/js/custom.js, shuup/themes/classic_gray/templates/classic_gray/shuup/front/basket/default_basket.jinja
Prevent multiple form submissions when deleting items from the customer basket.
Refs SHUUP-3057
=> Classic Gray Theme: Fix basket multi form submit (SHUUP-3057)

doc/changelog.rst, shuup/front/admin_module/__init__.py, shuup/front/admin_module/carts/views/_list.py, shuup/front/apps/saved_carts/__init__.py, shuup/front/apps/saved_carts/templates/shuup/saved_carts/cart_detail.jinja, shuup/front/apps/saved_carts/templates/shuup/saved_carts/cart_list.jinja, shuup/front/apps/saved_carts/urls.py, shuup/front/apps/saved_carts/views.py, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/themes/classic_gray/locale/en/LC_MESSAGES/django.po, shuup/themes/classic_gray/templates/classic_gray/shuup/front/basket/default_basket.jinja, shuup/themes/classic_gray/templates/classic_gray/shuup/front/includes/_navigation.jinja, shuup_tests/front/test_saved_carts.py, shuup_workbench/settings/base_settings.py
Add the ability for customers to save their cart.
* add save, view, delete cart views
* add view to all items in saved cart to current basket
=> Add ability to save cart for later (SHUUP-10)

doc/changelog.rst, shuup/admin/static_src/base/js/select.js, shuup/admin/views/select.py, shuup_tests/admin/test_select_view.py
=> Admin: Trim search criteria when using select2 (SHUUP-3144)

shuup/admin/modules/contacts/views/list.py, shuup/admin/modules/orders/views/list.py, shuup/admin/modules/users/views/list.py, shuup/front/admin_module/carts/views/_list.py
=> Admin: Translate picotable columns lazily

doc/changelog.rst, shuup/admin/templates/shuup/admin/orders/detail.jinja
=> Admin: Show account manager on order detail page (SHUUP-2977)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/modules/orders/json_order_creator.py, shuup/admin/modules/orders/static_src/create/view/customers.js
=> Admin: Add warning when editing order with no customer contact (SHUUP-3166)

shuup/core/utils/price_display.py, shuup_tests/core/test_price_display.py
=> Core: Fix changes to price display mode parameters

doc/changelog.rst, shuup/simple_supplier/__init__.py, shuup/simple_supplier/admin_module/__init__.py, shuup/simple_supplier/admin_module/views.py, shuup/simple_supplier/forms.py, shuup/simple_supplier/locale/en/LC_MESSAGES/django.po, shuup/simple_supplier/migrations/0003_stockcount_alert_limit.py, shuup/simple_supplier/models.py, shuup/simple_supplier/module.py, shuup/simple_supplier/notify_events.py, shuup/simple_supplier/templates/shuup/simple_supplier/admin/add_stock_form.jinja, shuup/simple_supplier/templates/shuup/simple_supplier/admin/stock_information.jinja, shuup/simple_supplier/utils.py, shuup_tests/simple_supplier/test_simple_supplier.py
Add a stock limit notification event when stock for a product falls below
the set limit.
Refs SHUUP-2862
=> Simple Supplier: Add stock limit notification event (SHUUP-2862)

shuup/simple_supplier/module.py
* Don't fetch the product unless needed
* Pass the product to alert limit reached event instead of product_id
Refs SHUUP-2862
=> Simple Supplier: Alert limit reached fixes (SHUUP-2862)

shuup/front/basket/update_methods.py
=> Front: Ensure basket line exists prior to deleting

shuup/front/apps/saved_carts/templates/shuup/saved_carts/cart_detail.jinja, shuup/front/apps/saved_carts/views.py
=> Front: Fix image and price display in saved carts

shuup/themes/classic_gray/static_src/less/classic-gray/basket.less, shuup/themes/classic_gray/templates/classic_gray/shuup/front/basket/default_basket.jinja
=> Classic gray: Style "Save Cart" button

doc/changelog.rst, shuup/admin/static_src/picotable/picotable.js
Call `refresh` directly and make `debounce` play nice with mithril
Refs SHUUP-3147
=> Admin: Fix picotable auto filtering (SHUUP-3147)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/orders/__init__.py, shuup/admin/modules/orders/views/__init__.py, shuup/admin/modules/orders/views/shipment.py, shuup/admin/templates/shuup/admin/orders/_order_shipments.jinja, shuup/core/models/__init__.py, shuup/core/models/_orders.py, shuup/core/models/_shipments.py, shuup/core/signals.py, shuup/simple_supplier/utils.py, shuup_tests/core/test_shipments.py, shuup_tests/functional/test_shipment_delete_with_simple_supplier.py
* Core: Enable soft delete for shipments
* Admin: Add option to delete shipments from order detail
=> Add option to delete shipments (SHUUP-3120)

doc/changelog.rst, shuup/admin/modules/contacts/sections.py, shuup/admin/modules/orders/views/edit.py, shuup/admin/modules/orders/views/list.py, shuup/admin/modules/products/sections.py, shuup/core/models/_orders.py
* Core: Exclude deleted orders from valid queryset
* Admin: Hide/exclude cancelled orders by default from lists
=> Admin: Hide/exclude cancelled orders by default from lists (SHUUP-2970)

doc/changelog.rst, doc/provides.rst, shuup/admin/__init__.py, shuup/admin/modules/orders/toolbar.py, shuup/admin/modules/orders/views/detail.py, shuup/admin/toolbar.py, shuup_tests/admin/test_order_detail_extensibility.py
* Add ``admin_order_toolbar_action_item`` provider for order toolbar
* Add deprecation warning for ``admin_order_toolbar_button`` usages
=> Admin: Update for order toolbar provide buttons (SHUUP-2544 / SHUUP-3204)

.travis.yml, doc/changelog.rst, shuup/testing/__init__.py, shuup/testing/browser_utils.py, shuup/testing/utils.py, shuup_tests/browser/admin/test_admin_section.py, shuup_tests/browser/front/test_checkout.py, shuup_tests/conftest.py, shuup_tests/front/test_checkout.py, tox.ini
Test checkout process in frontend
Test admin login and orders page load
Refs SHUUP-2698
=> Add simple browser tests (SHUUP-2698)

doc/changelog.rst, doc/provides.rst, shuup/admin/modules/contacts/views/detail.py, shuup/testing/__init__.py, shuup/testing/admin_module/toolbar.py, shuup_tests/admin/test_contact_extensibility.py
* Add ``admin_contact_toolbar_action_item`` provider
* Add deprecation warning for ``admin_contact_toolbar_button``
=> Admin: Add ``admin_contact_toolbar_action_item`` provider (SHUUP2544 / SHUUP-3205)

doc/changelog.rst, doc/provides.rst, shuup/admin/modules/products/views/toolbars.py, shuup/testing/__init__.py, shuup/testing/admin_module/toolbar.py, shuup/testing/utils.py, shuup_tests/browser/admin/test_product_detail.py, shuup_tests/browser/front/test_checkout.py
* Activate English in browser tests
* Add ``admin_product_toolbar_action_item`` provider
=> Admin: Add ``admin_product_toolbar_action_item`` provider (SHUUP-2544 / SHUUP-3206)

shuup/admin/modules/orders/views/shipment.py
User is able to set tracking codes and description when creating a shipment
=> Admin: set shipment tracking code and description

shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/contacts/views/edit.py
=> Add proper title to company creation (SHUUP-3222)

shuup/admin/modules/products/forms/base_forms.py, shuup/admin/templates/shuup/admin/products/edit.jinja, shuup_tests/browser/admin/test_product_detail.py
Show errors as messages and make default price a required field.
Refs SHUUP-3224
=> Admin: Fix product error handling (SHUUP-3224)

shuup_tests/campaigns/test_basket_campaigns.py
Add a test for category based basket discounts where two products from the
same category should trigger a discount for both products
=> Add test for category based discounts

doc/changelog.rst, shuup/core/telemetry.py, shuup_tests/core/test_telemetry.py
=> Send telemetry if no previous submission (SHUUP-3226)

shuup/admin/modules/contacts/views/edit.py
Fix is issue with contact editing title
Refs SHUUP-3233
=> Show addresses again in contact editing

shuup_tests/conftest.py
=> Disable telemetry on tests

doc/changelog.rst, shuup/front/basket/objects.py, shuup/front/checkout/confirm.py, shuup/front/checkout/empty.py, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/templates/shuup/front/base.jinja, shuup/front/templates/shuup/front/checkout/confirm.jinja, shuup/front/views/checkout.py, shuup_tests/campaigns/test_basket_category_products_campaigns.py, shuup_tests/campaigns/test_basket_product_conditions.py, shuup_tests/front/test_basket.py, shuup_tests/front/test_basket_commands.py, shuup_tests/front/test_checkout_flow.py
* exclude unorderable lines from basket
* check basket orderability on confirmation
* show non-field errors in front preferentially over errors
Refs SHUUP-3174
=> Front: Basket orderability checks (SHUUP-3174)

shuup/front/checkout/confirm.py
=> Fix issue with missing product ids (SHUUP-3248)

shuup/admin/modules/orders/static_src/create/view/customers.js, shuup/admin/modules/orders/static_src/create/view/lines.js, shuup/testing/browser_utils.py, shuup/testing/factories.py, shuup_tests/browser/admin/test_order_creator.py, shuup_tests/browser/admin/test_order_list.py, shuup_tests/browser/front/test_checkout.py
=> Admin: Add order creator browser tests (SHUUP-3120)

doc/changelog.rst, shuup/front/apps/auth/forms.py, shuup_tests/front/test_auth.py
=> Front: Fix password recovery form bug with invalid email

doc/changelog.rst, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/core/models/_orders.py, shuup_tests/core/test_orders.py, shuup_tests/core/test_shipments.py
Raise an exception when trying to create a shipment with insufficient
physical stock.
Refs SHUUP-3150
=> Core: Prevent shipping products with insufficient physical stock

shuup/testing/__init__.py, shuup/testing/templates/shuup_testing/highlight_plugin.jinja, shuup/testing/theme/__init__.py, shuup/testing/theme/plugins.py, shuup/xtheme/_theme.py, shuup/xtheme/layout.py, shuup/xtheme/plugins/_base.py, shuup/xtheme/views/editor.py, shuup/xtheme/views/forms.py, shuup_tests/xtheme/test_editor_forms.py, shuup_tests/xtheme/test_plugin_api.py
Plugins provided with `xtheme_plugin` provide spec are considered as global plugins.
Refs SHUUP-1806
=> Xtheme: Themes now own their own plugins (SHUUP-1806)

doc/changelog.rst, shuup/front/apps/simple_search/locale/en/LC_MESSAGES/django.po, shuup/front/apps/simple_search/templates/shuup/simple_search/search.jinja, shuup/front/apps/simple_search/views.py, shuup_tests/front/test_simple_search.py
Add tests for simple search, including tests for finding words and
normalizing spaces in search queries.
Refs SHUUP-2990
=> Front: Add tests for simple search

shuup/core/models/_service_base.py, shuup/front/basket/objects.py, shuup/front/template_helpers/general.py, shuup_tests/campaigns/test_catalog_campaign_admin.py
Based on the work @gurch101 made in PR #737 a bit tuned down version due the recent template changes.
Refs SHUUP-3038
=> Small performance fixes for front (SHUUP-3038)

shuup/front/apps/customer_information/__init__.py, shuup/front/apps/customer_information/forms.py, shuup/front/apps/customer_information/locale/fi_FI/LC_MESSAGES/django.po, shuup/front/apps/customer_information/views.py
* Remove fuzzy Finnish translations
* At forms change gettext_laxy to ugettext_lazy to make translations
in forms work properly
=> Customer information: Fix bugs in translations

shuup/reports/report.py
Add the possibility of passing `start_date` and `end_date` as key word arguments
to the report base class.
=> Report base QoL change

doc/index.rst, doc/templates.rst, doc/themes.rst
=> Add Theme and Macro documentation (SH-106)

shuup/admin/modules/product_types/views/edit.py, shuup/testing/admin_module/mocker_view.py, shuup/testing/factories.py
=> Fix slowness in Product Type creation (SH-73)

doc/changelog.rst, shuup/front/static_src/js/pagination.js, shuup/front/templates/shuup/front/base_ajax_content_only.jinja, shuup/front/templates/shuup/front/macros/category.jinja, shuup/front/templates/shuup/front/product/category.jinja
Fix category view paging and browser back/forward buttons.
Refs SH-40
I'd appreciate if someone with a windows PC can do a quick run through on IE :)
test:
go to category page
go to second category page
go to some other website (google.com)
press back/forward to make sure everything works.
=> Category view fixes (SH-40)

shuup/testing/browser_utils.py, shuup_tests/browser/admin/test_order_creator.py, shuup_tests/browser/admin/test_order_list.py, shuup_tests/browser/admin/test_picotable.py, shuup_tests/browser/admin/test_product_detail.py, shuup_tests/browser/front/test_checkout.py
Attempt to fix sporadic browser test failures by standardizing
how element clicking is done.
Refs SH-123
=> Fix browser test failures (SH-123)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/shops/views/edit.py, shuup/admin/static_src/base/js/select.js, shuup/themes/classic_gray/package.json, shuup_tests/admin/test_shop_edit.py
Rebased version of https://github.com/shuup/shuup/pull/764.
=> Admin: Make currency field a dropdown in Shops admin (SH-132)

doc/changelog.rst, shuup/campaigns/migrations/0004_logmodels.py, shuup/campaigns/models/campaigns.py, shuup/core/migrations/0006_logmodels.py, shuup/core/models/_addresses.py, shuup/core/models/_attributes.py, shuup/core/models/_contacts.py, shuup/core/models/_manufacturers.py, shuup/core/models/_order_lines.py, shuup/core/models/_payments.py, shuup/core/models/_product_media.py, shuup/core/models/_product_shops.py, shuup/core/models/_service_payment.py, shuup/core/models/_service_shipping.py, shuup/core/models/_shipments.py, shuup/core/models/_shops.py, shuup/core/models/_supplied_products.py, shuup/core/models/_suppliers.py, shuup/core/models/_taxes.py
=> Add log entries to core and campaigns (SH-133)

shuup/admin/modules/suppliers/__init__.py
=> Admin: Fix url bug in suppliers module

README.rst, doc/getting_started_dev.rst
=> Docs: Add links to contribution guide

shuup/testing/browser_utils.py, shuup_tests/browser/admin/test_order_creator.py
wait until customer info fields have refreshed before assertions.
Refs SH-89
=> Fix order creator browser test (SH-89)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/shops/views/edit.py, shuup/core/management/commands/shuup_init.py, shuup/core/migrations/0007_shop_languages_config.py, shuup/front/template_helpers/general.py, shuup/front/templates/shuup/front/macros/navigation.jinja, shuup/testing/factories.py, shuup_tests/admin/test_shop_edit.py
=> Allow shop languages to be set via admin (SH-189)

shuup/notify/static_src/script-editor.js
The old code does not work on Safari
=> Fix Notify editor script

shuup/core/formatters.py, shuup/core/models/_addresses.py, shuup/core/settings.py
A new spec is created to customize an address formatter
=> Core: create address formatter setting

shuup/importer/importing/importing.py, shuup/importer/importing/meta.py
=> Fix issues with importer

doc/changelog.rst, shuup/core/utils/formatters.py, shuup/regions/resources.py
* Regions: Fix bug in encoding
* Core: Do not render region twice in default address formatter
=> Fix for regions encoding and address formatting (SH-212 / SH-236 / SH-237)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/products/forms/base_forms.py
Raise proper validation error when trying to save product with duplicate SKU.
=> Admin: Add validation for duplicate product sku (SH-226)

doc/changelog.rst, shuup/front/static_src/less/front/footer.less, shuup/front/static_src/less/front/variables.less, shuup/front/templates/shuup/front/macros/footer.jinja
* Split footer to top and bottom
* Add placeholder for shop information in bottom footer
* Show powered by Shuup text in bottom footer
=> Front: Enhanced footer and powered by Shuup (SH-221)

shuup/admin/modules/services/views/_delete.py
=> Fix service delete success url

shuup/admin/static_src/base/js/main-menu.js, shuup/admin/static_src/base/less/shuup/base.less, shuup/admin/static_src/base/less/shuup/main-menu.less, shuup/admin/static_src/base/less/shuup/navigation.less, shuup/admin/static_src/dashboard/js/dashboard.js, shuup/admin/templates/shuup/admin/base/_main_menu.jinja
Admin menu had too many clicks to get to your location.
Now the menu is open all the time when on desktop size, mobile users
still have the possibility to toggle the menu.
Refs SH-218
=> Change Admin menu (SH-218)

shuup/admin/menu.py, shuup/admin/static_src/base/less/shuup/main-menu.less, shuup/admin/templates/shuup/admin/base/_main_menu.jinja
Add identifier for `_MenuCategory` class and use it as a target id instead of category name that is translated string.
=> Admin: Fix bug in opening menu

doc/changelog.rst, shuup/campaigns/models/campaigns.py, shuup/campaigns/models/catalog_filters.py, shuup/campaigns/models/matching.py, shuup_tests/campaigns/test_basket_campaigns.py, shuup_tests/campaigns/test_catalog_campaigns.py
* Avoid matching inactive filters and conditions
* Fix bug in product type catalog filter matching
=> Campaigns: Fix some matching issues (SH-330)

doc/changelog.rst, shuup/front/__init__.py, shuup/front/forms/product_list_modifiers.py, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/views/category.py, shuup_tests/browser/front/test_category_view.py
* Make first sort option default
* Enable sort by date created
=> Front: Make first sort option default and enable sort by date created (SH-284/ SH-347)

doc/changelog.rst, shuup/front/__init__.py, shuup/front/apps/simple_search/views.py, shuup/front/forms/product_list_modifiers.py, shuup/front/utils/sorts_and_filters.py, shuup/front/views/category.py, shuup_tests/browser/front/test_category_view.py
* Enable modyfying products queryset
* Enable option to filter with variation values
=> Front: Enable modifying prouduct lists queryset and filter with product variations (SH-284 / SH-346)

shuup/front/templates/shuup/front/macros/category.jinja, shuup/front/templates/shuup/front/product/category.jinja
Selectpickers were not working when product page content was loaded with ajax.
Move extrajs definition outside if...else and initialize selectpickers in category list js
no ref
=> Fix issue with selectpickers

.tx/config, doc/changelog.rst, doc/getting_started.rst, shuup/front/apps/recently_viewed_products/__init__.py, shuup/front/apps/recently_viewed_products/locale/en/LC_MESSAGES/django.po, shuup/front/apps/recently_viewed_products/plugins.py, shuup/front/apps/recently_viewed_products/static/shuup/recently_viewed_products/lib.js, shuup/front/apps/recently_viewed_products/templates/shuup/recently_viewed_products/list_view.jinja, shuup/front/static_src/less/front/product-list.less, shuup/front/templates/shuup/front/macros/category.jinja, shuup_tests/browser/front/test_recently_viewed_products.py, shuup_workbench/settings/base_settings.py
Show the five most recently viewed products by the customer.
Refs SH-396
=> Front: Add recently viewed products app (SH-396)

shuup/core/settings.py
=> Fix telemetry url (SH-301)

shuup/front/templates/shuup/front/checkout/_vertical_phases.jinja, shuup/front/templates/shuup/front/checkout/checkout_method.jinja, shuup/front/templates/shuup/front/checkout/register.jinja, shuup/front/templates/shuup/front/macros/checkout.jinja, shuup/regions/resources.py, shuup/testing/single_page_checkout_with_login_and_register_conf.py, shuup_tests/browser/front/test_checkout_with_login_and_register.py
* Testing: Define initial phase in checkout tests
* Front: Let the extended views define titles for checkout phases
* Front: Activate selectpickers in checkout method phase
* Front: Ensure separate id's for address divs
* Front: Enable regions JS for single page checkout
=> Front: Fix some bugs in single page checkout

doc/changelog.rst, shuup/front/apps/simple_search/templates/shuup/simple_search/search.jinja, shuup/front/static_src/less/front/product-list.less
Ensure product boxes on a given row are equal height
Refs SH-412
=> Fix search results list styles (SH-412)

doc/changelog.rst, shuup/addons/locale/it/LC_MESSAGES/django.po, shuup/admin/locale/it/LC_MESSAGES/django.po, shuup/admin/locale/it/LC_MESSAGES/djangojs.po, shuup/campaigns/locale/it/LC_MESSAGES/django.po, shuup/core/locale/it/LC_MESSAGES/django.po, shuup/customer_group_pricing/locale/it/LC_MESSAGES/django.po, shuup/default_importer/locale/it/LC_MESSAGES/django.po, shuup/default_reports/locale/it/LC_MESSAGES/django.po, shuup/default_tax/locale/it/LC_MESSAGES/django.po, shuup/front/apps/auth/locale/it/LC_MESSAGES/django.po, shuup/front/apps/customer_information/locale/it/LC_MESSAGES/django.po, shuup/front/apps/personal_order_history/locale/it/LC_MESSAGES/django.po, shuup/front/apps/recently_viewed_products/locale/it/LC_MESSAGES/django.po, shuup/front/apps/registration/locale/it/LC_MESSAGES/django.po, shuup/front/apps/simple_order_notification/locale/it/LC_MESSAGES/django.po, shuup/front/apps/simple_search/locale/it/LC_MESSAGES/django.po, shuup/front/locale/it/LC_MESSAGES/django.po, shuup/guide/locale/it/LC_MESSAGES/django.po, shuup/notify/locale/it/LC_MESSAGES/django.po, shuup/notify/locale/it/LC_MESSAGES/djangojs.po, shuup/order_printouts/locale/it/LC_MESSAGES/django.po, shuup/simple_cms/locale/it/LC_MESSAGES/django.po, shuup/simple_supplier/locale/it/LC_MESSAGES/django.po, shuup/testing/locale/it/LC_MESSAGES/django.po, shuup/themes/classic_gray/locale/it/LC_MESSAGES/django.po, shuup/utils/locale/it/LC_MESSAGES/django.po, shuup/xtheme/locale/it/LC_MESSAGES/django.po, shuup/xtheme/locale/it/LC_MESSAGES/djangojs.po, shuup_workbench/settings/base_settings.py
Thanks to Fabrizio Arzeni (@farzeni) for doing most of the job.
=> Add italian translations

shuup/front/__init__.py, shuup/front/forms/product_list_modifiers.py, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/static_src/less/front/product-list.less, shuup/front/templates/shuup/front/macros/category.jinja, shuup/front/templates/shuup/front/macros/general.jinja, shuup_tests/browser/front/test_category_view.py
* Show pagination details
* Show limit filter up top on category page
* Allow sort by oldest/newest first
Refs SH-399
=> Product filter fixes (SH-399)

shuup/admin/modules/products/mass_actions.py
=> Fix issue with unicode csv in mass action

shuup/front/apps/customer_information/templates/shuup/customer_information/macros/address.jinja, shuup/front/apps/customer_information/templates/shuup/customer_information/macros/buttons.jinja, shuup/front/apps/customer_information/templates/shuup/customer_information/macros/contact.jinja, shuup/front/apps/customer_information/templates/shuup/customer_information/macros/theme/address.jinja, shuup/front/apps/customer_information/templates/shuup/customer_information/macros/theme/buttons.jinja, shuup/front/apps/customer_information/templates/shuup/customer_information/macros/theme/contact.jinja, shuup/front/apps/personal_order_history/templates/shuup/personal_order_history/macros/order_detail.jinja
* Use checkout order detail view in personal order history
* Make customer info templates extensible
Refs PP-2
=> Front enhancements for personal order history and customer information apps (PP-2)

shuup/front/static_src/js/update_price.js, shuup/front/templates/shuup/front/product/detail_order_section_no_product.jinja, shuup/front/themes/views/_product_price.py, shuup_tests/front/test_product_price.py
check orderability every time the quantity or variation is updated.
Refs PP-48
=> Front: Update availability on product price update (PP-48)

shuup/campaigns/admin_module/views/_list.py
=> Fix issue with campaign list settings

shuup/front/templates/shuup/front/macros/category.jinja, shuup/front/templates/shuup/front/macros/product_information.jinja, shuup/front/templates/shuup/front/product/product_preview.jinja
Render product and category descriptions in markdown
Refs SH-126
=> Classic Gray: Render Product description in markdown (SH-126)

doc/changelog.rst, shuup/core/order_creator/_source.py
=> Front: Show validation errors as messages (SH-262)

shuup_workbench/settings/base_settings.py
Django countries was not in base_settings, add it there
Refs SH-319
=> Fix issue with country translations (SH-319)

doc/changelog.rst, shuup/core/models/_orders.py, shuup_tests/core/test_basic_order.py
If order was created from admin it might not
include any products and could not be set to completed.
Refs SH-310
=> Allow mark order without products completed (SH-310)

shuup/core/models/_units.py, shuup_tests/core/test_sales_unit.py
=> Core: Ensure string is returned for sales unit str

doc/changelog.rst, shuup/admin/static_src/picotable/picotable.js
Use a javascript datepicker since input type="date" isn't widely supported.
Refs SH-103
=> Admin: Fix picotable datepickers (SH-103)

shuup/admin/static_src/base/less/shuup/main-menu.less
=> Admin: Make menu fixed instead of absolute

shuup/admin/modules/shops/forms.py, shuup_tests/admin/test_wizard.py
revert code removal - this ensures that shop.name is set when using the wizard
=> Admin: Ensure shop name is set through wizard

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/modules/orders/static_src/create/actions/index.js, shuup/admin/modules/orders/static_src/create/reducers/lines.js, shuup/admin/modules/orders/static_src/create/reducers/order.js, shuup/admin/modules/orders/static_src/create/reducers/quickAdd.js, shuup/admin/modules/orders/static_src/create/view/customers.js, shuup/admin/modules/orders/static_src/create/view/lines.js, shuup/admin/modules/orders/static_src/create/view/methods.js, shuup/admin/modules/orders/static_src/create/view/utils.js, shuup/admin/static_src/base/less/shuup/order-create.less, shuup_tests/browser/admin/test_order_creator.py
* Add select2 for customer search.
* Improve quick adder usability by allowing product addition by clicking
or pressing enter
* Add help text to every field
Refs SH-447
=> Admin: order ui enhancements (SH-447)

shuup/admin/__init__.py, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/orders/sections.py, shuup/admin/static_src/base/less/shuup/base.less, shuup/admin/static_src/base/less/shuup/custom-forms.less, shuup/admin/templates/shuup/admin/orders/_admin_comment.jinja, shuup/admin/templates/shuup/admin/orders/_admin_comment_extra_js.jinja, shuup/admin/templates/shuup/admin/orders/_detail_payments.jinja, shuup/admin/templates/shuup/admin/orders/_order_contents.jinja, shuup/admin/templates/shuup/admin/orders/_order_log_entries.jinja, shuup/admin/templates/shuup/admin/orders/_order_log_entries_extra_js.jinja, shuup/admin/templates/shuup/admin/orders/_order_shipments.jinja, shuup/admin/templates/shuup/admin/orders/detail.jinja, shuup/order_printouts/templates/shuup/order_printouts/admin/section.jinja, shuup_tests/browser/admin/test_order_creator.py
* Show address and order contents in the detail section.
* Make UI for shipping/payment sections consistent.
* Add success message when adding comments or log entries.
* Align textarea buttons left
Refs SH-461
=> Admin: Order detail page UI updates (SH-461)

shuup_tests/core/test_telemetry.py
Stub out the `content` property for the mock telemetry response.
=> Testing: Fix telemetry test

doc/changelog.rst, shuup/core/telemetry.py, shuup_tests/core/test_telemetry.py
We need to be able to ensure the instances in
cloud are truly active.
Refs SH-460
=> Send admin user email and last login in telemetry

shuup/front/templates/shuup/front/macros/product.jinja, shuup/front/templates/shuup/front/product/detail.jinja
Add description and og:description metadata to product
detail page.
Refs SH-440
=> Front: Add product description metadata (SH-440)

shuup/admin/static_src/base/js/tour.js, shuup/admin/templates/shuup/admin/base/_navigation.jinja
=> Admin: Show tour link for every page (SH-430)

shuup/front/static_src/less/front/base.less, shuup/front/templates/shuup/front/base.jinja
=> Front: Add margin when admin tools are visible (SH-365)

shuup/admin/modules/orders/views/status.py
=> Order Status: Don't throw 500 if identifier exists

shuup/admin/utils/bs3_renderers.py
=> Admin: Fix help text when shown with errors (SH-445)

shuup/xtheme/locale/en/LC_MESSAGES/django.po, shuup/xtheme/static_src/admin/css/style.less, shuup/xtheme/templates/shuup/xtheme/admin/config_detail.jinja, shuup/xtheme/templates/shuup/xtheme/admin/macros.jinja
Xtheme admin: Fix screenshot styles
Xtheme Admin: Don't allow guide if theme not active
Refs SH-466, SH-449
=> Xtheme Admin: Fix theme guide and screenshot styles (SH-466, SH-449)

shuup/xtheme/templates/shuup/xtheme/admin/wizard.jinja
=> Xtheme: Fix wizard theme selection

shuup/xtheme/static_src/admin/css/style.less
=> Xtheme: Fix screenshot styles (SH-449)

doc/changelog.rst, shuup/simple_supplier/forms.py, shuup/simple_supplier/models.py, shuup_tests/simple_supplier/test_simple_supplier.py
Use shop price properties when in single shop mode
Refs SH-477
=> Simple Supplier: Use shop price properties (SH-477)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/orders/views/refund.py, shuup/admin/templates/shuup/admin/orders/create_full_refund.jinja, shuup/admin/templates/shuup/admin/orders/create_refund.jinja, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/core/models/_order_lines.py, shuup/core/models/_orders.py, shuup_tests/browser/admin/test_refunds.py, shuup_tests/functional/test_refunds.py
* Show line text for refund line picker
* Fix ability to add more than one refund row at a time
* Allow refunding by arbitrary amount
* Allow refund amount/quantity to be editable
Refs SH-454/SH-455
=> Admin: Misc refund fixes (SH-454/SH-455)

shuup/admin/modules/service_providers/forms.py, shuup/admin/modules/service_providers/views/_wizard.py, shuup/admin/templates/shuup/admin/service_providers/wizard_macros.jinja, shuup/admin/templates/shuup/admin/shops/_wizard_base_shop_script.jinja
Add the ability to restrict services by country since certain
services are only functional in certain countries.
Refs SH-478
=> Admin: Restrict wizard services by country (SH-478)

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/service_providers/views/_wizard.py, shuup/admin/static_src/base/js/form-utils.js, shuup/admin/static_src/wizard/js/wizard.js, shuup/admin/templates/shuup/admin/wizard/wizard.jinja
* Prevent the wizard from being skipped
* Ensure at least one payment method/shipping method is
activated
Refs SH-493
=> Admin: Make wizard mandatory (SH-493)

shuup/front/apps/carousel/templates/shuup/carousel/admin/edit.jinja
Activate select2 properly when adding new slides.
No ref
=> Carousel: Fix select2 when adding new slides

shuup/core/models/_currencies.py
should solve #974 , though i don't know possible implications
=> Fix wrong ISO-4217 validation

doc/changelog.rst, shuup/admin/views/select.py, shuup/campaigns/apps.py, shuup/campaigns/locale/en/LC_MESSAGES/django.po, shuup/campaigns/models/campaigns.py, shuup/campaigns/reports.py, shuup/default_reports/apps.py, shuup/default_reports/forms.py, shuup/default_reports/locale/en/LC_MESSAGES/django.po, shuup/default_reports/reports/__init__.py, shuup/default_reports/reports/customer_sales.py, shuup/default_reports/reports/new_customers.py, shuup/default_reports/reports/product_total_sales.py, shuup/default_reports/reports/refunds.py, shuup/default_reports/reports/shipping.py, shuup/default_reports/reports/taxes.py, shuup/default_reports/reports/total_sales.py, shuup/testing/factories.py, shuup_tests/campaigns/test_reports.py, shuup_tests/default_reports/test_default_reports.py, shuup_tests/reports/test_reports.py
- Create product total sales report
- Create new costumers report
- Total sales show customer average sales
- Create customer sales
- Create taxes report
- Create shipping report
- Create refunds reports
- Create coupons usage report
- Improve Select2Multiple search by custom fields 
Refs SH-504
=> Reports: create new reports (SH-504)

shuup/addons/admin_module/views/upload.py, shuup/apps/settings.py
* Fix an import issue affecting server reloading
* Replace zip support with wheel support
* Avoid renaming wheel files as is prevents them from installing
Ref: MAR-19
=> Add Wheel support for add-ons

shuup/admin/npm-shrinkwrap.json, shuup/admin/package.json, shuup/front/npm-shrinkwrap.json, shuup/front/package.json, shuup/themes/classic_gray/package.json, shuup/xtheme/npm-shrinkwrap.json, shuup/xtheme/package.json
This might be needed for compatibility reasons with Node 7 (The project still have issues with NPM 4)
=> Update to the latest version of gulp

shuup/core/utils/price_display.py
Reported by someone on Gitter a few hours ago.
=> Fix AttributeError on context_cache

shuup/core/migrations/0020_md_to_html.py
Significantly reduces the memory usage of Markdown parser by calling md.reset() in every iteration when using the same instance of Markdown. This also provides huge speed boost when run against database which has existing rows.
=> Optimize markdown conversion

shuup/admin/templates/shuup/admin/orders/detail.jinja, shuup/core/models/_orders.py
This information will help when processing order or just checking order information.
=> Add payment method and shipping method information to order detail template

doc/changelog.rst, shuup/admin/forms/widgets.py, shuup/admin/modules/products/views/list.py, shuup/admin/static_src/base/js/browse-widget.js, shuup/admin/static_src/picotable/picotable.js
* Hide mass actions from choice widgets
* Make product choice widget work
=> Admin: Fix issues with shop products list view (SH-528, SH-535)

shuup/front/apps/auth/__init__.py, shuup/front/apps/auth/api.py, shuup_tests/api/test_front_users_api.py
* Add API to send password reset email
* Add API to reset password with valid token
=> Add password reset APIs

shuup/core/api/basket.py, shuup/testing/factories.py, shuup_tests/api/test_basket_api.py
* Remove front middleware dependency
* Add ability to create order from basket
=> Update basket APIs

shuup/front/api/products.py, shuup_tests/api/test_front_products_api.py
* Make sure that all variation information available
at the response.
* The child product data is stil serialized with normal
product serializer
=> Front API: Fix for the product variations

doc/changelog.rst, shuup/core/api/basket.py, shuup_tests/api/test_basket_api.py
- Add method to set shipping address on basket
- Saving basket when adding coupon codes
- Add decorator with the serializer on `update_quantity` method to generate docs correctly
=> API: add set address method on basket endpoint

shuup/core/api/basket.py, shuup/core/basket/objects.py, shuup_tests/api/test_basket_api.py
When using DatabaseStorage the shipping and billing addresses were not saved anywhere.
=> Fix basket to save shipping and billing address

shuup/api/mixins.py, shuup/core/api/__init__.py
Log basket API POST requests if drf-tracking is installed.
Refs TREES-67
=> Add basket API logging

doc/changelog.rst, shuup/front/api/__init__.py, shuup/front/api/products.py, shuup_tests/api/test_front_products_api.py
The original products endpoint was renamed to shop_products
=> Create endpoint to return simple products

shuup/front/api/products.py, shuup_tests/api/test_front_products_api.py
- Removed distance location from shop_product
- Added shop filter on shop_product
=> Try to make queries somewhat faster

doc/changelog.rst, shuup/front/apps/personal_order_history/locale/en/LC_MESSAGES/django.po, shuup/front/apps/personal_order_history/templates/shuup/personal_order_history/macros/buttons.jinja, shuup/front/apps/personal_order_history/templates/shuup/personal_order_history/order_detail.jinja, shuup/front/apps/personal_order_history/urls.py, shuup/front/apps/personal_order_history/views.py, shuup_tests/admin/test_sales_dashboard_module.py
It's now possible to add old order to basket
=> Front: Reorder old order

shuup/admin/modules/sales_dashboard/dashboard.py, shuup/core/models/_orders.py, shuup/utils/dates.py, shuup_tests/admin/test_sales_dashboard_module.py
* Admin Dashboard: Fix timezone handling in shop overview block
* Fix timezone handling of OrderQuerySet.since
* shuup.utils.dates: Add to_aware and local_now
=> Fix timezone handling in couple places

shuup/front/api/products.py
Add more prefetching and serialize and fetch
variation children in bulk.
=> Improve shop product list API performance

shuup/admin/modules/products/mass_actions.py
ids are now ShopProduct ids and not regular product ids because of [323c274](https://github.com/shuup/shuup/commit/323c274). Adds some custom logic which will be used to strip column id so that it can be used with getattr function. Some columns are ShopProduct fields and some Product fields.
=> Fix product csv export mass action

shuup/core/api/basket.py, shuup/core/basket/objects.py, shuup_tests/api/test_basket_api.py
=> Added shipping/billing address methods on basket (TREES-406)

shuup/core/utils/db.py
=> Add wrapper to parse values to float in SQLite (TREES-359)

shuup/admin/modules/settings/consts.py, shuup/admin/modules/settings/forms/system.py, shuup/admin/modules/settings/views/system.py, shuup/admin/templates/shuup/admin/settings/edit.jinja, shuup/admin/templates/shuup/admin/settings/form_parts/settings_base.jinja, shuup/core/templatetags/shuup_common.py, shuup/front/apps/registration/__init__.py, shuup/front/apps/registration/forms.py, shuup/front/apps/registration/notify_events.py, shuup/front/apps/registration/templates/shuup/registration/company_register.jinja, shuup/front/apps/registration/templates/shuup/registration/register.jinja, shuup/front/apps/registration/urls.py, shuup/front/apps/registration/views.py, shuup/notify/base.py, shuup_tests/admin/test_settings.py, shuup_tests/admin/test_shop_edit.py, shuup_tests/front/test_registration.py
Continue Janne's work on company registration feature.
Enable companies to register in Shuup. Company is inactive by default, can be activated by admin.
=> Company registration

shuup/core/templatetags/shuup_common.py, shuup/front/apps/registration/templates/shuup/registration/register.jinja, shuup_tests/core/test_template_tags.py
Pick the fix from PR #1089 and add test cases to prove it's now working.
=> Fix get_shop_configuration template tag

shuup/core/api/basket.py, shuup_tests/api/test_basket_api.py
All contacts should have option to create, update or retrieve their own basket.
Staff member should only be ably to crate update or retrieve basket that belogns to the shop the staff member is linked to.
=> API: Fix basket API extra checks for customer permission

doc/changelog.rst, shuup/core/api/__init__.py, shuup/core/api/front_passwords.py, shuup/core/utils/forms.py, shuup/front/apps/auth/forms.py, shuup/front/apps/auth/views.py, shuup_tests/api/test_front_passwords.py, shuup_tests/api/test_front_users_api.py, shuup_tests/front/test_auth.py
* Add option to reset password for authenticated users
* Add opiton to reset password with token
* Move `PasswordRecoveryForm` under core since it is used from multiple places.
=> API: Add option to reset passwords

doc/changelog.rst, shuup/campaigns/admin_module/forms/_basket_effects.py, shuup/campaigns/migrations/0008_freeproductline_quantity_to_quantityfield.py, shuup/campaigns/models/basket_line_effects.py, shuup/core/models/_product_shops.py
Change FreeProductLine basket line effects quantity field
to QuantityField type because product units can have decimal
values. Add validation to FreeProductLine quantity field
so that quantity must be divisible with the product unit
step.
=> Change FreeProductLine quantity field type to QuantityField

shuup/default_reports/reports/taxes.py, shuup/testing/factories.py, shuup_tests/default_reports/test_default_reports.py
Extend default tax report to include following information:
* Total pretax amount
* total tax amount
* total
=> Extend default tax report

shuup/core/api/front_products.py
Some could extend and override the front shop product serializer completely
=> API: enable custom front shop product serializer

doc/changelog.rst, shuup/front/basket/__init__.py, shuup/front/checkout/_process.py, shuup/front/checkout/_storage.py, shuup/front/checkout/_view_mixin.py, shuup/front/checkout/methods.py, shuup/front/templates/shuup/front/checkout/_horizontal_phases.jinja, shuup/front/views/checkout.py, shuup_tests/front/test_checkout.py, shuup_tests/front/test_methods_phase.py
See the commit messages for details.
=> Checkout process fixes and improvements

doc/changelog.rst, shuup/core/basket/commands.py, shuup_tests/api/test_basket_api.py, shuup_tests/front/test_basket_commands.py
Adding variation parent in the basket shouldn't be possible.
=> Core: do not allow adding variation parents in basket

.travis.yml, _misc/sanity_utils.py, doc/howto/getting_started_dev.rst, shuup_tests/browser/admin/test_order_creator.py, shuup_tests/browser/admin/test_order_detail.py, shuup_tests/browser/admin/test_picotable.py, shuup_tests/browser/admin/test_product_create.py, shuup_tests/browser/admin/test_product_detail.py, shuup_tests/browser/admin/test_refunds.py, shuup_tests/browser/front/test_category_view.py, shuup_tests/browser/front/test_checkout_with_login_and_register.py, shuup_tests/browser/front/test_recently_viewed_products.py, shuup_tests/browser/notify/test_script_template.py, tox.ini
* Update all related packages
* Run admin and front tests in separate builds to prevent
build time to rise
* Do not run notify tests with Travis since not business
critical
* Split few tests to avoid individual tests take too much
time. This caused issues with Travis.
There are some problem spots which get fixed with some extra
waiting. Also it seems to be good practice to initialize
database before initializing tests, otherwise there might
be some random database locks happening.
=> Enable browser tests

doc/changelog.rst, shuup/core/api/orders.py, shuup/core/api/refunds.py, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/core/models/_orders.py, shuup_tests/api/test_refunds.py
As a side effect this creates created by option for full refund which was missing and I think needed.
=> Add refunds to the order API

shuup/admin/forms/fields.py, shuup/admin/static_src/base/js/select.js, shuup/admin/views/select.py, shuup_tests/admin/test_select_view.py
Add option for select2 multiselect for only normal and parent products.
=> Admin: Add form field for main products

shuup/reports/utils.py
=> Fix report timezones

shuup/core/api/basket.py, shuup/core/basket/objects.py, shuup_tests/api/test_basket_api.py
This is not the right to do this. A custom order source module should be the right feature.
=> Remove custom product price when adding to basket

shuup/simple_supplier/module.py, shuup_tests/functional/test_simple_supplier_out_of_stock.py
=> Fix simple supplier

shuup/default_tax/module.py, shuup_tests/default_tax/test_default_tax.py
=> Filter out tax rules that have disabled taxes

shuup/core/basket/objects.py, shuup_tests/core/test_basket.py
=> Core: do not cache basket info if product doesn't exist

shuup/admin/modules/categories/forms.py, shuup/admin/modules/categories/views/edit.py, shuup/admin/modules/categories/views/list.py, shuup/testing/factories.py, shuup_tests/xtheme/test_plugins.py
Do set shops attributes for categories after save as that will remove all shops already set before.
Filter categories for the current shop in categories edit view
No Refs
=> Admin: fix category form and view

shuup/core/api/front_products.py, shuup_tests/api/test_front_products_api.py
=> API: return product taxful and taxless base price

doc/changelog.rst, shuup/core/order_creator/_source.py, shuup/testing/factories.py, shuup_tests/api/test_basket_packages.py
Consider the number of packages when calculating the total quantity of products
No Refs
=> Core: fix order source line product quantities with packages

shuup/admin/forms/widgets.py, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/static_src/base/js/popover.js, shuup/admin/static_src/base/js/quick_add_related_objects.js, shuup/admin/static_src/base/less/shuup/picotable.less, shuup/admin/static_src/picotable/picotable.js
Fix issue where using touch devices, the quick add button required a lot of taps.
Fix issue where Picotable's "results per page" selector acted wonky on small screen sizes.
No Ref
=> Admin: Fix issue with quick add and picotable page select

doc/changelog.rst, shuup/core/api/refunds.py, shuup/core/excs.py, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/core/models/_orders.py, shuup_tests/api/test_refunds.py, shuup_tests/core/test_orders.py
This prevents creating infinite partial refunds for a single order line.
No Refs
=> Refund: check the max refundable items when doing partial refunds

shuup/admin/modules/contacts/form_parts.py
the `request` was not sent to the `CompanyContactBaseForm` which caused errors.
=> Admin: Fix issue with contact forms

shuup/front/utils/sorts_and_filters.py
This commit solves the problem where category filters were shown on front even if there were no options available.
=> Hide empty product list filters

shuup/front/apps/customer_information/views.py, shuup/regions/resources.py
* Fix region select for address edit
* Make allow company contact linkage per shop feature
=> Front: Fix issues with the customer information

doc/changelog.rst, shuup/admin/static_src/picotable/picotable.js, shuup/admin/utils/picotable.py
It is possible to invoke JavaScript callbacks through mass actions.
Add new mass action function to return extra action info to be rendered in the Html option element as data attributes
=> Admin: add JavaScript Mass Action type

shuup/admin/static_src/base/js/quick_add_related_objects.js
The function can be used by modules and plugins to setup the quick add as needed
=> Admin: expose quick add setup function to the world

doc/changelog.rst, shuup/core/basket/objects.py, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/front/__init__.py, shuup/front/admin_module/checkout/form_parts.py, shuup/front/apps/carousel/locale/en/LC_MESSAGES/django.po, shuup/front/basket/objects.py, shuup/front/checkout/methods.py, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/templates/shuup/front/admin/checkout.jinja, shuup/front/templates/shuup/front/checkout/confirm.jinja, shuup/front/templates/shuup/front/macros/checkout.jinja, shuup/front/templates/shuup/front/macros/order.jinja
- Core: move basket validation errors for methods to another function
- Front: add shop option to require payment and shipping methods on checkout
- Front: improve feedback messages in checkout phases
- Update translation strings for Core and Front apps
=> Checkout improvements

shuup/admin/modules/sales_dashboard/dashboard.py
Small was... well, too small and caused scrolling
=> Dashboard: Make recent orders medium

doc/changelog.rst, setup.py, shuup/importer/admin_module/forms.py, shuup/importer/admin_module/import_views.py, shuup_tests/importer/test_admin.py
Allow staff member only to select shops he or she is linked to. Also select supplier based on the currently selected shop. Pretty sure this supplier is only used for the note at the template.
=> Importer: Add multi shop support

shuup/admin/static_src/base/js/tour.js
Tour pretty much broke in a situations where custom admin implements a new menu
=> Admin: Make tour steps more dynamic

shuup/admin/static_src/base/js/tour.js, shuup/admin/template_helpers/shuup_admin.py, shuup/admin/templates/shuup/admin/base.jinja, shuup/admin/templates/shuup/admin/products/edit.jinja
* Make tour aware of URL it works in
* Admin: Product edit tour now more dynamic
=> Tour tuning

doc/changelog.rst, shuup/core/basket/objects.py, shuup/front/basket/objects.py, shuup_tests/core/test_basket.py
Make it possible to use a shop in the basket different from the request shop
=> Core: enable creating basket with a custom shop

doc/changelog.rst, shuup/admin/modules/media/views.py, shuup/front/template_helpers/general.py, shuup/utils/mptt.py
Fix already sent to https://github.com/django-mptt/django-mptt/pull/657
=> Front: add custom method to cache MPTT child nodes

shuup/admin/utils/picotable.py, shuup/gdpr/models.py, shuup/tasks/admin_module/views/list.py, shuup/tasks/locale/en/LC_MESSAGES/django.po, shuup/tasks/locale/fi_FI/LC_MESSAGES/django.po, shuup/tasks/templates/shuup/admin/tasks/task_edit.jinja, shuup_tests/admin/test_picotable.py
Admin: Ensure the default value has been selected
* In Picotable, if there was no default given, the filter dropdowns had no content. This commit adds the default value there selected by default.
Tasks: Add link to the task comment author
=> Admin: Ensure the default value has been selected 

shuup/gdpr/utils.py, shuup_tests/gdpr/test_admin_module.py, shuup_tests/gdpr/test_front_views.py
=> GDPR: Fix consent in different languages

shuup/admin/utils/picotable.py
Fixed the picotable values bug.
=> Admin: Fixed the picotable values

doc/changelog.rst, doc/ref/provides.rst, shuup/apps/provides.py, shuup_tests/core/test_provides.py
=> Core: fix typo on settings name

MANIFEST.in, shuup/importer/admin_module/import_views.py, shuup/importer/locale/en/LC_MESSAGES/django.po, shuup/testing/__init__.py, shuup/testing/importers.py, shuup_tests/importer/test_admin.py
Return 404 when the file content is None or doesn't exist
Refs POS-2494
=> Importer: add importer sample files extensions to MANINFEST

shuup/admin/modules/orders/views/list.py, shuup/admin/utils/picotable.py, shuup_tests/browser/admin/test_order_list.py
Picotable: Make option texts titled
replaces PR #1343 which was in Travis Limbo™
=> Admin: Make orderlist show everything by default

setup.py, shuup/testing/image_generator.py
After updating to new Pillow release, there are lot of tests failed. This pull request fixes it.
=> Pillow 5.2 upgrade fixes

README.rst, doc/conf.py, doc/howto/getting_started.rst, doc/howto/getting_started_dev.rst
* Readme: Add section for installation guide
* Readme: Add simplified roadmap
* Docs: Update copyright year
* Docs: Add installation instructions for Windows
=> Update readme and docs

doc/changelog.rst, shuup/front/templates/shuup/front/macros/order.jinja, shuup/order_printouts/templates/shuup/order_printouts/admin/order_base.jinja, shuup_tests/order_printouts/test_printouts.py
Check whether the addresses are valid before calling methods.
Refs POS-2501
=> Bug fix: fix order printouts template

shuup/admin/static_src/base/js/editor.js, shuup/xtheme/templates/shuup/xtheme/editor.jinja
This feature may cause the entire server to hang up
=> Summernote: Prevent drag n Drop of images

shuup/front/apps/auth/templates/shuup/user/login.jinja, shuup/front/settings.py, shuup/front/template_helpers/general.py, shuup/front/templates/shuup/front/base.jinja, shuup/front/templates/shuup/front/checkout/_horizontal_phases.jinja, shuup/front/templates/shuup/front/checkout/_vertical_phases.jinja, shuup/front/templates/shuup/front/macros/navigation.jinja, shuup_tests/browser/front/test_checkout_with_login_and_register.py, shuup_tests/front/test_general_template_helpers.py
Title says pretty much everything, added tests as well.
Refs POS-2444
=> GDPR: Added checkbox and removed the dropdown from the login page

shuup/order_printouts/templates/shuup/order_printouts/admin/macros.jinja, shuup/order_printouts/templates/shuup/order_printouts/admin/order_base.jinja
=> Add tracking codes to printouts and fix html printout styling

doc/changelog.rst, shuup/core/basket/objects.py, shuup/front/checkout/methods.py, shuup_tests/browser/front/test_checkout.py, shuup_tests/front/test_checkout_flow.py
There is some cases where the payment or shipping method
can be deleted and basket could contain invalid PKs.
This prevents errors from being raised.
Refs POS-2504
=> Core: Fix issues with disappearing services

shuup/front/apps/carousel/migrations/0003_add_shops.py
Refs https://github.com/shuup/shuup/issues/1396
=> Fix migration issue with Django 1.8

shuup/admin/utils/picotable.py, shuup_tests/admin/test_picotable.py
**Missing tests. Do not merge.**
=> Admin: Fix issue with picotable default ordering

shuup/admin/npm-shrinkwrap.json, shuup/front/npm-shrinkwrap.json, shuup/gdpr/npm-shrinkwrap.json, shuup/notify/npm-shrinkwrap.json, shuup/regions/npm-shrinkwrap.json, shuup/themes/classic_gray/npm-shrinkwrap.json, shuup/xtheme/npm-shrinkwrap.json
Run with node v8.11.3 and npm 6.3.0.
=> Update npm-shrinkwrap files

doc/changelog.rst, shuup/front/static_src/js/carousel.js, shuup/front/static_src/less/front/carousel.less, shuup/front/static_src/less/front/product-card.less, shuup/front/static_src/less/front/product-list.less, shuup/front/templates/shuup/front/macros/product.jinja, shuup/themes/classic_gray/templates/classic_gray/shuup/xtheme/plugins/cross_sells_plugin.jinja, shuup/themes/classic_gray/templates/classic_gray/shuup/xtheme/plugins/highlight_plugin.jinja
Improve products card styles to make them align nicely and add carousel for xtheme plugins
Refs POS-2543
=> Classic gray: improve products card styles add carousel in xtheme plugins

doc/changelog.rst, shuup/gdpr/serializers.py, shuup_tests/gdpr/test_data_download.py
=> GDPR: Fix user info serializer to consider the correct document consent

doc/changelog.rst, shuup/admin/__init__.py, shuup/admin/menu.py, shuup/admin/modules/orders/__init__.py, shuup/admin/modules/products/__init__.py, shuup/admin/modules/settings/__init__.py, shuup/front/build_resources.js, shuup/front/static_src/less/style.css, shuup/importer/admin_module/__init__.py, shuup/themes/classic_gray/static_src/blue/style.css, shuup/themes/classic_gray/static_src/pink/style.css, shuup_tests/browser/admin/test_picotable.py
- Admin: split OrderStatus admin module from Order admin module
- Admin: hide menu categories that don't have entries
- Fix Parcel style files extension
- Admin: add required permissions for missing modules
=> General fixes

shuup/xtheme/admin_module/views/_snippet.py
=> Xtheme: bump cache when snippet is deleted

.travis.yml, shuup_tests/browser/front/test_gdpr_consent.py, shuup_tests/browser/front/test_xtheme_edit.py, shuup_workbench/test_settings.py, tox.ini
Refs https://github.com/shuup/shuup/issues/1456
=> Update browser test dependencies

shuup/admin/menu.py
=> Admin: hide menu entries that don't have children

doc/changelog.rst, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/suppliers/views/edit.py, shuup/core/models/_orders.py, shuup_tests/core/test_orders.py
=> Core: prevent adjusting stocks on refund when supplier doesn't manage stocks

doc/changelog.rst, shuup/default_importer/importers/product.py, shuup/importer/importing/importing.py, shuup_tests/importer/test_product_import.py
Add the current shop relation in manufacturer and categories
Refs POS-2571
=> Importer: fix product importer adding shop relation correctly

doc/changelog.rst, shuup/front/template_helpers/general.py, shuup/xtheme/plugins/category_links.py, shuup/xtheme/plugins/products.py
Add option to filter orderable or discounted products for
category plugin.
=> Xtheme: Add option to filter products for category plugin

shuup/xtheme/static_src/editor/editor.js, shuup/xtheme/static_src/injection/editor-injection.js, shuup/xtheme/templates/shuup/xtheme/_editor_cell.jinja, shuup/xtheme/views/editor.py, shuup_tests/browser/front/test_xtheme_edit.py
User is now asked whether to save the plugin before publishing when there is pending changes in the form.
Refs POS-2565
=> Xtheme: ask to save the plugin when publishing with changes

.travis.yml, shuup/front/apps/carousel/migrations/0004_custom_colors.py, shuup_tests/core/test_migrations.py, tox.ini
Split Travis build into Development and Deploy
Development are a small set of tests that can be used to accept and merge pull requests
Deploy contains all the other tests for all other platforms and environments that Shuup supports and is only run when a PR is merged
No Refs
=> Improve Travis build jobs

shuup/xtheme/layout/_base.py, shuup/xtheme/locale/en/LC_MESSAGES/django.po, shuup/xtheme/rendering.py, shuup/xtheme/static_src/editor/editor.less, shuup/xtheme/templates/shuup/xtheme/_editor_cell.jinja, shuup/xtheme/views/forms.py, shuup_tests/browser/front/test_gdpr_consent.py, shuup_tests/xtheme/test_editor_forms.py
Added "Cell extra class" or "style_class" to cells. This is to be used by merchants for custom cell css.
Fixes #1475
=> Xtheme: Add Extra CSS/Style class to cells

shuup/xtheme/templates/shuup/xtheme/admin/macros.jinja
-  Admin: Enable theme configuration popover
Fixes #1508
=> Admin: Enable theme popover & make the menu retractable

shuup/admin/npm-shrinkwrap.json, shuup/admin/static_src/base/scss/shuup/base.scss, shuup/admin/static_src/base/scss/shuup/navigation.scss, shuup/admin/static_src/base/scss/shuup/picotable.scss, shuup/admin/static_src/base/scss/shuup/support-navigation.scss, shuup_tests/browser/admin/test_product_create.py
=> Admin: fix flex-wrapper and picotable item info

shuup/admin/static_src/base/js/main-menu.js, shuup/admin/static_src/base/scss/shuup/base.scss, shuup/admin/static_src/base/scss/shuup/link-blocks.scss, shuup/admin/static_src/base/scss/shuup/main-menu.scss, shuup/admin/static_src/base/scss/shuup/navigation.scss, shuup/admin/static_src/dashboard/js/dashboard.js, shuup/admin/templates/shuup/admin/base/_main_menu.jinja, shuup/admin/templates/shuup/admin/base/_navigation.jinja
Fixes #1501 
Replaces https://github.com/shuup/shuup/pull/1537
=> Admin: add option to close desktop menu 

shuup/admin/package.json, shuup/admin/static_src/base/js/tour.js, shuup/admin/static_src/base/scss/shuup/main-menu.scss, shuup/admin/static_src/base/scss/shuup/tour.scss, shuup/admin/static_src/base/scss/vendor.scss, shuup/admin/static_src/vendor/vendor.js, shuup/admin/templates/shuup/admin/base.jinja, shuup/admin/templates/shuup/admin/products/edit.jinja
=> Admin tour (#1498)

shuup/admin/static_src/base/scss/shuup/messages.scss
=> Admin: Fix misaligned messages

shuup/admin/static_src/base/scss/shuup/custom-forms.scss
=> Admin: Make checkboxes pop out a bit less

shuup/admin/modules/permission_groups/views/edit.py, shuup/admin/static_src/base/scss/shuup/content-blocks.scss
Desktop looks good
Mobile not as much...
Fixes #1458
=> Admin: Replace Select2 for choosing permission modules with Checkboxes

shuup/admin/modules/categories/__init__.py, shuup_tests/admin/test_category_module.py
=> Admin: Fix category search

.travis.yml, shuup_setup_utils/commands.py, shuup_setup_utils/resource_building.py, tox.ini
- Add verbosity to tox
- Do not audit npm packages when installing dependencies
- Change Travis cache settings
No Refs
=> Speedup unit tests

shuup/admin/modules/categories/views/edit.py
=> Admin: fix categories admin edit view title

shuup/admin/static_src/base/js/main-menu.js, shuup/admin/template_helpers/shuup_admin.py, shuup/admin/templates/shuup/admin/base.jinja, shuup/admin/urls.py, shuup/admin/utils/menu.py, shuup/admin/views/menu.py, shuup_tests/browser/admin/test_menu.py
=> Admin: Make menu stay hidden

shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/static_src/picotable/picotable.js
=> Picotable: Save filter selections

shuup/admin/static_src/base/scss/shuup/quick-add.scss
=> Admin: Fix quick add on mobile

shuup/admin/templates/shuup/admin/orders/_admin_comment.jinja, shuup/admin/templates/shuup/admin/orders/_detail_payments.jinja, shuup/admin/templates/shuup/admin/orders/_order_log_entries.jinja, shuup/order_printouts/templates/shuup/order_printouts/admin/section.jinja
=> Admin: fix order detail sections for small screen devices

shuup/admin/static_src/base/scss/shuup/quick-add.scss
=> Admin: Restyle quick-add buttons on mobile size

shuup/admin/static_src/base/scss/shuup/custom-forms.scss, shuup/admin/templates/shuup/admin/base/_navigation.jinja
=> Admin: make main dropdown static

shuup/xtheme/static_src/editor/editor.js
Fixes #1538 
Explanation here: https://github.com/RubaXa/Sortable/issues/370
=> Xtheme: Ensure drag works front

shuup/admin/modules/contacts/views/list.py, shuup/admin/modules/orders/static_src/create/index.js, shuup/admin/modules/orders/static_src/create/reducers/shop.js, shuup/admin/modules/orders/static_src/create/view/confirm.js, shuup/admin/modules/orders/static_src/create/view/customers.js, shuup/admin/modules/orders/static_src/create/view/index.js, shuup/admin/modules/orders/static_src/create/view/lines.js, shuup/admin/modules/orders/static_src/create/view/shops.js, shuup/admin/modules/orders/static_src/create/view/utils.js, shuup/admin/modules/orders/views/edit.py, shuup/admin/modules/shops/views/edit.py, shuup/admin/modules/shops/views/list.py, shuup/admin/package.json, shuup/admin/static_src/base/js/browse-widget.js, shuup/admin/static_src/base/js/components.js, shuup/admin/static_src/base/js/quick_add_related_objects.js, shuup/admin/static_src/base/js/select.js, shuup/admin/static_src/base/scss/shuup/base.scss, shuup/admin/static_src/base/scss/shuup/content-blocks.scss, shuup/admin/static_src/base/scss/shuup/custom-forms.scss, shuup/admin/static_src/base/scss/shuup/order-create.scss, shuup/admin/static_src/base/scss/shuup/quick-add.scss, shuup/admin/static_src/picotable/picotable.js, shuup/admin/utils/bs3_renderers.py, shuup/admin/views/select.py, shuup/testing/browser_utils.py, shuup_tests/admin/test_contact_module.py, shuup_tests/admin/test_select_view.py
- Allow superuser selecting any contact without shop filtering
- Show the contact type correctly on contact list view when mobile device
- Make scroll to top only render when current value has really changed, preventing calling thousands of redraws with no
reason
- Make buttons below scroll to top button container clickable
- Make order creator Back button style outline
- Fix styles for small screens
- Fix bottom bar width when menu is opened and closed on large screen sizes
- Fix order creator by showing shop select correctly
Refs POS-2626/POS-2627/ENT-2580
=> Admin: fix order creator form

shuup/admin/static_src/base/js/datetimepicker.js, shuup/admin/static_src/base/js/quick_add_related_objects.js, shuup/admin/static_src/base/scss/shuup/quick-add.scss, shuup/discounts/admin/views/_happy_hours.py
The close button background is transparent and sometimes it overlaps the content when scrolling, this makes it easier to users hit the button
=> Admin geral improvements

shuup/front/templates/shuup/front/macros/category.jinja, shuup/front/templates/shuup/front/macros/general.jinja, shuup_tests/browser/front/test_category_view.py
Fixes #1539 
All the themes should be fixed as well.
=> Front: use render_field instead of admin macros

shuup/admin/static_src/base/scss/shuup/custom-forms.scss
=> Admin UI: Fix action buttons

shuup/admin/forms/widgets.py, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/static_src/base/js/browse-widget.js
Make browse button label dynamic.
It is now possible to set label and icons for the browse widget.
Add a fix to not render 'False' when there is no item selected.
No refs
=> Admin: improve browse widget

shuup/admin/static_src/dashboard/js/dashboard.js
=> Admin: check whether Masonry can be created before initialize it

shuup/admin/templates/shuup/admin/base/_navigation.jinja
Clicking on eye now opens a new tab with shop storefront.
No refs
=> Admin: Make the eye goto shopfront open a new tab

shuup/xtheme/static_src/admin/snippet.less
Make it expand to the total space available
No Refs
=> Admin: fix codemirror component weight

shuup/admin/static_src/base/js/main-menu.js, shuup/admin/template_helpers/shuup_admin.py
=> Admin: Unhardcode menu-toggle URL

lib/shuup_static_build_tools/LICENSE, lib/shuup_static_build_tools/README.md, lib/shuup_static_build_tools/package.json
=> Publish static build lib to NPM registry

shuup/admin/package.json, shuup/admin/static_src/base/js/base.js, shuup/admin/static_src/base/js/color-picker.js, shuup/admin/static_src/base/scss/vendor.scss, shuup/admin/static_src/vendor/vendor.js, shuup/front/apps/carousel/locale/en/LC_MESSAGES/django.po, shuup/front/apps/carousel/templates/shuup/carousel/admin/_edit_slide_form.jinja, shuup/front/apps/carousel/templates/shuup/carousel/admin/edit.jinja, shuup/front/apps/carousel/templates/shuup/carousel/carousel.jinja, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/static_src/less/front/carousel.less, shuup_tests/browser/admin/test_carousel_edit.py
Make Bootstrap Colorpicker addon work again
- Add button to delete added slides
- Fix formset to start with index zero when adding the first slide
- Do not show delete checkbox on brand new slides
Refs ENT-2720
=> Admin: carousel improvements

shuup/admin/static_src/base/js/datetimepicker.js
Do no show time when a date field is configured
No Refs
=> Admin: fix date picker format

doc/howto/getting_started_dev.rst, tox.ini
=> Fix browser tests bumping selenium version

shuup/xtheme/static_src/editor/editor.js, shuup/xtheme/static_src/editor/editor.less, shuup/xtheme/static_src/injection/editor-injection.js, shuup/xtheme/static_src/injection/editor-injection.less, shuup/xtheme/templates/shuup/xtheme/editor.jinja
Fixes https://github.com/shuup/shuup/issues/1606
=> XTheme: Show editor on popup instead of sidebar

shuup/admin/modules/shops/__init__.py
=> Admin: Make only active shops visible in search

shuup_tests/browser/admin/test_tour.py
As content is added through javascript on page load, make sure wait a reasonable amount of time for it
No Refs
=> Add extra timeout to the tour browser test

_misc/ensure_code_style.py, _misc/ensure_unicode_literals.py, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/shop_provider.py, shuup/admin/utils/urls.py, shuup/core/middleware.py, shuup/core/models/_units.py, shuup/gdpr/providers.py, shuup/simple_supplier/admin_module/views.py, shuup_tests/admin/test_authentication.py, shuup_tests/admin/test_manufacturer.py, shuup_tests/admin/test_media_module_multi_shop.py, shuup_tests/admin/test_password_reset.py, shuup_tests/admin/test_shop_edit.py, shuup_tests/discounts/test_coupon_codes_admin.py, shuup_tests/discounts/test_discount_admin.py, shuup_tests/discounts/test_exceptions_admin.py, shuup_tests/discounts/test_happy_hours_admin.py, shuup_tests/importer/test_admin.py, shuup_tests/importer/test_product_import.py, shuup_tests/notify/test_notify_admin.py
There should be shop available for staff member to pass
authentication.
Make Problem response status code 400 instead of 200.
Replaces https://github.com/shuup/shuup/pull/1639
=>  Admin: Include shop parameter to authentication (ENT-2748)

shuup/xtheme/rendering.py, shuup/xtheme/static_src/injection/editor-injection.less, shuup_tests/xtheme/test_layout.py
=> Xtheme: make content titles a bit more visible (ENT-2757)

shuup/core/utils/price_display.py, shuup/front/static_src/js/update_price.js, shuup/front/templates/shuup/front/macros/category.jinja, shuup/front/templates/shuup/front/macros/product.jinja, shuup/front/templates/shuup/front/macros/product_ordering.jinja, shuup/front/templates/shuup/front/product/category.jinja, shuup/front/templates/shuup/front/product/detail.jinja, shuup/front/templates/shuup/front/product/detail_order_section.jinja, shuup/front/templates/shuup/front/product/forms/product_order_form.jinja, shuup/front/themes/views/_product_price.py, shuup/front/utils/product.py, shuup/front/views/category.py, shuup/front/views/product.py, shuup_tests/front/test_product_price.py, shuup_tests/supplier_prices/test_product_price_view.py
* Fix issues for prices reload
* Move default supplier behavior to view context data and use template fallback as last resource.
=> Front: fix issues while passing suppliers

shuup/front/basket/commands.py, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/static_src/less/front/basket.less, shuup/front/templates/shuup/front/macros/basket.jinja, shuup_tests/campaigns/test_basket_campaigns.py
Add list of used codes in basket and button to remove them
Fixes #1653
=> Front: add option to remove codes from the basket

shuup/admin/modules/orders/json_order_creator.py, shuup/admin/modules/orders/views/edit.py, shuup/admin/modules/orders/views/shipment.py, shuup/admin/modules/products/forms/base_forms.py, shuup/admin/modules/products/forms/package_forms.py, shuup/admin/modules/products/views/edit.py, shuup/core/api/front_products.py, shuup/core/api/products.py, shuup/core/basket/commands.py, shuup/core/migrations/0051_supplier_enabled.py, shuup/core/models/_product_shops.py, shuup/core/models/_suppliers.py, shuup/core/suppliers/strategies.py, shuup/default_importer/importers/product.py, shuup/front/apps/saved_carts/views.py, shuup/front/forms/product_list_supplier_modifier.py, shuup/front/template_helpers/general.py, shuup/front/template_helpers/product.py, shuup/front/themes/views/_product_price.py, shuup/front/views/product.py, shuup/simple_supplier/admin_module/views.py, shuup/testing/migrations/0005_supplierprice.py, shuup/testing/supplier_pricing/supplier_strategy.py, shuup_tests/admin/test_product_package.py, shuup_tests/core/test_suppliers.py
Suppliers can be enabled and disabled
Add a manager to Supplier model to filter by enabled suppliers and use it in all querysets
Refs ENT-2772
=> Core: add supplier status flag

shuup/admin/modules/sales_dashboard/dashboard.py, shuup_tests/admin/test_sales_dashboard_module.py
=> Admin: fix dashboard block to include the current shop in the queryset

.travis.yml, shuup_tests/simple_cms/test_opengraph.py
=> General: fix unit tests and add Django 1.8 test to first test phase

shuup/front/templates/shuup/front/macros/category.jinja
This is needed for vendor view
=> Add optional param item for product filters

shuup/front/templates/shuup/front/index.jinja
=> Front: Make goto admin button visible for everyone on wizard

shuup/admin/static_src/base/scss/shuup/content-blocks.scss, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/templates/shuup/front/checkout/confirm.jinja, shuup/front/templates/shuup/front/macros/checkout.jinja
- Front: Disable order confirmation button after order submission
Refs #1672
- Admin: Fix product attribute card not opening
No refs
=> Front: Disable order confirmation button after order submission

shuup/core/models/_addresses.py
Has been part of the EU since 2013.
=> Add Croatia to list of EU countries

shuup/core/api/front_orders.py, shuup/core/api/serializers/__init__.py, shuup/core/api/serializers/label.py, shuup/core/api/service.py, shuup/core/api/shop.py, shuup/utils/dates.py
=> API: add more fields in Order serializers

shuup/front/template_helpers/product.py, shuup_tests/front/test_product_template_helpers.py
Fixes https://github.com/shuup/shuup/pull/1720
=> Front: pull back removed template helpers vol 2

shuup/admin/templates/shuup/admin/macros/block.jinja
=> Admin: enable HTML content in help blocks

shuup/reports/writer.py, shuup_tests/reports/test_reports.py
Objects and models instances passed as report data was breaking the writer
Refs ENT-2960
=> Reports: fix excel report writer by forcing strings when writing

shuup/admin/modules/categories/__init__.py, shuup/admin/modules/orders/__init__.py, shuup/admin/modules/products/__init__.py, shuup/admin/modules/products/views/edit.py, shuup/admin/modules/products/views/list.py, shuup_tests/admin/test_product_module.py, shuup_tests/admin/test_views.py
- Admin: object check permissions for admin blocks before returning them
- Admin: fix product admin module to return only products of the current shop
No Refs
=> Admin: bug fixes

shuup/admin/static_src/base/scss/shuup/select.scss, shuup/admin/static_src/picotable/picotable.js
* Add option to call picotable for custom code
* Show all picotable mass-action options by default
=> Admin: enhance picotable

shuup/front/template_helpers/general.py, shuup_tests/front/test_general_template_helpers.py
=> Front: fix template helper that was removing already removed unorderable product

shuup/admin/modules/settings/view_settings.py
=> Remove language column from picotable settings

shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/static_src/base/js/dropzone.js
When the MediaBrowser is disable, make it possible to users browse local files
Refs MYS-65
=> Admin: fix dropzone component and allow browsing local files

shuup/front/apps/simple_search/forms.py, shuup/front/apps/simple_search/settings.py
=> Front: add settings to change the list of fields to be used in search query

shuup/xtheme/plugins/snippets.py, shuup/xtheme/resources.py, shuup_tests/xtheme/test_resources.py
Now the snippet plugin can leverage the power of Jinja
Refs MYS-68
=> Xtheme: enable Jinja template tags in Snippet plugin

shuup_tests/simple_supplier/test_simple_supplier.py
Covered process_stock_managed view with unit test
Refs MYS-52
=> Stock Management: add unit test for process_stock_managed

shuup/admin/static_src/base/scss/shuup/picotable.scss, shuup/admin/static_src/picotable/picotable.js
Changes:
- added checkbox in mobile mode and edit link to both table and mobile modes
- selection checks the checkbox
=> Admin: Improve picotable usability

shuup_tests/simple_supplier/test_simple_supplier.py
The test was disabling the stock management and expecting it was enabled
No Refs
=> Fix unit tests by sending the correct flag in stock managed

shuup/front/templates/shuup/front/macros/general.jinja
=> Front: add supplier link if that is available in front

shuup/admin/static_src/picotable/picotable.js
=> Admin: fix picotable to allow item link when there is no mass actions

shuup/admin/static_src/base/scss/shuup/custom-forms.scss, shuup/admin/utils/bs3_renderers.py
=> Admin: Make datetime form fields readonly

shuup/admin/static_src/base/scss/shuup/picotable.scss, shuup/admin/static_src/picotable/picotable.js
Fixed the checkbox Safari bug & improved edit button/checkbox alignment for mobile.
No refs
=> Picotable: Fix checkboxes for Mobile Safari & improve style

doc/ref/provides.rst, shuup/admin/__init__.py, shuup/admin/browser_config.py, shuup/admin/settings.py, shuup/admin/static_src/base/js/select.js, shuup/admin/template_helpers/shuup_admin.py, shuup/admin/urls.py, shuup/xtheme/static_src/editor/editor.js, shuup_tests/admin/test_template_helpers.py
Change the browser config provider to be more generic
and include extra settings options to be injected in browser.
Refs TCP-18
=> Admin: add select2 search inputs min length configurable

shuup/admin/static_src/base/scss/shuup/content-blocks.scss, shuup/admin/static_src/picotable/picotable.js, shuup/admin/templates/shuup/admin/products/_edit_attribute_form.jinja
Most importantly: finally remove the auto-collapsed attributes on product view :)
No Ref
=> Admin: Minor fixes

shuup/front/templates/shuup/front/base.jinja
Import of js-catalog was missing in base.jinja
Refs TCP-21
=> Translation: add gettext import for non admin users

shuup/front/__init__.py, shuup/front/admin_module/carts/form_parts.py, shuup/front/admin_module/carts/views/_list.py, shuup/front/templates/shuup/front/admin/cart_delay.jinja
Rendered cart delay form in admin module
Updated cart display according to Cart Inactivity Delay
Fixed styling issue
Used global variable and updated form validation
=> Front: add configuration form part for cart

shuup/admin/__init__.py, shuup/admin/modules/orders/__init__.py, shuup/admin/modules/orders/sections.py, shuup/admin/modules/orders/toolbar.py, shuup/admin/modules/orders/views/shipment.py, shuup/admin/static_src/base/scss/shuup/shipments.scss, shuup/admin/static_src/base/scss/style.scss, shuup/admin/templates/shuup/admin/orders/_order_shipments.jinja, shuup/admin/templates/shuup/admin/orders/create_shipment.jinja, shuup/core/models/_orders.py, shuup_tests/admin/test_shipment_creator.py
- Add option to get shipment related data per supplier
- Disable edit option when multiple suppliers are enabled since the admin order edit is not prepared for that
=> Admin: improve shipment handling

shuup/front/apps/simple_search/views.py, shuup/front/forms/product_list_modifiers.py, shuup/front/static_src/js/category.js, shuup/front/utils/sorts_and_filters.py, shuup/front/views/category.py
Fire event when filters are refreshed in JS.
Refs MYS-94
=> Front: fix sort & filters by not caching ids but instances

shuup/front/static_src/js/category.js
Add flag on fields to allow not refreshing products when field changes
Use jQuery to build the querystring instead of writing own method
Refs MYS-95
=> Front: improve sort & filters using jQuery

shuup/front/static_src/js/category.js
- Re-fix the parse of state into querystring
- Trigger event when user pop history state
Refs MYS-99
=> Front: improve sort & filters script

shuup/admin/modules/orders/views/status.py, shuup_tests/admin/test_orderstatusform.py
Fix form clean method
Added unit tests.
Refs TCP-25
=> OrderStatusForm: fix form clean method

shuup/front/apps/customer_information/templates/shuup/customer_information/macros/address.jinja, shuup/front/apps/customer_information/templates/shuup/customer_information/macros/buttons.jinja, shuup/front/static_src/less/front/user-account.less, shuup/front/templates/shuup/front/dashboard/dashboard.jinja
- Fix button styles and alignment
- Add id to the dashboard content to enable bookmark linking
No Refs
=> Front: add small improvements to customer dashboard

shuup/notify/admin_module/forms.py, shuup/notify/locale/en/LC_MESSAGES/django.po, shuup/notify/static/notify/admin/script-item-editor.js, shuup/notify/static_src/script-editor.js, shuup/notify/templates/notify/admin/script_item_editor.jinja, shuup/xtheme/parsing.py, shuup_tests/browser/notify/test_script_template.py
=> Notify: Improve styles for admin and fix email lang bug

shuup/admin/forms/fields.py, shuup_tests/admin/test_fields.py
WeekdaysSelectMultiple#format_value treated value as string but it could be list.
Refs TCP-25
=> Happy Hour: add check for weekdays value instance type

shuup/admin/browser_config.py, shuup/admin/npm-shrinkwrap.json, shuup/admin/package.json, shuup/admin/settings.py, shuup/admin/static_src/base/js/datetimepicker.js, shuup/admin/static_src/picotable/picotable.js
While at it activate the locale and remove the boostrap datetime picker from packages json as unused.
=> Add option to control time step for datetime pickers

shuup/front/apps/carousel/admin_module/forms.py, shuup/front/static_src/less/front/basket.less, shuup/front/static_src/less/front/inputs.less
- Front: Fix styles for product quantity field 
Refs ENT-3004
- Make category select for carousel async
Refs ENT-2964
=> Front: Fix styles for product quantity field & make category select async

shuup/front/package.json, shuup/front/static_src/js/update_price.js, shuup/front/templates/shuup/front/macros/product_image.jinja, shuup/front/templates/shuup/front/macros/product_ordering.jinja, shuup/front/themes/views/_product_price.py, shuup_tests/front/test_product_price.py
When changing variations in front, the images never changed. This PR adds a feature where images will change based on the variation children.
=> Front: Variation image changer

shuup/front/templates/shuup/front/product/category.jinja, shuup/front/urls.py, shuup/front/views/category.py, shuup/themes/classic_gray/templates/classic_gray/shuup/front/macros/theme/navigation.jinja, shuup_tests/front/test_all_categories.py, shuup_tests/front/test_edit_in_admin_toolbar.py
* /c/ which lists products for all visible categories
=> Front: add new products page

shuup/admin/utils/picotable.py, shuup_tests/admin/test_picotable.py
https://github.com/shuup/shuup/issues/1841
in check_different_types func - Manager returns '' value
which we can display to the user
=> Fix issue with picotable column values

Dockerfile, doc/changelog.rst
Hi guys. I updated your (3 years old) Dockerfile.
I prefer working with Docker more than virtualenv. So I created this Dockerfile for testing shuup_workbench, it follows your guide and creates superuser with admin/admin credentials.
I can create and add PR with docker-compose for easier development if you want.
PS: I hope this time CLA will work correctly :D
=> New Dockerfile

shuup/front/forms/product_list_modifiers.py, shuup_tests/front/test_filters.py
Create a custom field to support comma separated list of values as a string
Refs MYS-104
=> Front: fix categories product list filter

shuup/core/models/_orders.py
=> Core: do not allow creating payment when the not paid amount is not valid

shuup/front/templates/shuup/front/macros/general.jinja
Add behavior when dealing with multiple checkboxes options
=> Front: improve bootstrap field renderer

shuup/admin/modules/orders/views/refund.py, shuup/admin/templates/shuup/admin/orders/_refund_order_contents.jinja, shuup/admin/templates/shuup/admin/orders/create_refund.jinja, shuup/core/models/_orders.py, shuup/testing/supplier_provider.py, shuup_tests/admin/test_refund_creator_multiple_suppliers.py, shuup_tests/core/test_order_refund_utils.py, shuup_tests/core/test_orders.py
Replaces https://github.com/shuup/shuup/pull/1890
=> Extend order refund utils for suppliers while preparing admin for suppliers

shuup/admin/static_src/base/scss/shuup/base.scss, shuup/admin/template_helpers/shuup_admin.py, shuup/admin/templates/shuup/admin/base.jinja, shuup/testing/supplier_provider.py, shuup_tests/admin/test_active_shop_and_supplier.py
Next to the active shop information also show information about currently active vendor if multiple suppliers is enabled.
=> Admin: show name for active supplier at all times (RO-1)

shuup/xtheme/_theme.py
https://github.com/shuup/shuup/issues/1876
=> Xtheme: sort plugins items by name

shuup/front/templates/shuup/front/macros/product_information.jinja
=> Front: pass down the supplier in product macros

shuup/admin/templates/shuup/admin/base.jinja, shuup/admin/templates/shuup/admin/base/_navigation.jinja
Should be very useful for orders-list and dashboard for example.
=> Admin: add option to setup auto reload for page

shuup/core/fields/__init__.py, shuup/core/migrations/0059_contact_options.py, shuup/core/models/_contacts.py, shuup_tests/core/test_contacts.py
Original JSONField has a bug that doesn't consider django polymorphic environment and fail to deserialize the value
Add a new field to fix that
No Refs
=> Core: fix Contact field to use a field that considers django polymorphic

shuup/front/templates/shuup/front/macros/order.jinja, shuup_tests/api/test_front_products_api.py, shuup_tests/core/test_orders.py
File title is not required, so it should fallback to product name
Add file size for convenience
=> Fix a problem with file title

shuup/default_reports/reports/shipping.py, shuup_tests/default_reports/test_default_reports.py
=> Reports: Fix shipping report breaking with taxful & taxless orders

shuup/front/static_src/js/category.js
Also fix small eslint issues
No Refs
=> Front: fix pagination by adding default page number and clearing the loading state

shuup/core/api/__init__.py, shuup/core/api/contact_group.py, shuup/core/api/contact_group_price_display.py, shuup_tests/api/test_contact_group_api.py, shuup_tests/api/test_contact_group_display_api.py
Add basic crud API to for contact groups and contact group display options
=> Core: add contact groups to api

shuup/front/static_src/js/category.js
This is useful to bind new events on the loaded content
Refs MYS-138
=> Front: add custom event to warn that product list has been loaded

shuup/admin/toolbar.py, shuup_tests/admin/test_permissions.py
https://github.com/shuup/shuup/issues/1930
=> Add required_permissions into the URLActionButton

shuup/front/template_helpers/product.py
=> Front: Do not render bought with relations with siblings

shuup/admin/toolbar.py, shuup_tests/admin/test_permissions.py
Force to resolve the url to prevent sending __proxy__ class down to urlparse
=> Admin: fix action button url parse

shuup/front/checkout/addresses.py, shuup/front/templates/shuup/front/checkout/addresses.jinja, shuup/front/templates/shuup/front/macros/checkout.jinja, shuup/front/templates/shuup/front/macros/order.jinja
Do no request shipping address when there is no shipable lines
Refs HEAL-30
=> Front: make shipping address optional in checkout phase

shuup/admin/modules/orders/views/shipment.py, shuup/core/models/_orders.py, shuup/core/signals.py, shuup/front/__init__.py, shuup/front/notify_events.py, shuup_tests/front/test_notify_events.py, tox.ini
Bump mock to latest to be able to use mock call test correctly
Refs HEAL-34
=> Core: add signal and notify event when order status changes

shuup/front/views/category.py
=> Front: filter out invalid suppliers from category list

shuup/admin/static_src/base/js/dropzone.js
=> Admin: expose dropzone activation to the world

.travis.yml, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/modules/products/forms/variable_variation_forms.py, shuup/admin/modules/products/static_src/product-variation-variable-editor.js, shuup/admin/modules/products/views/edit_variation.py, shuup/admin/static_src/base/scss/shuup/content-blocks.scss, shuup/admin/static_src/base/scss/shuup/custom-forms.scss, shuup/admin/templates/shuup/admin/products/variation/_variation_variables.jinja, shuup_tests/admin/test_variation_templates.py, shuup_tests/browser/admin/test_variation_templates.py
Hoping this makes Travis happy.
=> Variation templates two

shuup/admin/package.json, shuup/admin/static_src/base/js/color-picker.js
Enable users to type in the field
Refs RO-119
=> Admin: fix color widget field

.travis.yml, shuup/admin/static_src/base/js/side-nav.js
Preserve selected section on object edit pages. Update window location hash on section change with proper section id.
=> Admin: preserve selected section

shuup/admin/forms/widgets.py, shuup/admin/static_src/base/js/dropzone.js, shuup_tests/admin/test_widgets.py
Some attributes can now be customized like maxFilesize using the new widget dict attribute
Only string based configurations can be set
No Refs
=> Admin: add option to pass extra dropzone configurations to widget

shuup/front/utils/cache.py
=> Front: fix constant name typo

README.rst, shuup/admin/form_part.py, shuup/admin/menu.py, shuup/admin/modules/orders/views/edit.py, shuup/admin/signals.py, shuup/admin/utils/views.py, shuup/utils/models.py, shuup_tests/utils/test_get_data_dict.py
Linked to https://github.com/shuup/shuup-logging
Refs REAL-57
=> Logging support

shuup/notify/actions/email.py, shuup/notify/admin_module/forms.py, shuup/notify/models/script.py, shuup/xtheme/engine.py, shuup/xtheme/settings.py, shuup_tests/notify/test_email.py, shuup_tests/notify/test_notify_admin.py, shuup_tests/xtheme/test_addon_injections.py
- Xtheme: add option to skip resource injection
- Notify: add option to wrap HTML body
=> Notify: add option to wrap HTML body

shuup/admin/modules/orders/views/detail.py, shuup/admin/modules/orders/views/list.py
=> Admin: Orders, changed queryset filter

shuup/admin/templates/shuup/admin/products/_edit_media_form.jinja
The correct name is data-file, not data-media
=> Admin: fix media template to use correct data-attr name

shuup/admin/modules/products/forms/base_forms.py, shuup_tests/admin/test_product_create.py
Initialize shop product suppliers with the only supplier when multiple suppliers is disabled at core settings.
=> Admin: init shop product suppliers with only supplier

shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/admin/static_src/base/js/editor.js, shuup/campaigns/locale/en/LC_MESSAGES/django.po, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/discounts/locale/en/LC_MESSAGES/django.po, shuup/front/apps/customer_information/locale/en/LC_MESSAGES/django.po, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/gdpr/locale/en/LC_MESSAGES/django.po, shuup/importer/locale/en/LC_MESSAGES/django.po, shuup/notify/locale/en/LC_MESSAGES/django.po, shuup/reports/locale/en/LC_MESSAGES/django.po, shuup/simple_cms/locale/en/LC_MESSAGES/django.po, shuup/simple_supplier/locale/en/LC_MESSAGES/django.po, shuup/xtheme/locale/en/LC_MESSAGES/django.po, shuup/xtheme/templates/shuup/xtheme/editor.jinja
Images are converted into Base64 and they could lead to slowness.
It is a good feature for vector images but adding too much content to
the HTML will lead to poor performance that is hard to track
Refs HEAL-29
=> Admin: do not allow large images to be inserted into summernote

shuup/admin/modules/orders/sections.py, shuup/admin/templates/shuup/admin/orders/_detail_section.jinja, shuup/admin/templates/shuup/admin/orders/_order_contents.jinja
When multiple shops or suppliers enabled show shop or supplier information at order detail.
=> Admin: add shop and supplier info to order detail

shuup/admin/form_part.py, shuup/admin/signals.py, shuup/admin/utils/views.py
It can help to inject extra validations before saving the view object and raise errors
Refs HEAL-30
=> Admin: add signal that is triggered when form is valid in views

shuup/core/basket/update_methods.py, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/core/order_creator/__init__.py, shuup/core/order_creator/_source.py, shuup_tests/front/test_basket_commands.py
Added orderline behaviour attribute
INHERIT = 1  # Inherits the quantity of the parent line if parent line exists
SKIP = 2  # Skips quantity change upon parent line quantity change
DELETE = 3  # Removes the line upon parent line quantity change
Refs HEAL-37
=> Core: Add orderline behaviour attribute

shuup/simple_cms/admin_module/views.py, shuup/simple_cms/models.py, shuup_tests/simple_cms/test_page_creation.py, shuup_tests/simple_cms/test_page_delete.py
Free page URL on delete.
Refs #2096
=> CMS: Free page URL on delete

shuup/xtheme/layout/_base.py, shuup/xtheme/models.py
=> Xtheme: add option to remove final placeholder row

shuup/front/utils/user.py, shuup_tests/front/test_utils.py
=> Front: Cache is_admin_user function

.travis.yml, tox.ini
Replace Python 2.7 tests with 3.7 tests
=> Drop tests for Python 2.7

CHANGELOG.md, shuup/notify/actions/email.py, shuup/notify/typology.py, shuup_tests/notify/test_email.py
=> Notify: add BCC and CC fields to SendEmail action

shuup/admin/modules/products/forms/base_forms.py
In some situations it was possible to receive ValueError "save() prohibited to prevent data loss due to unsaved related object 'primary_image'." while saving the primary image from first form.
Old solution seems rather complex since I think our goal is here to make sure there is at least one primary image for product.
=> Admin: improve primary image fallback for product

CHANGELOG.md, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/modules/products/static_src/product-variation-variable-editor.js, shuup/admin/static_src/base/scss/shuup/custom-forms.scss, shuup/admin/static_src/base/scss/shuup/custom-modals.scss, shuup/admin/static_src/picotable/picotable.js, shuup/notify/static_src/script-editor.js, shuup/xtheme/static_src/editor/custom-modals.less
- Render the filters button on small devices, even when there is no data, to allow resetting filters
- Improve the admin modals to use flexbox and work better on small devices
Refs MYS-243
=> Admin: render the filters button on small devices

CHANGELOG.md, shuup/admin/templates/shuup/admin/base/_main_menu.jinja
Changed the name of the class to be the same ass in the css so the admin menu loads right
Fixes #2128
=> Admin menu

CHANGELOG.md, shuup/admin/browser_config.py, shuup/admin/static_src/product/edit_media.js, shuup/admin/template_helpers/shuup_admin.py, shuup_tests/admin/test_template_helpers.py
=> Admin: remove pinned /sa/ URL from scripts to support dynamic admin URLs

shuup/simple_supplier/templates/shuup/simple_supplier/admin/product_form_part.jinja
Also improve the error texts to be more understandable and useful.
Before:
After:
=> Fix graphical (incorrect indent) bug in Product / Stock Management

CHANGELOG.md, shuup/front/static_src/js/category.js
=> Fix product pagination by not overriding the state with undefined values

CHANGELOG.md, shuup/discounts/admin/modules/__init__.py, shuup/discounts/admin/modules/_discounts.py, shuup/discounts/admin/views/_archive.py, shuup/discounts/admin/views/_edit.py, shuup/discounts/apps.py
=> Admin: Fix breadcrumbs double highlight

shuup/admin/modules/products/views/list.py
=> Admin: Fix product thumbnail URLs in picotable

CHANGELOG.md, shuup/admin/modules/users/views/detail.py, shuup/front/apps/registration/__init__.py, shuup/front/apps/registration/locale/en/LC_MESSAGES/django.po, shuup/front/apps/registration/notify_events.py, shuup/front/apps/registration/signals.py, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/locale/en/LC_MESSAGES/djangojs.po, shuup_tests/front/test_registration.py
Created a new signal that get sent when a account gets reactivated
Created a new notification that send a mail when it gets the signal
Fix #2143
=> Account reactivation notification

shuup_tests/core/test_order_creator.py
When total unpaid ammount is zero, all other patment attempts
are invalid.
Refs #1881
=> Test: Invalid order create

shuup/front/apps/registration/__init__.py, shuup/front/apps/registration/notify_events.py
AccountActivation event is triggered only when the user is activated for the first time.
No refs
=> Notify: Add AccountActivation event

shuup/simple_cms/plugins.py, shuup/simple_cms/utils.py, shuup/xtheme/static_src/editor/editor.js, shuup_tests/simple_cms/test_plugins.py
=> CMS: Add ordering to Page choices in Page Links Plugin

CHANGELOG.md, shuup/core/basket/objects.py, shuup/core/models/_basket.py, shuup/front/models/stored_basket.py, shuup/testing/factories.py, shuup_tests/front/test_basket.py
=> Core: save basket shipping and billing address as dictionary when id is not available

CHANGELOG.md, shuup/core/settings.py, shuup/core/tasks.py, shuup_tests/core/test_task_runner.py
=> Core: add task runner to support running tasks using 3rd party services like Celery

.travis.yml, CHANGELOG.md, shuup/admin/modules/products/__init__.py, shuup/admin/modules/products/views/copy.py, shuup/admin/modules/products/views/toolbars.py, shuup/admin/signals.py, shuup/admin/toolbar.py, shuup/customer_group_pricing/signal_handers.py, shuup/simple_supplier/__init__.py, shuup/simple_supplier/product_copy_signal_handler.py, shuup_tests/admin/test_product_copy.py, shuup_tests/functional/test_product_copy.py
Copy supplier, categories, media, stock managed value and customer group price
=> Admin: add improved product copy

shuup_workbench/settings/base_settings.py
Needed for incoming Docker improvements.
Refs SHU-24
=> Change sqlite db location

shuup_workbench/settings/base_settings.py
=> Revert "Change sqlite db location"

.dockerignore, CHANGELOG.md, Dockerfile-dev, README.rst, doc/howto/getting_started.rst, doc/howto/getting_started_dev.rst, docker-compose-dev.yml, docker-compose.yml, shuup/core/management/commands/shuup_init.py, shuup_workbench/settings/base_settings.py
=> Add docker-compose file and Docker instructions

shuup_tests/browser/admin/test_dev_onboarding.py
The test expected shop to be maintenance mode, this was changed.
Fixes broken CI from https://github.com/shuup/shuup/pull/2218
Refs SHU-24
=> Fix a browser test

CHANGELOG.md, shuup/core/basket/objects.py, shuup/core/basket/update_methods.py, shuup/front/forms/order_forms.py, shuup/front/utils/product.py
=> Front: Add priority attribute to base order form to enable using precedence

CHANGELOG.md, shuup/core/templatetags/shuup_common.py, shuup/core/utils/static.py, shuup_tests/core/test_template_tags.py
=> Core: add options to fetch a package's version to append in static url

CHANGELOG.md, shuup/admin/modules/orders/json_order_creator.py, shuup/admin/modules/orders/views/edit.py, shuup_tests/admin/test_order_creator.py
=> Admin: Fix issues in order editor

CHANGELOG.md, shuup/core/cache/impl.py
=> Prevent crashing when trying to cache an unpicklable value

shuup/importer/templates/shuup/importer/admin/import.jinja
- Added warning text to the template about the ignore column in the example files
refs JDL-31
=> Add warning text t template

CHANGELOG.md, shuup/notify/actions/email.py, shuup_tests/notify/test_email.py
=> Notify: unescape email subject and body to prevent sending broken characters in emails

CHANGELOG.md, shuup/simple_cms/plugins.py, shuup/xtheme/templates/shuup/xtheme/_editor_cell.jinja
Make sure to pass optional parameters through kwargs in form
Issue raised after updating to Shuup v2
No Refs
=> Xtheme: fix editor template issue

CHANGELOG.md, shuup/xtheme/plugins/social_media_links.py
Tiny bit ugly, but this works.
Refs IP-38
=> Xtheme: Fix social media plugin form initial data population

shuup/importer/transforms.py, shuup_tests/importer/test_product_import.py
Lowercase the imported headers also for CSV import so those match better with the impoter (same way as when importing Excel).
=> Importer: tune CSV import headers

CHANGELOG.md, shuup/front/templates/shuup/front/macros/basket.jinja
=> Fix button that removes coupon from the basket by using the correct JS event property

shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/locale/fi_FI/LC_MESSAGES/django.po, shuup/front/locale/ru/LC_MESSAGES/django.po, shuup/front/locale/sv_SE/LC_MESSAGES/django.po, shuup/front/locale/zh_Hans/LC_MESSAGES/django.po, shuup/front/templates/shuup/front/macros/general.jinja
`Items 1 of 12 of 16` => `Items 1 to 12 of 16`
=> Front: Fix typo in pagination

CHANGELOG.md, shuup/notify/script_template/generic.py
Not every script will have a language variable to attach the script variable
=> Notify: make the default script language be the fallback from Parler

CHANGELOG.md, shuup/admin/modules/products/views/list.py, shuup/admin/static_src/base/scss/shuup/picotable.scss, shuup/admin/static_src/picotable/picotable.js
- Fixed so when you are selecting a product for the product variation there is a select button for every product in the popup window.
refs https://shuupinc.slack.com/archives/C019X3NAD4K/p1602237415116100
=> Fixed so the product variation selection is more clear

CHANGELOG.md, shuup/core/models/_orders.py, shuup_tests/core/test_order_refund_utils.py
=> Core: Fix total refundable for suppliers

CHANGELOG.md, shuup/core/models/_suppliers.py
=> Change the Supplier.objects.enabled() filter to only return approved suppliers

CHANGELOG.md, shuup/gdpr/utils.py
The method shouldn't return booleans
=> GDPR: make sure to return a blank list in the `get_active_consent_pages`

CHANGELOG.md, shuup/gdpr/receivers.py
The checkout breaks while ordering as anonymous user and GDPR enabled
No Refs
=> GDPR: do not create consent for anonymous user in checkout

CHANGELOG.md, shuup/front/utils/dashboard.py, shuup/front/views/dashboard.py
Add a sorting attribute to dashboard item to allow sorting them
=> Dashboard: Sorting of dashboard items by ordering number

shuup/core/signal_handers.py, shuup/core/signals.py, shuup/core/utils/context_cache.py, shuup/core/utils/price_cache.py, shuup/front/signal_handlers.py, shuup/front/utils/cache.py, shuup_tests/browser/admin/test_tour.py
- Remove duplicate queries and actions.
- Optimize queries using id's instead objects
=> Core: optimize performance around cache bumps

CHANGELOG.md, shuup/front/templates/shuup/front/macros/product_information.jinja, shuup/front/templatetags/shuup_front.py
- Fixed so the mass and measurement units are the same as the settings and not hard coded
Refs JDL-2
=> Front: Use measurement units from the settings

CHANGELOG.md, shuup/front/templates/shuup/front/checkout/_vertical_phases.jinja
- Fix `_vertical_phases.jinja` incorrectly targets all forms
=> Front: Checkout Phase

CHANGELOG.md, shuup/admin/views/select.py
After choices composed they are sorted by key 'name'
=> MultiselectAjaxView returns ordered by name choices

CHANGELOG.md, shuup/admin/templates/shuup/admin/sales_dashboard/_recent_orders_dashboard_block.jinja, shuup/admin/templates/shuup/admin/sales_dashboard/_store_overview_dashboard_block.jinja
=> Admin: fix missing `tr` closing tags

CHANGELOG.md, shuup/xtheme/engine.py, shuup/xtheme/models.py, shuup/xtheme/resources.py, shuup_tests/xtheme/test_addon_injections.py
Custom snippets in global injection now supports Jinja2 markup rendering
=> Xtheme: add Jinja markup in custom snippet type

shuup/xtheme/rendering.py, shuup/xtheme/settings.py
Use following setting to enable per placeholder cache for rendering
SHUUP_XTHEME_DISABLE_PLACEHOLDER_CACHE = True
=> Xtheme: add option to add placholder cache

shuup/core/models/_addresses.py, shuup/core/models/_service_behavior.py, shuup/testing/factories.py, shuup_tests/core/test_addresses.py
=> Core: remove GB from countries in European Union

CHANGELOG.md, shuup/admin/__init__.py, shuup/admin/forms/_auth.py, shuup/admin/modules/users/mass_actions.py, shuup/admin/modules/users/views/password.py, shuup/admin/templates/shuup/admin/auth/recover_password_mail_content.jinja, shuup/core/signals.py, shuup/core/utils/forms.py, shuup/core/utils/users.py, shuup/front/apps/auth/templates/shuup/user/recover_password_mail_content.jinja, shuup/notify/__init__.py, shuup/notify/signal_handlers.py, shuup/notify/tasks.py, shuup/testing/factories.py, shuup_tests/admin/test_user_mass_actions.py
=> Bulk reset password for users in admin

CHANGELOG.md, shuup/core/fields/__init__.py, shuup/utils/i18n.py, shuup_tests/conftest.py, shuup_tests/utils/test_i18n.py
This improves performance for the customer edit view (profile dashboard)
by caching the extinct languages method that gets called multiple times
=> Core: cache language utils methods using LRU

CHANGELOG.md, doc/ref/provides.rst, shuup/admin/templates/shuup/admin/products/_edit_media_form.jinja, shuup/core/basket/command_dispatcher.py, shuup/core/basket/command_middleware.py, shuup/core/utils/product_subscription.py, shuup/front/static_src/js/index.js, shuup/front/static_src/js/product_order.js, shuup/front/static_src/less/front/product.less, shuup/front/template_helpers/basket.py, shuup/front/template_helpers/order.py, shuup/front/template_helpers/product.py, shuup/front/templates/shuup/front/macros/basket.jinja, shuup/front/templates/shuup/front/macros/navigation.jinja, shuup/front/templates/shuup/front/macros/order.jinja, shuup/front/templates/shuup/front/macros/product_ordering.jinja, shuup/front/templatetags/shuup_front.py, shuup/front/utils/order_source.py, shuup/testing/basket_middleware.py, shuup/testing/line_properties_descriptor.py, shuup/testing/subscription_option_provider.py, shuup_tests/core/test_basket_commands.py, shuup_tests/core/test_product_subscription_provider.py, shuup_tests/front/test_basket_line_descriptor.py, shuup_tests/front/test_product_subscription.py
Refs SH-40
With this features, it is possible to create addons that can provide subscription logic:
=> Introduce subscription options

shuup/admin/dashboard/blocks.py, shuup/admin/static_src/base/scss/shuup/base.scss, shuup/admin/static_src/base/scss/shuup/navigation.scss, shuup/admin/static_src/dashboard/scss/dashboard.scss, shuup/admin/templates/shuup/admin/base/_main_menu.jinja, shuup/admin/templates/shuup/admin/base/_navigation.jinja, shuup/admin/templates/shuup/admin/dashboard/dashboard.jinja, shuup/admin/templates/shuup/admin/sales_dashboard/_recent_orders_dashboard_block.jinja, shuup/admin/templates/shuup/admin/sales_dashboard/_store_overview_dashboard_block.jinja
* Remove dashboard and home icon links from top menu
* Change visit shop link from an icon to a button with text
* Always display the dashboard link in the main navigation as the first item
* Add text truncate CSS to user dropdown if the user's username gets too long and display only a user icon on mobile screens
<hr>
**Before:**
<hr>
**After:**
<hr>
=> Dashboard improvements

.gitignore, CHANGELOG.md, shuup/admin/modules/media/utils.py, shuup/admin/modules/media/views.py, shuup_tests/admin/test_media_module.py
=> Gracefully handle the error when deleting a PROTECTED MediaFolder

CHANGELOG.md, shuup/admin/templates/shuup/admin/permission_groups/edit.jinja
Resolves #2133
Refs SHU-23
https://user-images.githubusercontent.com/33625218/106000651-bc568300-60b7-11eb-8917-a236425b672d.mov
=> Admin: Add an open/close all permission groups button

.travis.yml, shuup/admin/locale/en/LC_MESSAGES/django.po, shuup/admin/locale/en/LC_MESSAGES/djangojs.po, shuup/core/basket/objects.py, shuup/core/locale/en/LC_MESSAGES/django.po, shuup/core/management/commands/makemessages.py, shuup/core/pricing/_context.py, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/middleware.py, shuup/front/templates/shuup/front/macros/navigation.jinja, shuup/notify/locale/en/LC_MESSAGES/django.po, shuup/xtheme/locale/en/LC_MESSAGES/django.po, shuup_tests/core/test_basket.py, shuup_tests/front/test_middleware.py, shuup_tests/front/test_stored_basket.py, tox.ini
- Core: add makemessages support for do and cache templatetags
- Front: skip front middleware for static and media
- Core: cache attributes while get and add cache key attribute 
- Core: avoid unnecessary touching to basket customer
- Front: add template cache to basket partial
=> Improve around basket performance

shuup/default_reports/apps.py, shuup/default_reports/forms.py, shuup/default_reports/mixins.py, shuup/default_reports/reports/__init__.py, shuup/default_reports/reports/customer_sales.py, shuup/default_reports/reports/new_customers.py, shuup/default_reports/reports/orders.py, shuup/default_reports/reports/product_total_sales.py, shuup/default_reports/reports/refunds.py, shuup/default_reports/reports/sales.py, shuup/default_reports/reports/shipping.py, shuup/default_reports/reports/taxes.py, shuup/reports/report.py, shuup/reports/settings.py, shuup_tests/default_reports/test_default_reports.py
=> Orders and orderlines export

CHANGELOG.md, shuup/core/models/_product_shops.py, shuup_tests/front/test_auth.py
=> Core: undeprecate signals for ShopProduct model

CHANGELOG.md, shuup/admin/static_src/base/scss/shuup/picotable.scss, shuup/admin/static_src/base/scss/shuup/select.scss
- Admin: Fix picotable mobile styling to default to full-width
=> fixed mobile picotable to full-width

CHANGELOG.md, shuup/front/templates/shuup/front/macros/product_ordering.jinja, shuup/front/themes/views/_product_price.py
refs. https://sentry.io/organizations/shuup/issues/2289258204/?project=5357331
=> Fix product page without approved suppliers error

CHANGELOG.md, shuup/admin/modules/taxes/views/edit.py
Pass languages to the TaxClassFormPart to show multilanguage forms
Refs https://sentry.io/organizations/shuup/issues/2351639411
=> Allow multilanguage support in TaxClass

CHANGELOG.md, shuup/front/apps/personal_order_history/templates/shuup/personal_order_history/macros/buttons.jinja, shuup/front/apps/personal_order_history/templates/shuup/personal_order_history/order_detail.jinja
Fix some styles and show order action buttons before the title in a single row
=> Fix the order detail template

CHANGELOG.md, shuup/front/utils/urls.py, shuup_tests/front/test_model_resolver.py
Consider the supplier from context or kwargs while reversing the product url
Refs MYYR-137
=> Front: improve product url resolver

CHANGELOG.md, shuup/admin/templates/shuup/admin/base.jinja, shuup/front/templates/shuup/front/macros/general.jinja, shuup/simple_supplier/forms.py
It doesn't contain translated string
=> Fix translations part 2

CHANGELOG.md, shuup/admin/templates/shuup/admin/forms/widgets/help_text.jinja, shuup/utils/multilanguage_model_form.py
When a base class and derived classes have translations,
show all of them in the form for configuration
Refs BH-104
=> Admin: show translation fields from all polymorphic models

CHANGELOG.md, shuup/front/apps/carousel/plugins.py, shuup/simple_cms/plugins.py, shuup/xtheme/layout/_base.py, shuup/xtheme/plugins/_base.py, shuup/xtheme/plugins/category_links.py, shuup/xtheme/plugins/image.py, shuup/xtheme/plugins/products.py, shuup/xtheme/plugins/products_async.py
=> Xtheme fixes v4

CHANGELOG.md, shuup/simple_cms/plugins.py, shuup/xtheme/locale/en/LC_MESSAGES/django.po, shuup/xtheme/plugins/_base.py, shuup/xtheme/plugins/category_links.py, shuup/xtheme/plugins/image.py, shuup/xtheme/plugins/products.py, shuup/xtheme/plugins/products_async.py, shuup/xtheme/templates/shuup/xtheme/plugins/highlight_plugin_async.jinja, shuup/xtheme/views/plugins.py
=> Fix more cache issues

CHANGELOG.md, shuup/notify/locale/en/LC_MESSAGES/django.po, shuup/notify/static_src/script-editor.less, shuup/notify/templates/notify/admin/script_item_editor.jinja
This fixes the size of the editor in some cases
=> Notify: add notify styles to the script editor iframe

CHANGELOG.md, shuup/importer/admin_module/import_views.py
- Importer: fix so the correct context is displayed on first request when selecting importer
=> Fix importer context

CHANGELOG.md, shuup/utils/multilanguage_model_form.py, shuup_tests/utils/test_multilanguage_model_form.py
- Utils: fix MultiLanguageModelForm so language dependent filed will only be required if the language is required
=> Fix MultiLanguageModelForm

CHANGELOG.md, shuup/core/models/_orders.py, shuup/core/models/_service_base.py, shuup/core/models/_service_behavior.py, shuup/core/order_creator/_source.py, shuup_tests/core/test_order_total_behavior_component.py, shuup_tests/core/test_waiving_cost_behavior.py, shuup_tests/core/test_weight_based_pricing_behavior.py
=> Core: only consider lines from the same supplier as the behavior component

CHANGELOG.md, shuup/importer/utils/importer.py
=> Reports: improve log when an importer fails

CHANGELOG.md, shuup/admin/utils/urls.py, shuup/core/basket/command_dispatcher.py, shuup/front/checkout/_process.py, shuup/front/urls.py, shuup/utils/excs.py, shuup/xtheme/urls.py, shuup/xtheme/views/command.py, shuup/xtheme/views/editor.py, shuup/xtheme/views/extra.py
The views were returning not escaped content which is unsafe
Thanks to Daniel Elkabes who reported the issue
Refs https://trello.com/c/VcQdVZ7X/102-shuup-fix-critical-vulnerabilities
=> General: Fix XSS vulnerability

CHANGELOG.md, shuup/campaigns/reports.py, shuup/default_reports/reports/customer_sales.py, shuup/default_reports/reports/orders.py, shuup/default_reports/reports/product_total_sales.py, shuup/default_reports/reports/refunds.py, shuup/default_reports/reports/sales.py, shuup/default_reports/reports/sales_per_hour.py, shuup/default_reports/reports/shipping.py, shuup/default_reports/reports/taxes.py, shuup/default_reports/reports/total_sales.py, shuup/reports/writer.py, shuup_tests/campaigns/test_reports.py, shuup_tests/default_reports/test_default_reports.py, shuup_tests/reports/test_reports.py
- Reports: add csv report writer
=> Add csv report writer

.github/workflows/shuup.yml, .gitignore, CHANGELOG.md, requirements-dev.txt, requirements-tests.txt, setup.py, shuup/reports/writer.py, shuup_tests/conftest.py, shuup_workbench/test_settings.py
=> Reports: clean malicious content

CHANGELOG.md, shuup/front/locale/en/LC_MESSAGES/django.po, shuup/front/middleware.py, shuup/front/npm-shrinkwrap.json, shuup/front/package.json, shuup/front/static_src/js/index.js, shuup/front/static_src/js/timezone.js, shuup/front/templates/shuup/front/base.jinja, shuup/front/templates/shuup/front/index.jinja, shuup/front/templates/shuup/front/macros/timezone.jinja, shuup/front/urls.py, shuup/front/views/timezone.py, shuup_tests/front/test_middleware.py, shuup_tests/front/test_timezone.py
=> Front: add timezone view to save the user's current timezone

CHANGELOG.md, shuup/core/models/_products.py, shuup/default_importer/importers/contact.py, shuup/default_importer/importers/product.py, shuup/front/templates/shuup/front/macros/general.jinja, shuup/importer/importing/importing.py
=> Reports: do not catch generic to prevent hiding other issues

CHANGELOG.md, shuup/front/forms/product_list_supplier_modifier.py
- Front: SupplierProductListFilter to take all vendors from the category and all sub categories
refs https://trello.com/c/4oI2oY1M/196-buy-happy-products-vendor-filter
=> Fix SupplierProductListFilter

CHANGELOG.md, shuup/xtheme/plugins/products_async.py
Refs https://sentry.io/organizations/shuup/issues/2395615135/
=> Xtheme: only use the id attribute if the variable is a Product

shuup/xtheme/__init__.py, shuup/xtheme/admin_module/__init__.py, shuup/xtheme/forms.py, shuup/xtheme/object_selector.py, shuup_tests/admin/test_object_selector.py
Adds font object selector form Admin Theme form.
=> Adds font object selector.

CHANGELOG.md, shuup/core/locale/fi_FI/LC_MESSAGES/django.po
refs https://trello.com/c/JNYedPrP/229-kukatkotiinproduct-list-not-loading-in-finnish-language-in-qa
=> Fix formatted Finish translations

CHANGELOG.md, shuup/default_importer/importers/product.py
=> Importer: index product after importing it

shuup/simple_supplier/module.py, shuup/simple_supplier/tasks.py
Accept supplier as optional kwargs
Refs https://sentry.io/organizations/shuup/issues/2564478128/?project=5752397
=> SimpleSupplier: fix the index product function name

CHANGELOG.md, shuup/admin/static_src/base/scss/shuup/buttons.scss, shuup/admin/static_src/base/scss/shuup/picotable.scss, shuup/admin/static_src/base/scss/shuup/select.scss
- Admin: Fix primary buttons, list buttons, and filter dropdowns to use css variables
REF:
https://trello.com/c/vaDra6hE/38-create-css-variables-to-make-the-color-uplift-tasks-less-time-consuming
=> Fixed Admin: Attached missing css variables in some elements

CHANGELOG.md, shuup/core/models/_categories.py
Reference: https://trello.com/c/RHuu7Xc0/248-kukatkotiin-the-campaigns-are-not-working-in-english-internal-server-error
=> Bug in Category.get_hierarchy

CHANGELOG.md, shuup/admin/utils/product.py
=> Admin: fix typo in product cloner
